### ISSUE TITLE
OTP not reading even with IFTTT premium account

### ISSUE THREAD

**Issue by pulkitpj93** [bombardier-gif/covid-vaccine-booking#100]
Downloaded the latest code, and followed all steps in readme to setup IFTTT, ran the code from src, when entering number and pressing n , OTP is being generated ( I get the SMS) but its not reading the OTP automatically. Waited for 15mins to allow it to read OTP but unsuccessful.
 
If pressing y for manual, OTP is not generating at all.

Till morning IFTTT was working perfectly for me, i have verified the URL also in both mobile and web using this: https://kvdb.io/3YgXf9PHYHbX6NsF7zP6Us/99XXXXXXXX

can anyone tell me if there is any changes that i need to do with new code?
![Error](https://user-images.githubusercontent.com/84080564/117977042-0e14d780-b34e-11eb-874d-b755852d42a3.JPG)

**Comment by GOODBOIXD** [comment]
IFTTT seemed to be glitching for me too, so I tried this - https://github.com/bombardier-gif/covid-vaccine-booking/pull/77 and it worked!

**Comment by GOODBOIXD** [comment]
Also, IFTTT glitch is probably temporary - maybe something to do with the slow cowin servers, since it takes a few minutes for the otp to come or atleast it did in my case. I tried the manual otp option, then the otp came after a minute or so. Idk why manual is not working for you.

**Comment by bombardier-gif** [comment]
So one of the thing is that the kvdb key had to be changed today. someone deleted it so i had to create a new one.
So you have to update the IFTTT applet with the new url with key AS.... and not 3Y...

**Comment by pulkitpj93** [comment]
> So one of the thing is that the kvdb key had to be changed today. someone deleted it so i had to create a new one.
> So you have to update the IFTTT applet with the new url with key AS.... and not 3Y...
This worked, now i feel stupid for not checking such a basic thing. Thanks for all the help and the amazing work being done behind this script :)
