### ISSUE TITLE
Slot openings not being notified properly

### ISSUE THREAD

**Issue by jivjen** [bombardier-gif/covid-vaccine-booking#102]
I have been checking the telegram channel and saw that there were around 200-300 slots that got opened today whereas my script kept running and never detected those openings. Any idea what the issue might be?

**Comment by ujaiswal** [comment]
+1 Was running the script. Got the telegram notification but the script did not detect the new slot opening.

**Comment by xxxAng** [comment]
This is because of non real time data iguess, sometimes availability api gives cached or old data.

**Comment by yashk2103** [comment]
@xxxAng Can we use protected APIs to work around that?
I had seen another script based on C# which has integrated the protected APIs. Maybe it could help us?

**Comment by jivjen** [comment]
Are we using the same APIs which are being used by these telegram channels?
If not we can try implementing them here to get more accurate and real time data right?

**Comment by xxxAng** [comment]
Telegram also misses slots I saw, they dont give update for small no of slots being opened.
They only update about big no of slots being opened.
So it might be telegram was lucky to catch it that time.

**Comment by yashk2103** [comment]
@jivjen Yes, exactly. I think pallupz the original creator of the script used public APIs because back then they worked fine and a lot of people didn't know about bots going on. But I think we should use the protected APIs as they seem to be reflecting real time data. 

P.S: Pls everyone let me know about your opinion and if it's doable. I have an idea but unfortunately I'm not a very techie guy and don't know coding much. Otherwise would have made a PR. If it's doable please someone volunteer so everyone can benefit

**Comment by yashk2103** [comment]
@xxxAng but I had seen this issue day before yesterday also. The bot often misses out on various centres and slots. Also, the available centres which it shows is often wrong when compared to CoWIN website

**Comment by xxxAng** [comment]
@yashk2103  thats what you get when we use public api which govt. made limited on 5th may.
Only option i see now,
1. Have a UI automation bot
2. Or buy private api may be Telegram/Healthify using those only.

**Comment by bombardier-gif** [comment]
I am closing this issue as its a known issue. Please feel free to continue your chat on this

**Comment by yashk2103** [comment]
@xxxAng @bombardier-gif what all things would we need to implement private api?

**Comment by RonakTotla** [comment]
I wouldn't worry too much about a couple of times the script missing out to detect slots. Have heard of other similar scripts failing because of cached data.
Yes there are ways around but this to me is good enough.

**Comment by yashk2103** [comment]
If you say so, it's just that I have gotten too desperate to get the damn vaccine. That's why I'm trying to see and eliminate anything that would slow us down. I guess I should rest and get my mind off of this

**Comment by xxxAng** [comment]
You got to have the protected api first..
I dont have the apis, if we get the api first then would have to think of
how to bypass their security.

**Comment by yashk2103** [comment]
I have the api links. I'll put them tomorrow on this discussion.

**Comment by xxxAng** [comment]
Ok good to know.
Share it whenever you feel, we can try to break the security.

**Comment by yashk2103** [comment]
@xxxAng @bombardier-gif  
Please check this out:  https://apisetu.gov.in/public/marketplace/api/cowin/cowin-protected-v2#/

Majority of API links I have is from here. Also, I had read there is some "secret" key that is asked in protected APIs to encode information going from our side? Starts from U2FsdGVkX1/K10bXSsDZI+l05XTwv2Hbo7+jbsk7AY******************************DnJPuwHUKOC5A==".

Please also check: https://documenter.getpostman.com/view/9564387/TzRPip7u#intro

Please let me know if any of this helps. If you need the "secret" key then also let me know.

**Comment by xxxAng** [comment]
Yashk if these are protected api URL  Bombardier used the right one,
See the util file,
BOOKING_URL = "https://cdn-api.co-vin.in/api/v2/appointment/schedule"
BENEFICIARIES_URL = "
https://cdn-api.co-vin.in/api/v2/appointment/beneficiaries"
CALENDAR_URL_DISTRICT = "
https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id={0}&date={1}
"
CALENDAR_URL_PINCODE = "
https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByPin?pincode={0}&date={1}
"
CAPTCHA_URL = "https://cdn-api.co-vin.in/api/v2/auth/getRecaptcha"
OTP_PUBLIC_URL = "https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP"
OTP_PRO_URL = "https://cdn-api.co-vin.in/api/v2/auth/generateMobileOTP"

I thought they had some secret API links for these which they are using
only for COWIN and AROGYA SETU..

**Comment by yashk2103** [comment]
I think I had read somewhere that the calendar URLs  often return stale data and that Find by URLs are better at responding. Because the Find by urls only search for today/tomorrow and Calendar urls search for 7 days worth of data. Could this be a factor in play?

**Comment by xxxAng** [comment]
What do you mean by find by URL ?
What API you are referring to instead of CalendarByState or CalendarByPin ?
