### ISSUE TITLE
Not getting beep sound

### ISSUE THREAD

**Issue by Blackpanther13** [bombardier-gif/covid-vaccine-booking#103]
I am not getting beep sound when captcha window pop-up. If not there then you can add some sound. I am using python script.

**Comment by bombardier-gif** [comment]
you need to install beep. check the readme for the steps. Reopen this issue if its not solved

**Comment by Blackpanther13** [comment]
I am using windows so there is no instruction for windows in read me.

**Comment by gitmnj** [comment]
Seriously the beep is not working please tell the detail instructions
