### ISSUE TITLE
CoWinOTPRetriver Custom app [cumbersome]: If navigate to other apps, it looses the session and stops

### ISSUE THREAD

**Issue by sumit2k21** [bombardier-gif/covid-vaccine-booking#104]
Would like a modification in the app so that it keeps running in background even if we move to other apps or tasks on phone. 
Once minimized, it again asks user for mobile number and start listening CoWIN OTP button becomes off. one has to reenter mobile number and switch it on again. that's cumbersome.
It should be running no matter what other apps/tasks user is using on phone.
#77 #78

**Comment by bombardier-gif** [comment]
Can you check the power settings on your phone? 
Also please bear in mind that this codebase is maintained by volunteers having a fulltime job. So code contribution is welcome here :)

**Comment by xxxAng** [comment]
@sumit2k21  turn off the power saver mode, change it to any non optimized power mode.

**Comment by GOODBOIXD** [comment]
also check if the app is allowed to run in background. you will find it in app settings.

**Comment by bombardier-gif** [comment]
I am closing this issue as you have multiple solutions recommended. Please reopen if you think otherwise
