### ISSUE TITLE
How to use auto captcha?

### ISSUE THREAD

**Issue by Samargup** [bombardier-gif/covid-vaccine-booking#106]
I am getting a pop up for captcha every time and have to enter it manually.
I read prior comments that there is a way to use auto captcha but could not find out how do do that.
Is there a help file for it or could someone guide please. Help is appreciated.

**Comment by yashk2103** [comment]
Buddy, there is support added for auto-captcha from anti-captcha.com but for that you have to first be a member of anti-captcha.com and it is a paid service. 
Though charges are nominal enough I feel we can type much faster as the automated service takes anywhere from 7-12 secs to solve the captcha

**Comment by Samargup** [comment]
> Buddy, there is support added for auto-captcha from anti-captcha.com but for that you have to first be a member of anti-captcha.com and it is a paid service.
> Though charges are nominal enough I feel we can type much faster as the automated service takes anywhere from 7-12 secs to solve the captcha

**Comment by Samargup** [comment]
I can subscribe to anti-captcha.com
How do I use that. Is there some help or steps for that please.
I often leave laptop unattended and this would prefer auto method

**Comment by yashk2103** [comment]
I suggest you to check #62 and also check Readme.md
