### ISSUE TITLE
Kvdb free bucket not working after 1800 ops approx

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#108]
Did create a Kvdb free bucket but it lasted for few hours only, though it was a free account but they promised 10000 operations.
I have just 1800 operation hits but not working since then.
Any clue ?

**Comment by bombardier-gif** [comment]
You can reach out to their support and ask. Also they have a rate limit of queries per hour. Check the response in curl (verbose mode)

**Comment by xxxAng** [comment]
Thank you can close this now.
