### ISSUE TITLE
Help Needed: Bucket not found error

### ISSUE THREAD

**Issue by avi2397** [bombardier-gif/covid-vaccine-booking#109]
"error fetching OTP API: bucket not found"

I am getting this error on the windows app

Things that I noticed and tried changing:
1) Db bucket key in windows app is: 3YgXf9PHYHbX6NsF7zP6Us
2) Default Db key in the android app is: ASth4wnvVDPkg2bdjsiqMN

while using default settings the android app shows "successfully sent CoWIN OTP"

when I changed the Db key to  "3YgXf9PHYHbX6NsF7zP6Us" in the android app it says failed to send OTP.

Error in the windows app is same in both the cases

**Comment by bombardier-gif** [comment]
The bucket has been updated to ASth4wnvVDPkg2bdjsiqMN 
Please use the script directly and not the exe
