### ISSUE TITLE
Getting Error fetching OTP API:bucket not found

### ISSUE THREAD

**Issue by Kash987** [bombardier-gif/covid-vaccine-booking#110]
Getting Error fetching OTP API:bucket not found

**Comment by bombardier-gif** [comment]
The key changed Please use ASth4wnvVDPkg2bdjsiqMN in IFTTT as well as your script (you can just pull the latest code)

**Comment by Kash987** [comment]
I have followed all the instruction mentioned in read me. I am using Windows.exe
