### ISSUE TITLE
How to get anti-captcha api key?

### ISSUE THREAD

**Issue by amanchandna241** [bombardier-gif/covid-vaccine-booking#112]
Do we need to buy a paid api key from anti-captcha.com? Do not see any details in the readme file

**Comment by MrAnkit007** [comment]
Just go to anticaptcha website and signup. They provide free demo api also with 1000 captcha solves. I used it and booked my slot. It automates the whole task

**Comment by amanchandna241** [comment]
On the first run I am getting this error while running test

Started solving captcha...
making request to createTask
could not create task
API error ERROR_ZERO_BALANCE: Account has zero or negative balance
Task finished with error: ERROR_ZERO_BALANCE - 0

**Comment by amanchandna241** [comment]
Found it need to go to demo credits in the finance tab
