### ISSUE TITLE
Can you please ask user to enable battery optimzation

### ISSUE THREAD

**Issue by vishalv26** [bombardier-gif/covid-vaccine-booking#114]
It would be beneficial if you check if battery optimization is enabled or not and then ask/guide user to do so.

This will greatly improve the UX. Below is some link for your help

https://stackoverflow.com/questions/39256501/check-if-battery-optimization-is-enabled-or-not-for-an-app

and also try to save the last kv bucket key instead of resetting it to default whenever app opens. It might need to be replaced every week.

**Comment by bombardier-gif** [comment]
@ujaiswal fyi

**Comment by ujaiswal** [comment]
@vishalv26 @bombardier-gif thanks for the stackoverflow link will take a look at this.

**Comment by ujaiswal** [comment]
Created a PR for suggested changes: https://github.com/bombardier-gif/covid-vaccine-booking/pull/128
