### ISSUE TITLE
how to add anti-captcha.com paid key

### ISSUE THREAD

**Issue by vesan83** [bombardier-gif/covid-vaccine-booking#115]
i was able to buy a paid key from anti-captcha.com
can you please help me where to put it.

i do not have any knowledge of python or programing

i cant find any details in the readme file also

**Comment by vesan83** [comment]
i donr see any details in the README file too

**Comment by bombardier-gif** [comment]
It asks for the key before you try to run the script. 

Do you want to automate captcha autofill? (yes or no) Default no:  enter yes

"Enter your Anti-Captcha API key:
