### ISSUE TITLE
Automatic OTP request before session expire

### ISSUE THREAD

**Issue by abhi98264** [bombardier-gif/covid-vaccine-booking#116]
Is it possible that at the end of 13 min an automatic request for otp is generated in the new cmd window session?
so that there is no gap between the next session

**Comment by bombardier-gif** [comment]
Its a good idea, but adds unnecessary complexity to the code. Right now the contributions in the last 2-3 days made the code slighly unstable. So i would focus on simplicity and stability as many people are using this script
