### ISSUE TITLE
Can you please merge the latest code from @pallupz, which contain captcha support

### ISSUE THREAD

**Issue by Anny1305** [bombardier-gif/covid-vaccine-booking#12]
Can you please merge the latest code from @pallupz, which contain captcha support

**Comment by bombardier-gif** [comment]
I updated the code. Please try again

**Comment by sid8840** [comment]
i ran this code on WSL linux on win 10. its runs prior to CAPTCHA step,but i could not get popup for captcha as you have mentioned in readme.

kindly suggest.

**Comment by bombardier-gif** [comment]
Do you see any error? also an image file should be generated in the folder. I have not tried linux but it sounds like a missing module. Did you install the requirements.txt (again after the update)?

**Comment by jalotra** [comment]
It works on Ubuntu 18.04.

**Comment by sid8840** [comment]
> It works on Ubuntu 18.04.

how...what extra steps you have undertaken?

**Comment by Anny1305** [comment]
getting below error on my mac
 ```
 File "/Users/kumar.anny/Work/vaccine3/covid-vaccine-booking/src/captcha.py", line 3, in <module>
    import PySimpleGUI as sg
  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 95, in <module>
    import tkinter as tk
  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by sid8840** [comment]
> getting below error on my mac
> 
> ```
> File "/Users/kumar.anny/Work/vaccine3/covid-vaccine-booking/src/captcha.py", line 3, in <module>
>    import PySimpleGUI as sg
>  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
>    from .PySimpleGUI import *
>  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 95, in <module>
>    import tkinter as tk
>  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/tkinter/__init__.py", line 36, in <module>
>    import _tkinter # If this fails your Python may not be configured for Tk
> ModuleNotFoundError: No module named '_tkinter'
> ```

apt-get install python-tk

**Comment by bombardier-gif** [comment]
> getting below error on my mac
> 
> ```
> File "/Users/kumar.anny/Work/vaccine3/covid-vaccine-booking/src/captcha.py", line 3, in <module>
>    import PySimpleGUI as sg
>  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
>    from .PySimpleGUI import *
>  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 95, in <module>
>    import tkinter as tk
>  File "/Users/kumar.anny/.pyenv/versions/3.7.3/lib/python3.7/tkinter/__init__.py", line 36, in <module>
>    import _tkinter # If this fails your Python may not be configured for Tk
> ModuleNotFoundError: No module named '_tkinter'
> ```

brew install python-tk solved this
