### ISSUE TITLE
OTP collection app on Android stops on background

### ISSUE THREAD

**Issue by dutta-alankar** [bombardier-gif/covid-vaccine-booking#120]
The OTP collection app stops when put in background.

**Comment by bombardier-gif** [comment]
Thanks for the feedback.  You can ask the author of the app @ujaiswal for pointers on this

**Comment by ujaiswal** [comment]
@dutta-alankar Please turn off battery optimizations and make sure power saver is off.
You can follow this: https://www.androidpolice.com/2020/05/30/how-to-prevent-apps-sleeping-in-the-background-on-android/

I will try and add some UI to disable the battery optimization through the app over the weekend.

**Comment by ujaiswal** [comment]
Check this https://github.com/bombardier-gif/covid-vaccine-booking/pull/128

**Comment by shailesh** [comment]
@ujaiswal it's good that you started storing the number for the background but the trigger to start listening gets off. When I open and see the trigger is off.
