### ISSUE TITLE
Error 200, 400, 401

### ISSUE THREAD

**Issue by ikornu1** [bombardier-gif/covid-vaccine-booking#121]
![image](https://user-images.githubusercontent.com/83777110/118086825-2df5db00-b3e2-11eb-931c-8d7e85f43172.png)
I am getting this error again and again.
Any instructions on how to resolve it?

**Comment by RonakTotla** [comment]
you must have missed the instructions for testing/setup before running the code
also do check the closed threads for discussions on same

**Comment by 180492sunney** [comment]
same error for me, i have the required fonts in here "C:\Users\<name>"\AppData\Local\Programs\Python\Python39\Lib\site-packages\reportlab\font . From the logs it seems like that it automatically submits some captcha and then there are issues in booking

**Comment by 180492sunney** [comment]
okay the issue is we instinctively press "n" instead of "no" at the captcha prefrence menu. Type "no" next time, and it should be fine.

**Comment by bombardier-gif** [comment]
@ikornu1 What are you trying to do? Do you want autocaptcha or manual?

- If you want manual captcha entry, choose that option
- if you want auto captcha i think you have supplied the right key
In any case the cowin captcha is buggy

**Comment by ikornu1** [comment]
> okay the issue is we instinctively press "n" instead of "no" at the captcha prefrence menu. Type "no" next time, and it should be fine.

This worked. Thanks @180492sunney.
