### ISSUE TITLE
Integrate 2captch API as well for automatic captcha solving

### ISSUE THREAD

**Issue by sumit2k21** [bombardier-gif/covid-vaccine-booking#122]
Currently I can see anticaptcha API has been added for automatic captcha solving.
Can someone raise a PR with 2captcha integration in the latest repo ?

**Comment by bombardier-gif** [comment]
Whats the advantage of 2captcha?

**Comment by sbhardwa123** [comment]
how does one get anticaptcha code?

**Comment by dap-123** [comment]
Refer Issue-[112](https://github.com/bombardier-gif/covid-vaccine-booking/issues/112)

**Comment by dap-123** [comment]
> how does one get anticaptcha code?

Refer Issue-[112](https://github.com/bombardier-gif/covid-vaccine-booking/issues/112)

**Comment by sumit2k21** [comment]
@bombardier-gif Its cheaper, Its success rate are higher, it has way more human workers compared to anti-captcha.
refer [this ](https://futmatebot.com/community/threads/change-anti-captcha-to-2captcha.15019/) if you want to know more.

**Comment by bombardier-gif** [comment]
PRs are welcome. I am not a fan of adding too many options and choices. The number of bugs increase a lot.
