### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by thepitzaboy1** [bombardier-gif/covid-vaccine-booking#123]
I keep getting the below error for captcha.

================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}

**Comment by bombardier-gif** [comment]
The cowin captcha itself is buggy.

**Comment by thepitzaboy1** [comment]
I didnt even get the pop up, i think the issue is the code expect the captcha option to be no rather than N everywhere else.

**Comment by bombardier-gif** [comment]
Let me update the code

**Comment by bombardier-gif** [comment]
updated the code to a simple y/n

**Comment by shailesh** [comment]
where do we get "Anti-Captcha API key" from?
