### ISSUE TITLE
SSL Verification failed

### ISSUE THREAD

**Issue by Pratik3** [bombardier-gif/covid-vaccine-booking#124]
Facing this issue while running the script:
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/99XXXXXXXX
HTTPSConnectionPool(host='kvdb.io', port=443): Max retries exceeded with url: /ASth4wnvVDPkg2bdjsiqMN/99XXXXXXXX(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

**Comment by Samargup** [comment]
I am getting same error. I was running it every 4 seconds. Now trying with 5 seconds. I believe some limit has been defined for number of tries

**Comment by Pratik3** [comment]
Did it work?

**Comment by bombardier-gif** [comment]
It does look like rate limited. what you can do is  use curl the url
curl https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/99XXXXXXXX -v

You will get the rate limit details such as
< x-ratelimit-limit: 10000
< x-ratelimit-remaining: 9999
< x-ratelimit-reset: 1620904856

**Comment by Samargup** [comment]
> Did it work?

Yes it worked fine after changing to 5 seconds

**Comment by Pratik3** [comment]
> > Did it work?
> 
> Yes it worked fine after changing to 5 seconds

Where did you make the change? Please guide

**Comment by bombardier-gif** [comment]
I think set the frequency to 5. the question is asked while running the script.
If you have already saved the json then you can delete and try again

**Comment by Pratik3** [comment]
> n is asked while running the script.

Bro... I get this error much before it asks me, and I have not saved any json. Can you explain what change do I need to do in steps please.

**Comment by Samargup** [comment]
I had set the frequency to 5 seconds and just got the same error again
