### ISSUE TITLE
error fetching OTP API:bucket not found

### ISSUE THREAD

**Issue by shubhamk2609** [bombardier-gif/covid-vaccine-booking#127]
Hi,
How to get rid of this issue? It wasn't appearing earlier.
Setup the IFTTT and also OTPRetriever but script seems to be not reading the OTP. However, OTP arrives in the phone.

**Comment by bombardier-gif** [comment]
can you see the IFTTT and check when it was run and was ther any error?
Also you can now use the android apk for a much smoother experience

**Comment by shubhamk2609** [comment]
I have tried both IFTTT and the OTPRetriever as mentioned. As a workaround, I have been using it by directly adding the bearer token but maybe it would be good to have the option to enter the OTP manually to get the bearer token and make the login.

**Comment by Dhanushrajashekar** [comment]
hey even im facing the same issuse

**Comment by mnjit007** [comment]
> 
> 
> Hi,
> How to get rid of this issue? It wasn't appearing earlier.
> Setup the IFTTT and also OTPRetriever but script seems to be not reading the OTP. However, OTP arrives in the phone.

First of all you only need one of the two apps on your mobile, preferred is `CoWinOtpRetreiver.apk`. If you are using a Xiaomi mobile, make sure you provide the SMS read permission to the `CoWinOtpRetreiver` application. 

Here's how to do it : Security --> Manage Apps --> CoWinOtpRetreiver --> Permissions --> Enable all permissions `Accept`

**Comment by bombardier-gif** [comment]
@mnjit007 Could you please update the readme? a lot of people would benefit out of this.

**Comment by shubhamk2609** [comment]
@bombardier-gif Yes I know only one of them should be able to solve the problem but even if both are present none of them are able to clear the bucket. Script is not able to resolve the error listed.
