### ISSUE TITLE
captcha new issue

### ISSUE THREAD

**Issue by rahul151894** [bombardier-gif/covid-vaccine-booking#130]
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}
Response: 400 : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}

can anyone help

**Comment by rahul151894** [comment]
i opted for auto captcha option, not the issue discussed in #123

**Comment by rahul151894** [comment]
can you @bombardier-gif help ?

**Comment by shailesh** [comment]
Where do we get "Anti-Captcha API key" from?

**Comment by bombardier-gif** [comment]
yes.. the captcha is a bit buggy from cowin side itself

**Comment by bombardier-gif** [comment]
> Where do we get "Anti-Captcha API key" from?

You need to register at the site

**Comment by shailesh** [comment]
> > Where do we get "Anti-Captcha API key" from?
> 
> You need to register at the site

Will the API key after registration will just work or need to pay for the premium?
