### ISSUE TITLE
covid-vaccine-slot-booking.py line no5 showing error on termux

### ISSUE THREAD

**Issue by Gmansign** [bombardier-gif/covid-vaccine-booking#132]
Dear sir,
covid-vaccine-slot-booking.py line no5 showing error on termux.
Sir please provide exe file for windows.

**Comment by bombardier-gif** [comment]
Can you please tell me more about the error?

**Comment by mnjit007** [comment]
Getting the below error on Windows too

```

D:\cowin\automatic\covid-vaccine-booking-main>cd src && python covid-vaccine-slot-booking.py
Traceback (most recent call last):
  File "D:\cowin\automatic\covid-vaccine-booking-main\src\covid-vaccine-slot-booking.py", line 5, in <module>
    import requests, sys, argparse, os, datetime
ModuleNotFoundError: No module named 'requests'

```

**Comment by mnjit007** [comment]
Solved it. Basically we need to run the command  `pip install -r requirements.txt` before we run the python script so the dependencies are fetched before. This info is deep inside the README.

**Comment by bombardier-gif** [comment]
thanks
