### ISSUE TITLE
Otp Receiver

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#134]
It stops working jn the background and then I have to re open and enter the phone number and enable it.

**Comment by ujaiswal** [comment]
@shailesh Download the latest apk. The app should be running in background if you disable battery optimization on startup. Also, you now no longer need to enter mobile number multiple times.

**Comment by vesan83** [comment]
@ujaiswal please give link to the latest verion

**Comment by ujaiswal** [comment]
@shailesh @vesan83  I have created another PR for fixing minor issues when the phone number might not be saved when the app is forcefully closed by the system.
https://github.com/bombardier-gif/covid-vaccine-booking/pull/144

You can download the apk from here which has this changes : https://github.com/ujaiswal/covid-vaccine-booking/blob/main/CoWinOtpRetreiver.apk

Please note that just disabling the battery optimization might not keep the app alive in the background all the time. There are certain phone settings like adaptive battery and power saver mode which causes the app in background to close. Refer to this link https://www.androidpolice.com/2020/05/30/how-to-prevent-apps-sleeping-in-the-background-on-android/

It is already there in the readme: https://github.com/bombardier-gif/covid-vaccine-booking#using-the-cowin-otp-retriever-android-app-1

**Comment by BumpyKnuckls** [comment]
Thanks @ujaiswal for the PR. Closing this one since the PR is merged. @shailesh @vesan83 Please download the apk and try again.
