### ISSUE TITLE
Booking is not Successful - After multiple tries

### ISSUE THREAD

**Issue by rajushinde451** [bombardier-gif/covid-vaccine-booking#135]
Thank you very much for this wonderful application. 

Somehow script is not able to confirm the booking in highly active location like Bengaluru. If you see the log the it shows 100 slots are available, it made 4 attempts to book slot.

1st attempt failed because of invalid captcha( that is fine)
2nd, 3rd and 4th attempt failed with error - This vaccination center is completely booked for the selected date. 
Where as slots were available,

Any idea what is the issue?

+-------+----------------+------------+-----------+-------------+------------+----------------------------------------+
|   idx | name           | district   |   pincode |   available | date       | slots                                  |
+=======+================+============+===========+=============+============+========================================+
|     1 | Manipal Clinic | BBMP       |    560078 |         100 | 14-05-2021 | ['02:00PM-04:00PM', '04:00PM-05:00PM'] |
+-------+----------------+------------+-----------+-------------+------------+----------------------------------------+
Random Rows.Column:1.2
============> Got Choice: Center #1, Slot #2
Booking with info: {'beneficiaries': ['16592039717030', '42826462064420', '10234024702910', '19209382851510'], 'dose': 1, 'center_id': 693681, 'session_id': '46ddb4f4-0ade-4c63-a79b-e3c95e2bf6bb', 'slot': '04:00PM-05:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
making request to createTask
created task with id 22709155
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task solved
Captcha text: YKAWe
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0045", "error":"Please provide valid security code"}
Response: 400 : {"errorCode":"APPOIN0045", "error":"Please provide valid security code"}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
making request to createTask
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
created task with id 22712281
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task solved
Captcha text: 8eNYH
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
===================================================================================
Centers available in 560066 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560078 from 14-05-2021 as of 2021-05-13 17:54:19: 1
Manipal Clinic 560078
Centers available in 560008 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560030 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560076 from 14-05-2021 as of 2021-05-13 17:54:19: 1
APOLLO HOSPITAL 1 560076
Centers available in 560002 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560037 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560020 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560034 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560001 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560003 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560011 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560029 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 562157 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 560023 from 14-05-2021 as of 2021-05-13 17:54:19: 0
Centers available in 562106 from 14-05-2021 as of 2021-05-13 17:54:19: 0
+-------+----------------+------------+-----------+-------------+------------+----------------------------------------+
|   idx | name           | district   |   pincode |   available | date       | slots                                  |
+=======+================+============+===========+=============+============+========================================+
|     1 | Manipal Clinic | BBMP       |    560078 |         100 | 14-05-2021 | ['02:00PM-04:00PM', '04:00PM-05:00PM'] |
+-------+----------------+------------+-----------+-------------+------------+----------------------------------------+
Random Rows.Column:1.1
============> Got Choice: Center #1, Slot #1
Booking with info: {'beneficiaries': ['16592039717030', '42826462064420', '10234024702910', '19209382851510'], 'dose': 1, 'center_id': 693681, 'session_id': '46ddb4f4-0ade-4c63-a79b-e3c95e2bf6bb', 'slot': '02:00PM-04:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
colinear!
colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
making request to createTask
created task with id 22714977
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task solved
Captcha text: WupWq
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
===================================================================================
Centers available in 560066 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560078 from 14-05-2021 as of 2021-05-13 17:54:34: 1
Manipal Clinic 560078
Centers available in 560008 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560030 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560076 from 14-05-2021 as of 2021-05-13 17:54:34: 1
APOLLO HOSPITAL 1 560076
Centers available in 560002 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560037 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560020 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560034 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560001 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560003 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560011 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560029 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 562157 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 560023 from 14-05-2021 as of 2021-05-13 17:54:34: 0
Centers available in 562106 from 14-05-2021 as of 2021-05-13 17:54:34: 0
+-------+----------------+------------+-----------+-------------+------------+----------------------------------------+
|   idx | name           | district   |   pincode |   available | date       | slots                                  |
+=======+================+============+===========+=============+============+========================================+
|     1 | Manipal Clinic | BBMP       |    560078 |         100 | 14-05-2021 | ['02:00PM-04:00PM', '04:00PM-05:00PM'] |
+-------+----------------+------------+-----------+-------------+------------+----------------------------------------+
Random Rows.Column:1.2
============> Got Choice: Center #1, Slot #2
Booking with info: {'beneficiaries': ['16592039717030', '42826462064420', '10234024702910', '19209382851510'], 'dose': 1, 'center_id': 693681, 'session_id': '46ddb4f4-0ade-4c63-a79b-e3c95e2bf6bb', 'slot': '04:00PM-05:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
making request to createTask
colinear!
colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
created task with id 22719514
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task solved
Captcha text: xqebr
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
===================================================================================

**Comment by vasugamdha** [comment]
Ah! Bad Luck!!
Do the automation till captcha and solve the captcha yourself.

**Comment by rajushinde451** [comment]
But if you see 2nd 3rd and 4th attempt, we are getting error while slots are available.

**Comment by sumit2k21** [comment]
#122 need 2captcha integration.

**Comment by bombardier-gif** [comment]
1. The cowin captcha itself is a bit buggy so even if you enter correct one manually there will be errors
2. This is a case of someone booking faster than you. 
2captcha will not solve the above.
