### ISSUE TITLE
Unable to detect slots

### ISSUE THREAD

**Issue by shanksmu** [bombardier-gif/covid-vaccine-booking#138]
I have been running this application continuously since morning to book a slot in Bangalore. On the last two occasions, the script was unable to detect open slots.
I was notified by telegram/Twitter that slots got opened today, however, the script did not detect it. 
I double-checked on the Cowin portal and slots were available and got filled

the script is set to ping at a 1-second interval, any thoughts?

**Comment by vesan83** [comment]
Yesterday i had started the script to detect slots in Mumbai and Thane both, it was unable to detect slots when two regions were working together.

later i shifted to only Mumbai and was able to detect the slots but was slow for booking it so got filled.

is the script working fine when two regions/cities are selected ? anyone had lick with it when  two regions/cities (mumbai and thane) are selected ?

**Comment by subashjain** [comment]
from yesterday evening i missed all slots opened in BBMP
not at all catching slots, all most all 5 centre opened 200 and 100 slots

**Comment by shanksmu** [comment]
N

> from yesterday evening i missed all slots opened in BBMP
> not at all catching slots, all most all 5 centre opened 200 and 100 slots

Same here, I just missed the Apollo slots which got opened.

**Comment by shanksmu** [comment]
> Yesterday i had started the script to detect slots in Mumbai and Thane both, it was unable to detect slots when two regions were working together.
> 
> later i shifted to only Mumbai and was able to detect the slots but was slow for booking it so got filled.
> 
> is the script working fine when two regions/cities are selected ? anyone had lick with it when two regions/cities (mumbai and thane) are selected ?

I got only 1 state and 1 district, the script seems to be running fine.

**Comment by vesan83** [comment]
> > Yesterday i had started the script to detect slots in Mumbai and Thane both, it was unable to detect slots when two regions were working together.
> > later i shifted to only Mumbai and was able to detect the slots but was slow for booking it so got filled.
> > is the script working fine when two regions/cities are selected ? anyone had lick with it when two regions/cities (mumbai and thane) are selected ?
> 
> I got only 1 state and 1 district, the script seems to be running fine.

How about 1 state and 2 districts ? does the script support it ?

**Comment by subashjain** [comment]
> > Yesterday i had started the script to detect slots in Mumbai and Thane both, it was unable to detect slots when two regions were working together.
> > later i shifted to only Mumbai and was able to detect the slots but was slow for booking it so got filled.
> > is the script working fine when two regions/cities are selected ? anyone had lick with it when two regions/cities (mumbai and thane) are selected ?
> 
> I got only 1 state and 1 district, the script seems to be running fine.
I also selected  1 state 1 district but still missed slots

**Comment by shanksmu** [comment]
> > > Yesterday i had started the script to detect slots in Mumbai and Thane both, it was unable to detect slots when two regions were working together.
> > > later i shifted to only Mumbai and was able to detect the slots but was slow for booking it so got filled.
> > > is the script working fine when two regions/cities are selected ? anyone had lick with it when two regions/cities (mumbai and thane) are selected ?
> > 
> > 
> > I got only 1 state and 1 district, the script seems to be running fine.
> 
> How about 1 state and 2 districts ? does the script support it ?

yes, the script works with 2 districts

**Comment by BumpyKnuckls** [comment]
Would suggest to try it for 1-2 days more. Many of us have had a similar experience because there are many others running some script, so its possible that slots get filled quite fast. 

Feel free to report again if it continues to be an issue

**Comment by subashjain** [comment]
> Would suggest to try it for 1-2 days more. Many of us have had a similar experience because there are many others running some script, so its possible that slots get filled quite fast.
> 
> Feel free to report again if it continues to be an issue

im facing it from 2 days

**Comment by vasugamdha** [comment]
> Yesterday i had started the script to detect slots in Mumbai and Thane both, it was unable to detect slots when two regions were working together.
> 
> later i shifted to only Mumbai and was able to detect the slots but was slow for booking it so got filled.
> 
> is the script working fine when two regions/cities are selected ? anyone had lick with it when two regions/cities (mumbai and thane) are selected ?

@vesan83 Not sure about the district option but if you narrow it down by a few nearby pincodes, it might retrieve faster and you might get a little faster than previous tries. It's worth a shot. It worked for me with 3 pincodes.

**Comment by vasugamdha** [comment]
Free advice:
Note down the particular time when the slots at the particular pincode open; there is a pattern. 
Observe for few days; note the pattern; run the script, and if possible keep entering the captchas yourself (I know you are faster than anti-captcha). There will be series of captcha popping one after another and you have to keep solving it. When @bombardier-gif merges #136, you just have to continuously enter captchas instead of "clicking and entering", and you will be faster.  (wait for it to merge or make changes in the code by yourself now).

**Comment by mnjit007** [comment]
Search by district seems to be broken. I checked the portal and found a free slot which was also verified by the below call but the script showed 0 slots

Request:
```
https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=726&date=15-05-2021&vaccine=COVISHIELD

```

Part of the json response
```
{"center_id":616400,"name":"Tofi SC","address":"Tofi Bangitola","state_name":"West Bengal","district_name":"Malda","block_name":"Kaliachak II","pincode":732207,"lat":0,"long":0,"from":"10:00:00","to":"16:00:00","fee_type":"Free","sessions":[{"session_id":"95579df4-8934-47b0-87e3-031b4e89ca54","date":"19-05-2021","available_capacity":2,"min_age_limit":45,"vaccine":"COVISHIELD","slots":["10:00AM-11:00AM","11:00AM-12:00PM","12:00PM-01:00PM","01:00PM-04:00PM"]}

```

Response from the script during the time :

```
===================================================================================
Centers available in Malda from 2021-05-15 as of 2021-05-14 14:26:29: 0
Centers available in North 24 Parganas from 2021-05-15 as of 2021-05-14 14:26:29: 0
```

While using Pincode, it was able to detect the slot but after entering the captcha I was getting 

```
x_order_2: colinear!
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 500
Booking Response : {}
Response: 500 : {}
===================================================================================
```

**Comment by shailesh** [comment]
> Free advice:
> Note down the particular time when the slots at the particular pincode open; there is a pattern.
> Observe for few days; note the pattern; run the script, and if possible keep entering the captchas yourself (I know you are faster than anti-captcha). There will be series of captcha popping one after another and you have to keep solving it. When @bombardier-gif merges #136, you just have to continuously enter captchas instead of "clicking and entering", and you will be faster. (wait for it to merge or make changes in the code by yourself now).

```
Opening test window. Click on "Quit" to run further tests
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Failed to load input file! (Error reading file 'captcha.svg': failed to load external entity "captcha.svg")
Traceback (most recent call last):
  File "tests/captcha_tests.py", line 99, in <module>
    test_captcha_builder()
  File "tests/captcha_tests.py", line 11, in test_captcha_builder
    renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")
  File "/Users/shailesh14.singh/Documents/scripts/covid-vaccine-booking/venv/lib/python3.8/site-packages/reportlab/graphics/renderPM.py", line 692, in drawToFile
    c = drawToPMCanvas(d, dpi=dpi, bg=bg, configPIL=configPIL, showBoundary=showBoundary,backend=backend)
  File "/Users/shailesh14.singh/Documents/scripts/covid-vaccine-booking/venv/lib/python3.8/site-packages/reportlab/graphics/renderPM.py", line 676, in drawToPMCanvas
    d = renderScaledDrawing(d)
  File "/Users/shailesh14.singh/Documents/scripts/covid-vaccine-booking/venv/lib/python3.8/site-packages/reportlab/graphics/renderbase.py", line 153, in renderScaledDrawing
    renderScale = d.renderScale
AttributeError: 'NoneType' object has no attribute 'renderScale'
```

Getting above error @vasugamdha

**Comment by vasugamdha** [comment]
@shailesh Can you show the code?

**Comment by shailesh** [comment]
> @shailesh Can you show the code?

`def test_captcha_builder():
    from PIL import Image
    from svglib.svglib import svg2rlg
    from reportlab.graphics import renderPM
    import PySimpleGUI as sg
    import re
    #with open('captcha.svg', 'w') as f:
    #    f.write(re.sub('(<path d=)(.*?)(fill=\"none\"/>)', '', resp['captcha']))
    drawing = svg2rlg("captcha.svg")
    renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")

    im = Image.open('captcha.png')
    im = im.convert('RGB').convert('P', palette=Image.ADAPTIVE)
    im.save('captcha.gif')

    layout = [[sg.Image('captcha.gif')],
          [sg.Text("Enter Captcha Below")],
          [sg.Input(key='input')],
          [sg.Button('Submit', bind_return_key=True)]]

    print("window opening ...")
    window = sg.Window('Enter Captcha', layout, finalize=True)
    window.TKroot.focus_force()         # focus on window
    window.Element('input').SetFocus()  # focus on field
    event, values = window.read()
    window.close()

    captcha_value = values['input']
    expected_captcha_value = "SNNvu"
    if captcha_value == expected_captcha_value:
        print("Yeah !!! you have entered captcha. This means you are all set to render required captcha at the time of booking ...\n")
    else:
        print("\nOhh NO !!! you have entered wrong captcha : %s while expected: %s" % (captcha_value, expected_captcha_value))
        print("Check if you are missing any required python packages\n\n")

def test_captcha_builder_auto(api_key):
    from PIL import Image
    from svglib.svglib import svg2rlg
    from reportlab.graphics import renderPM
    from anticaptchaofficial.imagecaptcha import imagecaptcha
    import re, time
    drawing = svg2rlg('captcha.svg')
    renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")

    solver = imagecaptcha()
    solver.set_verbose(1)
    solver.set_key(api_key)

    print("Started solving captcha...")
    tic = time.perf_counter()
    captcha_text = solver.solve_and_return_solution("captcha.png")
    toc = time.perf_counter()

    if captcha_text == "SNNvu":
        print(f"Captcha solve success: {captcha_text}")
        print(f"It took {toc - tic:0.4f} seconds to solve captcha")
    else:
        print(f"Task finished with error: {solver.error_code} - {captcha_text}")

    return captcha_text

def test_python_packages():
    try:
        from PIL import Image
        from svglib.svglib import svg2rlg
        from reportlab.graphics import renderPM
        import PySimpleGUI as sg
        import re
    except Exception:
        print("\n!!!!! Looks like you are missing required python packages. Please look at requirements.txt !!!!")
        exit(1)

def test_tkinter_lib():
    try:
        from PIL import Image
        from svglib.svglib import svg2rlg
        from reportlab.graphics import renderPM
        import PySimpleGUI as sg
        import re
    except Exception:
        print("\n!!!!! Looks like you are missing required python packages. Please look at requirements.txt !!!!")
        exit(1)
    try:
        import tkinter
        tkinter_version = tkinter.Tcl().eval('info patchlevel')
        print("Installed tkinter_version: %s \n %s" % (tkinter_version, "-"*100))
        print('Opening test window. Click on "Quit" to run further tests')
        tkinter._test()
    except Exception:
        print("\n!!!!! Looks like you are missing required 'tkinter' python package !!!!")
        print("Try installing looking at following resources:")
        print("1. https://tkdocs.com/tutorial/install.html#install-win-python")
        print("2. https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter")
        print()
        exit(1)


# test_python_packages()
# test_tkinter_lib()
test_captcha_builder()
# test_captcha_builder_auto("APIKEY") #http://anti-captcha.com`

**Comment by shailesh** [comment]
> @shailesh Can you show the code?

```
def test_captcha_builder():
    from PIL import Image
    from svglib.svglib import svg2rlg
    from reportlab.graphics import renderPM
    import PySimpleGUI as sg
    import re
    #with open('captcha.svg', 'w') as f:
    #    f.write(re.sub('(<path d=)(.*?)(fill=\"none\"/>)', '', resp['captcha']))
    drawing = svg2rlg("captcha.svg")
    renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")

    im = Image.open('captcha.png')
    im = im.convert('RGB').convert('P', palette=Image.ADAPTIVE)
    im.save('captcha.gif')

    layout = [[sg.Image('captcha.gif')],
          [sg.Text("Enter Captcha Below")],
          [sg.Input(key='input')],
          [sg.Button('Submit', bind_return_key=True)]]

    print("window opening ...")
    window = sg.Window('Enter Captcha', layout, finalize=True)
    window.TKroot.focus_force()         # focus on window
    window.Element('input').SetFocus()  # focus on field
    event, values = window.read()
    window.close()

    captcha_value = values['input']
    expected_captcha_value = "SNNvu"
    if captcha_value == expected_captcha_value:
        print("Yeah !!! you have entered captcha. This means you are all set to render required captcha at the time of booking ...\n")
    else:
        print("\nOhh NO !!! you have entered wrong captcha : %s while expected: %s" % (captcha_value, expected_captcha_value))
        print("Check if you are missing any required python packages\n\n")

def test_captcha_builder_auto(api_key):
    from PIL import Image
    from svglib.svglib import svg2rlg
    from reportlab.graphics import renderPM
    from anticaptchaofficial.imagecaptcha import imagecaptcha
    import re, time
    drawing = svg2rlg('captcha.svg')
    renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")

    solver = imagecaptcha()
    solver.set_verbose(1)
    solver.set_key(api_key)

    print("Started solving captcha...")
    tic = time.perf_counter()
    captcha_text = solver.solve_and_return_solution("captcha.png")
    toc = time.perf_counter()

    if captcha_text == "SNNvu":
        print(f"Captcha solve success: {captcha_text}")
        print(f"It took {toc - tic:0.4f} seconds to solve captcha")
    else:
        print(f"Task finished with error: {solver.error_code} - {captcha_text}")

    return captcha_text

def test_python_packages():
    try:
        from PIL import Image
        from svglib.svglib import svg2rlg
        from reportlab.graphics import renderPM
        import PySimpleGUI as sg
        import re
    except Exception:
        print("\n!!!!! Looks like you are missing required python packages. Please look at requirements.txt !!!!")
        exit(1)

def test_tkinter_lib():
    try:
        from PIL import Image
        from svglib.svglib import svg2rlg
        from reportlab.graphics import renderPM
        import PySimpleGUI as sg
        import re
    except Exception:
        print("\n!!!!! Looks like you are missing required python packages. Please look at requirements.txt !!!!")
        exit(1)
    try:
        import tkinter
        tkinter_version = tkinter.Tcl().eval('info patchlevel')
        print("Installed tkinter_version: %s \n %s" % (tkinter_version, "-"*100))
        print('Opening test window. Click on "Quit" to run further tests')
        tkinter._test()
    except Exception:
        print("\n!!!!! Looks like you are missing required 'tkinter' python package !!!!")
        print("Try installing looking at following resources:")
        print("1. https://tkdocs.com/tutorial/install.html#install-win-python")
        print("2. https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter")
        print()
        exit(1)


# test_python_packages()
# test_tkinter_lib()
test_captcha_builder()
# test_captcha_builder_auto("APIKEY") #http://anti-captcha.com
```

**Comment by vasugamdha** [comment]
@shailesh I just ran your code, and it works well. I am using python 3.9.2. You installed the requirements.txt, right? I am using python 3.9.2.

**Comment by shailesh** [comment]
> @shailesh I just ran your code, and it works well. I am using python 3.9.2. You installed the requirements.txt, right?

yes have installed it. I'm running on python 3.8

**Comment by shailesh** [comment]
> @shailesh I just ran your code, and it works well. I am using python 3.9.2. You installed the requirements.txt, right?

same error with 9. I'm on Mac OS

**Comment by vasugamdha** [comment]
Try changing the directory to tests/ and then run it.

**Comment by shailesh** [comment]
> Try going in the directory tests/ and then run it.

Actually not able to read file from directory tried this too

`Failed to load input file! (Error reading file 'captcha.svg': failed to load external entity "captcha.svg")`

**Comment by vasugamdha** [comment]
captcha.svg is in the same folder (tests/).

**Comment by shailesh** [comment]
> captcha.svg is in the same folder (tests/).
> Out of ideas. I think you should close this as it is going off-topic for this issue #138 and add the way you worked out to #153.

yes same folder

**Comment by shanksmu** [comment]
The script missed to detect another slot which got opened in Bangalore. I got informed via Telegram and tweet.

**Comment by Nakul93** [comment]
As discussed in #155 is the age filter causing an issue? @shanksmu does the centre you are booking for opens up slots for both 18+ and 45+ simultaneously?

**Comment by shanksmu** [comment]
I don't see 45+ slots for my center. Only 18+

![image](https://user-images.githubusercontent.com/84128838/118301878-33961280-b501-11eb-89aa-e8965be86102.png)

**Comment by viveka111** [comment]
ok guys I know why is this happening so since Private hospitals are opening their slots simultaneous for 45 and 18 + age brackets  the script is not iterating into sessions so it checks 45+ wala session it moves out of the function and removes every thing

**Comment by Nakul93** [comment]
> ok guys I know why is this happening so since Private hospitals are opening their slots simultaneous for 45 and 18 + age brackets the script is not iterating into sessions so it checks 45+ wala session it moves out of the function and removes every thing

Yeah exactly, and I believe it should remove the session_id rather than the center itself

**Comment by shailesh** [comment]
What is this mentioned on the Cowin booking page, maybe they do not allow this?

`To add multiple individuals in a single Dose 2 appointment, the vaccine and Dose 1 date must be the same.`

**Comment by bombardier-gif** [comment]
Thanks for the insight @viveka111 and @Nakul93 Could you please provide a patch for the fix?

**Comment by dap-123** [comment]
> > ok guys I know why is this happening so since Private hospitals are opening their slots simultaneous for 45 and 18 + age brackets the script is not iterating into sessions so it checks 45+ wala session it moves out of the function and removes every thing
> 
> Yeah exactly, and I believe it should remove the session_id rather than the center itself

Correct, this is the solution.

**Comment by dap-123** [comment]
@bombardier-gif I've implemented the fix to this. Will test it and create the PR in some time.

**Comment by viveka111** [comment]
@dap-123  can u share the fix

**Comment by dap-123** [comment]
Created the PR#[167](https://github.com/bombardier-gif/covid-vaccine-booking/pull/167)
