### ISSUE TITLE
Can we have support without the SMS Trigger ? 

### ISSUE THREAD

**Issue by jalotra** [bombardier-gif/covid-vaccine-booking#14]
I think some people will have difficulty in setting up IFTTT.  What do you think about it ?

**Comment by SherKhan9686** [comment]
IFTTT works well for me

**Comment by bombardier-gif** [comment]
The entire point of this project was to automate this. If you dont wat automatic triger than please use the original repo
https://github.com/pallupz/covid-vaccine-booking
