### ISSUE TITLE
captcha_builder() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by itsAkshayDubey** [bombardier-gif/covid-vaccine-booking#140]
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
captcha_builder() takes 0 positional arguments but 1 was given

**Comment by itsAkshayDubey** [comment]
I resolved with following code in captcha.py:

`def captcha_builder(self):
#with open('captcha.svg', 'w') as f:
#f.write(re.sub('(<path d=)(.*?)(fill="none"/>)', '', resp['captcha']))

    drawing = svg2rlg('captcha.svg')
    renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")

    im = Image.open('captcha.png')
    im = im.convert('RGB').convert('P', palette=Image.ADAPTIVE)
    im.save('captcha.gif')

    layout = [[sg.Image('captcha.gif')],
        [sg.Text("Enter Captcha Below")],
        [sg.Input()],
        [sg.Button('Submit', bind_return_key=True)]]

    window = sg.Window('Enter Captcha', layout)
    event, values = window.read()
    window.close()
    return values[1]`
    
    
    now getting below error:
Captcha Response Code: 200
colinear!
colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
colinear!
colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!

**Comment by bombardier-gif** [comment]
Are you seeing it again  and again ?

**Comment by BumpyKnuckls** [comment]
Closing it due to inactivity. Please feel free to reopen it
