### ISSUE TITLE
captcha solve error image format not supported

### ISSUE THREAD

**Issue by vegeta78** [bombardier-gif/covid-vaccine-booking#143]
![image](https://user-images.githubusercontent.com/16041379/118218797-cf8a3480-b495-11eb-85c2-e9685263d0c4.png)
Its error from anti-captcha

**Comment by rajushinde451** [comment]
Yes, I am also getting same error

**Comment by bombardier-gif** [comment]
Do you know what was the format of image which was uploaded?

**Comment by BumpyKnuckls** [comment]
Closing it due to inactivity. Please feel free to reopen it.
