### ISSUE TITLE
Display both the captchas, cleaned and uncleaned ones side by side as fallback. 

### ISSUE THREAD

**Issue by kanadenipun** [bombardier-gif/covid-vaccine-booking#145]
The captcha image at times is blacked out 

Can we print the 2 images side by side ?
Other suggestion is to have a button to request for a new captcha
Can we also skip printing logs of captcha cleaning. these are pollution the console. 
Is it possible to display the booking center name in the captcha window?

**Comment by vasugamdha** [comment]
> Can we print the 2 images side by side ?

Yeah, you can just copy-paste it twice in [`src/captcha.py`](https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/src/captcha.py)
```
.
.
drawing = svg2rlg('captcha.svg')  
renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")  
drawing2 = svg2rlg('captcha2.svg')  
renderPM.drawToFile(drawing2, "captcha2.png", fmt="PNG")  
  
im = Image.open('captcha.png')  
im2 = Image.open('captcha2.png')
im = im.convert('RGB').convert('P', palette=Image.ADAPTIVE)
im2 = im.convert('RGB').convert('P', palette=Image.ADAPTIVE)
im.save('captcha.gif')
im2.save('captcha2.gif')

layout = [[sg.Image('captcha.gif')],[sg.Image('captcha.gif')],
[sg.Text("Enter Captcha Below")], ...
.
.
```
 


> Other suggestion is to have a button to request for a new captcha

I guess hitting the 'enter key', indirectly requests a new captcha.

> Can we also skip printing logs of captcha cleaning. these are pollution the console.

True that.

> Is it possible to display the booking center name in the captcha window?

It is possible to print the booking center name, but reading the center name and then entering the captcha might slow you down, and reduce your chances of booking an appointment there.

**Comment by bombardier-gif** [comment]
These are good enhancements. I am pinning these issues i anyone wants to contribute.
Overall i like verbose logs as its easier to debug if someone is facing errors. At this moment its quite touch to fix bugs.

**Comment by shailesh** [comment]
@bombardier-gif close this

**Comment by BumpyKnuckls** [comment]
+1 Dont think this is needed with the ease of automated captcha ;)

**Comment by shailesh** [comment]
got it :)
