### ISSUE TITLE
excellent works sir 

### ISSUE THREAD

**Issue by Gmansign** [bombardier-gif/covid-vaccine-booking#147]
I tried two times and two times booked the slot. Thank you Sir

**Comment by Gmansign** [comment]
two times slot booked using two district selected. Excellent works sir

**Comment by sumit2k21** [comment]
If we have booked a slot, but we want to rebook it in a different center. So we need to cancel the appointment first ? or if we just run the bot it will reschedule it ? 
Bot reschedules appointment automatically ? or we need to cancel from the cowin manually and re run the bot to book again ?

**Comment by Gmansign** [comment]
Re run the bot than automatically rescheduled.

**Comment by bombardier-gif** [comment]
> If we have booked a slot, but we want to rebook it in a different center. So we need to cancel the appointment first ? or if we just run the bot it will reschedule it ?
> Bot reschedules appointment automatically ? or we need to cancel from the cowin manually and re run the bot to book again ?

My assmption is that you have to cancel the appointment. if you want to hold the booking there is one trick:
Register on another mobile number,using some other ID such as pancard, election, etc. That works.
