### ISSUE TITLE
Can you explain why do you want to choose random rows and cols ?

### ISSUE THREAD

**Issue by jalotra** [bombardier-gif/covid-vaccine-booking#15]
``` 
  randrow = random.randint(1, len(options))
  randcol = random.randint(1, len(options[randrow - 1]["slots"]))
  choice = str(randrow) + "." + str(randcol)
  print("Random Rows.Column:" + choice)
```
Do we have support for choosing a center within a Pincode? And if not can we implement that?
 Because in my area, centers are very far away from each other so it doesn't make sense to randomize choosing Centres.

**Comment by bombardier-gif** [comment]
The thought process is that ::

1. the original bot tried to book the first slot. So all the people who use the bot are competing for the same slot
2. At this moment I and my friends are ok with any slot and anywhere, so randomization gives a very good chance in the concurrent booking enironment.

**Comment by bombardier-gif** [comment]
And to your original question you can search by a pincode in the options 
        """Search by Pincode? Or by State/District? \nEnter 1 for Pincode or 2 for State/District. (Default 2) : """

**Comment by jalotra** [comment]
Cool thanks
