### ISSUE TITLE
Captcha response 200

### ISSUE THREAD

**Issue by Gmansign** [bombardier-gif/covid-vaccine-booking#152]
Captcha response 200 error plz resolve

**Comment by Gmansign** [comment]
showing error 

================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0045", "error":"Your transaction didn't go through. Please try again later"}
Response: 400 : {"errorCode":"APPOIN0045", "error":"Your transaction didn't go through. Please try again later"}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
colinear!
colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!

**Comment by bunduuk** [comment]
If you are using anti-captcha to auto fill the captcha, you need to get the demo balance first before adding the api key, in this script. This should remove the error.

**Comment by bombardier-gif** [comment]
Interesting inputs @bunduuk thanks! I will pin this issue.

**Comment by kritchadha** [comment]
> Captcha response 200 error plz resolve

please resolve this fast

**Comment by nirbhay18** [comment]
Please resolve this fast. It is happening even when auto captcha is not enabled.

**Comment by dasanupam** [comment]
Still getting this issue even when selecting no for captcha autofill.

 Also tried the captcha test script and that also fails. First it shows passed and then again shows the following errors message 

Installed tkinter_version: 8.6.9
 ----------------------------------------------------------------------------------------------------
Opening test window. Click on "Quit" to run further tests
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
window opening ...
Yeah !!! you have entered captcha. This means you are all set to render required captcha at the time of booking ...

x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
Started solving captcha...
making request to createTask
could not create task
API error ERROR_KEY_DOES_NOT_EXIST: Account authorization key not found in the system
Task finished with error: ERROR_KEY_DOES_NOT_EXIST - 0
