### ISSUE TITLE
Optimal Time Interval for polling

### ISSUE THREAD

**Issue by Prakhar-Shukla05** [bombardier-gif/covid-vaccine-booking#154]
What is the value you are using for Polling the open slots for high traffic cities like Bengaluru?

**Comment by bunduuk** [comment]
Default time of 15sec shouldn’t give you any problem, also you will be able to book the slots.

**Comment by sid8840** [comment]
> What is the value you are using for Polling the open slots for high traffic cities like Bengaluru?

5 sec is also good.

**Comment by bombardier-gif** [comment]
yeah. currently the cowin system does not have aggresive rate limiting. once they implement it we are in trouble :D
