### ISSUE TITLE
Cannot book slot in centers where slots open simultaneously for 2 age groups 

### ISSUE THREAD

**Issue by viveka111** [bombardier-gif/covid-vaccine-booking#155]

**Comment by vasugamdha** [comment]
If you're selecting multiple beneficiaries, make sure all are of the same age group (45+ or 18+) as defined by the govt. Please do not try to club together booking for younger and older beneficiaries.

**Comment by viveka111** [comment]
no no some centers like Nanavati open slots for both age groups which creates conflict in the script

**Comment by vasugamdha** [comment]
Ohh! I see.

**Comment by Nakul93** [comment]
I believe it has something to do with the filter_centers_by_age func in utils.py. I think the logic where it is removing the centre in line 270( resp["centers"].remove(center)) its probably removing centres for all ages maybe. I might be wrong but the function seems a bit dodgy

**Comment by viveka111** [comment]
yup even i think the same

**Comment by bombardier-gif** [comment]
This seems to be a buggy implementation of the filtering by age: 
@dap-123 and @ayushanshul07  could you please help fix this logic?

**Comment by viveka111** [comment]
def filter_centers_by_age(resp, min_age_booking):

    flag=0    
    if min_age_booking >= 45:
        center_age_filter = 45
    else:
        center_age_filter = 18
    resp_temp=copy.deepcopy(resp)
    if "centers" in resp_temp:
        for center in resp_temp["centers"]:
            for seq in center["sessions"]:
                if seq['min_age_limit'] != center_age_filter:
                    flag=1
                    resp["centers"][0]["sessions"].remove(seq,)
                else:
                    flag=0
                    break
            if flag :
                resp["centers"].remove(center)

    return resp


i think this is the fix

**Comment by bombardier-gif** [comment]
@viveka111 could you please raise a PR for this?

**Comment by viveka111** [comment]
Yes

**Comment by viveka111** [comment]
@bombardier-gif how do i test this what if it doesn't work

**Comment by dap-123** [comment]
@viveka111  But at a time, the script allows to book the beneficiaries of same age grp, so you anyway have to run the script separately for booking for 18+ and 45+ beneficiaries.

**Comment by Nakul93** [comment]
@dap-123 But the current function apparently removes both age group for the same center. The issue is that when a slot opens up for both age groups at the same center it shows 0 centers available, it doesn't filter properly.

**Comment by viveka111** [comment]
Yes @Nakul93  can you check for thie snippet i just send is it correct how do we test it?

**Comment by dap-123** [comment]
@viveka111 On the Cowin portal, Is it showing a single row entry for that center for both 18+ and 45+ or two separate rows for the same center? Can you please attach a screenshot if possible?
Because at my place too, there are centers which are vaccinating to both 18+ and 45+, but they appear as 2 different rows on Cowin, i.e, one each for 18+ and 45+ so in that case, this won't be the issue.

**Comment by viveka111** [comment]
![Uploading Screenshot_20210515-140648.jpg…]()

**Comment by Nakul93** [comment]
@dap-123 sometimes it shows up in the same row, this could be a glitch, check the screenshot below
![image](https://user-images.githubusercontent.com/24492930/118354026-b3b28b80-b586-11eb-82ca-ee4ac5d54a9a.png)

Also the filter_centers_by_age returns a center with both 18+ and 45+ slots, shouldn't it filter them

**Comment by viveka111** [comment]
It is not a glitch it is a feature by cowin which is used by private hospitals

**Comment by dap-123** [comment]
Created the PR#[167 ](https://github.com/bombardier-gif/covid-vaccine-booking/pull/167)for the fix to this.
