### ISSUE TITLE
Is there a way to make the beep louder? like a buzzer/siren sound

### ISSUE THREAD

**Issue by mnjit007** [bombardier-gif/covid-vaccine-booking#156]
Is there a way to make the beep louder? like a buzzer/siren sound. I am trying to book a slot and missing the captcha everytime. A loud sound would attract attention and will be able to book slots more easily

**Comment by mnjit007** [comment]
was able to solve it for myself  :) installed `playsound` and replaced 
```
def beep(freq, duration):
        threading.Thread(target=playsound, args=('src/siren.wav',), daemon=True).start()
```

**Comment by gitmnj** [comment]
Can you please elaborate how you did

**Comment by mnjit007** [comment]
1. First download a free siren wav file. Lots of free options here : https://mixkit.co/free-sound-effects/siren/
2. Rename it to `siren.wav` and keep it in the folder covid-vaccine-booking-main/src
3. Open file `covid-vaccine-booking-main/src/utils.py` using any text editor
4. Replace line 43 with `threading.Thread(target=playsound, args=('src/siren.wav',), daemon=True).start()` and save the file
5. Now run your main application as you would usually do

**Comment by AanchalV** [comment]
Getting the following error:

Traceback (most recent call last):
  File "covid-vaccine-slot-booking.py", line 132, in <module>
    main()
  File "covid-vaccine-slot-booking.py", line 20, in main
    beep(500, 150)
  File "C:\Users\Admin\Downloads\covid-vaccine-booking-main5\src\utils.py", line 41, in beep
    threading.Thread(target=playsound, args=('src/siren.wav',), daemon=True).start()
NameError: name 'threading' is not defined

**Comment by gitmnj** [comment]
![image](https://user-images.githubusercontent.com/66999015/118392445-66521f00-b657-11eb-83c8-a5dd243caa89.png)

**Comment by shailesh** [comment]
import threading

**Comment by gitmnj** [comment]
![image](https://user-images.githubusercontent.com/66999015/118395098-424a0a00-b666-11eb-980c-edecb3c7b1f0.png)

**Comment by mnjit007** [comment]
@gitmnj @AanchalV I updated my answer. Basically missed to mention that you need to add an import statement `import threading` in the `utils.py` file.

**Comment by shailesh** [comment]
> import threading

@mnjit007 I hope this helped

**Comment by gitmnj** [comment]
![image](https://user-images.githubusercontent.com/66999015/118406711-a090e000-b69a-11eb-9561-f295a5c5d013.png)

**Comment by gitmnj** [comment]
please I request you to send me a copy of the working program at https://t.me/manojchauhan16

**Comment by shailesh** [comment]
@gitmnj take a look at this 
https://stackoverflow.com/questions/53246933/python-execute-playsound-in-separate-thread

**Comment by gitmnj** [comment]
sir please i request you to send me the code at https://t.me/manojchauhan16 since I'm a beginner

**Comment by AanchalV** [comment]
Thanks. I worked

**Comment by NK0211** [comment]
can you help me with copy of your utils.py @mnjit007 @AanchalV @gitmnj @
