### ISSUE TITLE
Getting error "object is not iterable"

### ISSUE THREAD

**Issue by Samargup** [bombardier-gif/covid-vaccine-booking#157]
I configured the script to check for free slots every 6 seconds.

Get following error after every 1-2 hours:

('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))
'NoneType' object is not iterable

**Comment by bunduuk** [comment]
I think that’s because of the rate limit set by the api, which is 100 calls per 5 minutes. I haven’t had problem with 15sec or even with 10sec.

**Comment by bombardier-gif** [comment]
It is rate limiting. Try lower frequency
