### ISSUE TITLE
Giving today as date is not working . 

### ISSUE THREAD

**Issue by Prakhar-Shukla05** [bombardier-gif/covid-vaccine-booking#158]
Giving today as the date script is not able to do anything on active slots . Missed Apollo slots for Bengaluru.
===================================================================================
Centers available in BBMP from 15-05-2021 as of 2021-05-15 07:39:59: 3
===================================================================================
Centers available in BBMP from 15-05-2021 as of 2021-05-15 07:40:15: 3
===================================================================================
Centers available in BBMP from 15-05-2021 as of 2021-05-15 07:40:30: 3

**Comment by sid8840** [comment]
I have booked 2 slots with only one captcha attempt by myself.
and the slots got vanished within 3 sec.

**Comment by bombardier-gif** [comment]
It does miss slots. thats the problem with the API itself. nothing much we can do here :(
