### ISSUE TITLE
OTP Receiver issue

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#159]
I was able to receive OTP every 3 min at night but between 2 am to 6 am no OTP was sent to script via tp receiver. Woke up and saw this.
```
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
```
After 6 am automatically script started receiving OTP but missed the slot booking due to this issue.

**Comment by sid8840** [comment]
> I was able to receive OTP every 3 min at night but between 2 am to 6 am no OTP was sent to script via tp receiver. Woke up and saw this.
> 
> ```
> OTP SMS len is:0
> OTP SMS is:
> OTP SMS len is:0
> OTP SMS is:
> OTP SMS len is:0
> ```
> 
> After 6 am automatically script started receiving OTP but missed the slot booking due to this issue.

I think you must disable adaptive Battery manager under the battery setting.

**Comment by shailesh** [comment]
Already it was disabled.

**Comment by bombardier-gif** [comment]
Did you get OTP sms during this time?

**Comment by shailesh** [comment]
> Did you get OTP SMS during this time?

Yes

**Comment by bunduuk** [comment]
There can be N number of reasons, but the major issue would be the device went into sleep mode. I would suggest you open the app intermittently after every 1 hour and bring it to foreground.

There are different flavours of android, and few flavours still do aggressive battery saving even after disabling power saver mode.

**Comment by bombardier-gif** [comment]
Thanks @bunduuk for the tips,
I am closing this ticket as nothing much we can do there.
