### ISSUE TITLE
Still getting error with validate OTP

### ISSUE THREAD

**Issue by SherKhan9686** [bombardier-gif/covid-vaccine-booking#16]
Requesting OTP with mobile number xxxxxxxxxxxxx..
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:Your OTP to register/access CoWIN is 200768. It will be valid for 3 minutes. - CoWIN 
OTP SMS len is:85
Parsed OTP:200768 
Validating OTP..
Unable to Validate OTP
{ "errorCode": "USRAUT0014", "error": "Invalid OTP" }
clearing OTP bucket: https://kvdb.io/3YgXf9PHYHbX6NsF7zP6Us/xxxxxxxxxxxxxxxxxx
Requesting OTP with mobile number xxxxxxxxxxxxxxx..

**Comment by bombardier-gif** [comment]
Was this the only instance being run i.e. you did not use the cowin site on the side or ran another script?

**Comment by SherKhan9686** [comment]
This is the only instance

**Comment by bombardier-gif** [comment]
Is it still not working?

**Comment by SherKhan9686** [comment]
No it is isn't. Getting the same error.

**Comment by SherKhan9686** [comment]
The original script https://github.com/pallupz/covid-vaccine-booking is working fine...

**Comment by SherKhan9686** [comment]
I solved this by changing by changing line 801 of utils.py as 

`data = {"otp": sha256(str(**_OTP.strip()_**).encode("utf-8")).hexdigest(), "txnId": txnId}`

**Comment by bombardier-gif** [comment]
Thanks! I updated the code
