### ISSUE TITLE
captha screen not coming up in Mac

### ISSUE THREAD

**Issue by mohitkgec** [bombardier-gif/covid-vaccine-booking#160]
Getting Captcha Response Code: 200 but no separate window coming up to enter captha

<img width="1095" alt="Screen Shot 2021-05-15 at 9 35 30 AM" src="https://user-images.githubusercontent.com/20751630/118347421-e6e22400-b560-11eb-8d95-958f2b1b3bb2.png">

**Comment by Nakul93** [comment]
Did you install python tkinter package on your Mac?
Just run `brew install python-tk`

**Comment by mohitkgec** [comment]
@Nakul93 Yes it is already installed. How long does it take to get the captha window ? does anyone have the screenshot ?

<img width="539" alt="Screen Shot 2021-05-15 at 10 21 28 AM" src="https://user-images.githubusercontent.com/20751630/118348367-65da5b00-b567-11eb-8204-003e3ee88a09.png">

**Comment by Nakul93** [comment]
It takes around 2-3 seconds. Try running the test script for captcha to check. Its in /tests folder. Also check if you are using the latest python 
This is how it looks on my Mac
![image](https://user-images.githubusercontent.com/24492930/118348708-c2d71080-b569-11eb-89f1-7828b55d1902.png)

**Comment by mohitkgec** [comment]
@Nakul93 Thanks for the details. 

I ran the test script as mentioned. Before getting the captha screen i get a intermediate screen (tk screen) and have to select quit, then captcha screen pops up

<img width="1679" alt="Screen Shot 2021-05-15 at 10 51 57 AM" src="https://user-images.githubusercontent.com/20751630/118349057-09c60580-b56c-11eb-9d29-e8068aff90fe.png">


![Uploading Screen Shot 2021-05-15 at 10.56.11 AM.png…]()

**Comment by mohitkgec** [comment]
@Nakul93 Could you please your tinker and python version details. Also, the screenshot when you run the captcha script ? maybe i need to upgrade tinker package version

**Comment by chetan1989-cloud** [comment]
I have not had a chance to book a slot yet so not sure if captcha window is popping up or not. But when I try to run the test python script I also have to click quit before I get the window, am I hitting the same problem?

**Comment by Nakul93** [comment]
@mohitkgec I'm using Python version 3.9.4 and tkinter-3.9.4. So while running the tests I also got a window where I had click quit before the captcha window pops up. I've booked 3 slots and captcha window pops up normally in the main script

**Comment by chetan1989-cloud** [comment]
My python and tkinter version:
D:\covid-vaccine-booking-main\tests>python -V
Python 3.9.1

D:\covid-vaccine-booking-main\tests>python captcha_tests.py
Installed tkinter_version: 8.6.9
 ----------------------------------------------------------------------------------------------------
Opening test window. Click on "Quit" to run further tests

**Comment by shailesh** [comment]
I was running the test yesterday though I was not able to run and I was getting the same screen Quit because it was not able to find the path of captcha. In your captcha test please provide the full path

`/Users/************/Documents/scripts/covid-vaccine-booking/tests/captcha.png`

I then tried booking a slot from a random location to test if it works and I was able to book and pop up occurred for captcha.

**Comment by Nakul93** [comment]
> It takes around 2-3 seconds. Try running the test script for captcha to check. Its in /tests folder. Also check if you are using the latest python
> This is how it looks on my Mac
> ![image](https://user-images.githubusercontent.com/24492930/118348708-c2d71080-b569-11eb-89f1-7828b55d1902.png)

@mohitkgec if your getting the captcha window(along with that other window) in tests then it should work fine in the main script

**Comment by vasugamdha** [comment]
> @Nakul93 Thanks for the details.
> 
> I ran the test script as mentioned. Before getting the captcha screen i get a intermediate screen (tk screen) and have to select quit, then captcha screen pops up

@mohitkgec @chetan1989-cloud That window with the Quit option is for checking if you have successfully installed all the packages. It won't pop up when the main script is running. 
At the end of the code [`captcha_tests.py`](https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/tests/captcha_tests.py), there is a function call of `test_tkinter_lib()`, which pops the window with quit button. If you have entered the mentioned packages properly you can comment that call and will work smoothly.

And the last 2 function calls are for testing the captcha screen without anti-captcha and with anti-captcha, respectively. So, run any one of them while testing running that file.

**Comment by bombardier-gif** [comment]
I am closing this issue for clearing my dashboard. You can still continue the discussion here.
