### ISSUE TITLE
Bypass captcha code

### ISSUE THREAD

**Issue by Gmansign** [bombardier-gif/covid-vaccine-booking#161]
Sir could u please tell this code works or not.

https://gist.github.com/christianroman/5679049

https://mathieularose.com/decoding-captchas

**Comment by shailesh** [comment]
```
from captcha_solver import CaptchaSolver
solver = CaptchaSolver('antigate', api_key='API KEY')
raw_data = open('/Users/*****/Documents/scripts/covid-vaccine-booking/tests/captcha.png', 'rb').read()
print(solver.solve_captcha(raw_data))
```

This works, the same that is implemented in the script. But I would prefer the manual as it takes time 3-4 seconds.

**Comment by bombardier-gif** [comment]
@Gmansign This is promising, but it has a high error rate, if you look at the comments in the thread you shared. 
Right now we have fully automated and a manual one. so we are covered well
The main issue is that cowins captcha itself is a bit buggy

**Comment by Gmansign** [comment]
ok sir no problem
