### ISSUE TITLE
Captcha is buggy scenario

### ISSUE THREAD

**Issue by chetan1989-cloud** [bombardier-gif/covid-vaccine-booking#162]
You have mentioned that captcha is buggy and you had to retry 5-6 times. When you say "retry" does the script automatically retries/asks for captcha or we have to exit and start the script again because that will lose us valuable time.

Also you have said not to run script in parallel and open Cowin website to avoid the captcha issue but can I open Cowin website with a different mobile number though?

Thank you for your work. I only have 1 centre in my district and it fills up super fast, just came to know about this script today and now that I think of it everbody might be already using it that's why the centre fills up so fast.

**Comment by bunduuk** [comment]
The script automatically gives you another captcha you don't need to restart the script all together. To get over with head to anti-captcha make an account, go to finance, get demo credit. 
Go to settings, get the API key, and add to the script when it asks to. You won't be needing to enter the captcha manually. 
This should make your booking faster and get you a slot.


Happy Hunting
Stay safe!

**Comment by bombardier-gif** [comment]
Agree to what @bunduuk says.

**Comment by chetan1989-cloud** [comment]
@bunduuk isn't captcha entering manually faster than the anti-captcha service?

I am sorry I am new on GitHub and not sure if commenting on this closed issue will reopen it.

**Comment by bunduuk** [comment]
I have tried to book 3 times and I was able to get a slot, though later one of the centers got cancelled, but the anti-captcha service did the job nicely. In comparison to one time where I did it manually, which I took a little more time and it went through after 3 tries.

So, I prefer anti-captcha compared to manually doing it.

I have had no problem with anti-captcha service.
