### ISSUE TITLE
CowinOTPretriver App: button turns off if put in background

### ISSUE THREAD

**Issue by anjalicse001** [bombardier-gif/covid-vaccine-booking#163]
![ezgif-1-724687533875](https://user-images.githubusercontent.com/26187367/118354316-296b2700-b588-11eb-893a-2372f55a12d3.gif)

The latest updated app has this issue.

**Comment by BumpyKnuckls** [comment]
@ujaiswal would you know?

**Comment by anjalicse001** [comment]
![ezgif-1-724687533875](https://user-images.githubusercontent.com/26187367/118354300-16f0ed80-b588-11eb-8233-16938f4535d2.gif)

**Comment by shailesh** [comment]
This happens if we kill the app completely but we just minimize it, which works fine.

**Comment by ujaiswal** [comment]
@anjalicse001 Seems like you are closing the app because of which the otp listener stops. You need to have it running in the background.

**Comment by anjalicse001** [comment]
Not closing the app, just moving to other apps which minimises the app kind of puts it in the background only. You can see it in attached gif. 
In the App:
First turn on the button.
Now pressing the central button on phone which brings us on home screen, putting all the other apps in background only in running condition. 
Now, clicked on the app again to check it. 

There is some issue in the app, some one can test this scenario. It's clearly visible in the issue details I have attached, how am I killing the app ? It gets killed if we move it side or up but that's not happening here.
Hope someone can resolve this.

**Comment by shailesh** [comment]
> Not closing the app, just moving to other apps which minimises the app kind of puts it in the background only. You can see it in attached gif.
> In the App:
> First turn on the button.
> Now pressing the central button on phone which brings us on home screen, putting all the other apps in background only in running condition.
> Now, clicked on the app again to check it.
> 
> There is some issue in the app, some one can test this scenario. It's clearly visible in the issue details I have attached, how am I killing the app ? It gets killed if we move it side or up but that's not happening here.
> Hope someone can resolve this.

Happened to me the same earlier if you try to click back or go back which brings the app in the background doesn't work. Just need t minimize without switching between apps or clicking the back button

**Comment by ujaiswal** [comment]
@anjalicse001 I tried your steps on my phone. For me the switch is not turning off when I press the central button to go to homescreen.
Seems to be a phone model specific issue.
Here are some things you could try:
1. Serach for your phone model, if there are any app optimizations which causes this app closing behaviour like maybe adaptive battery.
2. Make sure you do not have lots of apps running simultaneously. The other heavy apps need phone memory to be able to function and if you move the otp retriever app out of focus, the system will try to force close it to be able to support other actively used apps

**Comment by anjalicse001** [comment]
There is no explicit minimize option in the app, like it's there in Windows softwares. How do you minimize ? Where is the minimize button ? We only have the option of using home/ middle/ central button that puts all the other apps in background or minimises.
Anyways,
Figured out the exact bug: if after minimizing you click on the app icon again restarts the app without checking if the app is already running if the app is already running and is in minimised state it should just get that running instance, but it restarts.

Way around is to not click on app again once started. If just want to view it so press the overview button and go to app from there.

**Comment by ujaiswal** [comment]
@shailesh Back button is a closing operation which will  turn off the app which true for any other app. It does not put your app in background. You might feel that the other apps are running in background when you close the app by pressing the back button because they save the app state when you close them and reload when you open them again. This does not mean they are running in background while you closed them by pressing the back button

**Comment by bombardier-gif** [comment]
Closing this issue. You can continue the conversatio.
