### ISSUE TITLE
Centre Info Mismatch

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#164]
There is a mismatch in Name also when I tried finding this using state and district could not find this center on the Cowin portal.

**Comment by vasugamdha** [comment]
What did you set as a preference for a fee? Free, Paid, or Both. 
If you set it for both then it randomly picked the paid center and slot.

**Comment by shailesh** [comment]
> What did you set as a preference for a fee? Free, Paid, or Both.
> If you set it for both then it randomly picked the paid center and slot.

Both

**Comment by vasugamdha** [comment]
> > What did you set as a preference for a fee? Free, Paid, or Both.
> > If you set it for both then it randomly picked the paid center and slot.
> 
> Both

Yeah! Then it worked accordingly. There is no mismatch. It picked up the paid one randomly.

> There is a mismatch in Name also when I tried finding this using state and district could not find this center on the Cowin portal.

On the COWIN portal, I can clearly see the below centers with pincode and even with "State: Karnataka District: BBMP"

<img src="https://user-images.githubusercontent.com/40864108/118355458-b95f9f80-b58d-11eb-9c12-c2020ebbb446.png" width=40% height=auto>

**Comment by shailesh** [comment]
Actually, the portal is buggy if one tries to see without login which is their public API does not show actual info as that of after logging in.
