### ISSUE TITLE
SSL validation issue

### ISSUE THREAD

**Issue by akashjajoo** [bombardier-gif/covid-vaccine-booking#166]
I entered my phone number, after that I do not get the OTP.
I am getting the following SSL issue.
Is it a known issue and we already have a solution?
HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/auth/generateMobileOTP (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by bombardier-gif** [comment]
I think you got rate limited. Please try after some time
