### ISSUE TITLE
Script stuck on same center BIG ISSUE

### ISSUE THREAD

**Issue by mnbhaker** [bombardier-gif/covid-vaccine-booking#169]
Please add function to exclude center which is already booked and still shows open slotes number for 30-40 sec.

When we type capcha and it shows center is already booked but script stucks on same center because in cowin it takes aroung 30-40 sec. To update data 

So please find some way to exclude Center which we tried already

**Comment by bombardier-gif** [comment]
This is something how the APIs behave. Nothing much we can do here.
