### ISSUE TITLE
about kvdb

### ISSUE THREAD

**Issue by bilal-fazlani** [bombardier-gif/covid-vaccine-booking#17]
first of all - **brilliant idea about kvdb and sms automation**! 

Just wanted to discuss about kvdb data that is being persisted.  Some points

- Can you please update the policy of kvdb your bucket to have ttl of 3 or 5 minutes?
- Everyone is using your bucket right now. Would it be wise to ask people to create their own buckets and ask bucket id as input param?

Again, awesome work dude! 👍🏽

**Comment by bombardier-gif** [comment]
Can you email me about how did you access everyones OTP? I had secured the list API on the bucket.

**Comment by bombardier-gif** [comment]
Actually I had another solution to store the kv and people found it very tough to install it esp non-it people. 

Overall it is a genuine security issue, though the otp is tied to a session ID so it cannot be re-used by other sessions and also has a timeout associated with it. Stil i will plug the security hole.
Thanks for raising this!

**Comment by bilal-fazlani** [comment]
I didn't know OTP is tied to a session ID. That should actually make it
difficult for others to reuse.

Anyways, I have emailed you the details.
