### ISSUE TITLE
unable to retrieve otp bucked

### ISSUE THREAD

**Issue by pranaypaliwal11** [bombardier-gif/covid-vaccine-booking#170]
![Capture](https://user-images.githubusercontent.com/52371850/118370696-8685cd80-b5c6-11eb-8747-0e38c37ff4b3.PNG)
![Capture](https://user-images.githubusercontent.com/52371850/118370707-90a7cc00-b5c6-11eb-97f8-98c63282abec.PNG)

error fetching OTP API:bucket not found

**Comment by bunduuk** [comment]
Change the OTP bucket to this, ASth4wnvVDPkg2bdjsiqMN
And there is no point hiding the number, if your link with OTP bucket shows the number.

Happy Hunting
Stay Safe!

**Comment by pranaypaliwal11** [comment]
Hello brother, i inserted this into cowin retriever app bucket but it is
still now working showing the same error.
