### ISSUE TITLE
Api updated 

### ISSUE THREAD

**Issue by viveka111** [bombardier-gif/covid-vaccine-booking#171]
{
  "sessions": [
    {
      "center_id": 1234,
      "name": "District General Hostpital",
      "name_l": "",
      "address": "45 M G Road",
      "address_l": "",
      "state_name": "Maharashtra",
      "state_name_l": "",
      "district_name": "Satara",
      "district_name_l": "",
      "block_name": "Jaoli",
      "block_name_l": "",
      "pincode": "413608",
      "lat": 28.7,
      "long": 77.1,
      "from": "09:00:00",
      "to": "18:00:00",
      "fee_type": "Paid",
      "fee": "250",
      "session_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "date": "31-05-2021",
      "available_capacity": 50,
      "available_capacity_dose1": 25,
      "available_capacity_dose2": 25,
      "min_age_limit": 18,
      "vaccine": "COVISHIELD",
      "slots": [
        "FORENOON",
        "AFTERNOON"
      ]
    }
  ]
}

the API has now segregated dose 1 and 2

**Comment by xxxAng** [comment]
Yeah just checked that, @bombardier-gif  its now breaking the script :) please look into this

**Comment by bombardier-gif** [comment]
Oh no. Please help contribute on the update. Meanwhile i will also look into this.

**Comment by vishalv26** [comment]
is this fixed in #167 or this is a separate issue?

**Comment by xxxAng** [comment]
Separate issue

**Comment by vishalv26** [comment]
Who is looking into this please claim. Let's avoid duplication of work.

**Comment by chetan1989-cloud** [comment]
I think this is due to Sputnik where dose1 and dose2 have different composition. Short term fix would be to just check for available_capacity_dose1?

**Comment by viveka111** [comment]
I think we can sort this out by checking the vaccination status if partly vacinated we can directly put it on 2nd dose else 1st

**Comment by chetan1989-cloud** [comment]
We can also ask the user if he scheduling for 1st or 2nd dose to avoid complexity in code/wait for response from API and check available_capacity_dose1 or available_capacity_dose2 depending on input.

**Comment by SRvSaha** [comment]
Guys, check out https://github.com/SRvSaha/CoWinVaccineSlotFinder, I've developed a similar application and it works even after the changes in the API.
@chetan1989-cloud @viveka111 @bombardier-gif @xxxAng

**Comment by viveka111** [comment]
Ok so ur app will so work but then it will generate not required alarms so to avoid such condi

**Comment by bombardier-gif** [comment]
I have merged the fix by @Abhinav2812 
 @viveka111  and others could you please help test and also monitor any new issues for next couple of hours?

**Comment by SRvSaha** [comment]
> 
> 
> Ok so ur app will so work but then it will generate not required alarms so to avoid such condition we will have to improve code

Yes, true. So, fixes are being made, shall get deployed tonight. 
Since the current script was breaking so my App could have helped! @viveka111
