### ISSUE TITLE
403 ERROR using auto captcha or manual captcha

### ISSUE THREAD

**Issue by Gmansign** [bombardier-gif/covid-vaccine-booking#172]
!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 0VVekBA7nJf1qg8b35n978qrRZpqAh6A2VTMD_yh7FvdEgtpFfMJKw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by chetan1989-cloud** [comment]
May be you did too much polling and is now being rate limited hence the 403 error? Cowin site says 100 per 5 minute API calls.

**Comment by bombardier-gif** [comment]
@chetan1989-cloud is correct. You are getting rate limited. Please try with less frequency, after a while
