### ISSUE TITLE
Need contribution to use portable python 

### ISSUE THREAD

**Issue by bombardier-gif** [bombardier-gif/covid-vaccine-booking#173]
https://github.com/vishalv26/covid-vaccine-booking : It uses portable python and simplifies running the code by avoiding the need for separate Python installation.

**Comment by shailesh** [comment]
@vishalv26 your help/guidance needed here :)

**Comment by vishalv26** [comment]
Hello. I have integrated this into my project. Now. If user double clicks on `advanced.bat` it will open the same script as this repo.

**Comment by bombardier-gif** [comment]
Can you raise a PR please? So that I can merge the script

**Comment by subho007** [comment]
I can send a PR, all that is required is add the portable python binary which should do the work.

**Comment by shailesh** [comment]
Thanks @subho007 for the PR. closing this.
