### ISSUE TITLE
covid-vaccine-slot-booking.exe file not found.

### ISSUE THREAD

**Issue by akshay8043** [bombardier-gif/covid-vaccine-booking#175]
Hello,

I am using this on windows and below section .exe is missing.

******************************************************************************************************************************
For the anyone not familiar with Python and using Windows, using the **covid-vaccine-slot-booking.exe** executable file would be the easiest way. It might trigger an anti-virus alert. That's because I used pyinstaller to package the python code and it needs a bit more effort to avoid such alerts.
***************************************************************************************************************************************

Can you please let me know. I want to book slot to get a shot asap for higher studies to avoid mandatory hotel quarantine.

Please help.

**Comment by bombardier-gif** [comment]
The exe has been broken so its not available. I suggest you run the script directly. Let us know if you face any trouble.

**Comment by akshay8043** [comment]
@bombardier-gif  Sorry But I am still learning, are you suggesting that I should run it directly from any latest version of windows python?

I don't have python installed on my system.

As of now, I am running, 
https://github.com/vishalv26/covid-vaccine-booking and it beeps and asks for OTP. then I put otp manually.

I believe as per the info provided by you, the above manual work is automated right?

My ifttt is set up and running.

Please suggest.

**Comment by Dhanushrajashekar** [comment]
> @bombardier-gif Sorry But I am still learning, are you suggesting that I should run it directly from any latest version of windows python?
> 
> My ifttt is set up and running.
> I don't have python installed on my system.
> 
> As of now, I am running,
> https://github.com/vishalv26/covid-vaccine-booking and it beeps and asks for OTP. then I put otp manually. (it has python binarys files available in his source itself)
> 
> Do you think you can also leverage local python files for newbie windows users?
> 
> I believe as per the info provided by you, the above manual work is automated right?
> 
> Please suggest.
> 
> Also, Do you have discord?
> 
> Screen recording is no big deal for anyone. So if you wish I can help you with a video for newbie users who can follow the video and avoid creating new issues in github? only if you wish.
> I will directly share video with you. Rest you can post it anywhere you want.

Are you able to run on windows bro? I dont find the windows.exe so help me please if you found a way to run this code

**Comment by gitmnj** [comment]
Revert me at discord for booking details gitmnj#1526
