### ISSUE TITLE
otp is not getting by using your python script

### ISSUE THREAD

**Issue by Gmansign** [bombardier-gif/covid-vaccine-booking#176]
otp is not getting by using your python script

**Comment by akshay8043** [comment]
I am also facing same issue

![image](https://user-images.githubusercontent.com/32493756/118386964-d8ffd200-b638-11eb-9767-589ecb1e31d3.png)

**Comment by akshay8043** [comment]
![image](https://user-images.githubusercontent.com/32493756/118387011-490e5800-b639-11eb-8b50-3326a2e09825.png)

Sorry, this is working for me.

**Comment by bombardier-gif** [comment]
@Gmansign please ensure that your bucket name is correct in IFTTT/android app.
