### ISSUE TITLE
OTP automation not working

### ISSUE THREAD

**Issue by Huzaifg** [bombardier-gif/covid-vaccine-booking#179]
Everything set up on IFTTT. Access to SMS given. Add battery saving modes disabled. 
Phone - Redmi Note 7
Android Version - 10

However, the response is not coming on the kvdb link. 

I have pulled the latest code.

Is this happening with anyone else?

![Screenshot 2021-05-16 at 1 40 46 PM](https://user-images.githubusercontent.com/64803446/118390484-e921ac80-b64c-11eb-944a-1c1b728432b6.png)
![Screenshot 2021-05-16 at 1 42 13 PM](https://user-images.githubusercontent.com/64803446/118390485-ea52d980-b64c-11eb-90f4-67099eeff7f9.png)

**Comment by akshay8043** [comment]
make sure your bucket name is correct. it is working for me.

**Comment by bombardier-gif** [comment]
Can you check your IFTTT applet to see if there are any errors, and also when it ran last?

**Comment by Huzaifg** [comment]
I have never tried to run it with automated OTP. Last time I used this script was 9th May when I entered the OTP manually. 
I dont find any errors in the applet. Check below




![WhatsApp Image 2021-05-16 at 6 07 07 PM](https://user-images.githubusercontent.com/64803446/118397667-cacea780-b672-11eb-8774-df9d7401a806.jpeg)
![WhatsApp Image 2021-05-16 at 6 17 39 PM](https://user-images.githubusercontent.com/64803446/118397918-e5555080-b673-11eb-98cc-25575007fbb8.jpeg)
![WhatsApp Image 2021-05-16 at 6 17 39 PM (1)](https://user-images.githubusercontent.com/64803446/118397927-e9816e00-b673-11eb-9092-1f81a6ebb870.jpeg)
![WhatsApp Image 2021-05-16 at 6 17 40 PM](https://user-images.githubusercontent.com/64803446/118397929-eb4b3180-b673-11eb-9887-0945bda0e259.jpeg)

**Comment by BumpyKnuckls** [comment]
@Huzaifg Are you getting the OTP SMS on your device? It can happen at times that the SMS is not sent and if you are seeing this, would suggest to try again in sometime.

In addition, as @bombardier-gif suggested, if you wanna check when your applet last ran, please open your IFTTT app and on the first page, click on the green tile which says "If New SMS received, ..." and on the next screen tap on "View Activity" to see when it ran last.

**Comment by akshay8043** [comment]
@Huzaifg @bombardier-gif I have also faced same problem a while ago.

I did following workaround.
But I have disconnected and connected in App in mobile as well as on IFTTT. 

Restarted IFTTT app on mobile and restarted otpreader app on mobile and now it is working again automatically.

**Comment by BumpyKnuckls** [comment]
Thanks @akshay8043 for the idea. @Huzaifg Please also consider trying this solution.

**Comment by Huzaifg** [comment]
@BumpyKnuckls 
The number is my friends number and he is getting the otp when I request it through the script. We will try again in sometime. 

On checking the IFTTT applet's activity, it says `never run`. However, we would have tried 5 times. 

PFA the screenshot
![WhatsApp Image 2021-05-16 at 7 23 06 PM](https://user-images.githubusercontent.com/64803446/118399787-74666680-b67c-11eb-84ff-5f89f22addab.jpeg)

**Comment by Huzaifg** [comment]
@akshay8043 
I am currently not using the OTP reader app. only using the IFTTT.  I will try restarting the IFTTT app. I will also try using the CoWIN OTP reader app.

**Comment by BumpyKnuckls** [comment]
@Huzaifg I think the problem maybe that IFTTT is running on one phone, but the sms is going to another phone? If thats the case then, can you try running IFTTT on the phone which is also receiving the sms?

I am closing this issue for now, since the way IFTTT is being used is incorrect. Requesting you to please try the above and reopen this issue, if the problem persists.

**Comment by Huzaifg** [comment]
@BumpyKnuckls 
IFTTT is running on the phone on which the OTP is being recieved (both my friends phone). Can you please reopen the issue as your assumption is incorrect? 
I will close the issue once I have tested the suggestions and found it to be working.
