### ISSUE TITLE
Session Object changed in response of appointment API

### ISSUE THREAD

**Issue by kevalp3** [bombardier-gif/covid-vaccine-booking#180]
Till now we were **tracking appointment based on available_capacity** now there is change in response of appointment API.

**New fields** has been added **available_capacity_dose1** and **available_capacity_dose2**. so now we **need to check the user's status** and **based on which** we need to **check the available capacity dose**.

Attached herewith is the block of response json for reference.

{"center_id": 692747, "name": "Jain Derasar Sec22", "address": "Jain Derasar Sec22", "state_name": "Gujarat", "district_name": "Gandhinagar Corporation", "block_name": "Gandhinagar Municipal Corporation", "pincode": 382022, "lat": 23, "long": 72, "from": "09:00:00", "to": "17:00:00", "fee_type": "Free", "sessions": [{"session_id": "e26a745a-471e-4d9f-93a2-03ab873e5b91", "date": "16-05-2021", "**available_capacity**": 5, "min_age_limit": 18, "vaccine": "COVAXIN", "slots": ["09:00AM-11:00AM", "11:00AM-01:00PM", "01:00PM-03:00PM", "03:00PM-05:00PM"], "**available_capacity_dose1**": 0, "**available_capacity_dose2**": 5}]}

**Comment by akshay8043** [comment]
@kevalp3 
![image](https://user-images.githubusercontent.com/32493756/118392319-b11f6700-b656-11eb-99bc-a87b50c352b1.png)

I was unable to create issue in your repo which Is why i am reaching out here. I new IFTTT app and configured the repo which you have on your github page.

After running.exe OTP is not received on as you can see in above and below pic 

![image](https://user-images.githubusercontent.com/32493756/118392353-ec219a80-b656-11eb-8e22-95377a9c5d85.png)

**Comment by shailesh** [comment]
> Till now we were **tracking appointment based on available_capacity** now there is change in response of appointment API.
> 
> **New fields** has been added **available_capacity_dose1** and **available_capacity_dose2**. so now we **need to check the user's status** and **based on which** we need to **check the available capacity dose**.
> 
> Attached herewith is the block of response json for reference.
> 
> {"center_id": 692747, "name": "Jain Derasar Sec22", "address": "Jain Derasar Sec22", "state_name": "Gujarat", "district_name": "Gandhinagar Corporation", "block_name": "Gandhinagar Municipal Corporation", "pincode": 382022, "lat": 23, "long": 72, "from": "09:00:00", "to": "17:00:00", "fee_type": "Free", "sessions": [{"session_id": "e26a745a-471e-4d9f-93a2-03ab873e5b91", "date": "16-05-2021", "**available_capacity**": 5, "min_age_limit": 18, "vaccine": "COVAXIN", "slots": ["09:00AM-11:00AM", "11:00AM-01:00PM", "01:00PM-03:00PM", "03:00PM-05:00PM"], "**available_capacity_dose1**": 0, "**available_capacity_dose2**": 5}]}

#171 #174

**Comment by SRvSaha** [comment]
Guys, check out https://github.com/SRvSaha/CoWinVaccineSlotFinder, I've developed a similar application and it works even after the changes in the API.
@shailesh @kevalp3

**Comment by bombardier-gif** [comment]
@akshay8043 Please create a new issue so that people can help you better.
@SRvSaha you could create a new issue too explaining how your repo has advantages over others. 

@kevalp3 There is a PR just merged which addresses the issue. Can you please check?
