### ISSUE TITLE
Add Sputnik support also

### ISSUE THREAD

**Issue by viveka111** [bombardier-gif/covid-vaccine-booking#181]

**Comment by shailesh** [comment]
Label added on the Cowin portal page :  Sputnik V

**Comment by shailesh** [comment]
```
def get_vaccine_preference():
    print(
        "It seems you're trying to find a slot for your first dose. Do you have a vaccine preference?"
    )
    preference = input(
        "Enter 0 for No Preference, 1 for COVISHIELD, or 2 for COVAXIN, or 3 for SPUTNIK V. Default 0 : "
    )
    preference = int(preference) if preference and int(preference) in [0, 1, 2, 3] else 0

    if preference == 1:
        return "COVISHIELD"
    elif preference == 2:
        return "COVAXIN"
    elif preference == 3:
        return "SPUTNIK-V"
    else:
        return None
```

**Comment by vishalv26** [comment]
How did you know it is SPUTNIK-V

**Comment by shailesh** [comment]
Looked into few commits, people making changes.

Can we first check for vaccine-type available by passing random district/pin code and then set all those in preferences so that we do not have to hard code every time a new vaccine gets added on the Cowin portal. 

But not sure because still Pincode/district may not have all types of vaccines listing

Checking here if they have any variables set/JSON file https://github.com/egovernments/DIVOC

**Comment by vishalv26** [comment]
Let us know the confirmed value and source

**Comment by shailesh** [comment]
Got this from Portal runtime filter JS

`"COVISHIELD"==e&&this.appointmentForm.get("covishieldFilter").setValue(""),"COVAXIN"==e&&this.appointmentForm.get("covaxinFilter").setValue(""),"SPUTNIK V"==e&&this.appointmentForm.get("sputnikFilter").setValue(""),`

**Comment by shailesh** [comment]
Hey, @bombardier-gif we can go ahead and add Sputnik V, I tried to look at the source of the Cowin app in dev tools. Here is what I found:

![screenshot](https://user-images.githubusercontent.com/9050349/118401074-dbd2e500-b681-11eb-80f3-b72de60863d0.png)

**Comment by vishalv26** [comment]
smart

**Comment by shailesh** [comment]
> smart

:-P @vishalv26 Please add that in your code too. Thanks.

Happy Hunting!!

**Comment by BumpyKnuckls** [comment]
@shailesh Thanks a lot for digging into it. Do you want to open a PR for it as well? That would be helpful to the entire community.

**Comment by shailesh** [comment]
Have asked @pallupz to add in their code and they have added it. Thanks

Discussion: https://github.com/pallupz/covid-vaccine-booking/discussions/160
Commit: https://github.com/pallupz/covid-vaccine-booking/commit/876b248fe1ca74f0bfeff9d5200cd41fd7d9d5f8

**Comment by shailesh** [comment]
> @shailesh Thanks a lot for digging into it. Do you want to open a PR for it as well? That would be helpful to the entire community.

I get permission error while pushing. :(

**Comment by shailesh** [comment]
> > @shailesh Thanks a lot for digging into it. Do you want to open a PR for it as well? That would be helpful to the entire community.
> 
> I get permission error while pushing. :(

Would be happy if you add me as a collaborator

**Comment by BumpyKnuckls** [comment]
Hey @shailesh, thanks a lot for the interest. In order to send a PR, you would have to fork the repo in your own GitHub, make code changes in the fork and then open a PR against the main branch of this repo. That would enable you to make code changes in this repo.

**Comment by shailesh** [comment]
> Hey @shailesh, thanks a lot for the interest. In order to send a PR, you would have to fork the repo in your own GitHub, make code changes in the fork and then open a PR against the main branch of this repo. That would enable you to make code changes in this repo.

Tried some permission issue then added Key to account further permission issue. I'll fix this next for next time. Please go ahead and make the changes. Thanks

**Comment by shailesh** [comment]
"center_id": 616291,
      "name": "Apollo Hosp Jubilee-INDUSTRIAL",
      "address": "Apollo Hospitals Enterprise LimitedDoor.No.8-2-293-82 J-111-900-A Jubilee Hills",
      "state_name": "Telangana",
      "district_name": "Hyderabad",
      "block_name": "Shaikpet",
      "pincode": 500033,
      "lat": 17,
      "long": 78,
      "from": "10:00:00",
      "to": "14:00:00",
      "fee_type": "Paid",
      "sessions": [
        {
          "session_id": "e95afb5a-5922-4f13-828e-7eb9ccc638f4",
          "date": "18-05-2021",
          "available_capacity": 0,
          "min_age_limit": 45,
          "vaccine": "SPUTNIK V",
          "slots": [
            "10:00AM-11:00AM",
            "11:00AM-12:00PM",
            "12:00PM-01:00PM",
            "01:00PM-02:00PM"
          ],
          "available_capacity_dose1": 0,
          "available_capacity_dose2": 0
        }
]
