### ISSUE TITLE
Thank you everyone

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#184]
Thanks, everyone for your support and help, though I'm not able to book one for me. I always get an error 500 while booking. 

#165 Mentioned here.

I guess I won't be able to book do not know the issue though. Thanks

@bombardier-gif thanks man 🥇 for this awesome automated script. Please close this anytime you feel.

**Comment by bombardier-gif** [comment]
There is another automated script lurking around. There was a person who was commenting on all the threads about this repo. Please try that once too.

**Comment by bombardier-gif** [comment]
The APIs are not as robust as we like. But if it was good, we would not be having this script in the first place :P

**Comment by shailesh** [comment]
> The APIs are not as robust as we like. But if it was good, we would not be having this script in the first place :P

Totally Agree 👍

**Comment by shailesh** [comment]
Worked for me 
#165

**Comment by shailesh** [comment]
Worked for me 
#165
