### ISSUE TITLE
Randomise Useragent

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#185]
```
from fake_useragent import UserAgent

base_request_header = {
            'User-Agent': UserAgent().random,
        }
```

**Comment by bombardier-gif** [comment]
Whats the advantage of doing this?

**Comment by shailesh** [comment]
Changing user agents can help one in getting around browser-based restrictions if any

**Comment by bombardier-gif** [comment]
We havent seen any restrictions so far. I will keep this in mind if we start seeing any.
Thanks @shailesh !
