### ISSUE TITLE
Max Retry : is it something expected? 

### ISSUE THREAD

**Issue by puneetlohia** [bombardier-gif/covid-vaccine-booking#187]
Centers available in 122002 from 16-05-2021 as of 2021-05-16 18:54:05: 2
Centers available in 122003 from 16-05-2021 as of 2021-05-16 18:54:05: 2
===================================================================================
Centers available in 122001 from 16-05-2021 as of 2021-05-16 18:54:08: 6
Centers available in 122002 from 16-05-2021 as of 2021-05-16 18:54:08: 2
Centers available in 122003 from 16-05-2021 as of 2021-05-16 18:54:08: 2
HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/appointment/beneficiaries (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106ddba30>: Failed to establish a new connection: [Errno 60] Operation timed out'))
Retryin in 5 seconds
===================================================================================
HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/appointment/sessions/calendarByPin?pincode=122001&date=16-05-2021 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106e25850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
'NoneType' object is not iterable
Retryin in 5 seconds

**Comment by shailesh** [comment]
There is a limit set of 100 calls per 5 minutes I guess. I have set my refresh to 8 sec and never got such an issue.
c.c @bombardier-gif

**Comment by bombardier-gif** [comment]
Yeah usually it goess off after some time. As @shailesh mentioned reduce the frequency for a while
