### ISSUE TITLE
Slots are already full but still getting captcha

### ISSUE THREAD

**Issue by akshay8043** [bombardier-gif/covid-vaccine-booking#188]
I am trying for 15 minutes and it is still coming up again and again even after slots are full.

![image](https://user-images.githubusercontent.com/32493756/118399770-53057a80-b67c-11eb-923f-b113841e6eea.png)

Maybe logic needs to be changed. People who are looking for 1st dose then script should continue to search that.

As of now Dose 2 is available but unable to book as I have not booked 1st dose. Because of this script is in loop for same slots or hospital.

![image](https://user-images.githubusercontent.com/32493756/118401227-7d5a3680-b682-11eb-82db-9d061a550f13.png)

**Comment by puneetlohia** [comment]
@akshay8043  This is an issue with cowin public and protected api. 
if you go and check the cowin website, you would be able to see similar redundancy there as well. 
publicly you would see the slots, but when you login and try to book, it wouldn't be available. 
Hence you can increase the minimum slots to 25 or something so whenever actual are available will be buzzed.

**Comment by BumpyKnuckls** [comment]
Thanks a lot @puneetlohia for chiming in with your help :) Marking this as closed since the query has been answered.
