### ISSUE TITLE
otp verification problem

### ISSUE THREAD

**Issue by Dhanushrajashekar** [bombardier-gif/covid-vaccine-booking#19]
I am getting the otp in my phone but im not able to enter it in the cmd (windows 10)
It shows as 
OTP SMS is:
OTP SMS len is: 0
![1](https://user-images.githubusercontent.com/70057181/117577322-f3045680-b106-11eb-8c13-30fcdc1e097b.PNG)

**Comment by bombardier-gif** [comment]
Did you get the OTP on your phone?
Also is your IFTTT working properly, and is it premium version?

**Comment by Dhanushrajashekar** [comment]
Yes i got the otp in my phone 
I did not  buy a premium version.
IFTTT is working i guess i followed what you had mentioned

**Comment by bombardier-gif** [comment]
So the premium version works realtime and forwards it quickly (as I mentioned in the doc).
Also ensure that your app is not on battery saver and other optimizations and never sleeps

**Comment by Dhanushrajashekar** [comment]
i get the same command in cmd for almost 3 mins and again a new otp comes to my phone but im not able to type the otp in the cmd cause these goes on in loop.

**Comment by Dhanushrajashekar** [comment]
I think the problem is this.Can you help me fixing this?

**Comment by Dhanushrajashekar** [comment]
I think this is the problem. Can you help me with this??![Screenshot_20210509-205624.png](https://user-images.githubusercontent.com/70057181/117577965-c1d95580-b109-11eb-8601-4c16dc4cbb1f.png)

**Comment by bombardier-gif** [comment]
Thanks it does seem that IFTTT was not able to make the web request. Can you make sure that there is no space or anything in the URL? (I deleted the screenshot as it had your phone number)

**Comment by bombardier-gif** [comment]
As a stop-gap solution you can use the script by the original repo. This enables you to enter OTP manually but you will have to do it every 15 mins.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lordlebu** [comment]
I am getting the below error when it is generating and displaying Captcha code

-----------
Random Rows.Column:1.3
============> Got Choice: Center #1, Slot #3
Booking with info: {'beneficiaries': ['59xxxxxxxxxx410', '558xxxxxxxxxx00'], 'dose': 1, 'center_id': 6xxxxxxxxx9, 'session_id': '1xxxxxxxxxxxxxxxxxxxxxxxxxxx8f2', 'slot': '12:00PM-01:00PM'}
'say' is not recognized as an internal or external command,
operable program or batch file.
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None

**Comment by Dhanushrajashekar** [comment]
Hey bro Thank you so much its working now i had left a space in the URL link which was causing the problem its working now!!!

**Comment by bombardier-gif** [comment]
Perfect. I am glad it is working! 
Stay safe!

**Comment by whizzkky** [comment]
Hey I'm facing the same issue, looks like IFTTT is not making the web request

**Comment by bombardier-gif** [comment]
So same thing again:
Is your IFTTT premium version
Disable any kind of battery saver setting for this app. It has to run all the time
Ensure that you are using the url without any spaces. 
Please check the IFTTT history to see any errors (and share with me if there is an error)

**Comment by whizzkky** [comment]
Hey, so checked everything - running pro ifttt, no battery saver, url is without spaces. looks like ifttt isn't recognising the sms on my phone, since it hasn't run at all in spite of getting a lot of OTP SMS's (no errors). i'm using quite an old version of android so may be that's causing the problem. will try with a different phone

**Comment by sodiumchloride2020** [comment]
Try with another android which is having android 10+.

I personally tested working fine as said.

**Comment by sodiumchloride2020** [comment]
If you know the slot time then you can manual trigger the ifttt applet.

Clicking check now!
[Screenshot_20210510-071255.jpg](https://user-images.githubusercontent.com/69193224/117595722-2ffc3780-b15f-11eb-8403-a79757f41aea.jpg)

**Comment by Nakul93** [comment]
I'm also getting the same error, is it important to have the IFTTT app on my android phone for this Applet to run?
