### ISSUE TITLE
Leverage an access to book a slot by Centre Name

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#190]
Can we allow users to book by center name? As for single PIN code [560076], there are different centers e.g 

1. APOLLO HOSPITAL 1, 
2. ARAKERE UPHC, 
3. KODICHIKKANAHALLI UPHC 

but I trust APOLLO more or the infra is great and want to book only in Apollo once available.

For me I've hardcoded now:
```
    if len(resp["centers"]) >= 0:
        for center in resp["centers"]:
            if "APOLLO" in center:    //look up for a matching center name in available centres
                for session in center["sessions"]:
```

I know this is an over-engineering for such script but maybe it is going to help someone out there looking for an option to book to a specific center because of multiple reseasons maybe distance, infra, environment, management ......

**Comment by Nakul93** [comment]
Actually I rather prefer keeping my fee preference as PAID to get pvt hosp since as you mentioned they have good infra.
The distance thing seems reasonable, I’ve seen there is API to search by lat-long maybe we could use that to find the nearest centre

**Comment by shailesh** [comment]
Lat-Long is a great idea but are we sure that it is going to return just a single centre and no other choice. I had this thought of paid but then there are again multi centres (distance will matter and maybe unknown hospital/clinic to the user)

**Comment by bombardier-gif** [comment]
it will end up in too many options. And also most of the people at moment need a slot anywhere they can get a shot

**Comment by shailesh** [comment]
I agree

**Comment by shailesh** [comment]
closing this for now, as there are not many requirements related.
