### ISSUE TITLE
How to select a slot rather than automatically picking one

### ISSUE THREAD

**Issue by Sanku827** [bombardier-gif/covid-vaccine-booking#191]
We see a lot of centers are glitched today. The glitched centers come on top every time causing other available centers to go down. This is leading to the failure of booking as the script always tries to book the first one and not the second one.
Can we get an option to select the slot?

**Comment by shailesh** [comment]
@Sanku827 https://github.com/bombardier-gif/covid-vaccine-booking#usage

**Comment by bombardier-gif** [comment]
This script selects a random slot. and not always the first slot. 
This is by design to maximize the success
