### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by jayanthbagare** [bombardier-gif/covid-vaccine-booking#192]
It would be nice to see if we can run this in the background on the server.

**Comment by shailesh** [comment]
@jayanthbagare https://stackoverflow.com/questions/39139165/running-simple-python-script-continuously-on-heroku

**Comment by bombardier-gif** [comment]
Thanks @shailesh for the tip!

**Comment by arcanebloke5888** [comment]
> @jayanthbagare
> https://stackoverflow.com/questions/39139165/running-simple-python-script-continuously-on-heroku
> https://medium.com/analytics-vidhya/schedule-a-python-script-on-heroku-a978b2f91ca8

@shailesh I'm struggling in setting it up on heroku. Can you provide more details?

**Comment by shailesh** [comment]
https://dev.to/josylad/how-to-deploy-a-python-script-or-bot-to-heroku-in-5-minutes-9dp

**Comment by arcanebloke5888** [comment]
> https://dev.to/josylad/how-to-deploy-a-python-script-or-bot-to-heroku-in-5-minutes-9dp
> https://stackoverflow.com/questions/27160244/how-to-run-python-script-continuously-on-heroku

This is super helpful. Keep being awesome!

**Comment by arcanebloke5888** [comment]
@shailesh how do i enter my phone number on heroku?

I keep getting this error (despite adding mobile number as a config variable)
![image](https://user-images.githubusercontent.com/84184377/118517544-ed38f180-b754-11eb-8b26-cb76ad7ba92b.png)

**Comment by shailesh** [comment]
This error is about a package beep which has been used to play a sound when slots are available. U do not need this while running on remote server. You can comment out the whole function and wherever used. 

I hope this helps.

**Comment by arcanebloke5888** [comment]
While i was able to get over the previous error (and some follow ups too), I'm stuck on this.
![image](https://user-images.githubusercontent.com/84184377/118531748-ccc46380-b763-11eb-8d83-267ef19852de.png)

How to I enter the phone number as a parameter?

**Comment by shailesh** [comment]
I've got an idea to dump a JSON file there with a mobile number or in a test file. Then add a parser to parse out the number and pass it in the funstion. Comment out all the input things from the script.

**Comment by arcanebloke5888** [comment]
> I've got an idea to dump a JSON file there with a mobile number or in a test file. Then add a parser to parse out the number and pass it in the funstion. Comment out all the input things from the script.

Thanks @shailesh for your relentless support.

I tried using a json file to set up the process. However, now I see the following error
![image](https://user-images.githubusercontent.com/84184377/118815999-63f9fa00-b8cf-11eb-8d36-d8e834b7027c.png)

Is this happening because a lot of users have already setup the script on heroku?
Any idea to bypass this error?
