### ISSUE TITLE
Script is getting old available slots. Looks like some change in apis

### ISSUE THREAD

**Issue by Prakhar-Shukla05** [bombardier-gif/covid-vaccine-booking#193]
================================================================================
Centers available in BBMP from 17-05-2021 as of 2021-05-17 11:46:51: 4
+-------+---------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                      | district   |   pincode |   available | date       | slots                                                                        |
+=======+===========================+============+===========+=============+============+==============================================================================+
|     1 | Apollo Hospital-JAYANAGAR | BBMP       |    560011 |          45 | 17-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+---------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+

Getting this message continously

**Comment by bombardier-gif** [comment]
Are you able to book the slot?

**Comment by shailesh** [comment]
I'm not getting this for:

```
  {
      "alert_freq": 1100,
      "district_id": 294,
      "district_name": "BBMP"
  }
```

Can check the time in system logs, when did you get that?

**Comment by vichuroxx** [comment]
same issue for me.. slot opening delayed reporting and captcha money gets used up because of this delay. vaccine also not getting booked now. I noticed without logged in i get the delayed slot update and after logging in to the cowin website gets the uptodate slot update.

i doubt cowin website team did something to delay the slot update to the public apis and gets uptodate slot data to the ones logged in to web

**Comment by shailesh** [comment]
#253 #256 this will resolve your issue. you do not have to solve captcha with anti-captcha anymore. this was a pain and we have resolved and completely removed this feature.
