### ISSUE TITLE
Change the Hotword trigger in IFTTT and the app (if the app uses the same trigger) from CoWIN to OTP*CoWIN (if IFTTT supports regex)

### ISSUE THREAD

**Issue by sbstratos79** [bombardier-gif/covid-vaccine-booking#194]
Having CoWIN as the hotword trigger is a HUGE privacy concern since IFTTT will trigger even on receiving the Slot Booking confirmation SMS. That means, the last message stored in the KVDB bucket will be an sms containing the Phone number as the key, and the SMS containing the Full Name of the user and the Vaccination Center, i.e. approximate location. That is a huge privacy risk. Using OTP*CoWIN as the hotword trigger fixes this issue.
OR
Another thing that can be done to fix this is clearing the bucket after the booking has been confirmed. 

Of course just using the first method is just a safer option.

**Comment by bombardier-gif** [comment]
Thanks @sbstratos79 did you test if OTP*CoWIN as the hotword trigger fixes this issue ?
If yes, then i will update the documentation asap.

**Comment by sbstratos79** [comment]
I tried it with Macrodroid, since that's what I am using for automation on phone. Can't say anything about IFTTT.

**Comment by sbstratos79** [comment]
Instead of using IFTTT, you can use Macrodroid. Macrodroid supports curl commands through shell. You can simply distribute the .macro file and users can directly use that to install the macro once Macrodroid is installed on their phone. No additional setup required.

**Comment by bombardier-gif** [comment]
@sbstratos79 You could create a PR with steps with macdroid. That would be helpful for the community

**Comment by sbstratos79** [comment]
I've never made a PR before. I'll just share the guide here.

1. Install Macrodroid from Play Store
2. Open the App Info Page by pressing and holding the Macrodroid icon and selecting App Info/Manage et al.
3. Once installed, give the app permissions for SMS, Phone, Storage and Contacts.
4. Disable Battery Optimization from App Info Page.
5. Download the [OTP_Sync_KVDB.macro](https://drive.google.com/file/d/1VZrwC6D6T5e7fG2ibLndHyND2a6M1TYD/view?usp=sharing) file on your phone.
6. It should open the Macrodroid screen. If it doesn't, manually run the file with Macrodroid.
7. Press the circle button at the bottom right.
8. Go to the CoWIN website (www.cowin.gov.in) and generate an OTP.
9. Once the OTP message arrives, a popup will appear on your phone, asking you to enter your phone number. Enter it.
10. After that another popup will appear asking you to enter the Bucket ID. Enter it.
11. In case you input a Bucket ID different from bombardier-gif's bucket ID, you'll have to change the bucket ID in utils.py.
12. Congrats! You have enabled Auto OTP.
