### ISSUE TITLE
help to install python properly

### ISSUE THREAD

**Issue by ketan1234fx** [bombardier-gif/covid-vaccine-booking#195]
can u please help me to install python to run this scripts,i am new in this so please guide sir

**Comment by vishalv26** [comment]
Go to https://github.com/vishalv26/covid-vaccine-booking and download the zip from latest release and run `advanced.bat` and you are good to go

**Comment by bombardier-gif** [comment]
Hi @ketan1234fx Installing python should be straightforward. You can refer to many tutorials online depending on your platform

**Comment by ketan1234fx** [comment]
its sowssyntex error while performing oprations
