### ISSUE TITLE
I do not want the script to auto book the slot

### ISSUE THREAD

**Issue by prakharaug** [bombardier-gif/covid-vaccine-booking#197]
The script is auto-booking the slot and is not displaying the option to select from our side whether to auto book or not. Please Help. 
![image](https://user-images.githubusercontent.com/59426657/118464222-3c176480-b71e-11eb-8192-e64d310171e0.png)

**Comment by shailesh** [comment]
Update "auto_book": "n" in vaccine details json and run the script again

**Comment by prakharaug** [comment]
thats a nice idea
