### ISSUE TITLE
Any issue with the script, it is not running for me now?

### ISSUE THREAD

**Issue by chetan1989-cloud** [bombardier-gif/covid-vaccine-booking#199]
Just stuck here:
Do you want to enter OTP manually, instead of auto-read?
Remember selecting n would require some setup described in README (y/n Default n): n
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/xxxxxxxxxx
Requesting OTP with mobile number xxxxxxxxxx

Also might be taking a long time in clearing the bucket, something wrong with my laptop? I have restarted it already.

**Comment by chetan1989-cloud** [comment]
Now this is coming, it has become really slow:
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/xxxxxxxxxxx
Requesting OTP with mobile number {mobile}..  **>>>>>>>>>>Not showing my mobile number**
hi
<module 'json' from 'C:\\Users\\Chetan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\__init__.py'>  >>>>>>>>>>> **What is this**

I have even reinstalled python and deleted script, downloaded a fresh copy.

**Comment by shailesh** [comment]
@chetan1989-cloud working fine for me, are you using any VPN?

**Comment by chetan1989-cloud** [comment]
No man, all of a sudden I had an issue with my hotspot and now it has stopped working.

**Comment by shailesh** [comment]
Quit and Restart again. I'm sure you must have done this couple of times. The same happened with me but I realized that I was connected to VPN

**Comment by chetan1989-cloud** [comment]
@shailesh rebooted PC multiple times, did python reinstall but nothing worked. At last switched hotspot connection same socket errors popped up and now it running smoothly again.

**Comment by shailesh** [comment]
Great it worked 😜
