### ISSUE TITLE
CAPTCHA Code displaying error

### ISSUE THREAD

**Issue by lordlebu** [bombardier-gif/covid-vaccine-booking#20]
I am getting the below error when it is generating and displaying Captcha code.

I had run the dependency check and few missing software were installed, but still this error kept showing up.

-----------
Random Rows.Column:1.3
============> Got Choice: Center #1, Slot #3
Booking with info: {'beneficiaries': ['59xxxxxxxxxx410', '558xxxxxxxxxx00'], 'dose': 1, 'center_id': 6xxxxxxxxx9, 'session_id': '1xxxxxxxxxxxxxxxxxxxxxxxxxxx8f2', 'slot': '12:00PM-01:00PM'}
'say' is not recognized as an internal or external command,
operable program or batch file.
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None

**Comment by bombardier-gif** [comment]
I think the root cause is 'say' is not recognized as an internal or external command,
I commented that. It works on mac, but maybe not on other platforms.
Please update the latest code

**Comment by Dhanushrajashekar** [comment]
Can we get the latest code please even im facing the same issue i got the slot but captcha response code 200

**Comment by lordlebu** [comment]
Pulled the latest code, will let you know if it successfully displays the captcha.

**Comment by lordlebu** [comment]
**Getting this new error**


================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None
===================================================================================
Centers available in Pune from 11-05-2021 as of 2021-05-10 15:00:22: 12
+-------+-----------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                        | district   |   pincode |   available | date       | slots                                                                        |
+=======+=============================+============+===========+=============+============+==============================================================================+
|     1 | SHIKRAPUR RH Local 18 To 44 | Pune       |    412208 |         150 | 11-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+-----------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
Random Rows.Column:1.3
============> Got Choice: Center #1, Slot #3
Booking with info: {'beneficiaries': ['5xxxxxxxxx10', 'xxxxxxxxxxxxxx'], 'dose': 1, 'center_id': 692726, 'session_id': '1a684b0a-2990-4e6f-b685-aa4a3f4911d1', 'slot': '01:00PM-03:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None
===================================================================================
('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))
'NoneType' object is not iterable
Exiting Script
Press any key to continue . . .
