### ISSUE TITLE
Throughput exceeds the current capacity of your table or index

### ISSUE THREAD

**Issue by japp2021** [bombardier-gif/covid-vaccine-booking#200]
Hello, 
While booking today got the following message after the captcha. Ultimately was not able to book. can you please suggest
================================ ATTEMPTING BOOKING ==================================================
Booking Response Code: 500
Booking Response : {"message":"Throughput exceeds the current capacity of your table or index. DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, check if you have a hot key: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html","code":"ThrottlingException","time":"2021-05-17T14:00:43.574Z","requestId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","statusCode":400,"retryable":true}
Response: 500 : {"message":"Throughput exceeds the current capacity of your table or index. DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, check if you have a hot key: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html","code":"ThrottlingException","time":"2021-05-17T14:00:43.574Z","requestId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","statusCode":400,"retryable":true}

**Comment by bombardier-gif** [comment]
Its an error on their backend. Usually it works after a while.
