### ISSUE TITLE
Existing Captcha

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#201]
Can this line of code by any chance pickup already exist captcha where one was not able to book successfully but had a chance to attempt a booking?

P.S: I know that downloading captcha happens first and will replace the existing one

https://github.com/bombardier-gif/covid-vaccine-booking/blob/76e6dcbe754196b552dad944b6016f9ebeecaa21/src/captcha.py#L8-L20

**Comment by bombardier-gif** [comment]
You could add logic to delete the existing files, before writing new ones

**Comment by shailesh** [comment]
closing this #253
