### ISSUE TITLE
Set the due date for each vaccine type

### ISSUE THREAD

**Issue by Nakul93** [bombardier-gif/covid-vaccine-booking#202]
Is it possible to get the dose1 date of a beneficiary and accordingly set the due date for his next dose, so that when one tries to book for 2nd dose, it should look for appointment dates after his due date automatically(without manually giving the date input)
Currently this script goes on and tries to book the 2nd dose and gets an error of 500.

**Comment by shailesh** [comment]
@Nakul93 As per my understanding of the code updated by @Abhinav2812 this scenario will not happen if a user has not taken dose one, script won't try to bool for dose 2 for user who are not vacinated. Dose two booking happens for those who are Partially vaccinated. 

Coming to error 500 thing, this is more related to #165  I had spent 2 days on this. Finally @Abhinav2812 understood and did RC on this. 

I hope this help you understand. Thanks

**Comment by shailesh** [comment]
@Abhinav2812 please bring a fix for this #165 . Much appreciated

**Comment by Nakul93** [comment]
@shailesh I'm not directly booking for dose2, I'm searching for a beneficiary who is partially vaccinated and his due date is not up yet for dose2 but the script goes ahead and tries to book anyway.
Also error 500 is not necessarily for the reschedule thing as mentioned in #165. As per the documentation it says "Internal Server Error"
I think this could be feature that we can add.

**Comment by shailesh** [comment]
Understood this might be an issue not letting users book a slot before date say until the due date

**Comment by BumpyKnuckls** [comment]
Closing this since its been addressed by @Nakul93 in #217
