### ISSUE TITLE
Script doesnt ask for preferred vaccine

### ISSUE THREAD

**Issue by get-vac** [bombardier-gif/covid-vaccine-booking#203]
With latest github pull when script is run:
If the user has pre-populated vaccine listed as COVISHIELD (Not sure where this is defined), status (Not Vaccinated):

When you select beneficiary i.e (beneficiary_dtls = get_beneficiaries(request_header)) in collect_user_details
it jumps to Select Location Info ->Additional Info. 
The script doesnt present user the option to set a preference for Vaccine.

**Comment by bombardier-gif** [comment]
If your cowin entry shows COVISHIELD and not vaccinated, you could delete your entry in cowin and create a new one. This would clear the previous setting.

**Comment by bombardier-gif** [comment]
Let me know if my understanding of your problem is not correct
