### ISSUE TITLE
Date format is wrong

### ISSUE THREAD

**Issue by Nakul93** [bombardier-gif/covid-vaccine-booking#204]
https://github.com/bombardier-gif/covid-vaccine-booking/blob/76e6dcbe754196b552dad944b6016f9ebeecaa21/src/utils.py#L228

When we type in a specific date instead of 1,2(today/tomorrow) the format of the date should be in dd-mm-yyyy instead of yyyy-mm-dd

**Comment by shailesh** [comment]
@Nakul93 please raise a PR 
Adding this : 
`datetime.datetime.strptime(start_date, '%d-%m-%Y')`

**Comment by Nakul93** [comment]
Ok doing it right away
