### ISSUE TITLE
Multi Preferences for Vaccines

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#207]
Currently, we have a single or all preference. Now that. we have more than two vaccines, can we make it to multi preferences?

@Abhinav2812 @Nakul93 M @ can one of you please create a PR for this one. Thanks

```
def get_vaccine_preference():
    print(
        "It seems you're trying to find a slot for your first dose. Do you have a vaccine preference?"
    )
    preference = input(
        "Enter 0 for No Preference, 1 for COVISHIELD, 2 for COVAXIN, or 3 for SPUTNIK V. Default 0 : "
    )
    preference = int(preference) if preference and int(preference) in [0, 1, 2, 3] else 0

    if preference == 1:
        return "COVISHIELD"
    elif preference == 2:
        return "COVAXIN"
    elif preference == 3:
        return "SPUTNIK V"
    else:
        return None
```
c.c @vishalv26

**Comment by shailesh** [comment]
Return a list of vaccines and filter out further after fetching centres by pin/district

**Comment by vishalv26** [comment]
Instead i would recommend taking comma seperated values like we take in user selection

**Comment by shailesh** [comment]
That is what is going to happen same as selecting beneficiaries and then storing them in an array. later looping in for this array to filter out types

**Comment by vishalv26** [comment]
Ops sorry i thought you posted solution code above. Didn't read it properly. Small screen problem (reading from phone)

**Comment by bombardier-gif** [comment]
These just add more complexities to the UX. Its already quite complicated. Most of the people are happy with any vaccine they get hold of.

**Comment by shailesh** [comment]
Agree, maybe we can keep this for future enhancements if required.
