### ISSUE TITLE
What is captcha_automation_api_key

### ISSUE THREAD

**Issue by mirajgodha** [bombardier-gif/covid-vaccine-booking#208]
Can someone help me , how to generate the captcha_automation_api_key ?

**Comment by gitmnj** [comment]
You have to buy subscription of ANTI CAPTCHA for that to automate the captcha process else just press enter to manually put the captcha

**Comment by mirajgodha** [comment]
Got it thanks, need subscription on https://anti-captcha.com/ .. done!! Thanks.
