### ISSUE TITLE
Unable to book slot with Captcha 

### ISSUE THREAD

**Issue by csg09** [bombardier-gif/covid-vaccine-booking#209]
When a slot opens up, it throws out the captcha. On entering the captcha correctly, it shows an error and the captcha loop repeats. Unable to book slot due to this. 

![image](https://user-images.githubusercontent.com/56230480/118616705-8f052080-b7df-11eb-9828-b9b9ff4d5483.png)

**Comment by gitmnj** [comment]
do you have the latest script or you're using the old code

please download the new script and try also check the details while booking and currently rescheduling is not working so request you to go on the cowin portal and cancel all the old appointments then give it a try

**Comment by csg09** [comment]
Oh! Seems like I had an old code. I had used the previous one a week back and it had worked, hence continued to use it. Trying with this one to test my luck!

**Comment by csg09** [comment]
Issue was fixed with the latest code. Closing the ticket.
