### ISSUE TITLE
Getting 400 provide valid security code

### ISSUE THREAD

**Issue by manojagarwal68** [bombardier-gif/covid-vaccine-booking#21]
Hi,

Thanks for your help with this code. The captcha window pops up multiple times and then gives this error. Is this the same issue you encountered when you say captcha is buggy? Would this happen with multiple pincodes or multiple benficiaries?

================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0045", "error":"Please provide valid security code"}
Response: 400 : {"errorCode":"APPOIN0045", "error":"Please provide valid security code"}

**Comment by bombardier-gif** [comment]
Yes this is the same issue. 
What I did was: 

- Make sure you dont run the script parallelly
- Dont use the cowin site while booking using this script

It take a bunch of tries but sometimes it does take it in one-shot.
All the best
