### ISSUE TITLE
enhancement to book slots only for a specific center_id

### ISSUE THREAD

**Issue by aryangupta1988** [bombardier-gif/covid-vaccine-booking#210]
I have used the code to book multiple slots till now and it has worked flawlessly for me(including the captcha). If an option can be added while searching for centers that a **_user can enter only a specific center_id to search and book available slots_**.
In my case, the pincode where I want to book the slot has multiple vaccination centers (all paid) but I want to book only at a specific center out of them (that center is properly sanitized multiple times daily). The present code selects the first available center and books the appointment. But if given an option to book if available only at specific center id is provided (may be at the point where it asks Location Info, user may enter "3" for directly specifying a particular center_id, it would be of great help to many others.
This will also reduce the iterations of the loop where a user specifies a pincode and the script loops through all the centers available in that pincode to check availability. 

![image](https://user-images.githubusercontent.com/84382149/118633721-6553f580-b7ef-11eb-834b-75daf779505f.png)

**Comment by shailesh** [comment]
#190
