### ISSUE TITLE
No validation on length of Mobile Number

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#214]
https://github.com/bombardier-gif/covid-vaccine-booking/blob/669fa39befc9518f4a359133abec707c6c29ae04/src/covid-vaccine-slot-booking.py#L31

**Comment by vishalv26** [comment]
Let's not crystalize this much. we are good as long as it allows to enter right number and accepts it and work with it.

**Comment by shailesh** [comment]
I agree but a simple validation for typos
