### ISSUE TITLE
ios shortcuts not sending the otp

### ISSUE THREAD

**Issue by cm3913** [bombardier-gif/covid-vaccine-booking#215]
i have setup ios shortcuts for sending the otp , when i get the otp i can see the Shortcut notification but the otp is not sent to the url https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/99xxxxxx

Phone Iphone x on 14.4

If i manually enter the scrip rest of the code is working fine 

I appreciate your efforts , Keep up the good work 

Please help , Thank You

**Comment by bombardier-gif** [comment]
@BumpyKnuckls fyi

**Comment by gitmnj** [comment]
It works properly for me, you have to add the shortcut properly and have to click the run button which is better than manually entering the otp I've even changed the notifications sound of this shortcut to make it more easy

**Comment by BumpyKnuckls** [comment]
@cm3913 Can you try out the following:

1. Go through the setup steps again for iOS and ensure nothing is missed.
3. Ensure that url is correct and doesn't have spaces.
4. Ensure that ur config is correct (PUT endpoint, File parameters etc)

**Comment by cm3913** [comment]
It was working , I didn't know i had to manually click run 
Please mention it in the guide that we need to click on Run for the shortcut to run 

Thank You
