### ISSUE TITLE
The Program Semi-Crashes Through The Process | CloudFront Error

### ISSUE THREAD

**Issue by malayilneil** [bombardier-gif/covid-vaccine-booking#219]
Hey Bombaridier, Firstly thanks for creating this program I really appreciate the effort you are putting into it. Yesterday onwards I have been getting complaints that the program crashes midway (I feel its because of too much traffic and the server crashes) 

Here's the code 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 3zGaRm3HZrqdk6WkxXonkpKI_AvQoxR4S8k7ycnwZrrxck6637empg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

I feel it must be due to heavy traffic so if you start a donation page, we can add more servers to make sure it doesn't crash. Let me know what you think. 

Unfortunately, this happens at important moments which can't be wasted to find another otp. So I would love to see a fix for it. Let me know what you think.

**Comment by malayilneil** [comment]
The Program I use is the latest one just wanted to let you know.

**Comment by BumpyKnuckls** [comment]
@bombardier-gif can keep me sane here, but I don't think we can do much here from the script side since error looks like server side. You can possibly try two things:

1. Try running the script at another time and see if the requests go through
2. Maybe try running with a reduced polling frequency?

**Comment by malayilneil** [comment]
@BumpyKnuckls @bombardier-gif Well the script works most of the time. However, it crashes at essential times. Let's say in my place the slots open at 10:00 am, at 9:59 am the site crashes and this error is brought up. This error will initiate the process from the start (getting OTP from phone and so on). It takes a while to boot back up and by that time the slots will be gone.  I have tried reduced frequency the effect is still the same. Also in my area, the slots get booked in less than a minute. 

I'm helping out people with low technology resources so it would be great if we could figure something out. I just know very basic programming so apologies if my idea is dumb, but here are my two cents on the problem. 

1. Since it's a server side issue maybe we may need to amp up the servers from your end. So this problem won't happen again.
    1a) If that's not a possible (due to monetary constraints, capacity constraints,), maybe you can show us how to create a 
           server and changes in code which is required to make the program work using the server we just created. 
    1b) If it's just a monetary constraint we can set something up for donations.

**Comment by Nakul93** [comment]
Ok so @malayilneil this script doesn’t run on a servers. It’s running from your local machine. It’s just automates the entire process of booking that one would manually do it on the portal.
As for your issue, what system are you using?
Also try switching to a different internet(stable) connection and check.
Hope this helps

**Comment by malayilneil** [comment]
Hey @Nakul93 

I see now! Well, I'm using an i7 ultrabook with a 200 Mbps airtel connection.  Let me see if it switching to a different internet connection will work? Also, do you think it's a good idea if I add this program to repl.it and run it using their server since it must be much more stable than mine?

**Comment by Nakul93** [comment]
> Hey @Nakul93
> 
> I see now! Well, I'm using an i7 ultrabook with a 200 Mbps airtel connection. Let me see if it switching to a different internet connection will work? Also, do you think it's a good idea if I add this program to repl.it and run it using their server since it must be much more stable than mine?

You could give it a try with repl if you want to.
And are using windows/linux?
If using windows you can try out this repo https://github.com/SRvSaha/CoWinVaccineSlotFinder

**Comment by bombardier-gif** [comment]
> @bombardier-gif can keep me sane here, but I don't think we can do much here from the script side since error looks like server side. You can possibly try two things:
> 
> 1. Try running the script at another time and see if the requests go through
> 2. Maybe try running with a reduced polling frequency (not 100% it will help)?

As Mr. Bumpy said, this is a rate limiting error. It happens when too many people are using the script
The only way is to try again later.
