### ISSUE TITLE
Multiple beneficiary booking blocked by CoWIN ?

### ISSUE THREAD

**Issue by pradiptabasu** [bombardier-gif/covid-vaccine-booking#220]
**I noticed just now that booking slots for multiple benificary together is not being allowed in CoWIN or Arogya Setu UI.**
Has there been a change in the backend API also ? Any change needed in this script ?

**Comment by ithihasmadala** [comment]
Script works just fine for multiple beneficiaries as long as both are for a particular dose, vaccine and age group.

**Comment by ithihasmadala** [comment]
@bombardier-gif This can be closed

**Comment by BumpyKnuckls** [comment]
Thanks @ithihasmadala closing this now.
