### ISSUE TITLE
Error while booking - 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by darthfishious** [bombardier-gif/covid-vaccine-booking#222]
Getting an error - **'NoneType' object is not iterable** - at the time of finding centers. Centers are showing available in CoWin

My feetype is set to No Preference (0) and captcha automation is off.

**Comment by subashjain** [comment]
> Getting an error - **'NoneType' object is not iterable** - at the time of finding centers. Centers are showing available in CoWin
> 
> My feetype is set to No Preference (0) and captcha automation is off.

Same message i got

**Comment by inn-varun-suresh** [comment]
Same message here as well

**Comment by Nakul93** [comment]
Can you provide with some logs. Everything seems to be working fine at my end

**Comment by sanket-gupta** [comment]
'NoneType' object is not iterable just came for me

I was looking for paid  vaccine centers, any tyoe of vaccine
Centers available in Mumbai from 20-05-2021 as of 2021-05-19 16:49:43: 2
{'center_id': 595085, 'name': 'SAIFEE HOSPITAL', 'address': '15-17 Maharshi Karve Road', 'state_name': 'Maharashtra', 'district_name': 'Mumbai', 'block_name': 'Ward D Corporation - MH', 'pincode': 400004, 'lat': 18, 'long': 72, 'from': '09:30:00', 'to': '12:00:00', 'fee_type': 'Paid', 'sessions': [{'session_id': '5db50aa7-37fc-4e54-9609-2ac6e6dea718', 'date': '20-05-2021', 'available_capacity': 44, 'min_age_limit': 18, 'vaccine': 'COVAXIN', 'slots': ['09:30AM-11:30AM', '11:30AM-12:00PM'], 'available_capacity_dose1': 44, 'available_capacity_dose2': 0}], 'vaccine_fees': [{'vaccine': 'COVAXIN', 'fee': '1250'}]}
{'session_id': '5db50aa7-37fc-4e54-9609-2ac6e6dea718', 'date': '20-05-2021', 'available_capacity': 44, 'min_age_limit': 18, 'vaccine': 'COVAXIN', 'slots': ['09:30AM-11:30AM', '11:30AM-12:00PM'], 'available_capacity_dose1': 44, 'available_capacity_dose2': 0}
'fee_type'
'NoneType' object is not iterable
Retryin in 5 seconds

**Comment by vismaiy** [comment]
I had the same error! So now I have set the fee type to paid, just in case it works.

**Comment by sanket-gupta** [comment]
mine was set to paid, it failed for that also

**Comment by Abhinav2812** [comment]
@sanket-gupta can you try adding
`import traceback;print(traceback.format_exc())`
After `print('Exiting script)` in `covid-vaccine-slot-booking.py` and running again? This will give us more insight of where the error is originating

**Comment by sanket-gupta** [comment]
Centers available in 110085 from 20-05-2021 as of 2021-05-19 17:46:26: 17
{'center_id': 610022, 'name': 'Dr BSA Hospital DH 4', 'address': 'Sector -VI, Rohini, Delhi - 85', 'state_name': 'Delhi', 'district_name': 'North West Delhi', 'block_name': 'Not Applicable', 'pincode': 110085, 'lat': 28, 'long': 77, 'from': '09:00:00', 'to': '21:00:00', 'fee_type': 'Free', 'sessions': [{'session_id': '79a9aa54-9feb-4a29-9b89-6f62d98de72c', 'date': '20-05-2021', 'available_capacity': 68, 'min_age_limit': 45, 'vaccine': 'COVISHIELD', 'slots': ['09:00AM-12:00PM', '12:00PM-03:00PM', '03:00PM-06:00PM', '06:00PM-09:00PM'], 'available_capacity_dose1': 0, 'available_capacity_dose2': 68}, {'session_id': 'a65940ae-7420-4008-9c55-d9df8e5462dc', 'date': '21-05-2021', 'available_capacity': 120, 'min_age_limit': 45, 'vaccine': 'COVISHIELD', 'slots': ['09:00AM-12:00PM', '12:00PM-03:00PM', '03:00PM-06:00PM', '06:00PM-09:00PM'], 'available_capacity_dose1': 19, 'available_capacity_dose2': 101}, {'session_id': 'dae61d5e-6a82-4e9c-b9d3-182978b34ee3', 'date': '22-05-2021', 'available_capacity': 144, 'min_age_limit': 45, 'vaccine': 'COVISHIELD', 'slots': ['09:00AM-12:00PM', '12:00PM-03:00PM', '03:00PM-06:00PM', '06:00PM-09:00PM'], 'available_capacity_dose1': 64, 'available_capacity_dose2': 80}, {'session_id': '71912bb6-bc1e-499e-bfdf-3c16e4fdf3b1', 'date': '24-05-2021', 'available_capacity': 166, 'min_age_limit': 45, 'vaccine': 'COVISHIELD', 'slots': ['09:00AM-12:00PM', '12:00PM-03:00PM', '03:00PM-06:00PM', '06:00PM-09:00PM'], 'available_capacity_dose1': 94, 'available_capacity_dose2': 72}, {'session_id': '89fbeccd-c050-4ca5-8761-32874d58dea9', 'date': '25-05-2021', 'available_capacity': 181, 'min_age_limit': 45, 'vaccine': 'COVISHIELD', 'slots': ['09:00AM-12:00PM', '12:00PM-03:00PM', '03:00PM-06:00PM', '06:00PM-09:00PM'], 'available_capacity_dose1': 96, 'available_capacity_dose2': 85}]}
{'session_id': '79a9aa54-9feb-4a29-9b89-6f62d98de72c', 'date': '20-05-2021', 'available_capacity': 68, 'min_age_limit': 45, 'vaccine': 'COVISHIELD', 'slots': ['09:00AM-12:00PM', '12:00PM-03:00PM', '03:00PM-06:00PM', '06:00PM-09:00PM'], 'available_capacity_dose1': 0, 'available_capacity_dose2': 68}
{'session_id': 'a65940ae-7420-4008-9c55-d9df8e5462dc', 'date': '21-05-2021', 'available_capacity': 120, 'min_age_limit': 45, 'vaccine': 'COVISHIELD', 'slots': ['09:00AM-12:00PM', '12:00PM-03:00PM', '03:00PM-06:00PM', '06:00PM-09:00PM'], 'available_capacity_dose1': 19, 'available_capacity_dose2': 101}
'fee_type'
'NoneType' object is not iterable
Retryin in 5 seconds
Traceback (most recent call last):
  File "C:\Users\Sanket\Documents\Code\covid-vaccine-booking\src\covid-vaccine-slot-booking.py", line 116, in main
    token_valid = check_and_book(request_header, info.beneficiary_dtls, info.location_dtls, info.search_option,
  File "C:\Users\Sanket\Documents\Code\covid-vaccine-booking\src\utils.py", line 553, in check_and_book
    options = sorted(
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "C:\Users\Sanket\Documents\Code\covid-vaccine-booking\src\covid-vaccine-slot-booking.py", line 116, in main
    token_valid = check_and_book(request_header, info.beneficiary_dtls, info.location_dtls, info.search_option,
  File "C:\Users\Sanket\Documents\Code\covid-vaccine-booking\src\utils.py", line 553, in check_and_book
    options = sorted(
TypeError: 'NoneType' object is not iterable

**Comment by sanket-gupta** [comment]
this is the code at line 553


        if isinstance(options, bool):
            return False

        options = sorted(
            options,
            key=lambda k: (
                k["district"].lower(),
                k["pincode"],
                k["name"].lower(),
                datetime.datetime.strptime(k["date"], "%d-%m-%Y"),
            ),
        )

**Comment by sanket-gupta** [comment]
The problem is in the call to viable_options

**Comment by sanket-gupta** [comment]
![image](https://user-images.githubusercontent.com/4071709/118813336-a53cda80-b8cc-11eb-9755-5031d860c65b.png)

**Comment by sanket-gupta** [comment]
I think fee_type is part of the center object and not session

**Comment by Nakul93** [comment]
@sanket-gupta i think you are right, can you remove those lines and check

**Comment by sanket-gupta** [comment]
"fee_type": center["fee_type"], fixes the issue

**Comment by Nakul93** [comment]
> "fee_type": center["fee_type"], fixes the issue

Great, were you able to book now?

**Comment by sanket-gupta** [comment]
ha ha! the slots dont wait for us to fix the code!

I created a PR with the fix.

**Comment by sanket-gupta** [comment]
https://github.com/bombardier-gif/covid-vaccine-booking/pull/226
