### ISSUE TITLE
Delayed Availability Data

### ISSUE THREAD

**Issue by sanket-gupta** [bombardier-gif/covid-vaccine-booking#223]
I was tracking a particular center today. My Script was running at an interval of 10 seconds.

On Telegram , I received an update exactly at 16.00 hours that the center was available.
But my script showed the following

=========
Centers available in Mumbai from 20-05-2021 as of 2021-05-19 16:00:48: 0
===================================================================================
Centers available in Mumbai from 20-05-2021 as of 2021-05-19 16:00:58: 0
===================================================================================
Centers available in Mumbai from 20-05-2021 as of 2021-05-19 16:01:08: 1
=========

So  1 minute 8 seconds after the telegram message, the script got the center in the available list. Unfortunately, all the slots had already been booked at that point of time.
Do we know why/how the bots updating telegram are able to get availability data faster?

**Comment by japp2021** [comment]
Exact same issue with me. I was running at an interval of 5 seconds for COVAXIN in Mumbai. Missed it thrice as 3 centers opened in a span of an hour. It was not able to detect the availability whereas Telegram showed slots in all 3 instances.

**Comment by bombardier-gif** [comment]
Thats the nature of the APIs, you can run the script at 1 second freq, but still you will miss out some slots. the data is cached in their API so there is some discrepancy:
read the first para https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2
