### ISSUE TITLE
iOS OTP Automation

### ISSUE THREAD

**Issue by aryamangiri** [bombardier-gif/covid-vaccine-booking#225]
Hi,

I am getting the following error when I try OTP automation:

`
Do you want to enter OTP manually, instead of auto-read?
Remember selecting n would require some setup described in README (y/n Default n): n
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/8xxxxxxxxx
HTTPSConnectionPool(host='kvdb.io', port=443): Max retries exceeded with url: /ASth4wnvVDPkg2bdjsiqMN/8xxxxxxxxx  (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
`

In the first run of the script, I don't get the OTP on my phone or the run notification for the shortcut. So I ran using manual entry for OTP.
However, when the script resends the OTP after a while, I get a notification on my phone and I am able to see it in the KvDB link after I click Run. But since I chose manual option, this step does not get automated. 

Has anyone else encountered this? Any advice to fix this issue would be helpful!

Thanks in advance!

**Comment by BumpyKnuckls** [comment]
You can rerun the script and clear the earlier selected preference of manual OTP and instead chose auto-read.

**Comment by aryamangiri** [comment]
> You can rerun the script and clear the earlier selected preference of manual OTP and instead chose auto-read.

I tried that and it didn't work,
