### ISSUE TITLE
Why with the new script centers are showing Zero ?

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#227]
Why with the new script centers are showing Zero ? Earlier it used to show many.
I see at least there are 3 centers are available from the portal.
They are all booked but 3 centers are available with 0 available capacity.

**Comment by Nakul93** [comment]
Which district/pincode are you searching for?

**Comment by xxxAng** [comment]
@Nakul93  West Bengal (37 district code)
City -  Kolkata (17)
City - North 24 Parganas (22)

**Comment by Nakul93** [comment]
@xxxAng Sorry I could only check for COVISHIELD, 18+ and this area doesn't have any centers for the entire week. I've tried for other states and the script seems to work fine
Please check your preferences once before running.

**Comment by xxxAng** [comment]
@Nakul93  i checked both covaxin also...:( ... see the script should at least return 1
![image](https://user-images.githubusercontent.com/25231713/118856415-ec16da00-b8a4-11eb-9994-ce9d3a258a8f.png)

**Comment by Nakul93** [comment]
Have you pulled the latest changes?
Also try with different states&districts

**Comment by xxxAng** [comment]
Yes 2 hours ago @Nakul93

**Comment by xxxAng** [comment]
Checked it not working either showing 0 only

**Comment by bombardier-gif** [comment]
interesting, can you check some other city like bangalore where there are a lot more vaccines added continuously?

**Comment by xxxAng** [comment]
Will check and let you know

**Comment by xxxAng** [comment]
@bombardier-gif @Nakul93  it seems a bug on both side,

1. I had a registered candidate which appointment i cancelled for dose1, but it seems it kept the previous vaccine type Covishield for the user in cowin portal,
2. Since the script got vaccine type from COWIN its not letting me to select vaccine type for the person.
3. For cancelled candidate its picking Dose Number 2 instead of 1, Thats why the centers were showing 0 always.

Can we fix this guys ?

**Comment by xxxAng** [comment]
opened a separate bug
