### ISSUE TITLE
Not booking if 45+ & 18+ open together

### ISSUE THREAD

**Issue by pankajahuja1011** [bombardier-gif/covid-vaccine-booking#229]
Hi.

For centres that open 18+ and 45+ together like kokilabenin mumbai,
the script detects new centre in count of centres but doesnt book the slot

Is there a way out or help for this?

**Comment by chetan4635** [comment]
I am also facing the same issue when both 18 and 45+ opens it shows that centers are available but it does not book the slot

**Comment by NK0211** [comment]
no buddy that is not the case.... i tried multiple times with different location and centers...

**Comment by bombardier-gif** [comment]
+1 to what @Nakul93 said. @chetan4635 and @pankajahuja1011 Please check your inputs and the availability and let us know

**Comment by ithihasmadala** [comment]
Faced the same issue, will look into why it could be happening...

**Comment by BumpyKnuckls** [comment]
Folks any thoughts on what @bombardier-gif said?

**Comment by bombardier-gif** [comment]
Please re-open if this issue still exists
