### ISSUE TITLE
Captcha response 200

### ISSUE THREAD

**Issue by Dhanushrajashekar** [bombardier-gif/covid-vaccine-booking#23]
Hey!! i came into an problem with the captcha i got the slot but i was not able to get it booked automatically because it gave an error called captcha 200.. Can you please help with the new code 
![2](https://user-images.githubusercontent.com/70057181/117603911-cafe0d00-b171-11eb-8ca7-0b6d7dfb0573.png)

**Comment by dhiralkapadia** [comment]
Yes facing the same issue

**Comment by bombardier-gif** [comment]
So the root cause is that your machine does not have the fonts installed. 
Search for the error "Can`t setFont(Times-Roman) missing the T1 files?"

**Comment by abhinavj98** [comment]
Another work around is to run the python script directly in the src folder after installing the required modules from requirements.txt. That solved it for me

**Comment by Dhanushrajashekar** [comment]
> Another work around is to run the python script directly in the src folder after installing the required modules from requirements.txt. That solved it for me

I will try this out now. Hope it works!!

**Comment by jishnu-gv** [comment]
Hi , Can you add this and give the new exe for windows

Download this pfbfer.zip, and extract it.

Now put all the files of this pfbfer in...

/usr/lib/python2.7/dist-packages/reportlab/fonts/(put the files)

If the fonts folder is not available in reportlab directory then create it and put all the font-files in fonts from the extract folder pfbfer.

**Comment by bombardier-gif** [comment]
I dont use windows. So request you to do it and share the code. EXE creation is straightforward

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Dhanushrajashekar** [comment]
> Hi , Can you add this and give the new exe for windows
> 
> Download this pfbfer.zip, and extract it.
> 
> Now put all the files of this pfbfer in...
> 
> /usr/lib/python2.7/dist-packages/reportlab/fonts/(put the files)
> 
> If the fonts folder is not available in reportlab directory then create it and put all the font-files in fonts from the extract folder pfbfer.

Hey bro can you do it and send please im waiting from morning

**Comment by rationdukan** [comment]
Yup, I am also facing the same issue and waiting for you to resolve. @bombardier-gif Please help if you can

**Comment by BumpyKnuckls** [comment]
@rationdukan Can you consider giving @abhinavj98's solution a shot and see if it works for you? He was able to run it directly from the src folder.

**Comment by bombardier-gif** [comment]
> > Hi , Can you add this and give the new exe for windows
> > Download this pfbfer.zip, and extract it.
> > Now put all the files of this pfbfer in...
> > /usr/lib/python2.7/dist-packages/reportlab/fonts/(put the files)
> > If the fonts folder is not available in reportlab directory then create it and put all the font-files in fonts from the extract folder pfbfer.
> 
> Hey bro can you do it and send please im waiting from morning

@Dhanushrajashekar This solution is for some another package. I dont know where pfbfer.zip exists and what is reportlab.

**Comment by BlackRider97** [comment]
Anyone tried this on Windows ? 
I am also getting this captcha error

```
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None
===================================================================================
```

Still need to verify @abhinavj98 's solution.  waiting for slot to open :P

**Comment by dhawalpatel129** [comment]
Hi All, I tried the solution mentioned [here ](https://stackoverflow.com/questions/28281891/cant-setfonttimes-roman-missing-the-t1-files#:~:text=Download%20this%20pfbfer.,of%20this%20pfbfer%20in...&text=If%20the%20fonts%20folder%20is,from%20the%20extract%20folder%20pfbfer.) in Stackoverflow and it worked for me on windows.
Now seeing the captcha screen properly.

For me, I put the font files in this location:
"_C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\reportlab\fonts_"

Whichever python (2/3) you are using to run the program, put these files in that location. I'm using Python-3 here so I put those in the above path. (I also have Python2 with diff location)

**Comment by BumpyKnuckls** [comment]
@dhawalpatel129 thanks a lot for getting back. Let me know if you want to raise a PR and update the readme with this solution. I am thinking a dedicated section in README "Troubleshooting to common issues" and we can put this under this section. Else I'll be happy to raise it too!

**Comment by rheak01** [comment]
> Another work around is to run the python script directly in the src folder after installing the required modules from requirements.txt. That solved it for me

like its giving error when ran in src that utils not present how to resolve that?

**Comment by rheak01** [comment]
> Another work around is to run the python script directly in the src folder after installing the required modules from requirements.txt. That solved it for me

hey can you help how to do this

**Comment by BlackRider97** [comment]
Working for me after running script from `src` directory

**Comment by uvmittal** [comment]
> Hi All, I tried the solution mentioned [here ](https://stackoverflow.com/questions/28281891/cant-setfonttimes-roman-missing-the-t1-files#:~:text=Download%20this%20pfbfer.,of%20this%20pfbfer%20in...&text=If%20the%20fonts%20folder%20is,from%20the%20extract%20folder%20pfbfer.) in Stackoverflow and it worked for me on windows.
> Now seeing the captcha screen properly.
> 
> For me, I put the font files in this location:
> "_C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\reportlab\fonts_"
> 
> Whichever python (2/3) you are using to run the program, put these files in that location. I'm using Python-3 here so I put those in the above path. (I also have Python2 with diff location)

missing reportlab folder

**Comment by bombardier-gif** [comment]
> Another work around is to run the python script directly in the src folder after installing the required modules from requirements.txt. That solved it for me

This seems to be the solution which worked for a lot of people

**Comment by Ishvendra** [comment]
> > Hi All, I tried the solution mentioned [here ](https://stackoverflow.com/questions/28281891/cant-setfonttimes-roman-missing-the-t1-files#:~:text=Download%20this%20pfbfer.,of%20this%20pfbfer%20in...&text=If%20the%20fonts%20folder%20is,from%20the%20extract%20folder%20pfbfer.) in Stackoverflow and it worked for me on windows.
> > Now seeing the captcha screen properly.
> > For me, I put the font files in this location:
> > "_C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\reportlab\fonts_"
> > Whichever python (2/3) you are using to run the program, put these files in that location. I'm using Python-3 here so I put those in the above path. (I also have Python2 with diff location)
> 
> missing reportlab folder
> anyone
> im stuck at this place
> "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\

I think you gotta install reportlab.
1. open command prompt.
2. type- C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Scripts> pip install reportlab
This should create the reportlab and fonts folder

**Comment by uvmittal** [comment]
> > > Hi All, I tried the solution mentioned [here ](https://stackoverflow.com/questions/28281891/cant-setfonttimes-roman-missing-the-t1-files#:~:text=Download%20this%20pfbfer.,of%20this%20pfbfer%20in...&text=If%20the%20fonts%20folder%20is,from%20the%20extract%20folder%20pfbfer.) in Stackoverflow and it worked for me on windows.
> > > Now seeing the captcha screen properly.
> > > For me, I put the font files in this location:
> > > "_C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\reportlab\fonts_"
> > > Whichever python (2/3) you are using to run the program, put these files in that location. I'm using Python-3 here so I put those in the above path. (I also have Python2 with diff location)
> > 
> > 
> > missing reportlab folder
> > anyone
> > im stuck at this place
> > "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\
> 
> I think you gotta install reportlab.
> 
> 1. open command prompt.
> 2. type- C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Scripts> pip install reportlab
>    This should create the reportlab and fonts folder

![image](https://user-images.githubusercontent.com/69962764/117698855-cbce8780-b1e1-11eb-9176-e75cfedad5a2.png)

**Comment by Ishvendra** [comment]
> > > > Hi All, I tried the solution mentioned [here ](https://stackoverflow.com/questions/28281891/cant-setfonttimes-roman-missing-the-t1-files#:~:text=Download%20this%20pfbfer.,of%20this%20pfbfer%20in...&text=If%20the%20fonts%20folder%20is,from%20the%20extract%20folder%20pfbfer.) in Stackoverflow and it worked for me on windows.
> > > > Now seeing the captcha screen properly.
> > > > For me, I put the font files in this location:
> > > > "_C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\reportlab\fonts_"
> > > > Whichever python (2/3) you are using to run the program, put these files in that location. I'm using Python-3 here so I put those in the above path. (I also have Python2 with diff location)
> > > 
> > > 
> > > missing reportlab folder
> > > anyone
> > > im stuck at this place
> > > "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\
> > 
> > 
> > I think you gotta install reportlab.
> > 
> > 1. open command prompt.
> > 2. type- C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Scripts> pip install reportlab
> >    This should create the reportlab and fonts folder
> 
> ![image](https://user-images.githubusercontent.com/69962764/117698855-cbce8780-b1e1-11eb-9176-e75cfedad5a2.png)

https://www.howtogeek.com/wp-content/uploads/2020/02/change-directories-GIF.gif?format=mp4

type `cd ` then drag the scripts folder on the command prompt. Press enter. Then type ` pip install reportlab`

**Comment by uvmittal** [comment]
> Hi All, I tried the solution mentioned [here ](https://stackoverflow.com/questions/28281891/cant-setfonttimes-roman-missing-the-t1-files#:~:text=Download%20this%20pfbfer.,of%20this%20pfbfer%20in...&text=If%20the%20fonts%20folder%20is,from%20the%20extract%20folder%20pfbfer.) in Stackoverflow and it worked for me on windows.
> Now seeing the captcha screen properly.
> 
> For me, I put the font files in this location:
> "_C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Lib\site-packages\reportlab\fonts_"
> 
> Whichever python (2/3) you are using to run the program, put these files in that location. I'm using Python-3 here so I put those in the above path. (I also have Python2 with diff location)

issue persists even after fix

**Comment by uvmittal** [comment]
Captcha Response Code: 200
Warn: Can't find .pfb for face 'Times-Roman'
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None

**Comment by avadhut007** [comment]
What happens after you book the slot? Does the script stops or keep booking the slot at next center?

**Comment by rheak01** [comment]
> Captcha Response Code: 200
> Warn: Can't find .pfb for face 'Times-Roman'
> Can't setFont(Times-Roman) missing the T1 files?
> Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None

just run the file from src folder , and you will not face this error

**Comment by sid8840** [comment]
Issue solved
working fine on windows

**Comment by bombardier-gif** [comment]
> What happens after you book the slot? Does the script stops or keep booking the slot at next center?

The script exits with a beep.
