### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by darthfishious** [bombardier-gif/covid-vaccine-booking#230]
Getting error with captcha at the time of booking. Captcha Automation is off.

Captcha Response Code: 200
[Errno 13] Permission denied: 'captcha.svg'

![Error 200 Captcha](https://user-images.githubusercontent.com/84447012/118968215-438e7600-b989-11eb-800d-d115cd768025.png)

**Comment by xxxAng** [comment]
@darthfishious this is not a script issue this is rather permission issue for writing captcha in ur system,
Please place it to some other drive and make sure u run the EXE in administrator mode.
Not an issue

**Comment by darthfishious** [comment]
OK thanks @xxxAng . Running it in cmd rather than python 3.9 did the trick.
