### ISSUE TITLE
Captcha --  Is this normal?

### ISSUE THREAD

**Issue by biscuitdey** [bombardier-gif/covid-vaccine-booking#231]
![Screenshot 2021-05-20 at 6 58 19 PM](https://user-images.githubusercontent.com/5380018/118986884-59a63180-b99d-11eb-86cd-b78a5c37d2c7.png)

**Comment by gitmnj** [comment]
Add tk lib using requirements

**Comment by xxxAng** [comment]
@gitmnj  use command prompt and install the latest version of TkInker library

"pip install tk"

Close the issue if u are done

**Comment by gitmnj** [comment]
@xxxAng not my issue

**Comment by xxxAng** [comment]
@gitmnj  yeah the biscuit guy .. is not taggable .. lol
my bad

**Comment by biscuitdey** [comment]
Installed tkinter 8.5
