### ISSUE TITLE
Throughtput exceeding error after captcha enter

### ISSUE THREAD

**Issue by sanmil09** [bombardier-gif/covid-vaccine-booking#232]
Error in booking after captcha enter.

What can be done to resolve? 

Booking response code: 500 

![image](https://user-images.githubusercontent.com/46552771/118995682-f9b38900-b9a4-11eb-84c8-5a9670bca8ae.png)

**Comment by sanmil09** [comment]
I saw your comment on this being a error of scaling on their side, what can be done from our side?

**Comment by BlackRider97** [comment]
I have fixed this error issue in #216

**Comment by sanket-gupta** [comment]
Wasnt this an issue on the CowinApi Server?

**Comment by bombardier-gif** [comment]
This is being rate limited by the server. They use aws dynamodb. Try to reduce the frequency and try after a while
