### ISSUE TITLE
Dose 1 & Dose 2 separate slot issue

### ISSUE THREAD

**Issue by NK0211** [bombardier-gif/covid-vaccine-booking#233]
So, I have been using the code to book slots (a big thank you!!!) before CoWin site introduced separate slots for Dose 1 & Dose 2 .

Now the issue is that, suppose if I want to book a slot for Dose 1 at a particular center and if slots for Dose 2 are available at that center , the script will attempt to book (as it will see that slots are available)  and Captcha slide will appear. But as soon as you enter Captcha the script is stuck in loop as it could not find any slots in Dose 1 and thus the Captcha slide will keep on coming every time you enter.

Can this be resolved by minor changes in the code??

**Comment by Nakul93** [comment]
Maybe there was slots open for dose1 as well at the centre, but by the time you have entered the captcha it might have got filled.
What error are you getting, can you provide some logs?

**Comment by NK0211** [comment]
Hi @Nakul93, I have attached 2 screen shots , one is from CoWin site stating slots available for Covaxin but for Dose 2, whereas Json file for booking is for Dose1, for that the second screenshot of command prompt is attached.
![Cowin](https://user-images.githubusercontent.com/84517473/119018275-8ec07d00-b9b9-11eb-8e4b-4854b3b81ec5.png)
![JSON](https://user-images.githubusercontent.com/84517473/119018282-8ff1aa00-b9b9-11eb-92c7-158d9805380f.png)

**Comment by NK0211** [comment]
this captcha response 200 is a pinned issue .....is this a similar one??

**Comment by Nakul93** [comment]
@NK0211 Are you getting a Booking Response Code? (like resp code 200/400/500)

**Comment by NK0211** [comment]
Booking response code : 409

**Comment by Nakul93** [comment]
Ok that means all slots are booked. But ideally it shouldn't go through. I've tested it at my end and everything seems to be working fine. Have you pulled in the latest code?

**Comment by NK0211** [comment]
oh i was using the old file now loaded the new one its working perfectly fine.....sorry to bother buddy and thanks for the help......i am not much familiar with coding .......just followed steps and did ....thus was unaware ...anyway thanks
