### ISSUE TITLE
Captcha 200 issue while booking

### ISSUE THREAD

**Issue by dasanupam** [bombardier-gif/covid-vaccine-booking#237]
Still getting same  issue of Captcha 200 while booking slot even when selecting no for captcha autofill 

Also tried the captcha test script and that also fails only for the auto test function. First it shows passed for the mannaul test func and then again shows the following errors message for the auto test function

Installed tkinter_version: 8.6.9
Opening test window. Click on "Quit" to run further tests
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
window opening ...
Yeah !!! you have entered captcha. This means you are all set to render required captcha at the time of booking ...

x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
Started solving captcha...
making request to createTask
could not create task
API error ERROR_KEY_DOES_NOT_EXIST: Account authorization key not found in the system
Task finished with error: ERROR_KEY_DOES_NOT_EXIST - 0

**Comment by bombardier-gif** [comment]
API error ERROR_KEY_DOES_NOT_EXIST: Account authorization key not found in the system

Typically happens when you did not register for the third party captcha system, you also need to enter the key
