### ISSUE TITLE
Unwanted code | Data storing in own database

### ISSUE THREAD

**Issue by kondorpa** [bombardier-gif/covid-vaccine-booking#238]
In util.py file, line number 471 (at present), why are you sending data to your server after booking confirmation ?

`requests.put("https://kvdb.io/thofdz57BqhTCaiBphDCp/" + str(uuid.uuid4()), data={})`

Can someone tell me why this line of code is required?

**Comment by bombardier-gif** [comment]
This is anonymised counter to know how many people are using this script. 
Based on the usage, we merge PRs aggresively/ or hold on.

A major problem with this script is that we cannot test any change, so PRs have to be taken with a grain of salt.
