### ISSUE TITLE
BUG - For cancelled candidates its always searching for Dose 2 instead of 1

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#239]
1. I had a registered candidate which appointment i cancelled for dose1, but it seems it kept the previous vaccine type Covishield for the user in cowin portal,
2. Since the script got vaccine type from COWIN its not letting me to select vaccine type for the person.
3. For cancelled candidate its picking Dose Number 2 instead of 1, Thats why the centers were showing 0 always.
Can we fix this guys ?

image

**Comment by xxxAng** [comment]
![image](https://user-images.githubusercontent.com/25231713/119084853-8c1d5200-b9d0-11eb-939f-c0c924d9dc4d.png)

**Comment by Nakul93** [comment]
@xxxAng Please mask your ref id as well in the above image

**Comment by Nakul93** [comment]
I think its a bug from the CoWIN portal end that you cannot choose another vaccine type. As for the dose, can you change the get_dose_num func in utils.py in the followin manner and check
`def get_dose_num(collected_details):
    # If any person has vaccine detail populated, we imply that they'll be taking second dose
    # Note: Based on the assumption that everyone have the *EXACT SAME* vaccine status 
    if all(detail['status']== 'Partially Vaccinated'
           for detail in collected_details["beneficiary_dtls"]):
        return 2

    return 1`

**Comment by shailesh** [comment]
yes it is a cowin bug, verified

**Comment by xxxAng** [comment]
@Nakul93 @shailesh @bombardier-gif ,
Yes I mentioned its a bug in COWIN, we can fix it in script,
utils.py,
method - collect_user_details

add small piece of code,
`vaccine_statuses = [beneficiary["status"] for beneficiary in beneficiary_dtls]
    vaccine_status = vaccine_statuses[0]

    vaccine_type = vaccine_types[
        0
    ]  # if all([beneficiary['status'] == 'Partially Vaccinated' for beneficiary in beneficiary_dtls]) else None
    if not vaccine_type or vaccine_status == "Not Vaccinated":`

You can close this defect now..

**Comment by Akash199211113** [comment]
I am not getting how to fix this can you please help me I have changed the code as below in utils.py in the method collect_user_details as below

def collect_user_details(request_header):
    # Get Beneficiaries
    print("Fetching registered beneficiaries.. ")
    beneficiary_dtls = get_beneficiaries(request_header)


    if len(beneficiary_dtls) == 0:
        print("There should be at least one beneficiary. Exiting.")
        os.system("pause")
        sys.exit(1)
    
vaccine_statuses = [beneficiary["status"] for beneficiary in beneficiary_dtls]
vaccine_status = vaccine_statuses[0]
vaccine_type = vaccine_types[0]
if not vaccine_type or vaccine_status == "Not Vaccinated":
    
    # Make sure all beneficiaries have the same type of vaccine
    vaccine_types = [beneficiary["vaccine"] for beneficiary in beneficiary_dtls]
    vaccines = Counter(vaccine_types)

    if len(vaccines.keys()) != 1:
        print(
            f"All beneficiaries in one attempt should have the same vaccine type. Found {len(vaccines.keys())}"
        )
        os.system("pause")
        sys.exit(1)

    vaccine_type = vaccine_types[
        0
    ]  # if all([beneficiary['status'] == 'Partially Vaccinated' for beneficiary in beneficiary_dtls]) else None
    if not vaccine_type:
        print(
            "\n================================= Vaccine Info =================================\n"
        )
        vaccine_type = get_vaccine_preference()

    print(
        "\n================================= Location Info =================================\n"
    )
    # get search method to use
    search_option = input(
        """Search by Pincode? Or by State/District? \nEnter 1 for Pincode or 2 for State/District. (Default 2) : """
    )

    if not search_option or int(search_option) not in [1, 2]:
        search_option = 2
    else:
        search_option = int(search_option)

    if search_option == 2:
        # Collect vaccination center preferance
        location_dtls = get_districts(request_header)

    else:
        # Collect vaccination center preferance
        location_dtls = get_pincodes()

    print(
        "\n================================= Additional Info =================================\n"
    )

    # Set filter condition
    minimum_slots = input(
        f"Filter out centers with availability less than ? Minimum {len(beneficiary_dtls)} : "
    )
    if minimum_slots:
        minimum_slots = (
            int(minimum_slots)
            if int(minimum_slots) >= len(beneficiary_dtls)
            else len(beneficiary_dtls)
        )
    else:
        minimum_slots = len(beneficiary_dtls)

    # Get refresh frequency
    refresh_freq = input(
        "How often do you want to refresh the calendar (in seconds)? Default 10. Minimum 5. (You might be blocked if the value is too low, in that case please try after a while with a lower frequency) : "
    )

    refresh_freq = int(refresh_freq) if refresh_freq and int(refresh_freq) >= 1 else 15
    
    
    #Checking if partially vaccinated and thereby checking the the due date for dose2
    if all([beneficiary['status'] == 'Partially Vaccinated' for beneficiary in beneficiary_dtls]):
        today=datetime.datetime.today()
        today=today.strftime("%d-%m-%Y")
        due_date = [beneficiary["dose2_due_date"] for beneficiary in beneficiary_dtls]
        dates=Counter(due_date)
        if len(dates.keys()) != 1:
            print(
                f"All beneficiaries in one attempt should have the same due date. Found {len(dates.keys())}"
            )
            os.system("pause")
            sys.exit(1)
            
            
        if (datetime.datetime.strptime(due_date[0], "%d-%m-%Y")-datetime.datetime.strptime(str(today), "%d-%m-%Y")).days > 0:
            print("\nHaven't reached the due date for your second dose")
            search_due_date=input(
                "\nDo you want to search for the week starting from your due date(y/n) Default n:"
            )
            if search_due_date=="y":
                
                start_date=due_date[0]
            else:
                os.system("pause")
                sys.exit(1)

    else:
        # Get search start date
        start_date = input(
                "\nSearch for next seven day starting from when?\nUse 1 for today, 2 for tomorrow, or provide a date in the format dd-mm-yyyy. Default 2: "
            )
        if not start_date:
            start_date = 2
        elif start_date in ["1", "2"]:
            start_date = int(start_date)
        else:
            try:
                datetime.datetime.strptime(start_date, "%d-%m-%Y")
            except ValueError:
                start_date = 2
                print('Invalid Date! Proceeding with tomorrow.')
    # Get preference of Free/Paid option
    fee_type = get_fee_type_preference()

    print(
        "\n=========== CAUTION! =========== CAUTION! CAUTION! =============== CAUTION! =======\n"
    )
    print(
        "===== BE CAREFUL WITH THIS OPTION! AUTO-BOOKING WILL BOOK THE FIRST AVAILABLE CENTRE, DATE, AND A RANDOM SLOT! ====="
    )
    auto_book = "yes-please"

    print("\n================================= Captcha Automation =================================\n")

    captcha_automation = input("Do you want to automate captcha autofill? (y/n) Default y: ")
    captcha_automation = "y" if not captcha_automation else captcha_automation

    collected_details = {
        "beneficiary_dtls": beneficiary_dtls,
        "location_dtls": location_dtls,
        "search_option": search_option,
        "minimum_slots": minimum_slots,
        "refresh_freq": refresh_freq,
        "auto_book": auto_book,
        "start_date": start_date,
        "vaccine_type": vaccine_type,
        "fee_type": fee_type,
        'captcha_automation': captcha_automation,
    }

    return collected_details

**Comment by Nakul93** [comment]
> I think its a bug from the CoWIN portal end that you cannot choose another vaccine type. As for the dose, can you change the get_dose_num func in utils.py in the followin manner and check
> 
> ```
> def get_dose_num(collected_details):
>     # If any person has vaccine detail populated, we imply that they'll be taking second dose
>     # Note: Based on the assumption that everyone have the *EXACT SAME* vaccine status 
>     if all(detail['status']== 'Partially Vaccinated'
>            for detail in collected_details["beneficiary_dtls"]):
>         return 2
> 
>     return 1
> ```

@Akash199211113 Could you try this and let me know if this works for you?

**Comment by Akash199211113** [comment]
Its working now thanks
