### ISSUE TITLE
'types.SimpleNamespace' object has no attribute 'captcha_api_choice'

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#240]
<img width="1788" alt="Screenshot 2021-05-21 at 10 59 01 AM" src="https://user-images.githubusercontent.com/9050349/119086772-9c125180-ba23-11eb-8513-c978ab583b43.png">

**Comment by ithihasmadala** [comment]
Have you cloned the latest commit? I just rechecked and there is no problem..

**Comment by shailesh** [comment]
yes

**Comment by shailesh** [comment]
On mac it is fixed getting error in ubuntu

**Comment by shailesh** [comment]
this was resolved after re-editing the JSON file not accepting older one

**Comment by BlackRider97** [comment]
@bombardier-gif new features should be added with default values so that existing JSON configs should work
