### ISSUE TITLE
Not able to detect slots which open up

### ISSUE THREAD

**Issue by darthfishious** [bombardier-gif/covid-vaccine-booking#242]
It's getting tougher to book slots using this script. It's repeatedly failed to detect recently opened slots for me at least 5 times since yesterday. By the time it detects, the slots are all booked and there are no viable options. Is this only due to the API limitations or something can be done about this? Wasn't facing this issue day before yesterday.

![screenshot](https://user-images.githubusercontent.com/84447012/119124826-ba417700-ba4e-11eb-9e80-d244f5a71dbd.png)

**Comment by shailesh** [comment]
same here, what is the time frequency you are running?

**Comment by darthfishious** [comment]
2 seconds

**Comment by xxxAng** [comment]
same here

**Comment by xxxAng** [comment]
May be your search criterion didnt match the center opened

**Comment by darthfishious** [comment]
no the criteria was exactly as per the center details. had been fed specifically to get this center. and that's why you can see that at 16:00:28 it shows 0 centers and 2 seconds later it shows 1 center but it is all booked. it wouldn't even show 1 center if the criteria was different.

**Comment by xxxAng** [comment]
@darthfishious  to be honest i am also not getting any luck since last 2 days, may be they have cashed the the data more ...
In busy area its not working as expected since last 2 days.
BTW how much interval u r using to pull up the data

**Comment by darthfishious** [comment]
2 seconds

**Comment by xxxAng** [comment]
May be we are using it to fast and thats why getting cached data,
I will try with 5 lets see..
Earlier 2 even 1 second yielded me good result but not since last 2 days

**Comment by Nakul93** [comment]
A trick that might work is to know the exact timing of the centres slot availability. A min or 2 before that just login and set all your preferences and keep but don’t start the search, wait for the telegram notification as soon as it arrives(which is always on time) hit it and you should instantly get the slots.

**Comment by malayilneil** [comment]
I have the same issue here. An interesting thing that I noticed is that a telegram bot noticed the slots had opened while the program didn't. I know the cached data issue but why does the telegram bot get an alert but we didn't? Is it because they are using different API's which is not the case for us? 

I'm using 1-second intervals. Worked yesterday, the program did not recognize it at all today.

PS :- The Telegram Bot which I'm talking about is under45.in. Which districts are you located in?

**Comment by darthfishious** [comment]
@Nakul93, unfortunately in pune, the timings are very erratic. so it's not possible to be ready always. which is why i was trying the more reliable options in mumbai. but then i faced this issue today.

**Comment by gitmnj** [comment]
Same happened with me the slots didn't showed up only and I kept the frequency at 3 still no catcha poped up

**Comment by malayilneil** [comment]
@Nakul93  any other suggestions you have in mind?

**Comment by Nakul93** [comment]
Check the telegram alerts and look for a pattern, most of the times the slots for a particular centre open within a specific time bracket. Try to analyse that and accordingly run the script. Plus if the slots open at a random time there won’t be much traffic and you should be able to book it quickly.

**Comment by shailesh** [comment]
> Check the telegram alerts and look for a pattern, most of the times the slots for a particular centre open within a specific time bracket. Try to analyse that and accordingly run the script. Plus if the slots open at a random time there won’t be much traffic and you should be able to book it quickly.

this is suggested and great idea to understand the slot opening patterns

**Comment by kondorpa** [comment]
same problem i am also facing. I am running it in 10 sec, and there no way that slots can be filled with in 10 seconds. 20 centers opened up and i could get none. it even did not attempt to book any slot.

**Comment by shailesh** [comment]
please read about this more here

https://github.com/bombardier-gif/covid-vaccine-booking/issues/266#issuecomment-846399904

**Comment by shailesh** [comment]
I hope you were able to book one, hence closing this
