### ISSUE TITLE
BREAKING ISSUE - It seems API changed again, Slots not getting identified

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#244]
We are getting error for unable to figure out slots,

![image](https://user-images.githubusercontent.com/25231713/119135573-9a895f00-ba0c-11eb-9fe3-c453936df7db.png)

@bombardier-gif

**Comment by Nakul93** [comment]
I searched for this pincode but didn’t find this center. Maybe it was a bug on cowin

**Comment by xxxAng** [comment]
I checked now, nevermind... it was a data glitch from COWIN.
