### ISSUE TITLE
Booking responce code 500 

### ISSUE THREAD

**Issue by vesan83** [bombardier-gif/covid-vaccine-booking#245]
can somone please help why i am getting these errors ?

ERROR 1

![error1](https://user-images.githubusercontent.com/2079099/119138808-e9141900-ba5f-11eb-8fe7-7887568e0c71.jpg)

ERROR 2

================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
making request to createTask
created task with id 201827434
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task solved
Captcha text: 8YNrB
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0045", "error":"Your transaction didn't go through. Please try again later"}
Response: 400 : {"errorCode":"APPOIN0045", "error":"Your transaction didn't go through. Please try again later"}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!

**Comment by sanket-gupta** [comment]
These are issues on the Cowin portal.
We cannot do much about this.
Keep trying

**Comment by BumpyKnuckls** [comment]
+1 @sanket-gupta These are issues with Cowin apis itself. Unfortunately we can't do much here.
