### ISSUE TITLE
Booking not going through even though options match

### ISSUE THREAD

**Issue by deveshmanish** [bombardier-gif/covid-vaccine-booking#247]
The booking is not going through even though the options are matching, it just keeps on repeating the loop of no viable options.

===================================================================================
Centers available in 249403 from 22-05-2021 as of 2021-05-21 19:06:25: 0
Centers available in 249407 from 22-05-2021 as of 2021-05-21 19:06:25: 2
Centers available in 249401 from 22-05-2021 as of 2021-05-21 19:06:25: 0
Centers available in 249402 from 22-05-2021 as of 2021-05-21 19:06:25: 0
No viable options. Next update in 3 seconds..

Settings:

{
    "auto_book": "yes-please",
    "beneficiary_dtls": [
        {
            "age": xx,
            "bref_id": "xxxxxx,
            "name": "xxxxx",
            "status": "Not Vaccinated",
            "vaccine": ""
        },
        {
            "age": xx,
            "bref_id": "xxxxxxxx",
            "name": "xxxxx,
            "status": "Not Vaccinated",
            "vaccine": ""
        }
    ],
    "captcha_api_choice": "0",
    "captcha_automation": "y",
    "captcha_automation_api_key": "xxxxxxxxxxxxxxxxxxxxxx",
    "fee_type": [
        "Free"
    ],
    "location_dtls": [
        {
            "alert_freq": 440,
            "pincode": "249403"
        },
        {
            "alert_freq": 660,
            "pincode": "249407"
        },
        {
            "alert_freq": 880,
            "pincode": "249401"
        },
        {
            "alert_freq": 1100,
           "pincode": "249402"
        }

    ],
    "minimum_slots": 2,
    "refresh_freq": 5,
    "search_option": 1,
    "start_date": 2,
    "vaccine_type": null
}

**Comment by kishansinght** [comment]
What was the minimum slots u chose while running the script? It must have been more than 2. Thats why it didnt take it.
You can reduce it to 1 and run it
This one: Filter out centers with availability less than ? Minimum 1 :

**Comment by deveshmanish** [comment]
I had attached the json file for reference purpose only, I had selected 2.

**Comment by BumpyKnuckls** [comment]
@deveshmanish Its possible that by the time, the script made a request to book one of the 2 the open slots, they got already filled and hence it proceeded forward with the search. You should continue trying and hopefully we are able to get a slot for you when a bigger batch of slots opens up. Also to increase your chances of getting a slot, you should consider pulling the latest changes as a recent contribution has been able to cut down the captcha solving time from seconds to under a second.

**Comment by deveshmanish** [comment]
That might be the case, but shouldn't the next api fetch display the slot availability as booked?

**Comment by Abhinav2812** [comment]
> That might be the case, but shouldn't the next api fetch display the slot availability as booked?

The script quotes whatever is reported by the APIs, and they usually take some time to sync up
