### ISSUE TITLE
[Question] How does auto captcha work?

### ISSUE THREAD

**Issue by bilal-fazlani** [bombardier-gif/covid-vaccine-booking#256]
Hi,

Could someone please explain how does automatic captcha resolution works?

```python
def captcha_builder_auto(resp):
    model = open(os.path.join(os.path.dirname(sys.argv[0]), "model.txt")).read()
    svg_data = resp['captcha']
    soup = BeautifulSoup(svg_data, 'html.parser')
    model = json.loads(base64.b64decode(model.encode('ascii')))
    CAPTCHA = {}

    for path in soup.find_all('path', {'fill': re.compile("#")}):
        ENCODED_STRING = path.get('d').upper()
        INDEX = re.findall('M(\d+)', ENCODED_STRING)[0]
        ENCODED_STRING = re.findall("([A-Z])", ENCODED_STRING)
        ENCODED_STRING = "".join(ENCODED_STRING)
        CAPTCHA[int(INDEX)] = model.get(ENCODED_STRING)

    CAPTCHA = sorted(CAPTCHA.items())
    CAPTCHA_STRING = ''

    for char in CAPTCHA:
        CAPTCHA_STRING += char[1]
    return CAPTCHA_STRING
```

**Comment by BumpyKnuckls** [comment]
@shailesh deferring this to you :)

**Comment by shailesh** [comment]
code is a bit readable and understandable where we get the captcha in JSON which contains SVG data. now we just go ahead and do the parsing since SVG has HTML tags later we encode the whole string after parsing. we do encoding to get the correct captcha index.

Few references to read more about it.
https://www.scrapehero.com/how-to-solve-simple-captchas-using-python-tesseract/
https://gist.github.com/scrapehero/b85a280dc0d993f665c91e0332cf618f

**Comment by bilal-fazlani** [comment]
Interesting. Thanks for quick response.

How does the parsing happen? The resources you point to refer to OCR mechanism using PyTesseract. But I don't see that imported here..

Does this mechanism use OCR? and what is the role of model.txt?

**Comment by shailesh** [comment]
Parsing via bBeatifulsoup library

wanna learn more about it learn here; https://automatetheboringstuff.com/chapter11/

**Comment by bilal-fazlani** [comment]
Ok. thanks!

**Comment by bilal-fazlani** [comment]
this may be a stupid question, but shouldn't `ENCODED_STRING = re.findall("([A-Z])", ENCODED_STRING)` be using `[a-zA-Z)` if this is regular expression? 
@shailesh

**Comment by shailesh** [comment]
@pallupz would you mind adding this too?

This is a question because your readme highlighted this line

`We are getting all kinds of attention now - which I do not want to handle. So there won't be any additional commits to this project. It has been put on indefinite hold.`

**Comment by pallupz** [comment]
@shailesh while this is very interesting, I won't be implementing automation for OTP or Captcha in our repo as a matter of principle.

**Comment by shailesh** [comment]
> this may be a stupid question, but shouldn't `ENCODED_STRING = re.findall("([A-Z])", ENCODED_STRING)` be using `[a-zA-Z)` if this is regular expression?
> @shailesh
This is the functional way of doing this. Try and test with some more complex SVGs. I've done extensive testing did not find any loophole here.

Try to understand in the loop next to this line, we get the encoded string, and then join this way we get the actual index.

**Comment by bilal-fazlani** [comment]
Ok will try to test it
