### ISSUE TITLE
Captcha_automation_api_key is not defined error.

### ISSUE THREAD

**Issue by abhi24ca** [bombardier-gif/covid-vaccine-booking#259]
Hi
While trying the new auto captcha I got the error captcha_automation_key not defined on my Windows 10. However the auto captch works flawlessely in my another Windows 7 machine, but not working in W10. Attaching the SS for reference.
![IMG_20210522_125259](https://user-images.githubusercontent.com/84614107/119219136-95f2a280-bb01-11eb-9dec-91815348c6ff.jpg)

**Comment by shailesh** [comment]
captcha_automation_key

this dependency is removed from utils and is no more required. pull the latest code say yes for auto captcha. AI solves the captcha

#249 #253

**Comment by shailesh** [comment]
pull the latest code

**Comment by shailesh** [comment]
got it, something went wrong while resolving conflicts by @BlackRider97

c.c @bombardier-gif

**Comment by abhi24ca** [comment]
Hi
I tried just 10 minutes back with latest code only and the last update is 2 hrs ago. @shailesh

**Comment by shailesh** [comment]
I got it.

@bombardier-gif please revert back 

https://github.com/bombardier-gif/covid-vaccine-booking/pull/216

c.c @BlackRider97

**Comment by gitmnj** [comment]
@shailesh @BumpyKnuckls @bombardier-gif not working for me too pulled the new repo 2 mins ago and tried giving me the same error

**Comment by shailesh** [comment]
, captcha_automation_api_key, captcha_api_choice from utils.py until there is another merge

**Comment by shailesh** [comment]
@BumpyKnuckls @bombardier-gif 

@gitmnj please raise a PR after this

booking_status = book_appointment(request_header, new_req, mobile, captcha_automation, captcha_automation_api_key, captcha_api_choice)


to 

`booking_status = book_appointment(request_header, new_req, mobile, captcha_automation)
`


, captcha_automation_api_key, captcha_api_choice

**Comment by bombardier-gif** [comment]
Made the changes. Please take a look again.
And also please be careful while raising PRs. We have no way to test the changes, so the only way is when someone fail when real slots open.

**Comment by abhi24ca** [comment]
Will test it now
