### ISSUE TITLE
Error while booking the slot

### ISSUE THREAD

**Issue by lordlebu** [bombardier-gif/covid-vaccine-booking#26]
Script is exiting without booking.  I was try to book for today.

===================================================================================
Centers available in xxxxxxx from 10-05-2021 as of 2021-05-10 10:56:12: 342
+-------+--------------------------------+------------+-----------+-------------+------------+---------+
|   idx | name                           | district   |   pincode |   available | date       | slots   |
+=======+================================+============+===========+=============+============+=========+
|     1 | xxxxxxx | xxxxxx       |    xxxxxx |         100 | 10-05-2021 | []      |
+-------+--------------------------------+------------+-----------+-------------+------------+---------+
empty range for randrange() (1,1, 0)
Exiting Script
Press any key to continue . . .

**Comment by bombardier-gif** [comment]
Its looks like bad data from the server itself. there seems to be no slot available (see that the array is empty).
I agree that we are not handling it well. I shall add checking the corner cases better.

**Comment by lordlebu** [comment]
Getting this new error


```
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None
===================================================================================
Centers available in Pune from 11-05-2021 as of 2021-05-10 15:00:22: 12
+-------+-----------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                        | district   |   pincode |   available | date       | slots                                                                        |
+=======+=============================+============+===========+=============+============+==============================================================================+
|     1 | SHIKRAPUR RH Local 18 To 44 | Pune       |    412208 |         150 | 11-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+-----------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
Random Rows.Column:1.3
============> Got Choice: Center #1, Slot #3
Booking with info: {'beneficiaries': ['5xxxxxxxxx10', 'xxxxxxxxxxxxxx'], 'dose': 1, 'center_id': 692726, 'session_id': '1a684b0a-2990-4e6f-b685-aa4a3f4911d1', 'slot': '01:00PM-03:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None
===================================================================================
('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))
'NoneType' object is not iterable
Exiting Script
Press any key to continue . . .
```

**Comment by devansh7777** [comment]
> @lordlebu @abhinavj98 reported a solution in #23. Maybe you can consider trying that and see if it works for you too.

where's that solution i had the same error.

**Comment by devansh7777** [comment]
> > @lordlebu @abhinavj98 reported a solution in #23. Maybe you can consider trying that and see if it works for you too.
> 
> where's that solution i had the same error.
i installed dependencies and ran the script (no exe) then it didn't show any error captcha came up too, i was just a bit slow.
also this script is faster than those telegram updaters.

**Comment by yashk2103** [comment]
@devansh7777 I was trying to book for Mumbai but it showed delayed data and when it reflected the centres till then all slots were booked. It kept showing me no viable options. What do I do now?

**Comment by devansh7777** [comment]
Also @bombardier-gif bro i owe you a drink ✌️🍻

**Comment by devansh7777** [comment]
> Also, @bombardier-gif @devansh7777 what do you both recommend using? the executable file or run it through python?
> 

I personally used python as the exe file was showing error.

**Comment by avadhut007** [comment]
what happens after it books slot? Does the script stop ? or it keeps booking slot at next center?

**Comment by BumpyKnuckls** [comment]
> what happens after it books slot? Does the script stop ? or it keeps booking slot at next center?

It congratulates you with a congratulatory message and exits the script ;)
