### ISSUE TITLE
Remove unwanted params

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#260]
https://github.com/bombardier-gif/covid-vaccine-booking/blob/c03b9671bc6727766d57b87de3c5f460b8b50bae/src/utils.py#L663

to

`booking_status = book_appointment(request_header, new_req, mobile, captcha_automation)
`

gone wrong by @BlackRider97 while resolving conflicts

will resole #259

**Comment by bombardier-gif** [comment]
Done

**Comment by bombardier-gif** [comment]
@shailesh PTAL at the latest change
