### ISSUE TITLE
Alternatives to using https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/99XXXXXXXX

### ISSUE THREAD

**Issue by malayilneil** [bombardier-gif/covid-vaccine-booking#261]
Hey, @bombardier-gif Can we make an alternative link, that we can use instead of this since this link crashes all the time? Maybe something paid for worry-free usage? So those who want free can use one link and the paid users can use another one? 

I'm getting 403 Cloudfront Error for 6 hours straight now. I'm trying to help people get slots but it's failing due to this.

**Comment by xxxAng** [comment]
This is not for this, this is from COWIN, i think there is too many bot requests goin on...
COWIN APis are hosted in cloudfront

**Comment by shailesh** [comment]
set your frequency to 7 seconds or more and you won't find this issue.

Another way is join a telegram t get updates, see the patterns and then hit the API within that time frame so that we are not bombarding Cowin server for OTP

**Comment by malayilneil** [comment]
@shailesh where can I change the frequency to 7? are you talking about changing refresh freq to 7? Sorry for the dumb question

**Comment by xxxAng** [comment]
@shailesh i think one of the reason also, many noobs are trying their luck and they are running multiple instances of same bot from same machine....
request all to run 1 instance per 1 ip, running multiple not gonna get extra chances if using same ip

**Comment by shailesh** [comment]
vaccine booking JSON file 

"refresh_freq": 7,

**Comment by shailesh** [comment]
> @shailesh i think one of the reason also, many noobs are trying their luck and they are running multiple instances of same bot from same machine....
> request all to run 1 instance per 1 ip, running multiple not gonna get extra chances if using same ip

I agree
