### ISSUE TITLE
Option to select yes-please or no in automated booking.

### ISSUE THREAD

**Issue by abhi24ca** [bombardier-gif/covid-vaccine-booking#262]
Hi 
I am using this script due to auto captcha functionality. I know the slot opening time at my center and i want to manually select the center rather than yes-please command. Here centers open one by one at the interval of 10 to 15 sec. and I dont want to book first center. So please allow option to select yes-please or no for the booking. I know this defeat the purpose of automation of this script and if not possible to merge pls tell me the code to be modified in utils.py, I will modify it for my use.

Thanks

**Comment by shailesh** [comment]
it's there with y and n
y for auto and n for manul window pop up

**Comment by abhi24ca** [comment]
Shailesh I got mail with yr reply but cant trace it here. The thing u telling is for auto captcha not for center selection.

**Comment by Nakul93** [comment]
For temporary fix you can change auto_book="no" and add/change the following lines in src/util.py after line 580 :
```
if auto_book=="yes-please":
                randrow = random.randint(1, len(options))
                randcol = random.randint(1, len(options[randrow - 1]["slots"]))
                choice = str(randrow) + "." + str(randcol)
                print("Random Rows.Column:" + choice)
            else:
                choice = inputimeout(
                    prompt="----------> Wait 20 seconds for Updated Options OR \n----------> Enter a choice e.g: 1.4 for (1st Centre & 4th Slot): ",
                    timeout=20,
                )
```

**Comment by abhi24ca** [comment]
@bombardier-gif Thanks wilk do that, hopefully it will give both the option to choose from yes or no as its in pallupz repo.

**Comment by shailesh** [comment]
@abhi24ca / @Nakul93 please create a PR

**Comment by abhi24ca** [comment]
@shailesh @Nakul93 pls someone create pr bcz i have done manually and cant do it properly, its not working for me. I m newbie so might done a mistake

**Comment by abhi24ca** [comment]
Hey @Nakul93 Can u upload modified utils.py here so that I can test it and also try booking slots at 8 PM. merging will take time. its kind of urgent.

**Comment by Nakul93** [comment]
Just copy the utils.py file contents from pr and run it

**Comment by abhi24ca** [comment]
@Nakul93 I tested it its not working even if I selected no it auto books.

**Comment by Nakul93** [comment]
> For temporary fix you can change auto_book="no" and add/change the following lines in src/util.py after line 580 :
> 
> ```
> if auto_book=="yes-please":
>                 randrow = random.randint(1, len(options))
>                 randcol = random.randint(1, len(options[randrow - 1]["slots"]))
>                 choice = str(randrow) + "." + str(randcol)
>                 print("Random Rows.Column:" + choice)
>             else:
>                 choice = inputimeout(
>                     prompt="----------> Wait 20 seconds for Updated Options OR \n----------> Enter a choice e.g: 1.4 for (1st Centre & 4th Slot): ",
>                     timeout=20,
>                 )
> ```

Try this. I’ve probably have to commit again
