### ISSUE TITLE
A working CAPTCHA solver in Python that you guys can probably integrate with this project

### ISSUE THREAD

**Issue by janghaludu** [bombardier-gif/covid-vaccine-booking#263]
Have just published a working CAPTCHA solver in Python here => https://github.com/janghaludu/cowin-captcha
Thought you guys might be interested.

Cheers

**Comment by shailesh** [comment]
#249 #253

**Comment by BumpyKnuckls** [comment]
Thanks a lot @janghaludu for sharing it with us. Appreciate the pointer here :). @shailesh introduced something similar in the repo today morning :)

**Comment by janghaludu** [comment]
> Thanks a lot @janghaludu for sharing it with us. Appreciate the pointer here :). @shailesh introduced something similar in the repo today morning :)

Ah ok cool :) Thank you guys too for fighting the good fight.
