### ISSUE TITLE
Anti-Captca option

### ISSUE THREAD

**Issue by pradeepprabhakar** [bombardier-gif/covid-vaccine-booking#264]
Not getting the option to add the anti-captca key after the latest pull

**Comment by BumpyKnuckls** [comment]
@pradeepprabhakar @shailesh introduced an enhancement via #253 removing dependency on anti-captcha and thus cutting down the time to read captcha significantly.

**Comment by BumpyKnuckls** [comment]
Hence you no longer would need anti-capctcha :) . Closing this for now. Please feel free to reopen it if you have more questions
