### ISSUE TITLE
When connecting wifi and trying to get otp the error comes but works when connected to mobile hotspot

### ISSUE THREAD

**Issue by dasanupam** [bombardier-gif/covid-vaccine-booking#265]
Unable to Generate OTP
403 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: PnKyLSupSyR2ACiyT3osEeK1hocruHoleXYEM2BpXcTHBqJhrDd8pg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

Is there some kind of ip blocking ?

**Comment by bombardier-gif** [comment]
Yes. you seem to have been rate-limited. Try with lesser frequency. after sometime

**Comment by dasanupam** [comment]
@bombardier-gif  but the api page tells that 100 api calls per 5 min per ip is the limit . And I am having 3 places and polling in 20 sec but still getting rate limited

**Comment by shailesh** [comment]
read about more here

https://github.com/bombardier-gif/covid-vaccine-booking/issues/266#issuecomment-846399904
