### ISSUE TITLE
Issue when script try to auto create the OTP (sometimes same behaviour can be seen in the first try for OTP)

### ISSUE THREAD

**Issue by officialrahulmandal** [bombardier-gif/covid-vaccine-booking#267]
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/7048948811
Requesting OTP with mobile number 7048948811..
Unable to Create OTP
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 13wOKOjD4rBvkpjXiqctIIRpmoSJo2zCwPxzqbbpW2WhvdZrUVsTkw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by officialrahulmandal** [comment]
Guys , I think it's because of this centre named KANVA DIAGNOSTIC1 . what it does is within fraction of seconds it try to book almost 30-40 times as i can see in the logs and i guess that's the reason we are getting blocked for certain period of time from cowin api's.

just a small observation i did . open for suggestions.

**Comment by bombardier-gif** [comment]
You got rate limited. Try after a while and use a lesser frequency

**Comment by RonakTotla** [comment]
Tried it with lesser frequency but still same issue persists.
The script tries to regenerate OTP again but continuously fails. 
@bombardier-gif

**Comment by officialrahulmandal** [comment]
yeah as @RonakTotla  said i kept a frequency of 8s then after i am facing the same issue again and again @bombardier-gif
