### ISSUE TITLE
Rate limit issue or token getting invalid prematurely 

### ISSUE THREAD

**Issue by dasanupam** [bombardier-gif/covid-vaccine-booking#270]
My refresh frequency is 25 sec and i am constantly facing this issue only after 2-3 polls . I think there is come upgrade done on cowin side which is blocking automation

 Successfully requested OTP for mobile number xxxxx at 2021-05-22 17:02:12.195487..
Enter OTP (If this takes more than 2 minutes, press Enter to retry): xxxxx
Validating OTP..
Token Generated: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIyZWVjODE5YS1hMmJkLTQxNzMtYTQwMC05YTdmOTc2ODViNTUiLCJ1c2VyX2lkIjoiMmVlYzgxOWEtYTJiZC00MTczLWE0MDAtOWE3Zjk3Njg1YjU1IiwidXNlcl90eXBlIjoiQkVORUZJQ0lBUlkiLCJtb2JpbGVfbnVtYmVyIjo4NzU0NjQxMDM0LCJiZW5lZmljaWFyeV9yZWZlcmVuY2VfaWQiOjYxOTY0NTI5NTI4NTAwLCJzZWNyZXRfa2V5IjoiYjVjYWIxNjctNzk3Ny00ZGYxLTgwMjctYTYzYWExNDRmMDRlIiwidWEiOiJNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xMF8xKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMzkuMC4yMTcxLjk1IFNhZmFyaS81MzcuMzYiLCJkYXRlX21vZGlmaWVkIjoiMjAyMS0wNS0yMlQxMTozMjoyOS44MTFaIiwiaWF0IjoxNjIxNjgzMTQ5LCJleHAiOjE2MjE2ODQwNDl9.eCHiv2-JtEAta7bxLgD2qrmVsNxXgY5da56GRRVzyzY
===================================================================================
Centers available in Bangalore Urban from 23-05-2021 as of 2021-05-22 17:02:30: 0
Centers available in BBMP from 23-05-2021 as of 2021-05-22 17:02:30: 6
===================================================================================
Centers available in Bangalore Urban from 23-05-2021 as of 2021-05-22 17:02:55: 0
Centers available in BBMP from 23-05-2021 as of 2021-05-22 17:02:55: 6
Token is INVALID.. Next update in 1 seconds...
Unable to Generate OTP
403 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 87MQdwPyPRz8ISLJeRqKrV1s22XLxbXucpUerB3C6ylrSrFEoR6Grw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by slomogangsta** [comment]
Seems like an issue with Co-WIN API itself
![image](https://user-images.githubusercontent.com/42892043/119225468-91d67d00-bb21-11eb-97a2-c64f367fc56e.png)

**Comment by dasanupam** [comment]
No use different wifi or mobile hotspot and u can login, I think the IP is getting blocked for some time

**Comment by dasanupam** [comment]
Also my update frequency is 25 sec so it should not hit the throttle limit

**Comment by darthfishious** [comment]
yes it doesn't seem to matter if the refresh rate is set to 2 or 10 or 25. at some stage it gets blocked. it's random for me. sometimes a 2 second refresh rate doesn't get blocked for 8 minutes while sometimes a 7 second refresh rate gets blocked after 3 minutes. not sure what is triggering it.

**Comment by shailesh** [comment]
wait for some time, close the script do not bombard the Cowin server, because of too many people running. imagine about their server load.

the best way is to join a telegram channel and get the notification or see the patterns of slot availability for centres nearby you and start the script.

**Comment by shailesh** [comment]
https://github.com/bombardier-gif/covid-vaccine-booking/issues/266#issuecomment-846399904

read about this more here

**Comment by darthfishious** [comment]
have tried that as well. decided to test it with only one center today which was to open at 5 pm so waited for 2 hours without running the script and turned it on at 4.58 pm with a 10 second refresh rate. the IP got blocked 1 and a half minute later.

**Comment by shailesh** [comment]
Similar Conversation activities on other opened issues, hence closing this one.
