### ISSUE TITLE
Captcha key not defined error

### ISSUE THREAD

**Issue by ashishd751** [bombardier-gif/covid-vaccine-booking#275]
Hi,
Getting the below error - 
`name 'captcha_automation_api_key' is not defined`

I'm using Windows and I don't see any  `covid-vaccine-slot-booking.exe` file in the project folder either.

Am I missing any step ?

Any help would be appreciated.

Regards,
**Ashish Deshpande**

**Comment by abhi24ca** [comment]
You updated to latest code?

**Comment by sodiumchloride2020** [comment]
Try in cmd line.

**Comment by akshay8043** [comment]
@ashishd751 covid-vaccine-slot-booking.exe is removed by developer probably has some bug. Directly run from command prompt/powershell
python.exe src\covid-vaccine-slot-booking.py

then fill inputs in the script when asked.

**Comment by kmukhrjee** [comment]
I am facing the same issue when using the latest code - 'captcha_automation_api_key' is not defined. I am using Mac OS Bug Sure and running from the command line. I got two slot bookings last week by using anti-captcha.

**Comment by ashishgupta1020** [comment]
@kmukhrjee Can you provide more details on how you're running? Can you please try re-downloading the main branch code. In the current main, 'captcha_automation_api_key' is not used anywhere in code.

**Comment by kmukhrjee** [comment]
@ashishgupta1020  I am using the latest code did a clone yesterday. I am running the script with python3 on my mac bigsur and was using the covinretriever app for automation OTP flow. I clone the code again and started the script let me try it.

**Comment by ashishd751** [comment]
Issue **not** existing with latest code.

Anyone facing it, please update to latest.

Closing issue.
