### ISSUE TITLE
Is there a way to search multiple districts at same time or in loop

### ISSUE THREAD

**Issue by Samargup** [bombardier-gif/covid-vaccine-booking#276]
Hi,
How do I change code so it can search multiple districts together or in loop. Thus, it searches first district and then second and then first and so on?

regards
Samar

**Comment by Abhinav2812** [comment]
You can already do that no? Just specify a coa separated list of district numbers. It'll do a loop of query over all specified districts, wait for the duration you specified, and then repeat the query.
You can't keep querying because cowin rate limits the API

**Comment by Samargup** [comment]
Is there a way to search in districts across states?
I know we can search across multiple districts in same state.
Example: Could I search for South Delhi and Gurugram in loop?
