### ISSUE TITLE
Dose 2 getting picked up for dose one

### ISSUE THREAD

**Issue by Akash199211113** [bombardier-gif/covid-vaccine-booking#277]
Slots which are open for second dose is also getting picked up and shown and COWIN portal will not accept

**Comment by Nakul93** [comment]
Is it similar to #239?

**Comment by bombardier-gif** [comment]
Can you pull the latest code please? Is it still posing a problem?

**Comment by Akash199211113** [comment]
Yes I pulled recent one and still the same problem exists, the script is picking up 4 hospitals and they have 2nd dose openings not for the first done, please check the attached screen shot
![Capture](https://user-images.githubusercontent.com/84634712/119250591-bcc2de80-bbbe-11eb-9f2f-73a7d1f6bd21.PNG)

**Comment by Akash199211113** [comment]
This issue is resolved now after following the below suggestion 

https://github.com/bombardier-gif/covid-vaccine-booking/issues/239#issuecomment-846512825

**Comment by Nakul93** [comment]
So basically this is a bug on CoWIN, whenever a appointment gets cancelled the vaccine type gets stored for that beneficiary and can't be changed apparently
As @Akash199211113  #239 (comment) resolved it. I'll create a PR for this bug fix
