### ISSUE TITLE
The calendar API is not showing updated data, so is this script still working ?

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#28]
The calendar API is not showing updated data, so is this script still working ?
I have tried for hours, it didnt not able to find available centers probably due to cached data.

@bombardier-gif

**Comment by xxxAng** [comment]
@bombardier-gif  I see you are first checking for available slots and then only you are booking it ....
but if available slots are showing 30 minutes old cached data, how can we book slots ?

Can you explain me ? if its still working or not ?

**Comment by bombardier-gif** [comment]
This has worked for a bunch of people. You have to run it for a while to get any available slots. 
Also you will see that some slots are filled within seconds, and hence you might see a notification in telegram and not here. Sometimes the other way
