### ISSUE TITLE
cant select benefeciery

### ISSUE THREAD

**Issue by uvmittal** [bombardier-gif/covid-vaccine-booking#281]
################# IMPORTANT NOTES #################
        # 1. While selecting beneficiaries, make sure that selected beneficiaries are all taking the same dose: either first OR second.
        #    Please do no try to club together booking for first dose for one beneficiary and second dose for another beneficiary.
        #
        # 2. While selecting beneficiaries, also make sure that beneficiaries selected for second dose are all taking the same vaccine: COVISHIELD OR COVAXIN.
        #    Please do no try to club together booking for beneficiary taking COVISHIELD with beneficiary taking COVAXIN.
        #
        # 3. If you're selecting multiple beneficiaries, make sure all are of the same age group (45+ or 18+) as defined by the govt.
        #    Please do not try to club together booking for younger and older beneficiaries.
        ###################################################

Enter comma separated index numbers of beneficiaries to book for : 1
time data '' does not match format '%d-%m-%Y'
Exiting Script

**Comment by BumpyKnuckls** [comment]
As suggested by @Nakul93 in #272 a fix has been pushed to main. Requesting you to please pull the latest main and try again.
