### ISSUE TITLE
Capture of OTP is not very consistent. Getting a CloudFront Error! 

### ISSUE THREAD

**Issue by kriprasad** [bombardier-gif/covid-vaccine-booking#282]
I have setup everything as suggested here. I did this yesterday. I get the below error (mentioned in the screenshot). The automation slot searching is very inconsistent. Please HELP.

![image](https://user-images.githubusercontent.com/84540072/119237258-8a32ca80-bb59-11eb-83b6-6f30517605a1.png)

**Comment by kriprasad** [comment]
This issue persists for about 5 minutes. And then automatically it generates and reads the OTP and starts working fine, but that is only for a few seconds. Later the above issue lingers for another 5 minutes.

**Comment by Saubhik-Som** [comment]
I am also having the same peoblem

**Comment by Saurabh-meshram** [comment]
Server is blocking your request. Server is expected to allow max 100 API in 5 minute from one IP Address but looks like server is expiring the session randomly after fewer API calls and blocking the request from the same IP address.

**Comment by chhatrapalsinhzala07** [comment]
Yesterday I am also getting same error, so I increased refresh time to around 15-25 seconds and it's work perfectly.

Although some time you will face same error, but wait for 5 minutes and try again.
