### ISSUE TITLE
OTP being asked after the every time interval for check availability of vaccines

### ISSUE THREAD

**Issue by ashishb341** [bombardier-gif/covid-vaccine-booking#286]
Now instead of using the same token generated for one otp it is asking for otp after every time interval selected. I have selected 15 secs as time interval and it is asking me otp every 15 secs

**Comment by bombardier-gif** [comment]
That is wierd.. there were some fixes made yesterday... check the closed PRs

**Comment by ashishb341** [comment]
the latest pull requests have some issue...I did checkout to a previous version...the issue is not happening there.

**Comment by bombardier-gif** [comment]
The issue seems to be fixed. Please reopen if seen again
