### ISSUE TITLE
Option to Search slot for next 7 days

### ISSUE THREAD

**Issue by jatinguta** [bombardier-gif/covid-vaccine-booking#287]
Can you include option in dates to check for next 7 days, as now a days private hospitals are getting slots for whole week.

**Comment by Nakul93** [comment]
The current script already does that. It searches for the next 7 days from the start date

**Comment by BumpyKnuckls** [comment]
Thanks a lot @Nakul93 for chipping in with the response. Closing this since its been answered. @jatinguta feel free to reopen if you have more questions :)
