### ISSUE TITLE
Getting error 403 which is generated by cloudfront.

### ISSUE THREAD

**Issue by dobariadhruv** [bombardier-gif/covid-vaccine-booking#288]
![Screenshot 2021-05-23 165658](https://user-images.githubusercontent.com/51911668/119258605-0c69d000-bbe8-11eb-9e18-5f4a68be9e84.jpg)

**Comment by gitmnj** [comment]
Keep refresh frequency above 15 and try

**Comment by georgeabp** [comment]
Try using a server in India for running the script.

**Comment by dobariadhruv** [comment]
> Keep refresh frequency above 15 and try
> If this error appears wait for 4-5 mins and then re try for otp

>Sloved

**Comment by kriprasad** [comment]
Any idea what exactly is the root cause of this issue?
I have it set at 20 but still getting the error after 3-4 iterations

**Comment by jeeiee** [comment]
same issue here....

**Comment by bombardier-gif** [comment]
Cowin seems to have set the rate limiting aggressively. 
One workaround: Get a hosted instance on the cloud, which gives you a new ip address when you restart, and whenever you get rate-limited, do a restart of your vm.

**Comment by ashishd751** [comment]
facing same issue

**Comment by kriprasad** [comment]
> Cowin seems to have set the rate limiting aggressively.
> One workaround: Get a hosted instance on the cloud, which gives you a new ip address when you restart, and whenever you get rate-limited, do a restart of your vm.

Any other workarounds? do you know of free proxy managers? and can we use proxy severs?

**Comment by shailesh** [comment]
> Cowin seems to have set the rate limiting aggressively.
> One workaround: Get a hosted instance on the cloud, which gives you a new ip address when you restart, and whenever you get rate-limited, do a restart of your vm.

Can we use proxy to get new random IP whenever there is 403 as tor browser does

**Comment by shailesh** [comment]
> > Cowin seems to have set the rate limiting aggressively.
> > One workaround: Get a hosted instance on the cloud, which gives you a new ip address when you restart, and whenever you get rate-limited, do a restart of your vm.
> 
> Any other workarounds? do you know of free proxy managers? and can we use proxy severs?

Same thing I can think of

**Comment by 6mxo89sqh** [comment]
CoWIN's api rate limit is 100 per five minute for an IP. You need to ensure you don't pass more than that.
Each district and each pin contribute to an API call.

Example:
Lets say i am searching for 2 pincode.
At refresh rate of 5sec, my total requests in 5 min would be 120. [ I will get blocked ]
At refresh rate of 6sec, my total requests in 5 min would be 100. [ I may get blocked when there are OTP calls]
At refresh rate of 7sec, my total requests in 5 min would be 85. [ GOOD ]

Formula: 5 x 60 x refresh rate / no of api calls

Calculate your API calls and you should be good. If you are using Pincode based search, use option 3 as it will save your calls.

**Comment by shailesh** [comment]
This is known issue related to rate limit. And we are on it.
