### ISSUE TITLE
Cant find "covid-vaccine-slot-booking.exe" in window exe even after doing captcha test

### ISSUE THREAD

**Issue by aadishj19** [bombardier-gif/covid-vaccine-booking#290]

**Comment by shantanu-deriv** [comment]
I am facing this issue too. For now use [this](https://github.com/vishalv26/covid-vaccine-booking/blob/main/advanced.bat)

**Comment by hiteshkhatri97** [comment]
You can find it [here](https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/covid-vaccine-slot-booking.exe)

**Comment by aadishj19** [comment]
> You can find it [here](https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/covid-vaccine-slot-booking.exe)

Thanks! So it works? Were you able to get a slot

**Comment by hiteshkhatri97** [comment]
> > You can find it [here](https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/covid-vaccine-slot-booking.exe)
> 
> Thanks! So it works? Were you able to get a slot

Yes I got a slot

**Comment by bombardier-gif** [comment]
The exe is available in the repository, is that not enough? (are you still facing problems?)

**Comment by aadishj19** [comment]
> The exe is available in the repository, is that not enough? (are you still facing problems?)

Getting an error "bool object is not callable"

**Comment by shailesh** [comment]
reference #304

**Comment by Adeshwar03** [comment]
> 
> 
> The exe is available in the repository, is that not enough? (are you still facing problems?)

Well still facing an issue. Not able to find the exe in the repositor or after running the captcha test
Able to run the Vishal fork version without an issue using the alternative or the native.bat 

Disclaimer- Dont know any phython knowledge

**Comment by ankit4000** [comment]
> The exe is available in the repository, is that not enough? (are you still facing problems?)

This file is not available anymore, can you please provide it.

Thanks
