### ISSUE TITLE
Android app Start listening cowin sms radio button automatically deactivates

### ISSUE THREAD

**Issue by nikunjbhartia** [bombardier-gif/covid-vaccine-booking#291]
I am using the cowinOTPRetriver Android app for listening to cowin sms but the "start listening to cowin sms" radio button automatically deactivates when i close and reopen the app. 

Tried following:
1) have all required permissions
2) removed cache
3) deleted app and reinstalled using latest apk
4) activated the sms listener radio button, requested an otp from cowin website keeping the app open, sms got sent to kvdb, closed app, reopened the app, the sms listener radio button was deactivated ! 

Phone : samsung galaxy m20 
OS : One Ui Core 2.0 ( android 10 )

**Comment by beastmaster-bit** [comment]
+1

**Comment by BumpyKnuckls** [comment]
@chris-10 would you know?

**Comment by chris-10** [comment]
@BumpyKnuckls Not able to repro this issue on my device. Need to look at the logs to fix this.
@nikunjbhartia Do you think you could collect logs of the issue using this guide - https://www.xda-developers.com/how-to-take-logs-in-android ?

**Comment by nikunjbhartia** [comment]
Sure, will try and send logs.

@beastmaster-bit do you think you could also try and send logs following the link in above comment?

**Comment by chris-10** [comment]
@nikunjbhartia @beastmaster-bit Could you check with the latest APK if it fixes your issue?

**Comment by darthfishious** [comment]
@chris-10 , the toggle still goes to off position after killing the app after the latest apk.

**Comment by chris-10** [comment]
@darthfishious If the app is killed (by going to recents apps and swiping it away), the toggle will be turned off. This is as designed. The app needs to be running in the background for toggle to remain on.
Can you explain your use case in detail?

**Comment by beastmaster-bit** [comment]
@chris-10 @nikunjbhartia The latest update didnt fix the problem. But, I realized that the issue appears to go away if I change my navigation bar settings from gesture-based to fixed buttons. @nikunjbhartia , You too can try removing gesture based navigation and check...
