### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by Kanchangk** [bombardier-gif/covid-vaccine-booking#292]
1. option to exclude particular pincode(s) of a particular district. This is helpful in searching centers for elderly or very young people who can't afford to centers too far away.

2.  Give preference to nearby centers while booking slots. 
One way of doing this may be selecting a random center (if there's more than than ) based on a user provided pincode and  giving preference to the centers by sorting lat-long data of the available centers at that moment. 

3. Browser based UI (easier  than other UIs I guess, hence this option) to enable maximum  non tech savvy user engagement. Win exe (one fork has already been created for that) with UI will engage more users I guess.

**Comment by shailesh** [comment]
3 one is probably not possible since again either someone would have ro run a server on their local machine or either we will have to host it (framework would be fastapi or flask or maybe django (not required though)). And again a server on top of another server would not make a sence. 

Probably a google chrome extension make more sense like how extensions are there for IRCTC ticket booking. My thoughts

**Comment by Kanchangk** [comment]
actually i was referring to something Eel, as it requires no servers (it uses it's own built in sever).

I have never used this library, so probably you will know better :)

**Comment by bombardier-gif** [comment]
Thanks for the recommendations @Kanchangk 
Can you please point out to the fork for Win  exe?

1 and 2: The main aim of this script was to serve people who are desperate to get vaccinated, anywhere where it is available. The logic would become more complex and introduce a lot more bugs too. Right now we dont have a way to test the changes, so many PRs have broken the core functionality sooner or later. Thats why I am very cautious to introduce new features.

3 I agree with shailesh that a chrome extension is a better option. But again it would need some extensive work to develop it. It would definitely serve more users. But at this moment considering the way CoWIN is implementing rate limiters, these solutions might not last long enough

**Comment by bombardier-gif** [comment]
I re-enabled the exe creation action. 
Someone had made changes to also include some fonts but that only works for ubuntu and it failed the windows exe. Those breaking changes are now reverted.
