### ISSUE TITLE
start date

### ISSUE THREAD

**Issue by uvmittal** [bombardier-gif/covid-vaccine-booking#294]
Do you want to automate captcha autofill? (y/n) Default y:
local variable 'start_date' referenced before assignment
Exiting Script
Press any key to continue . . .

second dose cowaxin 45+

**Comment by Nakul93** [comment]
This has now been fixed, please check and close it if resolved

**Comment by BumpyKnuckls** [comment]
Please feel free to reopen it if it remains unresolved
