### ISSUE TITLE
"model.txt" not found in windows

### ISSUE THREAD

**Issue by hiteshkhatri97** [bombardier-gif/covid-vaccine-booking#296]
While running in windows using **covid-vaccine-booking/covid-vaccine-slot-booking.exe**, getting error saying can't find **covid-vaccine-booking/model.txt**. Simplest fix could be to copy/paste model.txt from src to parent folder.

**Comment by shailesh** [comment]
Can you try this, pasting it to parent folder. If it works please feel free to raise a PR. Thanks for identifying this.

**Comment by hiteshkhatri97** [comment]
Yes @shailesh I have already tried and it worked for me, I was able to book a slot, here is the [PR](https://github.com/bombardier-gif/covid-vaccine-booking/pull/302) for same.
