### ISSUE TITLE
Not able to see the bookings on the cowin or aarogya setu portal

### ISSUE THREAD

**Issue by Chief-Rishab** [bombardier-gif/covid-vaccine-booking#299]

**Comment by Chief-Rishab** [comment]
Got a message for booking, but no reflection in the portal, neither I could cancel the booking I made by mistake

**Comment by shailesh** [comment]
BBMP ?

**Comment by Chief-Rishab** [comment]
Nope, Kolkata. The booking didn't reflect in the Cowin portal, so did this script really worked with the booking or not I am still not sure. I wanted to cancel it since it was 40 kilometers away

**Comment by shailesh** [comment]
I'm guessing you were able to resolve this.
