### ISSUE TITLE
No Merge without Rigorous Testing

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#301]
Too many bugs coming to the branch and people are failing to book the slots. I would suggest either test it out before merge or ask someone to test. Taking time to test is better than having buggy code. Thanks

**Comment by shailesh** [comment]
@BlackRider97 @Nakul93 @bombardier-gif

**Comment by bombardier-gif** [comment]
To be honest. I dont like new features added at all. 
Our aim was basic vaccination for people who are desperate. 


Second dose, cherry picking slots, centers, they make the code into spaghetti.
People raise PRs and already spend so much time so I dont feel like rejecting their hard work.

Our work should be basically fixing the bugs in the core flow. 

One suggestion to mitigate this: From now onwards, before starting work on any feature, create an issue and ask for opinions from the community. Only when there are no objections they can proceed on the work. Else they can work on their own branches. 


Thoughts?

**Comment by shailesh** [comment]
+1

**Comment by Nakul93** [comment]
Yeah I also agree, lets not add any more feature for a while, it gets too complicated. Creating an issue for a new feature sounds like a good approach, everyone can vote and then decide if we want to merge that into main or not

**Comment by Nakul93** [comment]
@bombardier-gif can you please pin this issue

**Comment by uvmittal** [comment]
> To be honest. I dont like new features added at all.
> Our aim was basic vaccination for people who are desperate.
> 
> Second dose, cherry picking slots, centers, they make the code into spaghetti.
> People raise PRs and already spend so much time so I dont feel like rejecting their hard work.
> 
> Our work should be basically fixing the bugs in the core flow.
> 
> One suggestion to mitigate this: From now onwards, before starting work on any feature, create an issue and ask for opinions from the community. Only when there are no objections they can proceed on the work. Else they can work on their own branches.
> 
> Thoughts?

but please fix issues like #308 #300 #305 
as icant book my second dose

**Comment by 6mxo89sqh** [comment]
@bombardier-gif Please setup secrets as mentioned [here](https://github.com/bombardier-gif/covid-vaccine-booking/pull/311#issuecomment-846945980)

**Comment by shailesh** [comment]
is it possible to set up a unit test mechanism? Anyone one guys?

c.c @bombardier-gif @Nakul93

**Comment by shailesh** [comment]
> sir i have windows 7 but captcha app is not open and its show this errorsho how can i solv ethis error error is the exception unknown software expection(0×40000015) occured the application at location (0×3f5f85b3). Please help me sir and i am student so please write in easy steps. @shailesh
> ![Uploading 20210524_233851.jpg…](

try yes for auto captcha. and please share more logs so that one of us can understand a bit more and help you fix those.

**Comment by Nakul93** [comment]
@shailesh I was also thinking of writing unit tests. That we could be better test the code.

**Comment by shailesh** [comment]
Let me know if you need me. We can go with few things such as 

```
1. create a JSON file that will contain all test suites such as a list of beneficiaries
2. Booked and Unbooked beneficiaries JSON 
3. list of centres available and unavailable some for 18+ and some for 45+
4. we can bypass captcha and get/validate OTP
```

_Pass random choices from those JSON and check if the main algorithms/functions are working fine._

**IDEA IS TO MOCK THOSE EXTERNAL APIs AND TEST MAIN LOGIC.** 

let me know if have something to add to this.
