### ISSUE TITLE
Max Retries Exceeded Error

### ISSUE THREAD

**Issue by ashishd751** [bombardier-gif/covid-vaccine-booking#303]
Hi,

Getting below error - 
`Max retries exceeded with url: /api/v2/auth/generateMobileOTP`

I've set the refresh config as below -
`"refresh_freq": 20`

Please let me know how I can overcome this.

Regards,
**Ashish Deshpande**

**Comment by bombardier-gif** [comment]
Try after sometime? You got rate limited.

**Comment by ashishd751** [comment]
I tried that, and the error for `/generateMobileOTP` went away.

But now, the same error seems to be occuring for
`HTTPSConnectionPool(host='kvdb.io', port=443): Max retries exceeded with url:/ASth4wnvVDPkg2bdjsiqMN/**********`

Let me know what can be done.

**Comment by sumit7** [comment]
I think this has nothing to do with api rate limit. Its connection issue.
just put the request between while try except. (put time.sleep(1) in except for sanity

**Comment by shailesh** [comment]
Related to rate limit and we are working on it  I hope you were able to book one
