### ISSUE TITLE
Error - 'bool' object is not callable

### ISSUE THREAD

**Issue by darthfishious** [bombardier-gif/covid-vaccine-booking#304]
Getting error - 'bool' object is not callable

can we please revert back to the previous version of the code until the current issue is fixed. it was working perfectly till last night. the previous change (PR 293) seems to have caused this.

![screenshot](https://user-images.githubusercontent.com/84447012/119300644-c01d9f00-bc7e-11eb-91a7-8ca1c13438de.PNG)

**Comment by aadishj19** [comment]
Getting the same whenever a slot is available

**Comment by Nakul93** [comment]
Are you guys using option3 ( State/District filter by Pincodes) the feature that got added recently?

**Comment by darthfishious** [comment]
No. I’m still using the older State-District option with no filter

**Comment by Nakul93** [comment]
@BlackRider97 could you look into this?

**Comment by darthfishious** [comment]
issue still persists even after the latest update PR 298. 

@aadishj19 is right. the issue appears whenever a slot is available for booking. 

this completely breaks the script if it cant book available slots anymore. please fix this urgently or revert to code before PR 293.

**Comment by Nakul93** [comment]
@darthfishious temporarily you can switch to the commit-id before PR 293 locally. 
just do `git checkout <commit-id>`

**Comment by darthfishious** [comment]
@Nakul93 thanks. gone back to the older version. at least this works.

**Comment by Nakul93** [comment]
> @darthfishious temporarily you can switch to the commit-id before PR 293 locally.
> just do `git checkout <commit-id>`

@uvmittal Try this

**Comment by aadishj19** [comment]
> @darthfishious temporarily you can switch to the commit-id before PR 293 locally.
> just do `git checkout <commit-id>`

how to do this for someone who's using the exe file and a noob :')  ?

**Comment by darthfishious** [comment]
thank you @6mxo89sqh and @bombardier-gif . the issue is resolved with the latest PR 312.
