### ISSUE TITLE
Script is exiting without any reason

### ISSUE THREAD

**Issue by Akash199211113** [bombardier-gif/covid-vaccine-booking#307]
I have tried to execute the script multiple times but its exiting with out any reason can anyone please help
![image](https://user-images.githubusercontent.com/84634712/119302036-12f85600-bc81-11eb-9603-66fa34c0994d.png)

**Comment by Nakul93** [comment]
Duplicate #300

**Comment by 6mxo89sqh** [comment]
#312 will fix this.

**Comment by bombardier-gif** [comment]
Please pull the latest code and let me know

**Comment by BumpyKnuckls** [comment]
@Akash199211113 Were you able to check if it works on the latest main?

**Comment by Nakul93** [comment]
This issue has been fixed. Please feel free to reopen it if you encounter this issue again.
