### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by uvmittal** [bombardier-gif/covid-vaccine-booking#308]
location_dtls:
+-------+---------------+------------------+--------------+
|   idx |   district_id | district_name    |   alert_freq |
+=======+===============+==================+==============+
|     1 |           146 | North Delhi      |         1100 |
+-------+---------------+------------------+--------------+
|     2 |           143 | North West Delhi |         1540 |
+-------+---------------+------------------+--------------+
|     3 |           150 | South West Delhi |         2420 |
+-------+---------------+------------------+--------------+
|     4 |           142 | West Delhi       |         2640 |
+-------+---------------+------------------+--------------+
        pin_code_location_dtls:
list index out of range
Exiting Script

**Comment by shailesh** [comment]
#300 #304
