### ISSUE TITLE
where do we fill the Captcha API key from anti-captcha.com

### ISSUE THREAD

**Issue by vesan83** [bombardier-gif/covid-vaccine-booking#315]
PREVIOUSLY WHEN USING THE OLDER VERSION ON THE SCRIPT WE USE TO GET AN OPTION TO FILL THE API IN THE NEXT FEILD, NOW THERE IS NO OPTION AVAILABLE. 

================================= Vaccine Info =================================

It seems you're trying to find a slot for your first dose. Do you have a vaccine preference?
Enter 0 for No Preference, 1 for COVISHIELD, 2 for COVAXIN, or 3 for SPUTNIK V. Default 0 : 1

================================= Location Info =================================

Search by Pincode? Or by State/District Or Smart search State/District for selected Pincodes ?
Enter 1 for Pincode or 2 for State/District or 3 for State/District filter by Pincodes (Optimized for rate-limit) (Default 2): 1
Enter comma separated index numbers of pincodes to monitor: 400056

================================= Additional Info =================================

Filter out centers with availability less than ? Minimum 1 : 1
How often do you want to refresh the calendar (in seconds)? Default 10. Minimum 5. (You might be blocked if the value is too low, in that case please try after a while with a lower frequency) : 10

Search for next seven day starting from when?
Use 1 for today, 2 for tomorrow, or provide a date in the format dd-mm-yyyy. Default 2: 2

Do you have a fee type preference?
Enter 0 for No Preference, 1 for Free Only, or 2 for Paid Only. Default 0 : 0

=========== CAUTION! =========== CAUTION! CAUTION! =============== CAUTION! =======

===== BE CAREFUL WITH THIS OPTION! AUTO-BOOKING WILL BOOK THE FIRST AVAILABLE CENTRE, DATE, AND A RANDOM SLOT! =====

================================= Captcha Automation =================================

Do you want to automate captcha autofill? (y/n) Default y: y

================================= Save Info =================================

Would you like to save this as a JSON file for easy use next time?: (y/n Default y): n

================================= Confirm Info =================================

        beneficiary_dtls:

**Comment by vesan83** [comment]
THIS IS HAPPENEING ON THE LATEST ZIP DOWNLOADED FROM GITHUB, JUST BEFORE POSTING

**Comment by RonakTotla** [comment]
it has been updated. if you want to use anti-captcha, you'll have to go to the previous versions

**Comment by YashMohanGarg** [comment]
why it has been removed is there any issue with it or was it slower than the manual process of entering captcha ?

**Comment by RonakTotla** [comment]
To be honest, it was a good option. But looking at the scarcity of the slots available, it stands slow.
If you are lucky, you might get it solved in 3-4 seconds and get a slot.

**Comment by vesan83** [comment]
How do i get the previous version ? what is the link to download ?

Please put it back it was a fantastic option. you did not need to sit in front of laptop all the time, you could start it with it and leave it on

it always was an option if you wated to use it or not

----------


If its removed why is it asking 
================================= Captcha Automation =================================

Do you want to automate captcha autofill? (y/n) Default y: y

**Comment by bombardier-gif** [comment]
Right now autofill captcha is AI assisted, it does not need any registration with third party. Users have reported very high success rates.

Hence the older paid algorithms have been deprecated. suggest you to use the new algorithm (it does not need any API key)
