### ISSUE TITLE
Getting Logged out every few minutes and not generating any OTP after

### ISSUE THREAD

**Issue by rajmishra78** [bombardier-gif/covid-vaccine-booking#316]
**Unable to Generate OTP**
**403 ERROR: The request could not be satisfied**

**The request could not be satisfied.**
```
Request blocked. 
We can't connect to the server for this app or website at this time. 
There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: fyv__ZfVYTBYIFTVRdRnlfTduchmnWC6hevmi76fV5hsgC7qBZz1sw==
```

**Comment by 6mxo89sqh** [comment]
@rajmishra78 

CoWIN's api rate limit is 100 per five minute for an IP. You need to ensure you don't pass more than that. 
Each district and each pin contribute to an API call. 

Example:
Lets say i am searching for 2 pincode.
At refresh rate of 5sec, my total requests in 5 min would be 120. [ I will get blocked ]
At refresh rate of 6sec, my total requests in 5 min would be 100. [ I may get blocked when there are OTP calls]
At refresh rate of 7sec, my total requests in 5 min would be 85. [ GOOD ]

Formula: 5 x 60 x refresh rate / no of api calls

Calculate your API calls and you should be good. If you are using Pincode based search, use option 3 as it will save your calls.

**Comment by rajmishra78** [comment]
@6mxo89sqh @bombardier-gif @BumpyKnuckls 

I knew about this and I tried too.
I set the refresh rate to 30 sec still this problem persists. 30 seconds is a big number in comparison to 5-7 as you explained but still the problem remains. It logs me out and doesn't let me in for some time.

Please try yourself and respond regarding the same. It's hard to book.

**Comment by dimpuknath** [comment]
I saw similar issue after updating to the latest code...something is wrong.

**Comment by 6mxo89sqh** [comment]
I have tried it. If the IP is dedicated to you, the calculations are correct. Your ISP might be NATting IP. Try with a different ISP and check.  

> @6mxo89sqh @bombardier-gif @BumpyKnuckls
> 
> I knew about this and I tried too.
> I set the refresh rate to 30 sec still this problem persists. 30 seconds is a big number in comparison to 5-7 as you explained but still the problem remains. It logs me out and doesn't let me in for some time.
> 
> Please try yourself and respond regarding the same. It's hard to book.

**Comment by rajmishra78** [comment]
Okay. Thanks.
