### ISSUE TITLE
Executable missing

### ISSUE THREAD

**Issue by ankit4000** [bombardier-gif/covid-vaccine-booking#320]
Hello Bombardier,

Can you please compile and provide an executable.

**Comment by ithihasmadala** [comment]
Can you please elaborate on the error by posting a screenshot?

**Comment by ankit4000** [comment]
Windows Executable file is now missing from your repository in the current branch, can you please compile the package and upload the windows executable.

**Comment by ithihasmadala** [comment]
Its in the test folder

**Comment by ankit4000** [comment]
Hi,

I have checked and unable to find it in the current branch, please assist

**Comment by 6mxo89sqh** [comment]
@bombardier-gif 

Please follow the steps mentioned in #311 and make a release to generate the executable.

**Comment by bombardier-gif** [comment]
@6mxo89sqh I added a token to the yaml. But still I am not able to run the action. Can you check it please?

**Comment by 6mxo89sqh** [comment]
No, token is to be added to Github Secrets. [Here is the full reference. ](https://docs.github.com/en/actions/reference/encrypted-secrets)
Go to Settings --> Secrets --> New repository secret --> Name: TOKEN --> Value: (your personal access token) --> Add secret

[Here](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) is how to generate personal access token.

> @6mxo89sqh I added a token to the yaml. But still I am not able to run the action. Can you check it please?

**Comment by shailesh** [comment]
@ankit4000 : https://github.com/bombardier-gif/covid-vaccine-booking/releases

@bombardier-gif please close this

**Comment by shantanu-deriv** [comment]
This might be related to #290
