### ISSUE TITLE
Slots are available but not proceeding to book

### ISSUE THREAD

**Issue by raviteja-chunduri** [bombardier-gif/covid-vaccine-booking#321]
while the script is running, atleast 3 - 5 times slots are opened at a tune of 100 each time but the script is saying there are no viable options. I can see other people booking manually too

	minimum_slots	: 3
	pin_code_location_dtls	: []
	refresh_freq	: 7
	search_option	: 2
	start_date	: 1
	vaccine_type	: None

am I missing anything to be taken care of in the script

**Comment by shailesh** [comment]
any error on your screen?

**Comment by raviteja-chunduri** [comment]
nothing..very smooth 7 sec updates. in one of the case, I am able to book manually but the script showed no viable options

**Comment by Nakul93** [comment]
are you able to see available centers?  Or is that 0 as well

**Comment by raviteja-chunduri** [comment]
I can see the available centers with correct count for the districts I selected

**Comment by Nakul93** [comment]
Ok that means the script seems to work fine, just check your json file again. Maybe you are looking for dose1, but all the centers have dose2 available, thats why it is showing no viable options.

**Comment by raviteja-chunduri** [comment]
all of the notifications are for the dose1. happened again just now. it is counting the new center after the centers releases vaccines but not showing the availability. for example, you can see the center count increase by 1 as just now one of the center released the slots

===================================================================================
Centers available in Bangalore Urban from 24-05-2021 as of 2021-05-24 22:28:38: 1
Centers available in BBMP from 24-05-2021 as of 2021-05-24 22:28:38: 16
===================================================================================
Centers available in Bangalore Urban from 24-05-2021 as of 2021-05-24 22:28:45: 1
Centers available in BBMP from 24-05-2021 as of 2021-05-24 22:28:45: 16

Centers available in Bangalore Urban from 24-05-2021 as of 2021-05-24 22:30:31: 1
Centers available in BBMP from 24-05-2021 as of 2021-05-24 22:30:31: 17
===================================================================================
Centers available in Bangalore Urban from 24-05-2021 as of 2021-05-24 22:30:38: 1
Centers available in BBMP from 24-05-2021 as of 2021-05-24 22:30:38: 17

**Comment by Nakul93** [comment]
Have you set a fee preference? That could be 1 issue. Also try a different start date

**Comment by raviteja-chunduri** [comment]
No preference on the fee. Let me try a different start date

**Comment by 1nfected** [comment]
> all of the notifications are for the dose1. happened again just now. it is counting the new center after the centers releases vaccines but not showing the availability. for example, you can see the center count increase by 1 as just now one of the center released the slots
> 
> # ===================================================================================
> Centers available in Bangalore Urban from 24-05-2021 as of 2021-05-24 22:28:38: 1
> Centers available in BBMP from 24-05-2021 as of 2021-05-24 22:28:38: 16
> Centers available in Bangalore Urban from 24-05-2021 as of 2021-05-24 22:28:45: 1
> Centers available in BBMP from 24-05-2021 as of 2021-05-24 22:28:45: 16
> 
> # Centers available in Bangalore Urban from 24-05-2021 as of 2021-05-24 22:30:31: 1
> Centers available in BBMP from 24-05-2021 as of 2021-05-24 22:30:31: 17
> Centers available in Bangalore Urban from 24-05-2021 as of 2021-05-24 22:30:38: 1
> Centers available in BBMP from 24-05-2021 as of 2021-05-24 22:30:38: 17

This just means there are 1 / 17 centers available. It doesn't mean there are slots available in those centers. When there are slots available, it lists something like the following
> Centers available in Pune from 25-05-2021 as of 2021-05-24 22:01:31: 13
> +-------+----------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
> |   idx | name                       | district   |   pincode | vaccine    | fee_type   |   available | date       | slots                                                                        |
> +=======+============================+============+===========+============+============+=============+============+==============================================================================+
> |     1 | Deenanath Hospital Private | Pune       |    411004 | COVISHIELD | Paid       |         400 | 25-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-07:00PM'] |
> +-------+----------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
> ============> Trying Choice # 0 Center # 607457, Slot #09:00AM-11:00AM

Do you see anything like the above?

**Comment by raviteja-chunduri** [comment]
I am not able to see anything like you provided. I know the script will show the options if there is availability, but it is not showing. Ideally when it does not show any options it means there are no slots available but you can see the slots available for the same options in the cowin/arogya setu/ umang app

**Comment by Nakul93** [comment]
> I am not able to see anything like you provided. I know the script will show the options if there is availability, but it is not showing. Ideally when it does not show any options it means there are no slots available but you can see the slots available for the same options in the cowin/arogya setu/ umang app

I tried to look into those above mentioned centers but they have it only for 45+ age group. Are you also looking for that?

**Comment by raviteja-chunduri** [comment]
no, they have a lot of slots opened for 18-44 also. for reference, attaching once screenshot, have more cases 




![Screenshot 2021-05-24 at 11 11 16 PM](https://user-images.githubusercontent.com/64302736/119386783-a4011880-bce5-11eb-8f6d-a70b579e6f10.png)

**Comment by Nakul93** [comment]
Ok what possibly might have happened here is by the time the script detected the slots( which are always a bit delayed) it might have got booked, thats why it was showing center available but no viable options.

**Comment by Yash-97** [comment]
> Ok what possibly might have happened here is by the time the script detected the slots( which are always a bit delayed) it might have got booked, thats why it was showing center available but no viable options.

Faced this same issue as mentioned by @raviteja-chunduri 
Could be a CoWin issue as the slots were booked before being reflected on the website as well.

**Comment by omkark96** [comment]
Faced the same issue right now. The script, running for 7 minutes before the telegram bots started reporting available slots, reported 'no viable options' with all possible options set to 'NO PREFERENCE'.

Cloned source code this afternoon so have the latest changes 👍🏻
