### ISSUE TITLE
Alternate ways to donate

### ISSUE THREAD

**Issue by 1nfected** [bombardier-gif/covid-vaccine-booking#323]
Would love to donate. But don't want to sign-up at paypal.

Could you add alternate ways of donation, which don't require sign-up etc?

**Comment by bombardier-gif** [comment]
I am not sure, is there any alternative?

**Comment by 1nfected** [comment]
It seems it's already possible to accept payments through UPI.

I'm new to buymeacoffee.com, but according to the following links, it seems it's possible.
Maybe some setting that you need to look into?

https://twitter.com/pradologue/status/1315286963818119168
https://building.buymeacoffee.com/feature-requests/p/upi-payments-india

**Comment by sumit2k21** [comment]
> Would love to donate. But don't want to sign-up at paypal.
> 
> Could you add alternate ways of donation, which don't require sign-up etc?

http://buymeacoff.ee/CovidVaccine

**Comment by shailesh** [comment]
@1nfected just try this https://www.buymeacoffee.com/shailes

DO NOT DONATE ON ABOVE JUST TRY.

If it works I'll help @bombardier-gif setup upi

**Comment by bombardier-gif** [comment]
My aim was to 

1. cover the kvdb.io costs as we make significant calls to the buckets.
2. cover the 2captcha costs by buying a single key so that everyone could use it. But a more robust solution is in place which is also free.

**Comment by techiemonk** [comment]
@bombardier-gif  - Why don't you use [keyvalue](http://keyvalue.immanuel.co/) instead of kvdb.io? It's free!!

https://stackoverflow.com/questions/9024819/free-cloud-data-stores-that-use-get-post#comment80957247_30934715

**Comment by bombardier-gif** [comment]
@techiemonk thanks for the idea. This looks good too. Do you know any limitations of it?
kvdb also has a free tier but the number of calls are limited.

**Comment by techiemonk** [comment]
> @techiemonk thanks for the idea. This looks good too. Do you know any limitations of it?
> kvdb also has a free tier but the number of calls are limited.

@bombardier-gif I don't know of any limitations. However, I did some quick API rate testing, and was able to make >1000 request per minute for >20000 requests.

**Comment by 1nfected** [comment]
> @1nfected just try this https://www.buymeacoffee.com/shailes
> 
> DO NOT DONATE ON ABOVE JUST TRY.
> 
> If it works I'll help @bombardier-gif setup upi

Yes! I was able to see option to pay using UPI.

**Comment by shailesh** [comment]
Cool! @bombardier-gif let me know I can help you then
