### ISSUE TITLE
Slots are available but not being detected by script. Showing "no viable options".

### ISSUE THREAD

**Issue by Yash-97** [bombardier-gif/covid-vaccine-booking#324]

**Comment by Yash-97** [comment]
Centers available in Kolkata from 25-05-2021 as of 2021-05-24 22:33:19: 4
===================================================================================
Centers available in Kolkata from 25-05-2021 as of 2021-05-24 22:33:22: 5

Number of centers is increasing as it is being added but slots not getting detected.

**Comment by Nakul93** [comment]
Duplicate #321
