### ISSUE TITLE
Validating OTP.. Unable to Validate OTP

### ISSUE THREAD

**Issue by ravichoubey5** [bombardier-gif/covid-vaccine-booking#325]
Validating OTP..
Unable to Validate OTP

**Comment by raviteja-chunduri** [comment]
happening with me too from 10:40. assuming it can be of some issue from cowin as script able to read and parse the otp correctly but endpoint issue it is

**Comment by KamleshkumarShah** [comment]
Having same issue for last 50 minutes. Below is the snippet.

![image](https://user-images.githubusercontent.com/84586208/119388481-f6dbcf80-bce7-11eb-9090-62e767cdfdee.png)

**Comment by 1nfected** [comment]
> Having same issue for last 50 minutes. Below is the snippet.
> 
> ![image](https://user-images.githubusercontent.com/84586208/119388481-f6dbcf80-bce7-11eb-9090-62e767cdfdee.png)

Please do not expose your mobile number.

**Comment by nolimits0007** [comment]
facing same otp issue. after some time it says timeout.

**Comment by ravi16696** [comment]
i am also facing
Validating OTP..
Unable to Validate OTP
Response: {"message": "Endpoint request timed out"}

**Comment by sumit2k21** [comment]
Unable to Validate OTP
Response: {"message": "Endpoint request timed out"}

**Comment by hirparadhaval15** [comment]
I face the same issue. Should I go back to the previous commits to resolve this issue?

**Comment by sanket-gupta** [comment]
Calls from the browser to the same endpoint seem to be working fine but calls from python are timing  out.

**Comment by lightningfuzion2** [comment]
they may have Blocked the Secret.. it seems

**Comment by sanket-gupta** [comment]
what secret?

**Comment by chandrachur1982** [comment]
facing same issue ....
Enter OTP (If this takes more than 2 minutes, press Enter to retry): 849808
Validating OTP..
Unable to Validate OTP
Response: {"message": "Endpoint request timed out"}

**Comment by nikunjbhartia** [comment]
Same here

**Comment by sanket-gupta** [comment]
The solution to the problem is to use this

        base_request_header = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66',
            'origin': 'https://selfregistration.cowin.gov.in',
            'referer': 'https://selfregistration.cowin.gov.in/'
        }


What i dont know yet is if it will break any other call. But this definitely fixes the OTP Validation issue

**Comment by ithihasmadala** [comment]
@sanket-gupta gg it works, tested it all the way till booking

**Comment by sanket-gupta** [comment]
Cool, if possible can u create a PR ?

**Comment by ithihasmadala** [comment]
Done

**Comment by ravichoubey5** [comment]
base_request_header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66',
        'origin': 'https://selfregistration.cowin.gov.in',
        'referer': 'https://selfregistration.cowin.gov.in/'
    }

**Comment by ravichoubey5** [comment]
> The solution to the problem is to use this
> 
> ```
>     base_request_header = {
>         'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66',
>         'origin': 'https://selfregistration.cowin.gov.in',
>         'referer': 'https://selfregistration.cowin.gov.in/'
>     }
> ```
> 
> What i dont know yet is if it will break any other call. But this definitely fixes the OTP Validation issue

Thanks

**Comment by nolimits0007** [comment]
Thank u Ithihas Madala & Sanket Gupta for solving the problem.

**Comment by vishykane2** [comment]
> @sanket-gupta gg it works, tested it all the way till booking

This solution was working fine until 5 AM IST, Time delay is worse now. Did Cowin reduce the API call rate?

**Comment by bombardier-gif** [comment]
@ithihasmadala Thanks a ton for the PR!
