### ISSUE TITLE
Did Cowin reduce the API call rate this morning ? 25th may 2021 ??

### ISSUE THREAD

**Issue by vishykane2** [bombardier-gif/covid-vaccine-booking#329]
> @sanket-gupta gg it works, tested it all the way till booking

This solution was working fine until 5 AM IST, Time delay is worse now. Did Cowin reduce the API call rate?

_Originally posted by @vishykane2 in https://github.com/bombardier-gif/covid-vaccine-booking/issues/325#issuecomment-847464469_

**Comment by bombardier-gif** [comment]
I wont be surprised. 
I would have loved if they had a better system in place before introducing rate limiting ¯\_(ツ)_/¯

**Comment by shailesh** [comment]
Other similar active issues are already opened for conversation and we are working on it. Hence closing this for now.
