### ISSUE TITLE
Booking for 45+ members showing 18+ centers too

### ISSUE THREAD

**Issue by dap-123** [bombardier-gif/covid-vaccine-booking#33]
Even if 45+ beneficiaries are selected for booking, slot availability alerts are being shown for 18+ centers too. Could you please also include an age bracket/group check while trying to book a slot?

**Comment by bombardier-gif** [comment]
Thanks for identifying the issue: For 45+ Why do you need a script? The availability should be high anyway.

**Comment by dhawalpatel129** [comment]
At our place currently, even 45+ people are facing issues getting slots due to their limited availability. People trying to get one by being in large queues and repeatedly checking with corresponding centers with no luck.

**Comment by dhawalpatel129** [comment]
I've modified the code to be able to book for 45+ age group people in 45+ centers.
Will be creating the PR in some time :)

**Comment by bombardier-gif** [comment]
Kudos @dap-123 for identifying and also owning the issue! 🥇

**Comment by dap-123** [comment]
> Kudos @dap-123 for identifying and also owning the issue! 🥇

Tysm @bombardier-gif :) and Kudos to you too for all of your work on this script 💯
