### ISSUE TITLE
Validation of OTP Failing Since Last Night 25th May

### ISSUE THREAD

**Issue by blrvac** [bombardier-gif/covid-vaccine-booking#331]
Validating OTP..
Unable to Validate OTP
{"message": "Endpoint request timed out"}

Hi, facing an issue with OTP validation since last night. The script is able to pull the correct OTP from the android phone but after that point, it fails while validating. Can you please help me?

It was working fine till around 11 PM last night. I tried a different phone number as well but faced the same issue.

Thank you.

**Comment by vishykane2** [comment]
Yes, Validation is very slow.so are other API calls.
https://github.com/bombardier-gif/covid-vaccine-booking/issues/329

**Comment by janghaludu** [comment]
Probably because Headers need to be updated. Just the User Agent and Authorization token don't suffice anymore it seems.  I don't know what headers you guys are using but that probably is the case.

`authheaders = {
                    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
                    ,'content-type':'application/json'
                    ,'origin':'https://selfregistration.cowin.gov.in'
                    ,'sec-fetch-site':'cross-site'
                    ,'sec-fetch-mode':'cors'
                    ,'sec-fetch-dest':'empty'
                    ,'referer':'https://selfregistration.cowin.gov.in/',
                    'authorization' : f'Bearer {token}',
                    
                }`

**Comment by vishykane2** [comment]
@bombardier-gif  can we verify this and create a PR ?

**Comment by sumit7** [comment]
@janghaludu can you tell me how you found out what headers are needed?

**Comment by janghaludu** [comment]
> @janghaludu can you tell me how you found out what headers are needed?

Friend of mine told me so and I updated accordingly. My personal script started working again after that.

**Comment by janghaludu** [comment]
This change happened apparently around 11PM last night

**Comment by sumit7** [comment]
@janghaludu Yeah I saw that too. I would really like to know how your friend found out if it is not too much trouble.

**Comment by janghaludu** [comment]
> @janghaludu Yeah I saw that too. I would really like to know how your friend found out if it is not too much trouble.

Trial and error. She checked the request headers logging in from browser, copied the headers and tried them in the script and it worked.

**Comment by slomogangsta** [comment]
I've updated the base_request_header with the info given here. But I still face issues with OTP validation!

**Comment by janghaludu** [comment]
Hmmm if its of any help, we are using a hardcoded value for secret during OTP generation. 

`secret = "U2FsdGVkX18s/oUTUJOmDy27XnsU5MQK+iwUroz0Qt8GFhlG76l3NzNxxJxtm2BptyYFmTQCHA+x1KfO+8iwag=="`

**Comment by Kanchangk** [comment]
> Probably because Headers need to be updated. Just the User Agent and Authorization token don't suffice anymore it seems. I don't know what headers you guys are using but that probably is the case.
> 
> ```
> baseHeaders = {
>                     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
>                     ,'content-type':'application/json'
>                     ,'origin':'https://selfregistration.cowin.gov.in'
>                     ,'sec-fetch-site':'cross-site'
>                     ,'sec-fetch-mode':'cors'
>                     ,'sec-fetch-dest':'empty'
>                     ,'referer':'https://selfregistration.cowin.gov.in/',                    
>                 }
> 
> 
> authHeaders = {
>                     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
>                     ,'content-type':'application/json'
>                     ,'origin':'https://selfregistration.cowin.gov.in'
>                     ,'sec-fetch-site':'cross-site'
>                     ,'sec-fetch-mode':'cors'
>                     ,'sec-fetch-dest':'empty'
>                     ,'referer':'https://selfregistration.cowin.gov.in/',
>                     'authorization' : f'Bearer {token}',
>                     
>                 }
> ```


How about using 127.0.0.1 for origin and referer?

**Comment by janghaludu** [comment]
OK so here's what seems to be working for me.

Headers for OTP generation 

`{  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36' }`

Headers for OTP Validation

```
{
                    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
                    ,'content-type':'application/json'
                    ,'origin':'https://selfregistration.cowin.gov.in'
                    ,'sec-fetch-site':'cross-site'
                    ,'sec-fetch-mode':'cors'
                    ,'sec-fetch-dest':'empty'
                    ,'referer':'https://selfregistration.cowin.gov.in/',
                    
                }

```

Headers everywhere else

```
{
                    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
                    ,'content-type':'application/json'
                    ,'origin':'https://selfregistration.cowin.gov.in'
                    ,'sec-fetch-site':'cross-site'
                    ,'sec-fetch-mode':'cors'
                    ,'sec-fetch-dest':'empty'
                    ,'referer':'https://selfregistration.cowin.gov.in/',
                    'authorization' : f'Bearer {token}',
                    
                }
```

Adding extra headers during OTP generation threw up error consistently and reverting back to the simple useragent header worked.

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
"Test Release 1" fixed this issue ( for now )... was able to log in

**Comment by vaccine-warrior** [comment]
> U2FsdGVkX18s/oUTUJOmDy27XnsU5MQK+iwUroz0Qt8GFhlG76l3NzNxxJxtm2BptyYFmTQCHA+x1KfO+8iwag==

The documentation does not seem to ask for a secret

https://apisetu.gov.in/public/api/cowin#/User%20Authentication%20APIs/generateOTP

Why are we then sending a secret

**Comment by vaccine-warrior** [comment]
A fix was applied on the main branch  few hours ago to fix the OTP Validation issue?

Are some people still facing an issue while using the latest code?

**Comment by vishalv26** [comment]
Yes. The error is still there. Also, it is not about header.

**Comment by janghaludu** [comment]
> > U2FsdGVkX18s/oUTUJOmDy27XnsU5MQK+iwUroz0Qt8GFhlG76l3NzNxxJxtm2BptyYFmTQCHA+x1KfO+8iwag==
> 
> 
> 
> The documentation does not seem to ask for a secret
> 
> 
> 
> https://apisetu.gov.in/public/api/cowin#/User%20Authentication%20APIs/generateOTP
> 
> 
> 
> Why are we then sending a secret

Ah ok that's news to me :| I started working on a script based on the requests sent from https://selfregistration.cowin.gov.in It has a secret parameter sent during OTP generation. Came across this repo soon after and used the code here as reference for captcha generation calls etc. When my script stopped working, I came here to check and noticed you guys facing the same issue. When my friend then told me about how the script started working again after updating the headers, I thought I should share here. Apologies for any confusion from my end.

**Comment by sync-1203** [comment]
> A fix was applied on the main branch few hours ago to fix the OTP Validation issue?
> 
> Are some people still facing an issue while using the latest code?

I just tried, no issue there.. validation is working fine

**Comment by skapa-xd** [comment]
Still Endpoint request timed out!

**Comment by skapa-xd** [comment]
> A fix was applied on the main branch few hours ago to fix the OTP Validation issue?
> 
> Are some people still facing an issue while using the latest code?

Still facing the issue

**Comment by gsofficework** [comment]
Still, OTP validation is not working.


![image](https://user-images.githubusercontent.com/62834149/119866793-cfc90c00-bf3a-11eb-8c67-9dafa2966c94.png)

**Comment by shailesh** [comment]
This seems to be an issue with Cowin Server. I hope your OTP was validated later.
