### ISSUE TITLE
There is no "**covid-vaccine-slot-booking.exe**, it was there when I downloaded yesterday!

### ISSUE THREAD

**Issue by skapa-xd** [bombardier-gif/covid-vaccine-booking#334]
![Screenshot (74)](https://user-images.githubusercontent.com/68050388/119460223-17de0800-bd5c-11eb-8774-fa4ae226ace5.png)

**Comment by skapa-xd** [comment]
I deleted the whole thing and downloaded the new code zip as there was a patch, but I don't see the application?!

**Comment by nolimits0007** [comment]
In folder tests u can see the exe file. ur antivirus might be quarantine the file. Its false positive.

<img width="1003" alt="Screenshot 2021-05-25 at 13 48 20" src="https://user-images.githubusercontent.com/84738436/119464454-5e356600-bd60-11eb-9431-f41abb47382c.png">

**Comment by skapa-xd** [comment]
Now come back to main folder unzip "**windows exe.zip**"go to this###  **"****windows exe**" folder**** 
there is no windows exe.
also turned off all antivirus and firewall.

**Comment by shailesh** [comment]
Download it from here: https://github.com/shailesh/covid-vaccine-booking/releases/download/main/covid-vaccine-slot-booking.exe

@bombardier-gif please look into the release

**Comment by shailesh** [comment]
@skapa-xd please close this if you are able to download from the shared link

**Comment by skapa-xd** [comment]
thanks downloaded it, but endpoint request timeout
