### ISSUE TITLE
Endpoint request timed out

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#338]
OTP SMS is:Your OTP to register/access CoWIN is ######. It will be valid for 3 minutes. - CoWIN
OTP SMS len is:##
Parsed OTP:######
Validating OTP..
Unable to Validate OTP
{"message": "Endpoint request timed out"}

**Comment by pranjalmundra** [comment]
Same issue is happening with me

**Comment by pathobby** [comment]
#331 This is the same issue

**Comment by darthfishious** [comment]
I'm getting this during OTP validation. but it seems that its the same issue.

Error :   Too Many Requests

![screenshot](https://user-images.githubusercontent.com/84447012/119487076-947de000-bd76-11eb-9020-64dc02866228.PNG)

**Comment by bheriyaJ** [comment]
Encountered same issue. Has apisetu blocked api call from programs?

**Comment by shailesh** [comment]
Closing this, seems some issue from Cowin server, ;later I was able to book
