### ISSUE TITLE
This vaccination center is completely booked for the selected date

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#339]
Centers available in North West Delhi from 25-05-2021 as of 2021-05-25 16:36:32: 13
+-------+------------------------+------------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                   | district         |   pincode | vaccine    | fee_type   |   available | date       | slots                                                                        |
+=======+========================+==================+===========+============+============+=============+============+==============================================================================+
|     1 | Fortis Shalimar Site 4 | North West Delhi |    110088 | COVISHIELD | Paid       |           2 | 25-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+------------------------+------------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     2 | Max Hospital Site 3    | North West Delhi |    110088 | COVISHIELD | Paid       |          64 | 26-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-06:00PM'] |
+-------+------------------------+------------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+

This loops keep repeating for long so many times. and everytime the response is 

Captcha Response Code: 200
```
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date. Please try another date or vaccination center."}
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date. Please try another date or vaccination center."}
Center is fully booked..Trying another..
```

why is it even looping it again and again?

**Comment by Yash-97** [comment]
> Centers available in North West Delhi from 25-05-2021 as of 2021-05-25 16:36:32: 13
> +-------+------------------------+------------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
> | idx | name | district | pincode | vaccine | fee_type | available | date | slots |
> +=======+========================+==================+===========+============+============+=============+============+==============================================================================+
> | 1 | Fortis Shalimar Site 4 | North West Delhi | 110088 | COVISHIELD | Paid | 2 | 25-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
> +-------+------------------------+------------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
> | 2 | Max Hospital Site 3 | North West Delhi | 110088 | COVISHIELD | Paid | 64 | 26-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-06:00PM'] |
> +-------+------------------------+------------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
> 
> This loops keep repeating for long so many times. and everytime the response is
> 
> Captcha Response Code: 200
> 
> ```
> ================================= ATTEMPTING BOOKING ==================================================
> Booking Response Code: 409
> Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date. Please try another date or vaccination center."}
> Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date. Please try another date or vaccination center."}
> Center is fully booked..Trying another..
> ```
> 
> why is it even looping it again and again?

It keeps attempting to book for random slot timings after every failed response is received and stops after all slots have been completely booked.

**Comment by dasanupam** [comment]
Yes I am also facing the same issue now with latest script 
Once the centre is fully booked we should not loop on the same Centre and move on to looking for available center

**Comment by 6mxo89sqh** [comment]
> You are getting this log message `print('Center is fully booked..Trying another...')` ?
> If yes, then it will check next center instead of different slot of same center.
> 
> If no, please share full logs if possible
> 
> https://github.com/bombardier-gif/covid-vaccine-booking/blob/24a445c64649ac3b91e2a220ca92879ffe8bdad0/src/utils.py#L738

@BlackRider97 Are you trying all slots of the center? I guess we should move on to next center even if we dont get booking in one slot. As slot doesn't matter.

**Comment by ggoel1998** [comment]
Same thing happened with me too and at the end coWIN blocked my ip with error message as `{
 "error": "Too Many Requests"
}
`
I am attatching logs for the same instance
[log.txt](https://github.com/bombardier-gif/covid-vaccine-booking/files/6541149/log.txt)

**Comment by Kanchangk** [comment]
anyone got any  update on this issue?

**Comment by shailesh** [comment]
> anyone got any update on this issue?

on it!

**Comment by BlackRider97** [comment]
```
$ grep 'Booking with info' /mnt/c/Users/ramithar/Downloads/full.log.txt
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '11:00AM-01:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '11:00AM-01:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '11:00AM-01:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '11:00AM-01:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '01:00PM-03:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '09:00AM-11:00AM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '01:00PM-03:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '11:00AM-01:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '03:00PM-06:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '03:00PM-05:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '03:00PM-06:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '01:00PM-03:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '09:00AM-11:00AM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '11:00AM-01:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '09:00AM-11:00AM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '09:00AM-11:00AM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '01:00PM-03:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '03:00PM-05:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '01:00PM-03:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '09:00AM-11:00AM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '11:00AM-01:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '03:00PM-05:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '01:00PM-03:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '09:00AM-11:00AM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 612451, 'session_id': '318a86b5-5813-444a-98f1-############', 'slot': '01:00PM-03:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707148, 'session_id': 'ae0becf0-85c7-445d-93d8-d6411477d8b9', 'slot': '01:00PM-03:00PM'}
Booking with info: {'beneficiaries': ['############', '############'], 'dose': 1, 'center_id': 707152, 'session_id': 'd6db6f5d-8073-481e-af06-26b6b820cb97', 'slot': '01:00PM-03:00PM'}
```

@shailesh I have looked at your logs. It seems that logic is working as expected. 
I think issue is slots opening APIs is returning response with slots are open while at the time of booking it is saying "center is fully booked"

We can not skip a center in next run as sometime a center opens multiple time with different vaccine types.
