### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Yash-97** [bombardier-gif/covid-vaccine-booking#340]
Can we add an optimization that skips trying to book time slots that are already completely booked?

**Comment by shailesh** [comment]
> Is there way to check if center is fully booked or not without making booking API request ?

Same that we call centre list to check available slots.

I guess this refers to. #339

**Comment by bombardier-gif** [comment]
See one of the issues is that the center has vacant slots but they get booked by the time our script attempts to book. There is nothing much we can do here, as it depends on various issues such as caching and concurrency. 

Please reopen this issue if you feel there is still a problem with our code.
