### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dasanupam** [bombardier-gif/covid-vaccine-booking#343]
Would it be possible to pause the request in the middle off session using any keyboard shortcut or something so that when ever we want, we resume the checking again
@bombardier-gif Your thoughts ?

**Comment by shailesh** [comment]
CTRL + C 

or 

CTRL +  Z

**Comment by dasanupam** [comment]
That would kill the script ,

 I was thinking like pausing the script so that and then rerunning . This would help as we can enable the script back again exactly before the slots open and

**Comment by shailesh** [comment]
Token will expire anyway

**Comment by dasanupam** [comment]
How long does the token stay active ? Actually some centre in blore have fixed time of opening the slots . Eg slots for hosp 1 opening on 7am so i start script 6.59 if i miss hosp1 i pause script and then hosp 2 opens at 7.30 then i restart again

**Comment by shailesh** [comment]
15 mins

**Comment by shailesh** [comment]
Please try to customize the code your way as per requirements. We are bringing new features basis of voting since a lot of things starts breaking on too much customizations

c.c @bombardier-gif

**Comment by 6mxo89sqh** [comment]
Hi @dasanupam , you can do so by using the cli flags. The code is still not merged but u can try it. #318 

How to do it:
1. Run the script normally first to generate your config.
2. Copy the token during your first run.
3. When you want to resume, run as following:
`./src/covid-vaccine-slot-booking.py --mobile <ur number> --no-tty --token <copied_token>`

Hope this helps.
