### ISSUE TITLE
Anyone who was able to book a slot with the current main branch?

### ISSUE THREAD

**Issue by omkark96** [bombardier-gif/covid-vaccine-booking#344]
Was able to book slots with the 10th May 2021 main branch source code. Something has most likely broken as open slots are being missed by the script which defeats the whole aim of the project :(

Seems like added customization have created a lot of noise that might have let a bug or two slip in. 

P.S.: I have hot-tested this twice with NO_PREFERENCE options for all the options to keep the chances of booking as wide as possible.

Ref: #321 #342 #345

**Comment by siddharthgoyal90** [comment]
Same, just have the slots open, but script was not able to pick them. Can we use the one we had just before that with that OTP validation issue fixed in that branch? @bombardier-gif

**Comment by BlackRider97** [comment]
I just completed two booking with latest `main` branch code.  
Can you share what error you are getting ?

**Comment by siddharthgoyal90** [comment]
No errors. It just says no viable option available, inspite of the fact - on CoWIN platform, slots did opened up.

**Comment by Nakul93** [comment]
@omkark96 @siddharthgoyal90 You can switch to a older commit and check if that works for you

**Comment by gitisuam** [comment]
Yes even I was not able to book with current version. It says no viable options

**Comment by omkark96** [comment]
> > @omkark96 @siddharthgoyal90 You can switch to a older commit and check if that works for you
> 
> Already tried. It doesn't work for older branch, as for older branch it started giving OTP validation issue after entering registered mobile number from today morning/ late last night. It was working perfectly fine before that. See below:
> ![OTP Validation Issue](https://user-images.githubusercontent.com/84772298/119525491-2ea44f00-bd9c-11eb-9d4c-19cb4e0df780.png)
> 
> Is there a way we can fix this issue in branch just before this latest one to fix this OTP issue?
> 
> Best Regards,

Change to these lines for fixing OTP validation issues:
https://github.com/bombardier-gif/covid-vaccine-booking/blob/24a445c64649ac3b91e2a220ca92879ffe8bdad0/src/covid-vaccine-slot-booking.py#L33-L38

**Comment by shivaslifzz** [comment]
I am able to book the slots but only diffcult portion is entering the OTP manually everytime

**Comment by Nakul93** [comment]
> [full log.txt](https://github.com/bombardier-gif/covid-vaccine-booking/files/6540403/full.log.txt)
> 
> Error Log. I was able to book too but after so many tries which where already booked to the same center again and again
> 
> refers to. #340 #339

@BlackRider97  what are your thoughts on this. This is not good. I think we need to switch back to the older logic.

**Comment by shailesh** [comment]
```
            for i in range(0, len(options)):
                option = options[i]
                all_slots_of_a_center = option.get("slots", [])
                if not all_slots_of_a_center:
                    continue
```

============> Trying Choice 

take a kook at logs, it is interesting actually.

**Comment by Nakul93** [comment]
> Actually, if you see it tried the same center **26 times**. I searched for this text "Center is fully booked..Trying another...
> " in the log shared above.
> 
> somewhere loop is breaking I guess.

Thats not good. I think you were lucky enough to get the slot even after so many retries. We definitely need to change the logic. 
Suggestion:
Maybe pick a random center and iterate through all the slots, if everything is booked then that center should be marked as false and shouldn't be even displayed in the table and move on to the next random center

**Comment by shailesh** [comment]
I've got a doubt in checking slots_available, we just make it true false but where are we checking on dose_1 and dose_2 we have missed that in the code I guess where earlier we had this in place due to which I guess this kept trying for maybe 2nd dose or a 45+ centre but Cowin returned 409.  with error message "This vaccination centre is completely booked for the selected date". 

The second point might not be true but the first one slightly buggy I'm just guessing.

**Comment by nolimits0007** [comment]
Today with the same script i did book 2 slot simultaneously at 17:00 without automatic captcha settings.
But now getting OTP Len is :0 issue through iphone.
<img width="917" alt="Screenshot 2021-05-25 at 21 47 44" src="https://user-images.githubusercontent.com/84738436/119532995-0bc96900-bda3-11eb-8a4b-e2184f078705.png">

**Comment by Nakul93** [comment]
For the age group we already filtering that and according to the beneficiary and dose num is taken care here
https://github.com/bombardier-gif/covid-vaccine-booking/blob/24a445c64649ac3b91e2a220ca92879ffe8bdad0/src/utils.py#L723-L732

What I don't get it is why is it iterating over the same slot which has been tried out already.

**Comment by shailesh** [comment]
Observations:

```
- Trying Choice # 0 Center # 612451, Slot #11:00 AM-01:00 PM ------> 3 times in log tried the same center same time and got 409: it should not be repeated if in the first place for this center and slot if it returned 409
- Trying Choice # 1 Center # 707148, Slot #11:00AM-01:00PM. ------> same with this 4 times | 409
- Trying Choice # 0 Center # 612451, Slot #01:00PM-03:00PM ------> 8 times | 409
- Trying Choice # 1 Center # 707148, Slot #09:00AM-11:00AM -------> 4 times | 409
- Trying Choice # 0 Center # 612451, Slot #01:00PM-03:00PM -------> 6 times | 409
- there are more............. it tried all combinations of center and slots and returned 409
```

Seeing above in the first place, should not be repeated if failed. update a dictionary with tried center id and slots for that session(must) because if the same center opened slots for another day this should not be the blocker.

Second need to check and verify if we are updating the list of center and availability if failed are going back to check the new center or looping in the first whatever we have in response?

Last we were earlier checking on available_capacity_dose1 and available_capacity_dose2, now I can not find these checks in the code?

**Comment by shailesh** [comment]
isn't this a bug too?

```
def filter_centers_by_age(resp, min_age_booking):
    if min_age_booking >= 45:
        center_age_filter = 45
    else:
        center_age_filter = 18
    if "centers" in resp:
        for center in list(resp["centers"]):
            for session in list(center["sessions"]):
                if session['min_age_limit'] != center_age_filter:
                    center["sessions"].remove(session)
                    if (len(center["sessions"]) == 0):
                        resp["centers"].remove(center)
```


for this:


```
{
      "center_id": 610031,
      "name": "Fortis Hospital Shalimarbagh 3",
      "address": "Fortis Hospital A Block Shalimar Bagh New Delhi 110088",
      "state_name": "Delhi",
      "district_name": "North West Delhi",
      "block_name": "Not Applicable",
      "pincode": 110088,
      "lat": 28,
      "long": 77,
      "from": "09:00:00",
      "to": "17:00:00",
      "fee_type": "Paid",
      "sessions": [
        {
          "session_id": "67dfadc5-25a9-46ad-8368-60b16bfa11d9",
          "date": "25-05-2021",
          "available_capacity": 0,
          "min_age_limit": 45,
          "vaccine": "COVISHIELD",
          "slots": [
            "09:00AM-11:00AM",
            "11:00AM-01:00PM",
            "01:00PM-03:00PM",
            "03:00PM-05:00PM"
          ],
          "available_capacity_dose1": 0,
          "available_capacity_dose2": 0
        },
        {
          "session_id": "4259adc7-ed60-4b3f-9ca7-d7dd59a5b311",
          "date": "26-05-2021",
          "available_capacity": 0,
          "min_age_limit": 18,
          "vaccine": "COVISHIELD",
          "slots": [
            "09:00AM-11:00AM",
            "11:00AM-01:00PM",
            "01:00PM-03:00PM",
            "03:00PM-05:00PM"
          ],
```

**Comment by BlackRider97** [comment]
@Nakul93 Logic is try for all centers and every slot of each center and if a center is fully booked then skip all other slots of that center.

**Comment by shailesh** [comment]
> @Nakul93 Logic is try for all centers and every slot of each center and if a center is fully booked then skip all other slots of that center.

But this is happening repeatedly

**Comment by Nakul93** [comment]
Exactly look at the logs by @shailesh

**Comment by gitmnj** [comment]
@shailesh @Nakul93 @bombardier-gif @BlackRider97 @BumpyKnuckls 

this new script is missing the slots and even detecting the center's lately when all slots are gone and for areas where large amount of slots are available it is working normally

**Comment by akashdmahali** [comment]
I too was able to book slots this morning

**Comment by gitmnj** [comment]
Enter comma separated index numbers of beneficiaries to book for : 2
Selected beneficiaries:
+-------+----------------+--------+-----------+-------+----------------+--------------+
|   idx |        bref_id | name   | vaccine   |   age | status         | dose1_date   |
+=======+================+========+===========+=======+================+==============+
|     1 | 66671805918150 | Hhsh   |           |    31 | Not Vaccinated |              |
+-------+----------------+--------+-----------+-------+----------------+--------------+

================================= Vaccine Info =================================

It seems you're trying to find a slot for your first dose. Do you have a vaccine preference?
Enter 0 for No Preference, 1 for COVISHIELD, 2 for COVAXIN, or 3 for SPUTNIK V. Default 0 : 0

================================= Location Info =================================

Search by Pincode? Or by State/District Or Smart search State/District for selected Pincodes ?
Enter 1 for Pincode or 2 for State/District or 3 for State/District filter by Pincodes (Optimized for rate-limit) (Default 2): 2
+-------+-----------------------------+
|   idx | state                       |
+=======+=============================+
|     1 | Andaman and Nicobar Islands |
+-------+-----------------------------+
|     2 | Andhra Pradesh              |
+-------+-----------------------------+
|     3 | Arunachal Pradesh           |
+-------+-----------------------------+
|     4 | Assam                       |
+-------+-----------------------------+
|     5 | Bihar                       |
+-------+-----------------------------+
|     6 | Chandigarh                  |
+-------+-----------------------------+
|     7 | Chhattisgarh                |
+-------+-----------------------------+
|     8 | Dadra and Nagar Haveli      |
+-------+-----------------------------+
|     9 | Daman and Diu               |
+-------+-----------------------------+
|    10 | Delhi                       |
+-------+-----------------------------+
|    11 | Goa                         |
+-------+-----------------------------+
|    12 | Gujarat                     |
+-------+-----------------------------+
|    13 | Haryana                     |
+-------+-----------------------------+
|    14 | Himachal Pradesh            |
+-------+-----------------------------+
|    15 | Jammu and Kashmir           |
+-------+-----------------------------+
|    16 | Jharkhand                   |
+-------+-----------------------------+
|    17 | Karnataka                   |
+-------+-----------------------------+
|    18 | Kerala                      |
+-------+-----------------------------+
|    19 | Ladakh                      |
+-------+-----------------------------+
|    20 | Lakshadweep                 |
+-------+-----------------------------+
|    21 | Madhya Pradesh              |
+-------+-----------------------------+
|    22 | Maharashtra                 |
+-------+-----------------------------+
|    23 | Manipur                     |
+-------+-----------------------------+
|    24 | Meghalaya                   |
+-------+-----------------------------+
|    25 | Mizoram                     |
+-------+-----------------------------+
|    26 | Nagaland                    |
+-------+-----------------------------+
|    27 | Odisha                      |
+-------+-----------------------------+
|    28 | Puducherry                  |
+-------+-----------------------------+
|    29 | Punjab                      |
+-------+-----------------------------+
|    30 | Rajasthan                   |
+-------+-----------------------------+
|    31 | Sikkim                      |
+-------+-----------------------------+
|    32 | Tamil Nadu                  |
+-------+-----------------------------+
|    33 | Telangana                   |
+-------+-----------------------------+
|    34 | Tripura                     |
+-------+-----------------------------+
|    35 | Uttar Pradesh               |
+-------+-----------------------------+
|    36 | Uttarakhand                 |
+-------+-----------------------------+
|    37 | West Bengal                 |
+-------+-----------------------------+

Enter State index: 5
+-------+----------------+
|   idx | district       |
+=======+================+
|     1 | Araria         |
+-------+----------------+
|     2 | Arwal          |
+-------+----------------+
|     3 | Aurangabad     |
+-------+----------------+
|     4 | Banka          |
+-------+----------------+
|     5 | Begusarai      |
+-------+----------------+
|     6 | Bhagalpur      |
+-------+----------------+
|     7 | Bhojpur        |
+-------+----------------+
|     8 | Buxar          |
+-------+----------------+
|     9 | Darbhanga      |
+-------+----------------+
|    10 | East Champaran |
+-------+----------------+
|    11 | Gaya           |
+-------+----------------+
|    12 | Gopalganj      |
+-------+----------------+
|    13 | Jamui          |
+-------+----------------+
|    14 | Jehanabad      |
+-------+----------------+
|    15 | Kaimur         |
+-------+----------------+
|    16 | Katihar        |
+-------+----------------+
|    17 | Khagaria       |
+-------+----------------+
|    18 | Kishanganj     |
+-------+----------------+
|    19 | Lakhisarai     |
+-------+----------------+
|    20 | Madhepura      |
+-------+----------------+
|    21 | Madhubani      |
+-------+----------------+
|    22 | Munger         |
+-------+----------------+
|    23 | Muzaffarpur    |
+-------+----------------+
|    24 | Nalanda        |
+-------+----------------+
|    25 | Nawada         |
+-------+----------------+
|    26 | Patna          |
+-------+----------------+
|    27 | Purnia         |
+-------+----------------+
|    28 | Rohtas         |
+-------+----------------+
|    29 | Saharsa        |
+-------+----------------+
|    30 | Samastipur     |
+-------+----------------+
|    31 | Saran          |
+-------+----------------+
|    32 | Sheikhpura     |
+-------+----------------+
|    33 | Sheohar        |
+-------+----------------+
|    34 | Sitamarhi      |
+-------+----------------+
|    35 | Siwan          |
+-------+----------------+
|    36 | Supaul         |
+-------+----------------+
|    37 | Vaishali       |
+-------+----------------+
|    38 | West Champaran |
+-------+----------------+

Enter comma separated index numbers of districts to monitor : 4
Selected districts:
+-------+---------------+-----------------+--------------+
|   idx |   district_id | district_name   |   alert_freq |
+=======+===============+=================+==============+
|     1 |            83 | Banka           |         1100 |
+-------+---------------+-----------------+--------------+

================================= Additional Info =================================

Filter out centers with availability less than ? Minimum 1 : 1
How often do you want to refresh the calendar (in seconds)? Default 10. Minimum 5. (You might be blocked if the value is too low, in that case please try after a while with a lower frequency) : 7

Search for next seven day starting from when?
Use 1 for today, 2 for tomorrow, or provide a date in the format dd-mm-yyyy. Default 2: 1

Do you have a fee type preference?
Enter 0 for No Preference, 1 for Free Only, or 2 for Paid Only. Default 0 : 0

=========== CAUTION! =========== CAUTION! CAUTION! =============== CAUTION! =======

===== BE CAREFUL WITH THIS OPTION! AUTO-BOOKING WILL BOOK THE FIRST AVAILABLE CENTRE, DATE, AND A RANDOM SLOT! =====

================================= Captcha Automation =================================

Do you want to automate captcha autofill? (y/n) Default y:

================================= Save Info =================================

Would you like to save this as a JSON file for easy use next time?: (y/n Default y): n

================================= Confirm Info =================================

        beneficiary_dtls:
+-------+----------------+--------+-----------+-------+----------------+--------------+
|   idx |        bref_id | name   | vaccine   |   age | status         | dose1_date   |
+=======+================+========+===========+=======+================+==============+
|     1 | 66671805918150 | Hhsh   |           |    31 | Not Vaccinated |              |
+-------+----------------+--------+-----------+-------+----------------+--------------+
        location_dtls:
+-------+---------------+-----------------+--------------+
|   idx |   district_id | district_name   |   alert_freq |
+=======+===============+=================+==============+
|     1 |            83 | Banka           |         1100 |
+-------+---------------+-----------------+--------------+
        pin_code_location_dtls  : []
        search_option   : 2
        minimum_slots   : 1
        refresh_freq    : 7
        auto_book       : yes-please
        start_date      : 1
        vaccine_type    : None
        fee_type        : ['Free', 'Paid']
        captcha_automation      : y

Proceed with above info (y/n Default y) :
===================================================================================
Centers available in Banka from 26-05-2021 as of 2021-05-26 12:57:57: 13
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                           | district   |   pincode | vaccine    | fee_type   |   available | date       | slots                                                                        |
+=======+================================+============+===========+============+============+=============+============+==============================================================================+
|     1 | Girls HIGH School Amarpur18-44 | Banka      |    813101 | COVISHIELD | Free       |          63 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     2 | GNMSchool Administrative 18-44 | Banka      |    813102 | COVISHIELD | Free       |         243 | 26-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     3 | PHC Banka Block 18-44          | Banka      |    813102 | COVISHIELD | Free       |         209 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     4 | Barahat SabhaagaarBarahat18-44 | Banka      |    813103 | COVISHIELD | Free       |         255 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     5 | OLD Hospital Baunsi 18-44      | Banka      |    813104 | COVISHIELD | Free       |         232 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     6 | Adarsh MiddleSchool KTOR 18-44 | Banka      |    813106 | COVISHIELD | Free       |         229 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     7 | P SchoolBaalBhartiRajoun 18-44 | Banka      |    813107 | COVISHIELD | Free       |         209 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     8 | PHC BELHAR OLD BULDING 18-44   | Banka      |    813202 | COVISHIELD | Free       |         257 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|     9 | FullidumarBlockSabhaagaar18-44 | Banka      |    813207 | COVISHIELD | Free       |         239 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|    10 | Primary School Kaurma 18-44    | Banka      |    813211 | COVISHIELD | Free       |         205 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|    11 | High School Dhoraiya18-44      | Banka      |    813224 | COVISHIELD | Free       |         263 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
|    12 | OLD PHC Bulding Chandan18-44   | Banka      |    814131 | COVISHIELD | Free       |         274 | 26-05-2021 | ['10:00AM-11:00AM', '11:00AM-12:00PM', '12:00PM-01:00PM', '01:00PM-04:00PM'] |
+-------+--------------------------------+------------+-----------+------------+------------+-------------+------------+------------------------------------------------------------------------------+
============> Trying Choice # 0 Center # 563455, Slot #10:00AM-11:00AM
Booking with info: {'beneficiaries': ['66671805918150'], 'dose': 1, 'center_id': 563455, 'session_id': '68ef9f68-b47a-427d-9673-3d7959564a38', 'slot': '10:00AM-11:00AM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 200
Booking Response : {"appointment_confirmation_no":"bbd968a8-0028-488a-b4c2-0cbc7fd63ae6"}
##############    BOOKED!  ############################    BOOKED!  ##############
                        Hey, Hey, Hey! It's your lucky day!

Press any key thrice to exit program.
Press any key to continue . . .

**Comment by gitmnj** [comment]
when tried here it is working like charm but in situations where slots are released at specific time like at 400053 around 1600 they release slots please check and let me know

**Comment by uzmamarturclim8invest** [comment]
@gitmnj where u able to book for 400053 pin today using this script ?

**Comment by gitmnj** [comment]
I was not able to the script didn't showed the slots detected the centre when slots were gone

**Comment by uzmamarturclim8invest** [comment]
@gitmnj ya same happened with me. People have commented that the earlier version of script didnt have this problem. Is it true? Whats your thought is it due new commits? or CoWIN is able to detect the automated  request and skipping them ?

**Comment by gitmnj** [comment]
I think it is because of the new commits in the code

**Comment by nolimits0007** [comment]
Everything working great with this new script . I booked in Bombay with 2 Beneficiaries.

Thanks a Lot to everybody who helping the needy ones.

PFA screenshot .


<img width="923" alt="Screenshot 2021-05-26 at 17 02 20" src="https://user-images.githubusercontent.com/84738436/119654212-d1fd6e80-be45-11eb-992b-981ca42d958d.png">

**Comment by nolimits0007** [comment]
I think if u select more than 3 pin codes then it skipped for me also and u keep default frequency.

In the above mentioned booking i kept district as Mumbai and default frequency to be 7.

**Comment by gitisuam** [comment]
thanks @nolimits0007 .. Your trick to keep below 3 pincodes worked.  I could book in Lilavati. 
@gitmnj - I am the same person who asked for 400056 to you. Please put less than 3 pin codes it works.

**Comment by gitmnj** [comment]
Ok will try with 3 pincodes

**Comment by nolimits0007** [comment]
> thanks @nolimits0007 .. Your trick to keep below 3 pincodes worked. I could book in Lilavati.
> @gitmnj - I am the same person who asked for 400053 to you. Please put less than 3 pin codes it works.

ur welcome @gitmnj. what i think above 3 pin code makes it difficult. but if u keep =<3 then it work . Whole district is not an issue at all. Frequency is also imp.

**Comment by gitmnj** [comment]
Yaa but I don't run the script once i get the notifications from telegram i start it

**Comment by gitisuam** [comment]
@gitmnj start atleast 2 mins before. bcz has telegram has its own seconds delay.

**Comment by gitmnj** [comment]
Yaa but the slots are like 800-900 still it never catch them manually I have booked

**Comment by nolimits0007** [comment]
> @gitmnj start at least 2 mins before. bcz has telegram has its own seconds delay.

Boss u have run script continuously. Use CoWinOtpRetreiver.apk on ur android so that ur token does not expires and that's it 
Hurray!!!. Try again and again till u succeed. Enjoy Happy Vaccination for u & help others .
Don't wait for Telegram .

**Comment by BlackRider97** [comment]
@bombardier-gif  Can you also publish analytics daily reports collected from kvdb in automated manner. 
This will help in determining how many successful booking were made thru this. This will also help in highlighting any serious code issue in core path which is recently added to the repository.
@shailesh  thoughts ?

**Comment by manojagarwal68** [comment]
Is this still an issue? One suggestion was limiting to 3 pincodes. But is that needed if you are choosing option 3 where you provide state/district and then list of pin codes? Because in that case it gets all the data and then filters the data..

**Comment by nolimits0007** [comment]
> Is this still an issue? One suggestion was limiting to 3 pin codes. But is that needed if you are choosing option 3 where you provide state/district and then list of pin codes? Because in that case it gets all the data and then filters the data..

I don't think that it will be an  issue with option 3. I haven't tried  but it will work fine.

**Comment by imvishalpatel** [comment]
was trying to book using 3rd search option but unable to do so. then started with seach_option:1 (by Pincode) with 3 Pincode and was able to book it. Thanks for the script.

**Comment by shivaslifzz** [comment]
After every 10 mins the centers are not refreshed for next 5mins but this not related to API limit because I ran the code with two different frequencies 30, 13 seconds both are blocked after 10 mins and  released after new OTP any facing  this issue????

![image](https://user-images.githubusercontent.com/61616987/119926444-1186a080-bf95-11eb-8b26-168b95a1323a.png)
![image](https://user-images.githubusercontent.com/61616987/119926452-177c8180-bf95-11eb-94ee-4a71d7127550.png)

**Comment by nolimits0007** [comment]
> After every 10 mins the centers are not refreshed for next 5mins but this not related to API limit because I ran the code with two different frequencies 30, 13 seconds both are blocked after 10 mins and released after new OTP any facing this issue????
> 
> ![image](https://user-images.githubusercontent.com/61616987/119926702-7c37dc00-bf95-11eb-82dc-2cccc2a6893f.png)
> 
> ![image](https://user-images.githubusercontent.com/61616987/119926546-3bd85e00-bf95-11eb-9ea1-2db2b9d41967.png)

Change frequency to 7 then try again. Don't exceed pin code more than 3.

**Comment by omkark96** [comment]
Closing since pin codes <=3 and frequency between 6-8s works fine 👍🏻
