### ISSUE TITLE
Slots being missed by the script

### ISSUE THREAD

**Issue by rupamcroy** [bombardier-gif/covid-vaccine-booking#345]
Even though Slots did open in CoWin, was unable to book for last two days. I tried continuously for couple of days, but it does not identifies the open slots. There is no error but still most of the time slots are being missed. pls help.

**Comment by shailesh** [comment]
which district may I know, please?

**Comment by rupamcroy** [comment]
> which district may I know, please?

Its for Bangalore   BBMP

**Comment by bombardier-gif** [comment]
whats your frequency for polling?

**Comment by rupamcroy** [comment]
> whats your frequency for polling?

was Polling at 10 sec. Also tried changing it to 15. but no luck

**Comment by shailesh** [comment]
try 7, which I think best. 
Another way is to see the patterns of time frame for opening slots by centre via a telegram channel and minimise your frequency for that period and then chances of booking are more.

**Comment by bombardier-gif** [comment]
It is a bit of hit and miss due to the way the server caches the data, and also concurrency (lot of people are using these bots)
