### ISSUE TITLE
script is not listening to the OTP

### ISSUE THREAD

**Issue by shivaslifzz** [bombardier-gif/covid-vaccine-booking#346]
IFTTT sending the OTP to the shared location but script is not able to listen it 
<img width="575" alt="otp listener" src="https://user-images.githubusercontent.com/61616987/119527580-13d2da00-bd9e-11eb-9f27-e23a5aa3ee25.PNG">
<img width="489" alt="otp retriver" src="https://user-images.githubusercontent.com/61616987/119527584-159c9d80-bd9e-11eb-832f-b3a153bbd9f4.PNG">

**Comment by bombardier-gif** [comment]
I think you have entered manual OTP. try for auto-otp read.

**Comment by bombardier-gif** [comment]
reopen this issue if you are still facing problems

**Comment by shivaslifzz** [comment]
I am running this command "python src\covid-vaccine-slot-booking.py" and waited for 10 mins but auto login was not happening

**Comment by shivaslifzz** [comment]
Now I am able to understand it thanks @bombardier-gif
