### ISSUE TITLE
Unable to Get automatic OTP through iphone.

### ISSUE THREAD

**Issue by nolimits0007** [bombardier-gif/covid-vaccine-booking#347]
plz help as i am  not getting automatic OTP through iphone every time i have to press Run on iphone to send sms.
<img width="917" alt="Screenshot 2021-05-25 at 21 47 44" src="https://user-images.githubusercontent.com/84738436/119533863-ea1cb180-bda3-11eb-8d3c-0434ba6ef989.png">

**Comment by bombardier-gif** [comment]
yes.. thats how the shortcuts work in iphone. nothing much we can do here
