### ISSUE TITLE
Proceed with above info?

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#349]
By default, this should Y

1. most of the time mistakenly I have pressed enter and gone to the first step of selecting choices.
2. this is more important where I was out of rate limit by too many request calls after when I got the OTP and token was generated, the script automatically went on to the first step and came to last to proceed with the above info and nothing typed which exited the code and stoped.

```
Enter comma-separated index numbers of beneficiaries to book for: invalid literal for int() with base 10: ''
Exiting Script
sh: pause: command not found
```

this solves both the problem above

```
                file_acceptable = input("\nProceed with above info? (y/n Default y): ")
                file_acceptable = file_acceptable if file_acceptable else 'y'
```

**Comment by bombardier-gif** [comment]
Thanks Shailesh. Could you please raise a quick PR for this?

**Comment by shailesh** [comment]
#355

**Comment by harish0201** [comment]
Does this mean that without the user input "y" this is going to start processing the json? Because if not, can we make it the default behaviour?

I missed slot booking because for some reason the script got rate-limited and I was doing some chores :(
