### ISSUE TITLE
it'd be great if you could create a shortcuts automation thingy for people using ios devices

### ISSUE THREAD

**Issue by almostmeenal** [bombardier-gif/covid-vaccine-booking#35]
IFTTT doesn't support imessage

**Comment by bombardier-gif** [comment]
Thanks for thinking about iOS. What do you mean by shortcuts automation?

IFTTT cannot read SMS in iOS so, I would rather recommend using the original script from https://github.com/pallupz/covid-vaccine-booking which asks for manual input

**Comment by almostmeenal** [comment]
i dont know how to exactly work it out, but ios shortcuts app, can create triggers just like IFTTT, in some earlier versions it was linked to IFTTT. I know how to search for a specific message, there's an option for adding scripts, opening urls, getting contents, putting message input etc.  I couldnt work it out, but just a suggestion, if its of any help!

**Comment by almostmeenal** [comment]
yeah

**Comment by almostmeenal** [comment]
sure! if by chance I get some time I'll try to add a PR, happy to be of help ;)
