### ISSUE TITLE
[Logic for filtering via min_age_limit is wrong]

### ISSUE THREAD

**Issue by sumit7** [bombardier-gif/covid-vaccine-booking#350]
https://github.com/bombardier-gif/covid-vaccine-booking/blob/24a445c64649ac3b91e2a220ca92879ffe8bdad0/src/utils.py#L52

In viable_options() function if checks for session[min_age_limit]< min_age_booking.
But in case of booking for people above 45yers, it will accept bth 45yrs and 18-44yrs sessions as viable.

**Comment by Kanchangk** [comment]
isn't the centers are being filtered in filter_centers_by_age( ) brfore the viable_option() is called?

**Comment by Nakul93** [comment]
@Kanchangk is right. filter_centers_by_age() takes care of this

**Comment by Kanchangk** [comment]
on minimum slots: 

codes for minimum slots, or the option to enter minimum slots looking for is not required i believe as i am not sure why someone will look for centers having more than X number of slots if he needs only X slots.

**Comment by sumit7** [comment]
> isn't the centers are being filtered in filter_centers_by_age( ) brfore the viable_option() is called? may be that line itself is not required.

True the filtering out, saves the code. but then it doesn't do anything at all. And without filtering before calling viable options, then it is just wrong.
