### ISSUE TITLE
Getting ModuleNotFoundError: No module named 'jwt'

### ISSUE THREAD

**Issue by SachinBukkawar21** [bombardier-gif/covid-vaccine-booking#353]
Hi I'm Getting error as below

```
Traceback (most recent call last):
  File "covid-vaccine-slot-booking.py", line 8, in <module>
    import jwt
ModuleNotFoundError: No module named 'jwt'
```

when I run `python covid-vaccine-slot-booking.py`

Please help. I've downloaded the latest code

**Comment by Nakul93** [comment]
Install all the requirements as mentioned in the readme

**Comment by omkark96** [comment]
`pip install PyJWT` should do the trick

**Comment by BaasilSiddiqui** [comment]
google pip install jwt module it will give u code like pip install PyJWT paste that code in command prompt do this for any module it asks for.

**Comment by Kanchangk** [comment]
there are two different libraries, JWT and PyJWT. If you have installed both, it will create conflict. simple way to uninstall both and install PyJWT again.

**Comment by sumit7** [comment]
if you have JWT, the code is jwt.JWT.decode(token, do_verify=False)

**Comment by SachinBukkawar21** [comment]
Thank you, everyone, Now I can run the script but not able to auto fetch OTP. 
Created diff ticket for this. https://github.com/bombardier-gif/covid-vaccine-booking/issues/354
Please help me to sort this out if you can,

Thank you @Nakul93 @omkark96 @BaasilSiddiqui @Kanchangk for helping me out here
And closing this ticket as your suggestion fixed the mentioned issue.
