### ISSUE TITLE
Unable to autofetch OTP

### ISSUE THREAD

**Issue by SachinBukkawar21** [bombardier-gif/covid-vaccine-booking#354]
Autofetch OTP is not working on my site.

Note: 
1. I have the latest code
2. Installed and setup "CoWIN OTP Retriver" & "IFTTT" both the apps

Issue: it always showing below 
![InkedScreenshot 2021-05-26 115019_LI](https://user-images.githubusercontent.com/84830988/119612443-83d27600-be19-11eb-99de-02deca23354e.jpg)

**Comment by SachinBukkawar21** [comment]
@akashdmahali Yes I checked this.

Actually, it was working fine before 10 days.

**Comment by akashdmahali** [comment]
I guess the KVDB is rate limiting the requests to fetch the stored OTP

**Comment by akashdmahali** [comment]
The existing kvdb url is still working for me. I've raised a new [issue](https://github.com/bombardier-gif/covid-vaccine-booking/issues/357#issue-901895275) to discuss the possibility of using our own kvdb urls. This might get too technical and may add another step in setting up this whole ecosystem.

Coming to the existing kvdb url I do see a possibility  of it getting expired under the free trial (in 2 weeks) unless @bombardier-gif  has a paid subscription.

**Comment by BaasilSiddiqui** [comment]
I had the same problem the link shown in cmd prompt was different from what I had entered in IFTTT so I copy pasted the link then it worked fine. also ensure otp is coming on the same device in which u hv setup IFTTT. if it still doesn't work  u can choose to enter otp manually but u would hv to be present while running script bc it asks for otp whenever token expires.

**Comment by SachinBukkawar21** [comment]
> @SachinBukkawar21 could be the case that your IFTTT subscription limit might have been exceeded since you've been using it for long time. This can be a possible reason that IFTTT is not pushing the OTP to kvdb. Just thinking of possibilities.

this is not the case, because I can see toast message that OTP has been sent(push) to kvdb

**Comment by SachinBukkawar21** [comment]
> I had the same problem the link shown in cmd prompt was different from what I had entered in IFTTT so I copy pasted the link then it worked fine. also ensure otp is coming on the same device in which u hv setup IFTTT. if it still doesn't work u can choose to enter otp manually but u would hv to be present while running script bc it asks for otp whenever token expires.


Right!! I'm done with the booking by entering manual OTP

**Comment by SachinBukkawar21** [comment]
Although I'm Done booking by entering manual otp, I suggest to go with manual entering otp even if you are facing issue while auto fetching the OTP.

Still I'll keep this ticket open if anyone can do the improvement.
Or if you want me to close then pls LMK

**Comment by BumpyKnuckls** [comment]
@SachinBukkawar21 will mark this as closed, since the end goal has been met. We can revisit this later if more people report the issue.
