### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by Kanchangk** [bombardier-gif/covid-vaccine-booking#356]
can there be an option for going back? i mean, enter y for yes, n for no, b for going back to previous step. 

Many a times I find myself entering wrong options and I have to close the script and run again.

**Comment by bombardier-gif** [comment]
Its a good idea, but would add complexity in the creation of a state machine. 
once you save your options you dont need to enter them again (a workaround).

I am labelling the issue as an enhancement and closing this. we will revisit later We could consider this once our branch is more stable.
