### ISSUE TITLE
KVDB Bucket Name Update

### ISSUE THREAD

**Issue by akashdmahali** [bombardier-gif/covid-vaccine-booking#357]
@bombardier-gif  does the KVDB bucket changes after every few days or week? The current bucket is "ASth4wnvVDPkg2bdjsiqMN/". I was wondering if an option can be given to create own own kVDB buckets.

**Comment by bombardier-gif** [comment]
You can create the bucket and just replace the name in the script. 
(you also need to update your IFTTT/iOS Shortcuts/apk)
