### ISSUE TITLE
Not showing the list of available centers

### ISSUE THREAD

**Issue by akrutikhandelwal** [bombardier-gif/covid-vaccine-booking#362]
![vaccine](https://user-images.githubusercontent.com/43274159/119648972-b2fbde00-be3f-11eb-9114-ec75c8941bee.jpg)
Code not able to show the list of centers even though they are available

**Comment by sumit2k21** [comment]
It doesn't show the details when you search by state/district thing, it just show number of centers available which it is showing as 7 for BBMP district.
Its not an issue.

**Comment by akrutikhandelwal** [comment]
Then why is it not showing the slots available?

**Comment by sumit2k21** [comment]
@akrutikhandelwal  because its been programmed like that only, to not show slots details.

**Comment by siddharthgoyal90** [comment]
The latest code main branch is not attempting booking even when slots are open. It just continues to say no options viable…. This is something I am getting from last 2 days now. Any thoughts please?

**Comment by Nakul93** [comment]
duplicate #321
