### ISSUE TITLE
Captcha Code 200 - not successful with booking on windows 

### ISSUE THREAD

**Issue by mohanbigblue** [bombardier-gif/covid-vaccine-booking#363]
![Captcha Code 200](https://user-images.githubusercontent.com/27348780/119650865-f1929800-be41-11eb-81f8-cae1c49dba74.png)
anyone successfully booked with windows executable file?

**Comment by shivaslifzz** [comment]
I tried with covid-vaccine-slot-booking.py file it's working absolutely fine

**Comment by vishykane2** [comment]
You might have to try and copy the model.txt from src folder to the main folder.

**Comment by mohanbigblue** [comment]
thanks folks, it's indeed working.  I've successfully booked the slot.
