### ISSUE TITLE
Can we just get a New executable which is working with the new code??

### ISSUE THREAD

**Issue by skapa-xd** [bombardier-gif/covid-vaccine-booking#365]
Not been able to go past the validation of otp, tried new code and this came up
![Screenshot (76)](https://user-images.githubusercontent.com/68050388/119656342-33264180-be48-11eb-9e34-858393d0df6d.png)

**Comment by 6mxo89sqh** [comment]
Its here:
https://github.com/bombardier-gif/covid-vaccine-booking/releases/latest

**Comment by skapa-xd** [comment]
thanks
