### ISSUE TITLE
script unable to check slots at centers after some running time [Government not allowing continuous monitoring on portal as it seems] 423: Too many requests actually

### ISSUE THREAD

**Issue by sumit2k21** [bombardier-gif/covid-vaccine-booking#366]
Logs: printing availalbe centers at each pin, but after 1-2 minutes it just prints blank lines only '============'
![image](https://user-images.githubusercontent.com/81756345/119661031-8058e200-be4d-11eb-9635-7791972f23ee.png)

**Comment by sumit2k21** [comment]
are these pin codes getting removed some how ? so it printed all the pincodes then on next iteration just 4 then just 3 then nothing no pincodes are getting checked.

**Comment by sumit2k21** [comment]
![image](https://user-images.githubusercontent.com/81756345/119662036-8e5b3280-be4e-11eb-8fdf-045f38150747.png)
Seeing this Again I think when querying the list even in the cowin portal multiple times clicking search option it starts giving error.
`'Something went wrong, please try again later'`

**Comment by sumit2k21** [comment]
![image](https://user-images.githubusercontent.com/81756345/119664559-16423c00-be51-11eb-802f-432bd43a166e.png)
Checked in the developer tools it is giving `status code 429: too many requests.`
So we can not keep continuously searching the availibity in on OTP login also the site doesn't generate OTP with 3 minutes again that condition is also enhanced by cowin website developers to prevent automation of booking.

**Comment by omkark96** [comment]
When asked for 
`Enter 1 for Pincode or 2 for State/District or 3 for State/District filter by Pincodes (Optimized for rate-limit) (Default 2):`
choose option 3, 
Select State, District and then provide your list of pincodes.

**Comment by devakar80** [comment]
Same problem with me 
"Too Many Requests"

**Comment by bombardier-gif** [comment]
Yeah the "Too many requests" is the result of a rate limiter in place. There isnt much to do except reduce the frequency and try after a while
