### ISSUE TITLE
Keep zips / exe files as release artifacts

### ISSUE THREAD

**Issue by shantanu-deriv** [bombardier-gif/covid-vaccine-booking#368]
Currently files like several `.exe`, `.zip` and `.bat` are included in the repo. IMHO they should be removed from the repo and made part of release artifacts. This will reduce the repo size as git diff cannot determine file changes in such file types and blindly keeps all versions of these files.

If we dont want that have a look at: https://opensource.com/life/16/8/how-manage-binary-blobs-git-part-7 to manage other optimisations

**Comment by bombardier-gif** [comment]
+1 on the suggestion. I will mark this as an enhancement and close this. we can revisit it whenever someone wants to contribute
