### ISSUE TITLE
Add option to select time slot according to user's preference 

### ISSUE THREAD

**Issue by hpk22** [bombardier-gif/covid-vaccine-booking#369]
Please add option to select time slot according to user's preference. It would make this software complete 👍

**Comment by Nakul93** [comment]
Yeah there has been some updates in the API. It has added an option for ‘from’ and ‘to’ time in the appointment sessions API

**Comment by shan-96** [comment]
Hi @hpk22 can you please rename the issue title to `add option to select time slot according to user's preference` Feature request is too generic. Thanks

**Comment by shailesh** [comment]
@hpk22 I hope you were able to book one.

For now we are not going into this deep features bare minimum should work for getting a slot. 

And yes just to add there is option to select slot if you say not to auto book
