### ISSUE TITLE
Problem while trying in Linux system

### ISSUE THREAD

**Issue by Dhanushrajashekar** [bombardier-gif/covid-vaccine-booking#37]
![3](https://user-images.githubusercontent.com/70057181/117669021-1b05bf80-b1c4-11eb-81db-62b9d5b93c21.PNG)

**Comment by bilal-fazlani** [comment]
Use python3 latest version

**Comment by bombardier-gif** [comment]
Thanks @bilal-fazlani for being a good citizen! 
@Dhanushrajashekar I had mentioned in the readme that i also got a syntax error and python3 was the solution
