### ISSUE TITLE
Script not reading my OTP

### ISSUE THREAD

**Issue by AanchalV** [bombardier-gif/covid-vaccine-booking#372]
Despite recieving the OTP on phone (tried for different bookings on IFTT and Apple shortcuts both), script does not read the OTP. And it keeps on running in the loop. PFA screenshot.
![InkedCapture13_LI_Moment](https://user-images.githubusercontent.com/17899631/119726999-68a24d80-be8f-11eb-8312-f6cea81c7642.jpg)

**Comment by Nakul93** [comment]
Please mask your mobile no or any other personal details while you provide the logs.

I have tried it for iOS and it seems to work fine. Go through the Readme and follow all the instructions carefully. Maybe do the setup in IFTTT/Shortcut app once again and try.

**Comment by AanchalV** [comment]
Thanks Nakul. I have masked my details. Code was working fine for till yesterday. It has stopped to do so after the recent change of 26th May.

**Comment by Nakul93** [comment]
That is rather strange, there has only been 1 commit yesterday which had nothing to do with OTP, so the logic is unchanged. Check if your phone is not in battery saver mode, also check all the other tips related to auto OTP read from readme

**Comment by AanchalV** [comment]
Before this, i was using code version downloaded on 15th May. Then it started giving error #341 , so i re-downloaded the code, updated Python version and ran it. It is after that i am facing the above issue. Is there anything else that i am missing ?

**Comment by bombardier-gif** [comment]
1. Can you open the IFTTT applet and check the logs for errors, and also when did it run the last?
2. Did you buy the premium version of IFTTT? That runs realtime than the free one

**Comment by AanchalV** [comment]
Hey. Just checked again. I was using the old kvdb link. Updated that and it is working fine now.
Thanks for your support !

**Comment by nolimits0007** [comment]
Can anybody tell that IFTTT work for iphone also. plz elaborate if possible.

**Comment by BumpyKnuckls** [comment]
@nolimits0007 IFTTT setup will work only for Android. For iOS you can use shortcuts app. Please checkout the readme in case you want to setup the shortcuts app.
