### ISSUE TITLE
dose 2

### ISSUE THREAD

**Issue by Kanchangk** [bombardier-gif/covid-vaccine-booking#376]
What if beneficiaries have different does 2 dates but both are in past (assuming all other valid parameters like same vaccine type etc. )

https://github.com/bombardier-gif/covid-vaccine-booking/blob/f4e709b2b814dd624ac0677aca92f0cca76509d3/src/utils.py#L253

**Comment by Nakul93** [comment]
Currently different dose2 dates are not supported. If this is to be implemented then you have to make separate API calls for each date alongside PIN/district which might cause rate limiting issues.

**Comment by Kanchangk** [comment]
why cant we call same does 2 date for both since the does 2 dates are already in past?

**Comment by Nakul93** [comment]
What if X has due date on 21/05 and Y on 02/06 then it won’t work right since the weeks are separate. We can add this feature but this  would add complexity to the code since there are a lot edge cases.

**Comment by Kanchangk** [comment]
I guess instead of checking the length of the keys, simply checking if the due date are in past, should work. I am not sure if there is any other case to be considered here (assuming there is no deadline or max date for dose2. )

**Comment by Nakul93** [comment]
Well if you want you could modify the code locally and check for your case. And yes there is a max date for dose2 for each vaccine type, but moreover even if were to check that if dose2 dates are in past they should be falling in the same week else we need to make two separate calls

**Comment by Nakul93** [comment]
Tbh, very rarely there would be a case where a beneficiaries of same age group and same vaccine type of a single acc would have different due dates.

**Comment by siddharthgoyal90** [comment]
Does the current latest script allow booking of 2nd dose of vaccine, assuming beneficiaries are on same date for same vaccine?

**Comment by Nakul93** [comment]
> Does the current latest script allow booking of 2nd dose of vaccine, assuming beneficiaries are on same date for same vaccine?

Yes it does

**Comment by BumpyKnuckls** [comment]
Dont think we plan on supporting this edge case, since the script is more of general purpose one fitting most of the use cases.
