### ISSUE TITLE
Build a exe while testing

### ISSUE THREAD

**Issue by rajmishra78** [bombardier-gif/covid-vaccine-booking#377]
What is the command used by you guys to build an exe using pyinstaller??

I'm testing it using
```
pyinstaller -F covid-vaccine-slot-booking.py
```
but the exe fails at runtime.

Can you please share the command by which you build an exe for Windows?

**Comment by bombardier-gif** [comment]
https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/.github/workflows/main.yml
