### ISSUE TITLE
IFTTT MOBILE NUMBER STORAGE

### ISSUE THREAD

**Issue by Kanchangk** [bombardier-gif/covid-vaccine-booking#380]
Can you add the kvdb script you are using to facilitate OTP auto read so that

1. people can be assured that mobile numbers are not being stored 
2. other people can create /modify the kvdb script as per their own convenience?

**Comment by bombardier-gif** [comment]
I dont use any script. I used the APIs to read and write to the bucket.
The bucket is publically accesible so you can also see whats stored.
Each key has a TTL of 3 mins after that its automatically deleted.
