### ISSUE TITLE
Issue when booking the slot. The automation is TIMING OUT just when the slots are released

### ISSUE THREAD

**Issue by kriprasad** [bombardier-gif/covid-vaccine-booking#381]
When the slot is released, the automation doesn't seem to book the slot and time's out. This has been happening since the past two days. I just have two pincodes hitting the API and the refresh rate set is 7 seconds. So relatively I am hitting the API 84 times in 5 minutes and hence this is not an issue of IP Blocking.

Please HELP. It is timing out just when slots are getting released and comes back to normal form after about a minute or two when the slots are completely booked.

![image](https://user-images.githubusercontent.com/84540072/119849654-6f31d300-bf2a-11eb-9a94-28cbcae05395.png)

**Comment by kriprasad** [comment]
Does anyone else face this issue?

**Comment by 6mxo89sqh** [comment]
@kriprasad this is happening because day-before yesterday, cowin changed the status code for rate-limiting from 403 to 429.

**Comment by phvajjha** [comment]
It is rate limiting, I saw this issue too. Also, are you or someone else looking at slots from a different computer/phone on the same network maybe? This happened to me 2 days ago, I stopped checking for slots or even opening the portal/app from any other device on the same network. Never happened after that and booked 4 slots successfully.

**Comment by kriprasad** [comment]
@phvajjha : Yeah we had the Umang application open. I'll try this without opening any application tomorrow and try my luck. Thanks for the insight :-D Cheers! :-D
