### ISSUE TITLE
We all knew it'll be out on the news someday ...https://www.wired.co.uk/article/india-covid-vaccine-cowin

### ISSUE THREAD

**Issue by vishykane2** [bombardier-gif/covid-vaccine-booking#383]
https://www.wired.co.uk/article/india-covid-vaccine-cowin

The chances of getting a vaccine have been tilted in the favour of the rich, the educated and tech-savvy.

**Comment by bombardier-gif** [comment]
:) Our repo isnt mentioned right?

**Comment by vishykane2** [comment]
No, not by name. 

But they did say this 
At the time of writing, a search of ‘CoWin’ on GitHub gave 1,764 public repository results
