### ISSUE TITLE
Feature Request - Download Appointment Slip

### ISSUE THREAD

**Issue by dhhruv** [bombardier-gif/covid-vaccine-booking#385]
There should be an option in the script where the user can download appointment slip as soon as it gets booked.

**Comment by shivaslifzz** [comment]
why there is a need bro you can goto cowin portal and download at any point

**Comment by dhhruv** [comment]
It'd be better to download the appointment slip using the same token.

**Comment by bombardier-gif** [comment]
Its a good suggestion, but i feel we  have a workaround already. The code is a bit unstable these days, so lets wait till these things are more smooth
