### ISSUE TITLE
Is multiple booking working for this script right now? Let me know if someone tested ?

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#39]
Is multiple booking working for this script right now? Let me know if someone tested ?

**Comment by xxxAng** [comment]
@BumpyKnuckls  Yes ... multiple beneficiaries with ',' ... captcha not working it seems

**Comment by BumpyKnuckls** [comment]
Some of my friends were able to book with multiple beneficiaries, so the issue might be with the captcha than with multiple beneficiaries. And it be similar to the following note mentioned in the README:

`The captcha is a bit buggy and I had to make 5-6 tries before I was able to book.`

So I would suggest to retry multiple times when captcha appears. I also faced the captcha a few times, but it did work after retrying 3-4 times.

**Comment by bombardier-gif** [comment]
Yes confirming what @BumpyKnuckls said. I was able to book multiple beneficiaries yesterday. Captcha is a bit wierd at this moment
