### ISSUE TITLE
[Errno 2] No such file or directory: 'C:\\Users\\apoorvak\\Downloads\\model.txt' 

### ISSUE THREAD

**Issue by apoorvakasbekar** [bombardier-gif/covid-vaccine-booking#391]
![image](https://user-images.githubusercontent.com/69908205/119982903-11aa8e80-bfdd-11eb-8e93-54fd86a9d567.png)

**Comment by shailesh** [comment]
Put this file in the root directory

https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/src/model.txt

**Comment by kal149** [comment]
> 
> 
> Put this file in the root directory
> 
> https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/src/model.txt

How to do that.. Can you guide please.

**Comment by acousticvibes** [comment]
Copy Paste the Model.txt file from SRC folder to the Main Folder (root folder) where all other files are there.

**Comment by vishalv26** [comment]
[model.txt](https://github.com/bombardier-gif/covid-vaccine-booking/files/6565119/model.txt)

Attached is the file. Just Download it and run the exe

**Comment by BumpyKnuckls** [comment]
@apoorvakasbekar @kal149  Please try the tips proposed by folks here and reopen the ticket if the issue still persists.
