### ISSUE TITLE
Getting an OTP request every 3 minutes

### ISSUE THREAD

**Issue by mohitshah9920** [bombardier-gif/covid-vaccine-booking#395]
Is this normal? (See attached image)

Why does it need OTP to check for slots? Correct me if I wrong, availability is accessible even without signing in?

I followed the steps for mac and iPhone

![IMG_066F70938D09-1](https://user-images.githubusercontent.com/3580703/120020113-eccb1100-c006-11eb-85f8-b444e7b80472.jpeg)

**Comment by salian** [comment]
Availability status from the unauthenticated endpoint has a delay, and is practically useless for booking. 

A login is needed to check latest availability. In fact even with the authenticated endpoint you will have edge cases where the API returns stale status. Especially when just one slot was cancelled and becomes available, it often happens that the API says the slot is open and you get to the captcha only to find it has actually been booked already.

The API rate limit for all requests from your IP / network including umang, arogya setu etc combined, are discussed elsewhere. IIRC the cloudflare WAF is currently maxing out at around 100 requests every 5 minutes, while the token itself lasts for a max of 10 minutes if the rate limits are followed. 

But the 3 minute delay in your screenshot makes me think you aren't getting the OTP at all and the script is triggering a new OTP after the previous OTP's validity expires. Can you check if your script actually received any OTP and was able to log in?

**Comment by mohitshah9920** [comment]
I see.

 In the iPhone, it doesn't automatically send the OTP from the SMS to the server. For the automation to run I need to manually tap on 'Run'. This is not ideal because I have to keep doing this every 10 minutes?

**Comment by 6mxo89sqh** [comment]
yes @mohitshah9920 , on iPhone u have to do that. There is no other way. Its apple's security and privacy.
