### ISSUE TITLE
kvdb.io not working

### ISSUE THREAD

**Issue by darthfishious** [bombardier-gif/covid-vaccine-booking#396]
is the kvdb.io service down? it is unable to clear OTP bucket and move forward with requesting for OTP.

Manual OTP input is working fine but the automation is broken.

**Comment by darthfishious** [comment]
for some reason today, many anti viruses have started classifying kvdb.io as a phishing website. due to this, they are preventing access to this over the network. had to add this domain as an exception in my anti virus software and it fixed the issue.

**Comment by abhikumar9809** [comment]
I am facing the same Problem. Getting connection refused. How do i solve this issue for windows defender?
