### ISSUE TITLE
Feature Request- Search by Telegram alerts

### ISSUE THREAD

**Issue by Nakul93** [bombardier-gif/covid-vaccine-booking#398]
I was thinking, if we could add a feature to get alerts from the telegram bot(cowin alerts channel) for a selected district and only then the script should login and search for slots. 

This way we could keep the script running and call the APIs only if a specific slot at a centre/pincode opens up and that probably might resolve the rate limiting issue.
This would be helpful for those states where slots open up at random times.

Let me know of your thoughts on this.

**Comment by darthfishious** [comment]
telegram alerts come late for many people and slots are completely booked by then. if this feature is added, kindly make it an option and not the default.

**Comment by Nakul93** [comment]
> telegram alerts come late for many people and slots are completely booked by then. if this feature is added, kindly make it an option and not the default.

I disagree, telegram alerts are the fastest compared to all the other vaccine notification applications at least for the major cities.
And yeah I agree it shouldn’t be a default option

**Comment by bombardier-gif** [comment]
Our architecture doesnt support such usecases:
We have a pull architecture, where we poll the cowin backend for slots

For telegram we need a push architecture which would react on telegram`s notification. 

And adding to @darthfishious the telegram channel is also a hit and miss. I have seem multiple times our script catches slots which are not caught by telegram .

**Comment by shailesh** [comment]
@Nakul93 I agree, it is the fastest but as mentioned by @bombardier-gif sometimes even telegram misses the slots. so we can probably not rely on these push notifications. Users should either understand the patterns for slots opening timings or hit when opens up or keep it running with best frequency 6 or 7.

**Comment by Nakul93** [comment]
Well I was suggesting this as a separate script which could look for notification and thereby triggering the main script. I understand telegram also misses sometimes but I haven’t really noticed that at least for pvt hospitals.
This could have been useful where the script is running in the background, currently if we do that we constantly needs to refresh the token(getting new OTP) so that the rate limiting doesn’t occur.
Tbh sending these requests even at a interval of 7secs or more seems a bit redundant if you want to run this script for hours

**Comment by gitmnj** [comment]
@shailesh @Nakul93 @bombardier-gif we can implement it in our code and keep it as a option since in areas like mumbai the slots are released randomly and due to rate limit we can't run the script continuously so it's better to add a option to our code
