### ISSUE TITLE
OTP problem.

### ISSUE THREAD

**Issue by devansh7777** [bombardier-gif/covid-vaccine-booking#4]
@bombardier-gif i have mailed you my phone number as you asked. Also i continued my current issue of otp not coming on time.

**Comment by bombardier-gif** [comment]
Are you receiving the OTP sms on your phone in a timely way?

**Comment by bombardier-gif** [comment]
I updated the logic provided by another PR for resending the SMS. I am trying with the latest code again.

**Comment by devansh7777** [comment]
> Are you receiving the OTP sms on your phone in a timely way?

no not really. i am not running the script as of now , i though you might be using my number.

**Comment by bombardier-gif** [comment]
Party is over my friend. They imposed a capcha.More details here
https://github.com/pallupz/covid-vaccine-booking/issues/123

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gitmnj** [comment]
Please send the discord server link

**Comment by bombardier-gif** [comment]
I updated the code. Please try again. This has captcha support from the main repo by pallupz

**Comment by devansh7777** [comment]
> I updated the code. Please try again. This has captcha support from the main repo by pallupz

okay i was off of github for a while, did you guys found a way to work around captcha ? @bombardier-gif ??

**Comment by BumpyKnuckls** [comment]
Hey @devansh7777 @bombardier-gif introduced a popup for captcha, asking the users to enter the captcha which while doesn't automate it, is working well for most.
