### ISSUE TITLE
Faced this issue , response code 500

### ISSUE THREAD

**Issue by elv10** [bombardier-gif/covid-vaccine-booking#40]
![500](https://user-images.githubusercontent.com/83970080/117683915-24962400-b1d2-11eb-86d1-d6ce1ea2c7fe.png)

**Comment by bombardier-gif** [comment]
It is a scaling problem at their end. Their database (dynamodb) has issues. It should resolve after a while. We saw this yesterday.

**Comment by elv10** [comment]
Thanks , that was quick 
Appreciate the great work you have done
