### ISSUE TITLE
Total number of successful bookings

### ISSUE THREAD

**Issue by great1113** [bombardier-gif/covid-vaccine-booking#400]
While going through the code, I came across this line which executes on every successful booking.

 requests.put("https://kvdb.io/thofdz57BqhTCaiBphDCp/" + str(uuid.uuid4()), data={})

(If I am understanding this correctly)Can you tell us how many bookings have been done using this script?

@bombardier-gif

**Comment by salian** [comment]
Good try.

**Comment by bombardier-gif** [comment]
Its a public bucket. And someone deleted it :| 

Note: You can also check the entries by their curl examples in their doc.
