### ISSUE TITLE
2nd dose isssue

### ISSUE THREAD

**Issue by uvmittal** [bombardier-gif/covid-vaccine-booking#401]
bug
when booking for 2nd dose first dose appointment is shown

Proceed with above info? (y/n Default y):
The following appointments are active! Please cancel them manually first to continue
+-------+---------------+--------------+--------------+--------+------------+-----------+
|   idx | beneficiary   | name         | state_name   |   dose | date       | slot      |
+=======+===============+==============+==============+========+============+===========+
|     1 | XXXXXXX | XXXXXXXXXX | Delhi        |      1 | 22-04-2021 | Afternoon |
+-------+---------------+--------------+--------------+--------+------------+-----------+

_Originally posted by @uvmittal in https://github.com/bombardier-gif/covid-vaccine-booking/pull/318#issuecomment-850820934_

**Comment by 6mxo89sqh** [comment]
@uvmittal Can you check the status on CoWIN? Is it showing as 'Partially Vaccinated'? 

I tried to reproduce but wasn't able.

**Comment by subashjain** [comment]
> @uvmittal Can you check the status on CoWIN? Is it showing as 'Partially Vaccinated'?
> 
> I tried to reproduce but wasn't able.

I booked 2nd dose without any problem

**Comment by shivaslifzz** [comment]
I guess you didn't get certificate for the 1st dose, that's creating this problem

**Comment by Nakul93** [comment]
@uvmittal is this resolved?

**Comment by BumpyKnuckls** [comment]
Closing this to better track the open issues. Please continue the discussion if needed
