### ISSUE TITLE
Captchas have been updated by Cowin. 

### ISSUE THREAD

**Issue by acousticvibes** [bombardier-gif/covid-vaccine-booking#402]
Captcha Response Code: 200

Booking Response Code: 400 

Invalid Security Code

**Comment by abhikumar9809** [comment]
Meaning?

**Comment by bombardier-gif** [comment]
Do you have more information?

Invalid security code happens when the AI reads a wrong code.

**Comment by nolimits0007** [comment]
I booked few hour back . No Captchas has been updated.
<img width="914" alt="Screenshot 2021-05-30 at 12 04 32" src="https://user-images.githubusercontent.com/84738436/120095469-c5c62980-c143-11eb-8e41-6a1ccdffd5e9.png">

**Comment by shailesh** [comment]
Run a test within directory copying captcha response to check if anything has changed.

**Comment by shailesh** [comment]
Just tested it, this is working fine.

<img width="1792" alt="Screenshot 2021-05-30 at 1 25 11 PM" src="https://user-images.githubusercontent.com/9050349/120096695-96ff8180-c14a-11eb-8184-60b8b4f2b875.png">


<img width="1792" alt="Screenshot 2021-05-30 at 1 25 02 PM" src="https://user-images.githubusercontent.com/9050349/120096680-8222ee00-c14a-11eb-9d7c-8e95b8981b4c.png">

**Comment by BumpyKnuckls** [comment]
Marking this closed since folks are reporting that status quo hasn't changed.
