### ISSUE TITLE
OTP not getting validated

### ISSUE THREAD

**Issue by Ruchikaseth** [bombardier-gif/covid-vaccine-booking#404]
Validating OTP..
Unable to Validate OTP
{ "errorCode": "USRAUT0014", "error": "Invalid OTP" }
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/99XXXXXXXX

**Comment by great1113** [comment]
I am getting the following error.

clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/9963707062
Requesting OTP with mobile number XXXXXXXXXX..
error fetching OTP API:Not Found

**Comment by Ruchikaseth** [comment]
Got a slot!

Enter the OTP manually for the first instance. 

There on the OTP will be automatically read and the slot will be booked.
