### ISSUE TITLE
error fetching OTP API:Not Found

### ISSUE THREAD

**Issue by sync-1203** [bombardier-gif/covid-vaccine-booking#405]
Anyone getting this? - started getting this today in the evening around 4:40 PM

clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/XXXXXXXXXX
Requesting OTP with mobile number XXXXXXXXXX..
error fetching OTP API:Not Found

**Comment by darthfishious** [comment]
same issue. just came up a few minutes ago. was working fine until 10 minutes back

**Comment by Nikhil-Gohil** [comment]
Similar issue here as well, not able to send OTP form the phone either. The message is "Sending OTP failed with reason: null"

**Comment by nolimits0007** [comment]
> Anyone getting this? - started getting this today in the evening around 4:40 PM
> 
> clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/9987617614
> Requesting OTP with mobile number 9987617614..
> error fetching OTP API:Not Found

Try not to give ur number . Keep ur privacy

**Comment by sync-1203** [comment]
> > Anyone getting this? - started getting this today in the evening around 4:40 PM
> > clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/9987617614
> > Requesting OTP with mobile number 9987617614..
> > error fetching OTP API:Not Found
> 
> Try not to give ur number . Keep ur privacy

yeah, edited. can you edit your quote too?

**Comment by Sandeep-Works** [comment]
Hey anyone knows any fix for this error fetching OTP API

**Comment by nolimits0007** [comment]
> > > Anyone getting this? - started getting this today in the evening around 4:40 PM
> > > clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/XXXXXXX
> > > Requesting OTP with mobile number XXXXXXXX..
> > > error fetching OTP API:Not Found
> > 
> > 
> > Try not to give ur number . Keep ur privacy
> 
> yeah, edited. can you edit your quote too?

Delete ur reply

**Comment by sync-1203** [comment]
Closing this to maintain 1 thread/log. #406

**Comment by shivaslifzz** [comment]
dont create multiple keys better @bombardier-gif  if you create one generic key and update the same in main branch other wise kvdb server will go down
