### ISSUE TITLE
Sending OTP Failed with reason null

### ISSUE THREAD

**Issue by nibir08in** [bombardier-gif/covid-vaccine-booking#410]
CoWIN OTP Retriever gives error as "Sending OTP Failed with reason null." Retry attempt count increases but nothing happens.
Facing issue since afternoon 30th May 2021
![Cowin_OTP_Issue](https://user-images.githubusercontent.com/83547088/120108980-288be500-c185-11eb-90f8-e00309318130.jpg)

**Comment by gsagrawal** [comment]
same

**Comment by Bruce119-NC** [comment]
https://github.com/bombardier-gif/covid-vaccine-booking/issues/406 
monitor this.

**Comment by salian** [comment]
The "KV DB Bucket Key" was a trial version of a bucket and it expired. 

You can sign up yourself at kvdb.io, get your own key and change the key in the mobile app as well as in the script, that should do it. 

For further details look at #406 as Bruce119-NC mentioned.

**Comment by Bruce119-NC** [comment]
https://github.com/rooniks/covid-vaccine-booking
use this repo it's working perfect.

**Comment by nibir08in** [comment]
Fixed with personal KV DB Bucket Key
