### ISSUE TITLE
The Script closes as soon as I open the script

### ISSUE THREAD

**Issue by sharankumar-rgb** [bombardier-gif/covid-vaccine-booking#411]
The Script closes as soon as I open the script, I am trying to open covid-slot-vaccine-booking python file which is in the src folder.

**Comment by rooniks** [comment]
How are you trying to open it? Maybe share some screenshots.

**Comment by sharankumar-rgb** [comment]
> How are you trying to open it? Maybe share some screenshots.

Hey thanks for the reply, I figured that I didnt install the req.txt file. My bad.
