### ISSUE TITLE
Getting API not found error while its trying to get the OTP

### ISSUE THREAD

**Issue by vishalhappiest** [bombardier-gif/covid-vaccine-booking#412]
It was working all well, before today afternoon, now getting below error. I would like thank you for making this, really helping lot of people in booking. 

Error:
error fetching OTP API:Not Found
error fetching OTP API:Not Found
local variable 'OTP' referenced before assignment
OTP Retrying in 5 seconds
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/

**Comment by abhriyaroy** [comment]
Same here

**Comment by Nakul93** [comment]
@vishalhappiest check #406 
For now you could try manual OTP

**Comment by chandrachur1982** [comment]
It seems the issue persist in KVDB bucket, I have created one new for mine and modified the same cowin otp retriver and utils.py script. Right now it's working but not sure if any other functionalities broke or not

**Comment by Bruce119-NC** [comment]
https://github.com/rooniks/covid-vaccine-booking
use this repo it's working perfect.

**Comment by bombardier-gif** [comment]
I am closing this ticket for managing new tickets well. Please continue your conversation
