### ISSUE TITLE
401 error while submitting OTP in https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/XXXXXXXXX

### ISSUE THREAD

**Issue by subhankarhalder94** [bombardier-gif/covid-vaccine-booking#416]
getting no response from https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/xxxxxxxxxx

**Comment by rooniks** [comment]
Issue already reported: https://github.com/bombardier-gif/covid-vaccine-booking/issues/406
Pull request for the same: https://github.com/bombardier-gif/covid-vaccine-booking/pull/408

Until the above pull request is merged, you could clone this repo: https://github.com/rooniks/covid-vaccine-booking
It's working fine.

**Comment by Nakul93** [comment]
Closing this now since the issue has been fixed
