### ISSUE TITLE
Here's how to make it work when you get "error fetching OTP API:Not Found"

### ISSUE THREAD

**Issue by mohitshah9920** [bombardier-gif/covid-vaccine-booking#417]
1. Create a new bucket:
Go to https://kvdb.io/. Scroll down. Click on 'Sign up now' for a 14-day free trial. Enter your email and you'll get a new bucket with a key.

2.  Change bucket key in 2 files:
Replace string 'ASth4wnvVDPkg2bdjsiqMN' with your new bucket key
- Line 7 in /covid-vaccine-booking/src/CoWinOTPRetriever/app/src/main/res/values/strings.xml
- Line 1042 in /covid-vaccine-booking/src/utils.py

3. Change bucket key in Shortcuts app:
Go to the personal automation you created. Change the URL. Replace ASth4wnvVDPkg2bdjsiqMN with new key in the URL eg https://kvdb.io/XXXXXXXX/9999999999

Step 3 will be different for Android users, but similar where you just need to switch the ke in the URL

**Comment by RishabhMunjal** [comment]
Hi i don't have Python installed on my pc. Could you share the exe file without the bucket issue?

**Comment by mr-vaibh** [comment]
> Hi i don't have Python installed on my pc. Could you share the exe file without the bucket issue?

Just install python, it's easy

**Comment by souj13** [comment]
> 1. Create a new bucket:
>    Go to https://kvdb.io/. Scroll down. Click on 'Sign up now' for a 14-day free trial. Enter your email and you'll get a new bucket with a key.
> 2. Change bucket key in 2 files:
>    Replace string 'ASth4wnvVDPkg2bdjsiqMN' with your new bucket key
> 
> * Line 7 in /covid-vaccine-booking/src/CoWinOTPRetriever/app/src/main/res/values/strings.xml
> * Line 1042 in /covid-vaccine-booking/src/utils.py
> 
> 1. Change bucket key in Shortcuts app:
>    Go to the personal automation you created. Change the URL. Replace ASth4wnvVDPkg2bdjsiqMN with new key in the URL eg https://kvdb.io/XXXXXXXX/9999999999
> 
> Step 3 will be different for Android users, but similar where you just need to switch the ke in the URL

Are you sure about line 1042, it doesn't show about the the key?
![image](https://user-images.githubusercontent.com/70004065/120205851-1161fb80-c248-11eb-97d0-ed52acaa8c01.png)

**Comment by umeshrege** [comment]
I have created a new branch to address this issue, by making the kvdb bucket key as variable, which users can use after registering on kvdb.io as mentioned by @souj13 
You can download the **covid-vaccine-slot-booking_v1.0.6.exe** from https://github.com/umeshrege/covid-vaccine-booking/tree/kvdb

**Comment by Saubhik-Som** [comment]
THIS WORKS! THANKS 😁
