### ISSUE TITLE
[Android App] Sending OTP failed with reason null

### ISSUE THREAD

**Issue by rforttest** [bombardier-gif/covid-vaccine-booking#419]
On Android app co retriever shows sending OTP failed with reason null and continuously try it ..
But failed

**Comment by HarshGupta011** [comment]
This is happening in one of my phone too

**Comment by bombardier-gif** [comment]
@ujaiswal @chris-10 FYI

**Comment by chris-10** [comment]
@rforttest @HarshGupta011 This is an error communicating with the KVDB server and is thrown when the server response is not 200. **Null** is displayed when there is no message to parse from the error message returned by the server. Will modify app to display appropriate default error message in case server returns empty error message.

**Comment by MM1287** [comment]
@chris-10 - Continuous Error sending OTP to KVDB server from mobile.  Tried with another mobile as well similar error recieved.

@bombardier-gif  - error at Python screen as "error fetching OTP api".

**Comment by chris-10** [comment]
@MM1287 You need to update KVDB bucket as explained in #417. Update on the app as well.

**Comment by 333koranga** [comment]
Every time you open the app , you need to paste new kvdb storage link in the app. 
Even if the app shows new kvdb link, paste it again.
