### ISSUE TITLE
otp issue

### ISSUE THREAD

**Issue by uvmittal** [bombardier-gif/covid-vaccine-booking#42]
wont let me enter otp nor anyways
![image](https://user-images.githubusercontent.com/69962764/117688090-177b3400-b1d6-11eb-959c-560b04c51596.png)

**Comment by bombardier-gif** [comment]
Please check if IFTTT is running properly, and is the premium version, also disable any power saver options on the IFTTT app

**Comment by uvmittal** [comment]
thanks

**Comment by uvmittal** [comment]
> Please check if IFTTT is running properly, and is the premium version, also disable any power saver options on the IFTTT app

thanks sir for the great script
