### ISSUE TITLE
Booking Response Code: 409 : Showing center is full even it just opened and has all slots

### ISSUE THREAD

**Issue by parwaniravi248** [bombardier-gif/covid-vaccine-booking#421]
Facing this issue since last commit. Unable to book any slot.  
Getting : Booking Response Code: 409 : the center is completely booked even though it has just opened and shows all slots as available. 
Please see screenshot . 200 slots open for my region and they are available when 1st try happens for 10-12 PM slot but it shows booked, again for 2nd try for 12-02 PM slot, it shows 200 available but failed with same error for 409 ie slot is booked.

![image](https://user-images.githubusercontent.com/29358466/120199207-a06b1580-c240-11eb-88f3-578a05a7a2b9.png)

**Comment by manasshukla1** [comment]
In my case: whenever a slot opens and script tries to book, it gives error:

**Input code incorrect
Input code incorrect
Input code incorrect**

**Comment by siddharthgoyal90** [comment]
Is anyone able to book slot with latest main code branch with Option 2 and Option , ie, State OR State with pincode (Optimized) for 2nd dose?

**Comment by nolimits0007** [comment]
> Facing this issue since last commit. Unable to book any slot.
> Getting : Booking Response Code: 409 : the center is completely booked even though it has just opened and shows all slots as available.
> Please see screenshot . 200 slots open for my region and they are available when 1st try happens for 10-12 PM slot but it shows booked, again for 2nd try for 12-02 PM slot, it shows 200 available but failed with same error for 409 ie slot is booked.
> 
> ![image](https://user-images.githubusercontent.com/29358466/120199207-a06b1580-c240-11eb-88f3-578a05a7a2b9.png)

Try to do this troubleshooting in ur system first then try booking. follow below link.
https://github.com/bombardier-gif/covid-vaccine-booking/issues/397#issuecomment-851018802

**Comment by parwaniravi248** [comment]
@nolimits0007 : I don't see this as linked to above issue. I am running my code on mac, above link shows some model file for windows system

**Comment by nolimits0007** [comment]
> @nolimits0007 : I don't see this as linked to above issue. I am running my code on mac, above link shows some model file for windows system

Sorry i cant help for macOS.

**Comment by parwaniravi248** [comment]
@nolimits0007 : Yeah, i don't think this is related to any system. Just not able to book slots even though they are available. This is happening since v.1.0.3

@bombardier-gif : Can you please check? Has it got to do anything with latest release?
Thanks so much for this!

**Comment by Nakul93** [comment]
This could be a bug at CoWIN portal end, maybe the slots were booked completely as mentioned in the logs but the availability didn't get updated.

**Comment by nolimits0007** [comment]
> This could be a bug at CoWIN portal end, maybe the slots were booked completely as mentioned in the logs but the availability didn't get updated.

At the time of Hit slot availability was 200 ( probability with automatic Captcha is 99%) it is not possible that it was error from Cowin .  Might be captcha issue.

**Comment by parwaniravi248** [comment]
@nolimits0007 : FYI - I had kept auto-captha as yes.

**Comment by nolimits0007** [comment]
> @nolimits0007 : FYI - I had kept auto-captha as yes.

That why i am saying probability of booking with 200 slots with Auto Captcha ON . U can miss. This issue is something else.

**Comment by parwaniravi248** [comment]
@nolimits0007 : Yeah. Not able to book for last 2 days since I got the latest code. I have pulled old version now and will try tomorrow and see if that works. In my place the slot open only once at 6:00 PM. So I have to wait till tomorrow to check.

**Comment by manasshukla1** [comment]
@parwaniravi248 @nolimits0007 Guys..I also had the same problem..but in my case when slot opened it showed **Input code incorrect**. 

Then I deleted the whole folder and cloned it again just now around 7pm and it worked!!.

**Comment by nolimits0007** [comment]
> @nolimits0007 : Yeah. Not able to book for last 2 days since I got the latest code. I have pulled old version now and will try tomorrow and see if that works. In my place the slot open only once at 6:00 PM. So I have to wait till tomorrow to check.

U should switch to windows don't waste time on mac every body is able to do booking on windows . if u dont have try parallel desktop install windows and download main code from https://github.com/rooniks/covid-vaccine-booking.git.

**Comment by manasshukla1** [comment]
@nolimits0007 What is this rooniks repo? Is this improved version of bombardier repo?

**Comment by nolimits0007** [comment]
> @nolimits0007 What is this rooniks repo? Is this improved version of bombardier repo?

no this is not improved rather it solves the kvdb issue  ( already reported: #406
Pull request for the same: #408 )  and it helps to create ur own bucket at https://kvdb.io/

**Comment by manasshukla1** [comment]
Ok. Do you know about any other repo than bombardier and pallupz

**Comment by nolimits0007** [comment]
> Ok. Do you know about any other repo than bombardier and pallupz

I think this is the best . These people are really working hard.

I am using mac but i am running script on parallel windows unable to run script on mac.

**Comment by manasshukla1** [comment]
No idea bro. Never owned a Mac, so no clue

**Comment by nolimits0007** [comment]
> No idea bro. Never owned a Mac, so no clue

But u said u r running it on mac.

**Comment by manasshukla1** [comment]
When did I say that? I never said

**Comment by nolimits0007** [comment]
> @nolimits0007 : I don't see this as linked to above issue. I am running my code on mac, above link shows some model file for windows system

see this.

**Comment by Nakul93** [comment]
> > Ok. Do you know about any other repo than bombardier and pallupz
> 
> I think this is the best . These people are really working hard.
> 
> I am using mac but i am running script on parallel windows unable to run script on mac.
> 
> Do u have any link how to run this script on mac.

Have been running it on Mac since the start and never had a problem. I don't think the issue here is related to OS (Maclinux works best btw)
@parwaniravi248 I didn't see an error like 'input code incorrect' like in the case of @manasshukla1 so definitely not captcha related. 
What you can do is try searching for slots using option1 (pincode). It always works best

**Comment by parwaniravi248** [comment]
@Nakul93 : I use option 1 only always.

**Comment by nolimits0007** [comment]
> > > Ok. Do you know about any other repo than bombardier and pallupz
> > 
> > 
> > I think this is the best . These people are really working hard.
> > I am using mac but i am running script on parallel windows unable to run script on mac.
> > Do u have any link how to run this script on mac.
> 
> Have been running it on Mac since the start and never had a problem. I don't think the issue here is related to OS (Mac/linux works best btw)
> @parwaniravi248 I didn't see an error like 'input code incorrect' like in the case of @manasshukla1 so definitely not captcha related.
> What you can do is try searching for slots using option1 (pincode). It always works best

@Nakul93 can u plz help in running this script on mac . Any tutorial which can explain easily.

**Comment by Nakul93** [comment]
@nolimits0007 Its already there in [readme](https://github.com/bombardier-gif/covid-vaccine-booking#readme).  Have you installed the latest version of python on mac properly

**Comment by Nakul93** [comment]
> @Nakul93 : I use option 1 only always.

Ok. Try again tomorrow, it should work hopefully.

**Comment by nolimits0007** [comment]
> @nolimits0007 Its already there in [readme](https://github.com/bombardier-gif/covid-vaccine-booking#readme). Have you installed the latest version of python on mac properly

@Nakul93 can u help to run on mac as i have installed latest version python 3.9.5.

giving this error.

<img width="919" alt="Screenshot 2021-06-01 at 13 21 34" src="https://user-images.githubusercontent.com/84738436/120287158-9dbdfe00-c2dc-11eb-856a-cc5d04ab657d.png">

**Comment by nolimits0007** [comment]
> @nolimits0007 Its already there in [readme](https://github.com/bombardier-gif/covid-vaccine-booking#readme). Have you installed the latest version of python on mac properly

@Nakul93 Can u help with this i have installed latest version of python 3.9.5 & it is showing this error.

<img width="919" alt="Screenshot 2021-06-01 at 13 21 34" src="https://user-images.githubusercontent.com/84738436/120287691-1b820980-c2dd-11eb-9c55-a96f7e53a712.png">

**Comment by Nakul93** [comment]
@nolimits0007 type `python3` instead of `python` to get to python prompt

**Comment by nolimits0007** [comment]
> @nolimits0007 type `python3` instead of `python` to get to python prompt

@Nakul93 now unable to clone the git.

<img width="559" alt="Screenshot 2021-06-01 at 14 03 35" src="https://user-images.githubusercontent.com/84738436/120292931-605c6f00-c2e2-11eb-9f6d-3f5ee7c5d8b5.png">

**Comment by Nakul93** [comment]
No dude thats not how you clone a repo. Don't type the commands in python prompt. Just navigate to the folder where you want to clone the repo (for eg: lets say you want it in Desktop, so first open the Terminal and type `cd Desktop` and then type `git clone <link>`.

**Comment by nolimits0007** [comment]
> No dude thats not how you clone a repo. Don't type the commands in python prompt. Just navigate to the folder where you want to clone the repo (for eg: lets say you want it in Desktop, so first open the Terminal and type `cd Desktop` and then type `git clone https://github.com/bombardier-gif/covid-vaccine-booking.git`.)

@Nakul93 Can u now help with this how to upgrade.

<img width="955" alt="Screenshot 2021-06-01 at 14 58 13" src="https://user-images.githubusercontent.com/84738436/120301228-445ccb80-c2ea-11eb-84a6-548844f4cdd4.png">

**Comment by nolimits0007** [comment]
> > No dude thats not how you clone a repo. Don't type the commands in python prompt. Just navigate to the folder where you want to clone the repo (for eg: lets say you want it in Desktop, so first open the Terminal and type `cd Desktop` and then type `git clone https://github.com/bombardier-gif/covid-vaccine-booking.git`.)
> 
> @Nakul93 Can u now help with this how to upgrade.
> 
> <img alt="Screenshot 2021-06-01 at 14 58 13" width="955" src="https://user-images.githubusercontent.com/84738436/120301228-445ccb80-c2ea-11eb-84a6-548844f4cdd4.png">

@Nakul93 Done Thanks a lot for helping.

<img width="583" alt="Screenshot 2021-06-01 at 15 13 29" src="https://user-images.githubusercontent.com/84738436/120303363-65beb700-c2ec-11eb-8a12-a58d405d2e61.png">

**Comment by Nakul93** [comment]
@parwaniravi248 are you still facing this issue?

**Comment by parwaniravi248** [comment]
@Nakul93 : Yes, I am still facing the issue. Unable to use the script.

**Comment by Nakul93** [comment]
@parwaniravi248 have you pulled the latest changes?

**Comment by parwaniravi248** [comment]
@Nakul93 : Let me pull and try it today. The slots at my place open at 6 PM. I will let you know if this works today.

**Comment by parwaniravi248** [comment]
@Nakul93  : Getting this error while running latest 
Traceback (most recent call last):
  File "src/covid-vaccine-slot-booking.py", line 9, in <module>
    from ratelimit import disable_re_assignment_feature
  File "/Users/Ravi/Documents/covid-vaccine-booking/src/ratelimit.py", line 2, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'

**Comment by Nakul93** [comment]
Do this `pip3 install -r requirements.txt`

**Comment by parwaniravi248** [comment]
@Nakul93 : Sorry. I messaged too early as slots were about to open. I should have done that. But anyways I wasn't able to book slot. When they opened they were already booked. Couldn't book/test the new code.

**Comment by shailesh** [comment]
I hope you were able to book one. As if now we are limited as we have too many dependencies to rely on.
