### ISSUE TITLE
Second dose date selection issue

### ISSUE THREAD

**Issue by darthfishious** [bombardier-gif/covid-vaccine-booking#422]
while trying to run the script for second dose, it only allows you to search for the week starting from the due date. if we try to select the option to select our own starting date, the script just exits. if i want to take the vaccine in the second week post the due date and centers are opening slots for these dates, i cant run the script and book anything. please look into this.

i should be allowed to select any date post the due date as the starting point.

![screenshot](https://user-images.githubusercontent.com/84447012/120208556-3c018380-c24b-11eb-99f6-3573f6607478.jpg)

**Comment by Nakul93** [comment]
@darthfishious Having to put our own search date would defeat the purpose of the logic having a due date functionality. For now you could edit the json file and edit the date to your preferred one.

**Comment by darthfishious** [comment]
i totally agree that the due date functionality is absolutely needed. for that we can simply select y. and i think that in this case the default value should be y rather than n, which is the case right now.

however, in case i want to select a starting date post the due date, can we not select n and then use the same logic as what is used for date selection for first dose, to prevent people from selecting an earlier date? 

in the mean time, i'll work with the json. thanks @Nakul93

**Comment by Nakul93** [comment]
Yeah I could try that, although thats just making the code more complex since this would be a rare scenario coz most of the times slots don't up 2 weeks ahead.

**Comment by darthfishious** [comment]
> Yeah I could try that, although thats just making the code more complex since this would be a rare scenario coz most of the times slots don't up 2 weeks ahead.

no lets not make it more complex. will use the json for now.

btw, once due date has passed, does the script allow to then select a future starting date?

**Comment by Nakul93** [comment]
Yes it does

**Comment by darthfishious** [comment]
ya just checked the code. seems good enough for me. thanks
