### ISSUE TITLE
Permanent Fix for KVDB related Issues

### ISSUE THREAD

**Issue by PatelTilak** [bombardier-gif/covid-vaccine-booking#425]
Hello,

I created simple API to replace KVDB.

#### To Store OTP:
Make GET or POST request to 
`http://bombardier-cowin.rf.gd/store/` with parameters `key` & `value`
`
Example: http://bombardier-cowin.rf.gd/store/?key=TestKey&value=TestValue
`
**Note:** Old value is overwritten by default.

#### To Read OTP:
Make GET request to 
`http://bombardier-cowin.rf.gd/read/` with parameters `key`
`
Example: http://bombardier-cowin.rf.gd/read/?key=TestKey
`
**Note:** Once Value is read, it is deleted by default. No need to explicitly clear Value. But if you want to persist Value, pass additional parameter `clear` with value `0`
`
Example: http://bombardier-cowin.rf.gd/read/?key=TestKey&clear=0
`

This can be easily integrated in Android as well as Python Code. 
**To Enhance privacy**, Instead of passing Mobile Number as `Key`, pass MD5 or SHA hash of number & use the same for reading

Hope this helps.

**Comment by rooniks** [comment]
Is this tested for scale?

**Comment by PatelTilak** [comment]
> Is this tested for scale?

Bandwidth limit is 50000 hits per day. If required, we can setup multiple Instances.

**Comment by bombardier-gif** [comment]
Thanks @PatelTilak what is the backend for http://bombardier-cowin.rf.gd/store/ ?

**Comment by PatelTilak** [comment]
> Thanks @PatelTilak what is the backend for http://bombardier-cowin.rf.gd/store/ ?

I created this with PHP + MySQL & hosted on Shared Hosting account.

**Comment by PatelTilak** [comment]
> > Is this tested for scale?
> 
> Bandwidth limit is 50000 hits per day. If required, we can setup multiple Instances.

@rooniks @bombardier-gif 

I created 3 Instances.
We can use any of these Endpoints: 
http://bombardier-cowin.rf.gd/
http://bombardier-cowin2.rf.gd/
http://bombardier-cowin3.rf.gd/

We can have simple logic like this to loadbalance the hits:


**_Pseudo Code_**
<pre>
Endpoint = null

Endpoint1 = http://bombardier-cowin.rf.gd/
Endpoint2 = http://bombardier-cowin2.rf.gd/
Endpoint3 = http://bombardier-cowin3.rf.gd/

If ( Last digit of MobileNumber mod 3 == 0 )
     Endpoint = Endpoint1
If ( Last digit of MobileNumber mod 3 == 1 )
     Endpoint = Endpoint2
If ( Last digit of MobileNumber mod 3 == 2 )
     Endpoint = Endpoint3


StoreURL = Endpoint + "/store/"
ReadURL = Endpoint + "/read/"
</pre>

This will give us 50000 x 3 Hits per day. I doubt we would max-out this

**Comment by bombardier-gif** [comment]
Nice. Is the shared hosting account free of cost?

**Comment by PatelTilak** [comment]
> Nice. Is the shared hosting account free of cost?

Yes. It is provided by well known Hosting provider so I don't think it will create Uptime Issues.

**Comment by 6mxo89sqh** [comment]
There is a free service https://keyvalue.xyz/ . Should we try that out?

**Comment by bombardier-gif** [comment]
I like the keyvalue.xyz  @6mxo89sqh 
@PatelTilak I am less worried about uptime issues,but more worried about running the server for a month or more. Any insights on the usage terms?

**Comment by bombardier-gif** [comment]
@6mxo89sqh Also we need to overcome one major shortcoming of kvdb: Anyone can delete the bucket and create a problem for the whole community.

**Comment by bombardier-gif** [comment]
The tradeoff is that we added a SPOF with the solution which @PatelTilak proposed, the loadbalancing is fine but adds more moving parts.

Whereas kvdb/keyvalue.xyz is more stable and reliable. 

My initial thoughts on it, I am not against or for a particular solution

**Comment by 6mxo89sqh** [comment]
keyvalue.xyz doesn't have a delete API.

**Comment by PatelTilak** [comment]
> I like the keyvalue.xyz @6mxo89sqh
> @PatelTilak I am less worried about uptime issues,but more worried about running the server for a month or more. Any insights on the usage terms?

I have hosted this on https://infinityfree.net/
We are not storing anything that violates their Terms.

**Comment by PatelTilak** [comment]
> There is a free service https://keyvalue.xyz/ . Should we try that out?

Have they mentioned any limits on number of Requests ?

**Comment by 6mxo89sqh** [comment]
> > There is a free service https://keyvalue.xyz/ . Should we try that out?
> 
> Have they mentioned any limits on number of Requests ?

Not sure. I don't even know if they are reliable. His github has 0 stars and 1 fork.

**Comment by PatelTilak** [comment]
@6mxo89sqh API of keyvalue.xyz seems to be down.

I tried running the sample command that they have mentioned on their home page. Getting connection timeout. I dont know if I am doing something wrong. Accessing https://api.keyvalue.xyz/ from browser takes us to CloudFlare Error Page 

@bombardier-gif  I am of opinion that if we host the API ourselves, we will have better control. We take take other's views as well.

**Comment by 6mxo89sqh** [comment]
> @6mxo89sqh API of keyvalue.xyz seems to be down.
> 
> I tried running the sample command that they have mentioned on their home page. Getting connection timeout. I dont know if I am doing something wrong. Accessing https://api.keyvalue.xyz/ from browser takes us to CloudFlare Error Page
> 
> @bombardier-gif I am of opinion that if we host the API ourselves, we will have better control. We can take other's views as well.

Yup it is down. So, its not reliable! Also, i liked @vivek43nit 's idea (#414). Its quite simple and doesn't need any external dependency.

**Comment by PatelTilak** [comment]
> Yup it is down. So, its not reliable! Also, i liked @vivek43nit 's idea (#414). Its quite simple and doesn't need any external dependency.

Yes. @vivek43nit's Idea is very good. But while helping Friends/relatives in Booking, their phone may not be connected to same WiFi. So we will still require alternative.

**Comment by 6mxo89sqh** [comment]
@PatelTilak True.

**Comment by vivek43nit** [comment]
@PatelTilak , Agree, but my solution will reduce the traffic a lot from these free hosted dbs/apis.  So, after this, we may not need to worry about alternatives.

And, If someone wants to help their relatives who are living far, then he can register their names in his number itself.

**Comment by rooniks** [comment]
> The tradeoff is that we added a SPOF with the solution which @PatelTilak proposed, the loadbalancing is fine but adds more moving parts.
> 
> Whereas kvdb/keyvalue.xyz is more stable and reliable.
> 
> My initial thoughts on it, I am not against or for a particular solution

How about just creating a proxy api that routes to kvdb? The problem of anyone deleting the kvdb bucket arises because the bucket secret is exposed. The problem with deploying our own service similar to kvdb is to solve scalability. So we could just create a proxy api which just relays the request to kvdb and the secret is known only to that component. 

To put it more specifically, we will deploy an api say `api/bombardier/kvdb-proxy/9876543210` which takes `9876543210` as the key and value in the body, just as kvdb api. Internally, it would hit `https://kvdb.io/<secret-bucket>/9876543210`. Now since `<secret-bucket>` is not publicly exposed, there's no way some malicious user could go ahead and delete it. 

We can implement this proxy api using AWS Lambda which is basically a serverless compute that gives free 1 million requests per month in the free tier which would be active for a year. Pretty comfortable for our use case. Shouldn't take much time or effort.

**Comment by rooniks** [comment]
@bombardier-gif Also, could you please help me understand how exactly is someone deleting the bucket? The delete bucket api of kvdb is protected by a `supersecret`. As long as you protect it with a strong enough password, I don't see how the problem could arise in the first place.

**Comment by bombardier-gif** [comment]
the problem with kvdb is that you can create your account and delete my bucket. the support team mentioned that its in their roadmap to fix it.

Right now someone added a secret to write on the bucket. and now the bucket is unwritable.

**Comment by rooniks** [comment]
> the problem with kvdb is that you can create your account and delete my bucket. the support team mentioned that its in their roadmap to fix it.
> 
> Right now someone added a secret to write on the bucket. and now the bucket is unwritable.

Got it.

**Comment by bombardier-gif** [comment]
> There is a free service https://keyvalue.xyz/ . Should we try that out?

This seems to be down @6mxo89sqh

**Comment by 6mxo89sqh** [comment]
Yup, it is.

**Comment by bombardier-gif** [comment]
I am closing this ticket for managing new tickets well. Please continue your conversation
