### ISSUE TITLE
error fetching OTP API:Not Found

### ISSUE THREAD

**Issue by ganeshurao** [bombardier-gif/covid-vaccine-booking#426]
Hi ,

Since today morning , I am getting the following error 

error fetching OTP API:Not Found
error fetching OTP API:Not Found
error fetching OTP API:Not Found
error fetching OTP API:Not Found
error fetching OTP API:Not Found
error fetching OTP API:Not Found
error fetching OTP API:Not Found

Has it been shutdown ?

Can you help with this ...

**Comment by nolimits0007** [comment]
@ganeshurao already reported: #406
Pull request for the same: #408
Creat your own Bucket key.

**Comment by ganeshurao** [comment]
Thank you ...its resloved.

**Comment by nolimits0007** [comment]
@ganeshurao plz close this issue.

**Comment by shailesh** [comment]
closing as @ganeshurao reported it is resolved for him. Please feel free to open it if you encounter the issue again.
