### ISSUE TITLE
Discrepancy in the center availability data when choosing option3

### ISSUE THREAD

**Issue by Nakul93** [bombardier-gif/covid-vaccine-booking#427]
Yesterday I noticed that the number of centers available for 2 pincodes selected using option3 and the same pincodes used under option1 are different. Although this might not be affecting the end goal of booking the slots but I guess this could be looked into
![image](https://user-images.githubusercontent.com/24492930/120276185-ff2ba000-c2cf-11eb-903e-3d70910bb301.png)

![image](https://user-images.githubusercontent.com/24492930/120276223-094d9e80-c2d0-11eb-9e27-af3128ac5b6c.png)

As you could see the actual total number of centers available are 3(option1) but it is showing 11 with option3

**Comment by shailesh** [comment]
One says thane I mean this is a state/district and this could have multiple pin codes. whereas given 2 pin codes could have few centres so concluding this could be state/distci with more pin codes can have few more centres then these two

**Comment by Nakul93** [comment]
> One says thane I mean this is a state/district and this could have multiple pin codes. whereas given 2 pin codes could have few centres so concluding this could be state/distci with more pin codes can have few more centres then these two

Yeah I used option3 for thane district with same pincodes as shown in the 2nd screenshot.
Option3 is not filtering by centres it is taking each session as a centre.

**Comment by shivaslifzz** [comment]
> One says thane I mean this is a state/district and this could have multiple pin codes. whereas given 2 pin codes could have few centres so concluding this could be state/distci with more pin codes can have few more centres then these two

The count is based on state & district level and booking at pincode level

**Comment by Nakul93** [comment]
> > One says thane I mean this is a state/district and this could have multiple pin codes. whereas given 2 pin codes could have few centres so concluding this could be state/distci with more pin codes can have few more centres then these two
> 
> The count is based on state & district level and booking at pincode level

Nope it isn’t just checked the count for state and district level is even higher

**Comment by shivaslifzz** [comment]
> > > One says thane I mean this is a state/district and this could have multiple pin codes. whereas given 2 pin codes could have few centres so concluding this could be state/distci with more pin codes can have few more centres then these two
> > 
> > 
> > The count is based on state & district level and booking at pincode level
> 
> Nope it isn’t just checked the count for state and district level is even higher

I verified personally it's at State & district and the filter options you use

**Comment by Nakul93** [comment]
@shivaslifzz so your saying the centre count that shows up is filtered by age,vaccine type?

**Comment by shivaslifzz** [comment]
yep, PFA screen shot 

![image](https://user-images.githubusercontent.com/61616987/120370239-f5d31f80-c331-11eb-9d9a-e6e895b9bed1.png)

at 110021 pincode we have only 1 center but state & district (age,vaccine) we have 2 centers so it will show 2 centers as available but at the time of booking it will only look for 110021 pincode

**Comment by Nakul93** [comment]
ok got it thanks...closing it now
