### ISSUE TITLE
Getting Rate Limiting Error

### ISSUE THREAD

**Issue by ravibput** [bombardier-gif/covid-vaccine-booking#428]
![Issue](https://user-images.githubusercontent.com/85073707/120282099-0942a400-c2ba-11eb-8f24-113b117da67b.JPG)

**Comment by karanssh** [comment]
how often are you querying the API?

**Comment by ravibput** [comment]
Have been querying the API with a new kvdb bucket key since morning. The issue has started a couple of hours back. Was working fine before that.

**Comment by KUSHAGRA211** [comment]
Are you querying for pincode or districts ? if pincode how many of them ?

**Comment by ravibput** [comment]
> 
> 
> Are you querying for pincode or districts ? if pincode how many of them ?

districts, usually one but not more than two.

**Comment by subrat-mishra** [comment]
Could be possible if you are using a VPN connection just a thought.

**Comment by ravibput** [comment]
> 
> 
> Could be possible if you are using a VPN connection just a thought.

Yes I am using a VPN connection but it was working perfectly before.

**Comment by yohannlouis** [comment]
I was getting this error while querying 2 districts at 5sec interval rate. It even happened for 1 district but much less often. Does adding a district double the requests sent? 

No VPN being used.

5 sec interval rate :
60/5=12 requests a minute = 60 requests every 5mins 
if the limit is 100  requests every 5 mins, this should be fine..

If adding 2 districts means it gets doubled, it would make it 120 and cross that limit. Although, used to not face this issue before.

**Comment by ravibput** [comment]
> 
> 
> I was getting this error while querying 2 districts at 5sec interval rate. It even happened for 1 district but much less often. Does adding a district double the requests sent?
> 
> No VPN being used.
> 
> 5 sec interval rate :
> 60/5=12 requests a minute = 60 requests every 5mins
> if the limit is 100 requests every 5 mins, this should be fine..
> 
> If adding 2 districts means it gets doubled, it would make it 120 and cross that limit. Although, used to not face this issue before.

At present its happening for even 1 district. I will try to check it without VPN.

**Comment by dhhruv** [comment]
I'm getting the same issue, queried 4 pincodes at an interval rate of 45 seconds (just to test). Still facing this error after 10-12 minutes of usage. Didn't happen before.

**Comment by ravibput** [comment]
> 
> 
> > I was getting this error while querying 2 districts at 5sec interval rate. It even happened for 1 district but much less often. Does adding a district double the requests sent?
> > No VPN being used.
> > 5 sec interval rate :
> > 60/5=12 requests a minute = 60 requests every 5mins
> > if the limit is 100 requests every 5 mins, this should be fine..
> > If adding 2 districts means it gets doubled, it would make it 120 and cross that limit. Although, used to not face this issue before.
> 
> At present its happening for even 1 district. I will try to check it without VPN.

Working without vpn.

**Comment by ravibput** [comment]
Working without vpn.

**Comment by yohannlouis** [comment]
does adding districts increase the number of requests sent?
