### ISSUE TITLE
dose 2 question

### ISSUE THREAD

**Issue by darthfishious** [bombardier-gif/covid-vaccine-booking#429]
while booking for dose 2, the script only showed me a center after it was fully booked. on face value it appears as though the script missed the center.

however, on the telegram group, all the slots for this center appeared as dose 1 slots. so i am surprised why the script is even showing me a booked center whose slots were all dose 1 slots and are not applicable to dose 2 booking. even in the cowin portal the center appears as booked for me. 

so i have a query. do all centers have to bifurcate their slots into dose 1 and dose 2 or can the centers release slots without bifurcation and both dose 1 and dose 2 beneficiaries can book from this common pool? 

in the latter case it would make sense that the center appears to me as booked since i was eligible to book from the common pool. also in this case, the telegram channel is wrongly classifying the doses as only dose 1 slots.

however, if it is the former, the center should not appear to me as a booked center either in the script or on the cowin portal since dose 2 slots never even opened.

has anyone else faced this issue and could you please let me know how the slots are allotted in such a scenario.

**Comment by karanssh** [comment]
> do all centers have to bifurcate their slots into dose 1 and dose 2 or can the centers release slots without bifurcation and both dose 1 and dose 2 beneficiaries can book from this common pool?

yes, all centers mark dose 1 and dose 2 slots separately. 

> however, if it is the former, the center should not appear to me as a booked center either in the script or on the cowin portal since dose 2 slots never even opened.
