### ISSUE TITLE
Search for an issue (Filter: close/open) before creating one.

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#431]
@bombardier-gif can you please pin this. A number of issues are insanely getting larger and most of them seem related.

**Comment by bombardier-gif** [comment]
+1 to @shailesh on this.

**Comment by Nakul93** [comment]
I think most of the newbies are creating a lot of duplicate issues without even checking if a similar issue exists or not.

**Comment by BumpyKnuckls** [comment]
Closing this to better track open issues. This will still be pinned.
