### ISSUE TITLE
Expect delays in merging new PRs

### ISSUE THREAD

**Issue by bombardier-gif** [bombardier-gif/covid-vaccine-booking#434]
Due to the rampant disruption in basic flows after new features,

- New PRs with bug fixes would be merged ASAP
- New PRs which make the basic flow/setup easy for all would be merged fast

New ways of automating OTP, adding complicated filters, second dose optimisations would be kept aside till someone other than the author vouches for the PR.

Please bear with me as a lot of people are using the script, any disruptions cause lot of confusion and wasted time. 

At this moment the current state works very smoothly for booking the 1st dose, anywhere in the city. The assumption is that the people who are using this script are desperate/ helping out people who are desperate for getting vaccinated.

Happy to know your thoughts on this.

**Comment by Nakul93** [comment]
Yeah totally agree with this. Lets just merge PRs with bug fixes first.

**Comment by shivaslifzz** [comment]
But one serious issue which I observed today is Telegram channels are able to push the alerts 20-30 seconds before our script identifies the slots, because of this most of the times we are missing the slots

I explained the issues with complete details #433

**Comment by 6mxo89sqh** [comment]
@bombardier-gif #318 is open since 8 days and lot of folks have tried it. You must have see in many issues that they are pasting screenshots with it. The problem with such long delays is that the author has to keep merging (and resolving conflicts). 

What do you think?

**Comment by rooniks** [comment]
> Due to the rampant disruption in basic flows after new features,
> 
> * New PRs with bug fixes would be merged ASAP
> * New PRs which make the basic flow/setup easy for all would be merged fast
> 
> New ways of automating OTP, adding complicated filters, second dose optimisations would be kept aside till someone other than the author vouches for the PR.
> 
> Please bear with me as a lot of people are using the script, any disruptions cause lot of confusion and wasted time.
> 
> At this moment the current state works very smoothly for booking the 1st dose, anywhere in the city. The assumption is that the people who are using this script are desperate/ helping out people who are desperate for getting vaccinated.
> 
> Happy to know your thoughts on this.

@bombardier-gif Even for people who are desperate, the current master branch is broken. It still uses the expired/deleted kvdb bucket: `ASth4wnvVDPkg2bdjsiqMN` in case of automated OTPs. What's the immediate solution there?

**Comment by shivaslifzz** [comment]
> @bombardier-gif #318 is open since 8 days and lot of folks have tried it. You must have see in many issues that they are pasting screenshots with it. The problem with such long delays is that the author has to keep merging (and resolving conflicts).
> 
> What do you think?

bro still i am seeing rate limit issue I using the code from rate-limit-ip-restrictions branch 

![image](https://user-images.githubusercontent.com/61616987/120467498-df72a580-c3bd-11eb-8422-9d84de21c2a6.png)

**Comment by bombardier-gif** [comment]
> ASth4wnvVDPkg2bdjsiqMN

Oh no. Someone added a key to write on the bucket.

**Comment by bombardier-gif** [comment]
> > @bombardier-gif #318 is open since 8 days and lot of folks have tried it. You must have see in many issues that they are pasting screenshots with it. The problem with such long delays is that the author has to keep merging (and resolving conflicts).
> > What do you think?
> 
> bro still i am seeing rate limit issue I am using the code from rate-limit-ip-restrictions branch
> 
> ![image](https://user-images.githubusercontent.com/61616987/120467498-df72a580-c3bd-11eb-8422-9d84de21c2a6.png)

The rate limiter is pretty tough to bypass.

**Comment by rooniks** [comment]
@shivaslifzz 
I'd recommend to be polite to the server and hit one call every 6 seconds. i.e. if you have 3 pin codes in your preferences, give the update frequency as 18 seconds. If you have just district, then again 6 seconds. Works seamlessly. Booked multiple slots for friends and family.

**Comment by shivaslifzz** [comment]
> @shivaslifzz
> I'd recommend to be polite to the server and hit one call every 6 seconds. i.e. if you have 3 pin codes in your preferences, give the update frequency as 18 seconds. If you have just district, then again 6 seconds. Works seamlessly. Booked multiple slots for friends and family.

bro this is not about the main branch we are talking different branch were ip limit issue was fixed by using docker

**Comment by AK-1005** [comment]
> > @shivaslifzz
> > I'd recommend to be polite to the server and hit one call every 6 seconds. i.e. if you have 3 pin codes in your preferences, give the update frequency as 18 seconds. If you have just district, then again 6 seconds. Works seamlessly. Booked multiple slots for friends and family.
> 
> bro this is not about the main branch we are talking different branch were ip limit issue was fixed by using docker

HI! How did you manage to fix the IP limit issue using Docker?

**Comment by shivaslifzz** [comment]
> > > @shivaslifzz
> > > I'd recommend to be polite to the server and hit one call every 6 seconds. i.e. if you have 3 pin codes in your preferences, give the update frequency as 18 seconds. If you have just district, then again 6 seconds. Works seamlessly. Booked multiple slots for friends and family.
> > 
> > 
> > bro this is not about the main branch we are talking different branch were ip limit issue was fixed by using docker
> 
> HI! How did you manage to fix the IP limit issue using Docker?

please go through this doc and read me file 
https://github.com/6mxo89sqh/covid-vaccine-booking/tree/rate-limit-ip-restrictions/docs

**Comment by bombardier-gif** [comment]
I am closing this ticket for managing new tickets well. Please continue your conversation
