### ISSUE TITLE
Cowin API throwing 204 status 

### ISSUE THREAD

**Issue by lohithvadde** [bombardier-gif/covid-vaccine-booking#435]
Cowin API is throwing 204 status, just like 429 or 403. If we restart it immediately, it again throws 204 in <5 seconds.

How long do we need to wait and restart after getting 204 ? 

Is there a way to handle this ?

**Comment by 6mxo89sqh** [comment]
@ggoel1998 You might be facing this. I guess this recently came up.

**Comment by lohithvadde** [comment]
My code is exiting with status 204 at regular intervals. The interval varies from 1 sec - 11 min. 
If I restart the program with in no time, it immediately exits again with 204 status.

I tried this multiple things but nothing worked out.

> Changing IP using VPN
> Trying to login with different mobile numbers
> Exception` handling of 204 (Ignoring 204) and continuing
> Changing` the secret
> Increasing the sleep time to 10 sec (FYI, I am just using search by just 1 district ID, pin codes are no where in the picture)

Also, I observed that if I login after ~20 mins, it runs fine for first 10 mins and again throws the 204 after that. 
Not sure, how it is going to behave if we forcefully login again at 9.5 min. Still need to test this out properly ! But for now, even this doesn't seem to be working.

**Comment by 6mxo89sqh** [comment]
@ggoel1998  @lohithvadde , i ran for 2 hours and i m still not getting this.

**Comment by debashisdash94** [comment]
I am also facing the same. Please find the below screenshot.

![image](https://user-images.githubusercontent.com/79236490/120483229-87449f00-c3cf-11eb-9f97-521fa55f72ae.png)

**Comment by 6mxo89sqh** [comment]
@debashisdash94 what was your observation for 204?

Which Search Option are you using? Pincode/District?
What is your refresh frequency?
For @ggoel1998, it was automatically resuming after a minute or so, for @lohithvadde it wasn't resuming until 10 minutes. What is the behaviour with yours?
Is it resuming after login again?

**Comment by lohithvadde** [comment]
Anyone else facing this issue ?

**Comment by shailesh** [comment]
Try without VPN ? 

Were you able to get the OTP though or stuck at it?

**Comment by lohithvadde** [comment]
I tried with vpn and with out.
But anyways, its not throwing 204 anymore. It's 403 now and its resolved.
