### ISSUE TITLE
How Does Telegram Get Instant Notification?

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#436]
Anyone who has an idea about how are they tracking the availability of slots where they are not fired up with rate limit and they instantly notify users as reported by many. I've observed this too.

Depenediencies: #433 #407 #397 #375 #362 #342 #329 #321 #306 #288 #242 #235

c.c @bombardier-gif @BumpyKnuckls @Nakul93

**Comment by Nakul93** [comment]
Its like those alerts are not polling based, as soon as the slots open up the notification is instantly pushed.

**Comment by shailesh** [comment]
How does this happen btw, by any idea?

**Comment by adityap27** [comment]
> Its like those alerts are not polling based, as soon as the slots open up the notification is instantly pushed.

![image](https://user-images.githubusercontent.com/30194525/120446902-a2031d80-c3a7-11eb-9e8d-6948ca77c83b.png)

As per their website description, it is polling.

**Comment by adityap27** [comment]
Will this `Cache-control: no-cache` in request header help ?

**Comment by shailesh** [comment]
Since Telegram is open source, have they also open-sourced their notification script? Would be interesting to look into their way of polling.

**Comment by Nakul93** [comment]
> Will this `Cache-control: no-cache` in request header help ?

Interesting, have you tried this yourself

**Comment by adityap27** [comment]
> > Will this `Cache-control: no-cache` in request header help ?
> 
> Interesting, have you tried this yourself

nope, I haven't tried in this api but tried in my other projects.

**Comment by shailesh** [comment]
I had tried all the headers that Cowin uses in their browser Network call. Did not work for me though.

**Comment by adityap27** [comment]
> My question is how are they not getting rate limited, how often and how many requests are they sending. They have a channel for every district in country( for both under45 and above45)

They (under45 telegram bots) are having 2 advantages.
1. not getting rate limited.
2. instant notification (earlier than we get to see in this script)

Searched on github and their webpages, wasn't able to find any open-source repository.

**Comment by adityap27** [comment]
@Nakul93 @shailesh ,
For not getting rate limited, they **might** be rotating IP Addresses by using some proxy list.

References:
1. https://www.scrapehero.com/how-to-rotate-proxies-and-ip-addresses-using-python-3/
2. https://codelike.pro/create-a-crawler-with-rotating-ip-proxy-in-python/
there are tons of other examples on internet.

**Comment by shivaslifzz** [comment]
https://covialerts.in/ is even faster than the under45 telegram channel

**Comment by salian** [comment]
Those notifier channels are also getting data from same endpoints; calendarByDistrict or calendarByPin. This may be through cloudfront or by skipping CF and accessing the underlying server. 

Time shown on telegram is the time of response, time shown in script is the time of request and not response. So there may be a slight difference there, if the server is slow in responding.

If you want a faster response you can host your script on an AWS instance. The telegram notifier bots are polling from AWS with different IP addresses.

Lastly if I understand correctly, the `alert_freq` value tells us the update frequency for that endpoint. So in general pincode endpoints have lower `alert_freq` than the same district endpoint covering the same center. This would mean polling pincode endpoints is better if you want instant updates. The tradeoff is that larger number of requests mean hitting the rate limit sooner. So it's a good strategy for notifier bot with access to multiple accounts but a bad strategy for booking a slot on a particular account.

The request-based rate limit is handled in Cloudfront, while 15 min timeout is handled on the server. So if you manage to access the server directly (not through CF) then it might also help with not getting rate limited.

**Comment by shailesh** [comment]
I had an idea of hosting this over AWS Lambda as far as I can see a lot of telegram bots running over AWS Lambda for slot notifier.

**Comment by Nakul93** [comment]
If we are hosting it on AWS then we will probably need a app as a front end

**Comment by Nakul93** [comment]
@salian what do you think, which API are they using public/protected ? Protected API can’t be accessed without a token

**Comment by adityap27** [comment]
> @salian what do you think, which API are they using public/protected ? Protected API can’t be accessed without a token

https://github.com/cowinapi/developer.cowin/issues/189

**Comment by shailesh** [comment]
> If we are hosting it on AWS then we will probably need a app as a front end

Correct, but initially I was thinking for testing purposes or self. in this case, I would pick all values from JSON which I would store in an s3 bucket. 

I know this will be complicated for everyone like as you mentioned where we will need we client to update individual JSON. A lot of work just to bypass the rate limit. And even not sure if hosting on AWS would actually bypass.

**Comment by shailesh** [comment]
> @salian what do you think, which API are they using public/protected? Protected API can’t be accessed without a token

But @Nakul93 even public API doesn't give correct information because of cache thing. No real-time data from PUblic API. 

BUt correct how would they be doing then passing someone else number for fetching info for respective notifier info. This is interesting.

**Comment by salian** [comment]
Protected endpoints with multiple logins. 

If you're just looking to get the slot notification then doing it via a specific account is not necessary. There are only ~720 districts in India and the bots don't cover all of them. For individual use, say the CF WAF is rate-limiting you at 100 calls every 5 minutes, and you cannot access the server directly, then you just need to cycle through 3 accounts to get a continuous stream of 1-second interval data. 

For this to work, we have to separate calendar requests (from a cycled set of accounts) and once you get availability, finally book via the actual recipient's account.

One could even just use the telegram channel as the input for the availability signal, which then triggers the booking. It's a large change, and has a black box external dependency on the telegram channels, but if you are really aggrieved then probably that's something to try (as a different project). 

Having a central availability callback server would have the added benefit that CoWin servers are not hammered by everyone who is using the script.

**Comment by shailesh** [comment]
This is interesting.

**Comment by 6mxo89sqh** [comment]
> If we are hosting it on AWS then we will probably need a app as a front end

Frontend app is not needed i guess. In your first run you can store your json and exit after a minute, in the next run, your json should be picked up. No need for tty in that case. (thats the reason for me to add --no-tty). I run on aws only. 


> Will this `Cache-control: no-cache` in request header help ?

I have tried with no-cache headers, it doesn't help. (Still it is no harm in adding those headers).

**Comment by Nakul93** [comment]
> > If we are hosting it on AWS then we will probably need a app as a front end
> 
> Frontend app is not needed i guess. In your first run you can store your json and exit after a minute, in the next run, your json should be picked up. No need for tty in that case. (thats the reason for me to add --no-tty). I run on aws only.
> 
I was thinking of having a common app so that everyone can use it, not everyone would be comfortable for setting up AWS account just to run the script

**Comment by 6mxo89sqh** [comment]
> > > If we are hosting it on AWS then we will probably need a app as a front end
> > 
> > 
> > Frontend app is not needed i guess. In your first run you can store your json and exit after a minute, in the next run, your json should be picked up. No need for tty in that case. (thats the reason for me to add --no-tty). I run on aws only.
> 
> I was thinking of having a common app so that everyone can use it, not everyone would be comfortable for setting up AWS account just to run the script

Oh! Nice idea.

**Comment by shivaslifzz** [comment]
Running in aws giving me faster booking than the telegram channels currently I am using AWS EC2 instance(ubuntu)

![image](https://user-images.githubusercontent.com/61616987/120518482-42c8fb80-c3ef-11eb-82e0-df09c15ddd50.png)

**Comment by shailesh** [comment]
This is a nice research!

**Comment by Nakul93** [comment]
@saurabh1069 I agree. 
Btw Ive seen that using `findByPin` /  `findByDistrict` API has less delay compared to calendarbyDistrict /Pin. Need to investigate more on this

**Comment by shivaslifzz** [comment]
> > Running in aws giving me faster booking than the telegram channels currently I am using AWS EC2 instance(ubuntu)  UTC timestamp
> > ![image](https://user-images.githubusercontent.com/61616987/120518482-42c8fb80-c3ef-11eb-82e0-df09c15ddd50.png)
> > telegram channels sent the notification at 10:02:24, and our code book the slot yet 10:02:25 may be even faster
> > ![image](https://user-images.githubusercontent.com/61616987/120520143-13b38980-c3f1-11eb-941a-f54600284a31.png)
> > @shailesh @salian @bombardier-gif  look this complete 150 slots are available
> 
> Everyone can't use EWS..it's require credit/Debit card for setting up..in case you over use instance they will be sending thousands of bill..we still must find out real issue it used to book earlier some changes made API decently which causing this....

Aws ec2 free tier instance is free for first 1year

**Comment by pjainevdy** [comment]
@shivaslifzz - I am getting rate limit when running on aws ec2 instance even when the refresh is set at 12?

**Comment by shivaslifzz** [comment]
> @shivaslifzz - I am getting rate limit when running on aws ec2 instance even when the refresh is set at 12?

cowin has changed the refreshes for 10 per login if you made more than 10 refreshes than your ip will be blocked till the next login/otp

**Comment by shivaslifzz** [comment]
> @shivaslifzz - I am getting rate limit when running on aws ec2 instance even when the refresh is set at 12?

for now you can use the code from #449 but only draw back is it's public API

**Comment by 6mxo89sqh** [comment]
Looks like #452 (single date search) has made it to the telegram notifications

**Comment by shailesh** [comment]
Ohh Amazing 👍

**Comment by stockguy78** [comment]
Amazed to see Telegram gave me alert before I could see it on COWIN portal. after getting alert, I immediately checked and It was not there. After 2-3 seconds I again checked and there were 250 open slots... Curious to understand how they do it ?

**Comment by shailesh** [comment]
I had this read somewhere in the blog that they use https://nordvpn.com/ a paid service to bypass this. let me recall the blog here.

**Comment by shailesh** [comment]
Can we look into this one?
https://github.com/xsreality/covid19-vaccine-tracker/issues/24 : Use AWS Lambda to handle API rate limits

https://github.com/xsreality/covid19-vaccine-tracker/pull/25 : Add AWS Lambda support to make API calls

Same I had a thought earlier : https://github.com/bombardier-gif/covid-vaccine-booking/issues/436#issuecomment-852913418

**Comment by shailesh** [comment]
`I just confirmed the limits, the whole cowin system is changed. Now, one can have only a maximum of 20 requests per session, if one goes more than that which means if one makes 20 requests in a row one will be logged out. Besides this, there's an overall boundation of 100 requests per 5 mins. So, which means if one re-login and make more than 20 requests and one repeat this thing within 5mins (20*5) = 100 requests in 5 mins (with the same IP) One will be blocked again.`

Any logic/thoughts here?

**Comment by amit8-88** [comment]
> `I just confirmed the limits, the whole cowin system is changed. Now, one can have only a maximum of 20 requests per session, if one goes more than that which means if one makes 20 requests in a row one will be logged out. Besides this, there's an overall boundation of 100 requests per 5 mins. So, which means if one re-login and make more than 20 requests and one repeat this thing within 5mins (20*5) = 100 requests in 5 mins (with the same IP) One will be blocked again.`
> 
> Any logic/thoughts here?

I believe these limits are not applicable on /v2/appointment/sessions/public/findByDistrict api  and you can leverage this.  Lets say you make 3 calls for 3 different dates for this api in an interval of 5 seconds. You will be making 15 calls in 1 min and 75 calls in 5 mins. 
But yes, the limitation is there,  you can only query slots for next 3 days.

**Comment by 6mxo89sqh** [comment]
> `I just confirmed the limits, the whole cowin system is changed. Now, one can have only a maximum of 20 requests per session, if one goes more than that which means if one makes 20 requests in a row one will be logged out. Besides this, there's an overall boundation of 100 requests per 5 mins. So, which means if one re-login and make more than 20 requests and one repeat this thing within 5mins (20*5) = 100 requests in 5 mins (with the same IP) One will be blocked again.`
> 
> Any logic/thoughts here?

20 requests per session is not applicable to findBy* APIs. 

Two options i can think of: 1) Use public always for calendar api 2) ask user which api to use.

**Comment by saurabh1069** [comment]
> > `I just confirmed the limits, the whole cowin system is changed. Now, one can have only a maximum of 20 requests per session, if one goes more than that which means if one makes 20 requests in a row one will be logged out. Besides this, there's an overall boundation of 100 requests per 5 mins. So, which means if one re-login and make more than 20 requests and one repeat this thing within 5mins (20*5) = 100 requests in 5 mins (with the same IP) One will be blocked again.`
> > Any logic/thoughts here?
> 
> 20 requests per session is not applicable to findBy* APIs.
> 
> Two options i can think of: 1) Use public always for calendar api 2) ask user which api to use.

Yes just tested Re Assigment logic works when rate Limited by Cowin only when  don't use calender API. These seems Amazing..:)
![image](https://user-images.githubusercontent.com/26090183/120820450-302aff80-c572-11eb-9240-f3082d756774.png)

**Comment by Nakul93** [comment]
So I just did a test and observed that this findByPin API is pretty good I didn't get rate limited even with a refresh freq of 3secs.

**Comment by shailesh** [comment]
> So I just did a test and observed that this findByPin & findByDistrict API is pretty good I didn't get rate limited even with a refresh freq of 3secs.

any cache issue on these? are we able to verify this?

**Comment by Nakul93** [comment]
> > So I just did a test and observed that this findByPin & findByDistrict API is pretty good I didn't get rate limited even with a refresh freq of 3secs.
> 
> any cache issue on these? are we able to verify this?

Haven’t verified that yet

**Comment by amit8-88** [comment]
> > > So I just did a test and observed that this findByPin & findByDistrict API is pretty good I didn't get rate limited even with a refresh freq of 3secs.
> > 
> > 
> > any cache issue on these? are we able to verify this?
> 
> Haven’t verified that yet. But since we are using protected APIs caching shouldn’t be a problem I’m assuming

findBy* apis responses are not cached. Have verified this.

**Comment by nolimits0007** [comment]
I selected Date 05Jun21 they released slot on 06jun21 and vice versa . We have to do something about this date logic.
This thing Sucks. Rate limit with date selection sucks.!!!!

**Comment by shivaslifzz** [comment]
> I selected Date 05Jun21 they released slot on 06jun21 and vice versa . We have to do something about this date logic.
> This thing Sucks. Rate limit with date selection sucks.!!!!

Use wisely according to the trend or else use aws with 2 ec2 instances and Elastic IP you can beat the rate limit but it's chargeable

**Comment by bombardier-gif** [comment]
I am closing this ticket for managing new tickets well. Please continue your conversation

**Comment by nolimits0007** [comment]
> > I selected Date 05Jun21 they released slot on 06jun21 and vice versa . We have to do something about this date logic.
> > This thing Sucks. Rate limit with date selection sucks.!!!!
> 
> Use wisely according to the trend or else use aws with 2 ec2 instances and Elastic IP you can beat the rate limit but it's chargeable

@shivaslifzz can u help using aws with 2 ec2 instances and Elastic ip.

**Comment by 6mxo89sqh** [comment]
> I selected Date 05Jun21 they released slot on 06jun21 and vice versa . We have to do something about this date logic.
> This thing Sucks. Rate limit with date selection sucks.!!!!

ensure you have correct timezone. 
`export TZ=Asia/Kolkata`

**Comment by nolimits0007** [comment]
> > > > I selected Date 05Jun21 they released slot on 06jun21 and vice versa . We have to do something about this date logic.
> > > > This thing Sucks. Rate limit with date selection sucks.!!!!
> > > 
> > > 
> > > Use wisely according to the trend or else use aws with 2 ec2 instances and Elastic IP you can beat the rate limit but it's chargeable
> > 
> > 
> > @shivaslifzz can u help using aws with 2 ec2 instances and Elastic ip.
> 
> Are you familiar with aws and its charges ?

I am not familiar but if u tell I will become familiar.

**Comment by 6mxo89sqh** [comment]
@nolimits0007 , plz try the updated guide here -> https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/docs/AWS.md

**Comment by nolimits0007** [comment]
> https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/docs/AWS.md

@6mxo89sqh thank u so much for explaining . I am trying let see what happens.

**Comment by nolimits0007** [comment]
@6mxo89sqh how to download aws.template for uploading. the page doesn't show any download option.

**Comment by nolimits0007** [comment]
@6mxo89sqh what should be the name of stack which i am  creating.

**Comment by nolimits0007** [comment]
@6mxo89sqh is this ok.

<img width="1101" alt="Screenshot 2021-06-05 at 15 50 24" src="https://user-images.githubusercontent.com/84738436/120888472-1d6a0680-c616-11eb-9fb8-b6825c9573d0.png">

**Comment by 6mxo89sqh** [comment]
Yup it's fine

**Comment by nolimits0007** [comment]
> Yup it's fine

@6mxo89sqh keep helping , i am trying to complete it.

**Comment by nolimits0007** [comment]
> > Yup it's fine
> 
> @6mxo89sqh keep helping , i am trying to complete it.

Is it k.

<img width="1412" alt="Screenshot 2021-06-05 at 16 11 51" src="https://user-images.githubusercontent.com/84738436/120889024-e9441500-c618-11eb-8a4f-365799f0073e.png">

**Comment by nolimits0007** [comment]
@6mxo89sqh I am not able to do this step.

Connect to your instance based. Username is ec2-user on windows. Can u plz elaborate

**Comment by 6mxo89sqh** [comment]
Here : https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html

**Comment by nolimits0007** [comment]
> Here : https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html

@6mxo89sqh something like this is coming.

<img width="674" alt="Screenshot 2021-06-05 at 17 21 07" src="https://user-images.githubusercontent.com/84738436/120890785-89526c00-c622-11eb-8ea3-530fc669321f.png">

**Comment by Nakul93** [comment]
> > Here : https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html
> 
> @6mxo89sqh something like this is coming.
> 
> <img alt="Screenshot 2021-06-05 at 17 21 07" width="674" src="https://user-images.githubusercontent.com/84738436/120890785-89526c00-c622-11eb-8ea3-530fc669321f.png">

Press accept

**Comment by 6mxo89sqh** [comment]
Accept. You may connect with me on [this link](https://discord.gg/UDzShm7X)

**Comment by nolimits0007** [comment]
> Accept. You may connect with me on [this link](https://discord.gg/UDzShm7X)

@6mxo89sqh Login how?

<img width="674" alt="Screenshot 2021-06-05 at 17 26 22" src="https://user-images.githubusercontent.com/84738436/120890928-67a5b480-c623-11eb-9e90-0c44146d5e11.png">

**Comment by nolimits0007** [comment]
@Nakul93 Can u Help Plz. how to login further & what to do.

**Comment by Nakul93** [comment]
> Here : https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html

@nolimits0007 did you follow all the steps here.
Username would be your instance name

**Comment by nolimits0007** [comment]
> > Here : https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html
> 
> @nolimits0007 did you follow all the steps here.
> Username would be your instance name

@Nakul93 how to know my instance name.

**Comment by 6mxo89sqh** [comment]
Username is ec2-user
If u have loaded the key file, it should connect by entering user name as ec2-user and pressing enter.

**Comment by nolimits0007** [comment]
> Username is ec2-user
> If u have loaded the key file, it should connect by entering user name as ec2-user and pressing enter.

@6mxo89sqh No i have not loaded . From where to load it and from where to get it.

**Comment by 6mxo89sqh** [comment]
Connect with me on [this link](https://discord.gg/UDzShm7X), I will guide you there. It seems u have missed a few instructions for connecting.

**Comment by nolimits0007** [comment]
> Connect with me on [this link](https://discord.gg/UDzShm7X), I will guide you there. It seems u have missed a few instructions for connecting.

it is asking for my email & password
