### ISSUE TITLE
Getting API: Not Found Error

### ISSUE THREAD

**Issue by ranadeepsingh** [bombardier-gif/covid-vaccine-booking#439]
The storage_url seems to be deactivated. Getting the following error:
"error fetching OTP API:Not Found"

**Comment by beastmaster-bit** [comment]
+1

**Comment by shailesh** [comment]
Create your own kvdb bucket would help you fix this. http://kvdb.io/

**Comment by AanchalV** [comment]
> The storage_url seems to be deactivated. Getting the following error:
> "error fetching OTP API:Not Found"

Me too!

**Comment by nayakkiranraj** [comment]
Creating new bucket and updating new bucket code both on phone and utils.py actually works

**Comment by beastmaster-bit** [comment]
It works thanks..

**Comment by beastmaster-bit** [comment]
Those who end up coming here - visit the issue #[417 ](https://github.com/bombardier-gif/covid-vaccine-booking/issues/417) for details on resolution

**Comment by bombardier-gif** [comment]
Someone added a secret key to write to the bucket. It was a public bucket so people can do all kinds of mischief. 

A PR has been merged which lets you mention your own key. Creating a bucket in kvdb is free.

**Comment by sayantan3** [comment]
I think there are over use of key that is why they key is not working. It cab be fix.
Go to, src -> utils.py -> line number 1042 -> https://kvdb.io/
[you just need to generate your own id by just giving your mail id on kvdb site]
Just need to put the generated key value to the utils.py (1042 line) as well as your phone automaton.
Tested on Mac and iPhone (shortcut app) works flawlessly.

**Comment by ranadeepsingh** [comment]
Yes, true. Thank you for your comments.
Solution:
1. Create a new bucket on https://kvdb.io/, only need to enter email address and needs no setup.
2. Then use the new bucket name eg.. "https://kvdb.io/<bucket_name>/<mobile_no>" to change in src/utils.py and in the web hook link

**Comment by umeshrege** [comment]
To permanently resolve this, I have created a new branch where variablised the bucket key and is taken as input from user on the 1st run.
https://github.com/umeshrege/covid-vaccine-booking/tree/kvdb
You can use exe file for windows user. Recommended to over-write current json file, so that the prog does not ask for bucket key on every run.
