### ISSUE TITLE
Why the requirement to have KVDB Bucket?

### ISSUE THREAD

**Issue by Superfrag** [bombardier-gif/covid-vaccine-booking#441]
If I want to enter OTP manually, I'm still forced to enter a KVDB bucket value. Why is this enforced for people who do not want to setup OTP automation? 

For now we can enter any rubbish value to bypass the requirement, but if one opts out of OTP automation, they should not be asked to enter a KVDB bucket value.

**Comment by rooniks** [comment]
Yes, It was a miss. I'll rectify this.

**Comment by rooniks** [comment]
Pull request: https://github.com/bombardier-gif/covid-vaccine-booking/pull/442

**Comment by rooniks** [comment]
@Superfrag 
Just out of curiosity: Why are you not opting for automated OTPs? Isn't it tedious to keep entering the OTPs manually after every 15 minutes? Have you or your friends been able to book a slot using the manual OTP flow?

**Comment by Superfrag** [comment]
@rooniks So if you know roughly at what times the slots will open up, in Mumbai a lot of the hospitals' slots open up at roughly the same time, you can start the script just ahead of that time, and get the appointment successfully. In this way, some friends have been able to get their slots. Obviously automated OTP is superior, but it's not a must have.

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
> @rooniks So if you know roughly at what times the slots will open up, in Mumbai a lot of the hospitals' slots open up at roughly the same time, you can start the script just ahead of that time, and get the appointment successfully. In this way, some friends have been able to get their slots. Obviously automated OTP is superior, but it's not a must have.

Tangentially related to what @Superfrag said #https://github.com/abizerlokhandwala/Cowin-Notification-Service/issues/11
It is useful to have historical data for those CenterID that open erratically, not completely randomly , but the opening time tends to drift for some unknown magical reason.
