### ISSUE TITLE
[Need inputs] KVDB alternatives

### ISSUE THREAD

**Issue by bombardier-gif** [bombardier-gif/covid-vaccine-booking#444]
The main problem with kvdb is that it uses the concept of buckets which can be deleted/restricted by anyone and it makes it unusable for everyone.

The advantages of kvdb is that we dont have to maintain our servers. Just a script lets us implement the autoread of OTP

I wanted to know alternatives to make our lives easier.

1. keyvalue.xyz seems to be down.
2. https://meeiot.org/?p=home.php seems to be a decent platform but dont know about its uptime

Any more alternative?

**Comment by bombardier-gif** [comment]
http://keyvalue.immanuel.co/ is another interesting one

**Comment by bombardier-gif** [comment]
I prefer immanuel because its straightforward, no concept of buckets, and no listing allowed, so one cannot list the keys in the store

**Comment by bbalegere** [comment]
restdb.io

**Comment by bombardier-gif** [comment]
> restdb.io

seems to be limited for free version https://restdb.io/pricing/
1qps is too low

**Comment by bombardier-gif** [comment]
So my initial analysis

- http://keyvalue.immanuel.co/
- Pros: is very simple and does not have way to list the keys
- Cons: I was not able to set the value with spaces in it (the sms body has spaces in it)

https://www.meeiot.org/
- Pros: Simple and works e2e
- Cons: It does not support TTL, and also others can list the keys: workaround is to delete the key once it has been read.



I will wait till evening for more inputs, and then will share a PR on it.

It will be a breaking change and need changes in App, and documentation. So want to discuss with community before proceeding.

**Comment by shailesh** [comment]
https://keyvalue.xyz/

Swagger/API doc here for above: https://app.swaggerhub.com/apis-docs/KVaaS/KVaaS/1.0.0

They claim that this is free and forever. 

Repo: https://github.com/kvaas

**Comment by shailesh** [comment]
http://keyvalue.immanuel.co/ 

This is also god though.

**Comment by bombardier-gif** [comment]
@shailesh I liked keyvalue.xyz but the system does not seem to be up. Can you try its API and let me know?

**Comment by 6mxo89sqh** [comment]
Are you considering GCP Firestore and Datastore? Pricing [here](https://cloud.google.com/datastore/pricing). Above the free usage, they give $300 for free trial.

**Comment by bombardier-gif** [comment]
I would avoid paid options as much as possible.

**Comment by 6mxo89sqh** [comment]
> I would avoid paid options as much as possible.

GCP's free offering is higher than KVDB. KVDB 10K operations & 10MB in free trial. GCP is giving 20K per day and 1GB storage. (Storage-wise 1GB should be awesome). If 20K writes per day is fine, we should be good with google's free offering.

**Comment by Nakul93** [comment]
@6mxo89sqh do you have GCP free tier account. Also how about using S3 bucket?

**Comment by bombardier-gif** [comment]
So I used to pay for kvdb myself. The problem in such solutions is that usually we would have to put a credit card and any mischief might rack up costs for the person.
There are some solutions like privacy.com for creating virtual credit cards and all but overall I am wary of such paid solutions.

**Comment by 6mxo89sqh** [comment]
In GCP, you can disable billing. This will ensure you are never charged.

**Comment by Nakul93** [comment]
One problem with GCP is that it doesn't accept credit cards with 3D authentication.

**Comment by 6mxo89sqh** [comment]
Btw, I think the current state Is good where we ask our users to enter kvdb.io key. I recommend to wait and see if users demand an easy alternative.

**Comment by bombardier-gif** [comment]
I do agree that current state is not bad and people can also use manual otp.

**Comment by Nakul93** [comment]
Can't we just secure the KVDB account by using the secret key so that no can access and delete the bucket?

**Comment by bombardier-gif** [comment]
I reached out to the customer support. Thats in their roadmap :|

**Comment by Nakul93** [comment]
> I reached out to the customer support. Thats in their roadmap :|

Great, till then I guess asking the users to enter their own kvdb key seems reasonable if they want auto OTP read.

**Comment by pradiptabasu** [comment]
Back4App (https://www.back4app.com/)

**Comment by PatelTilak** [comment]
> Back4App (https://www.back4app.com/)

Free Plan provides 10K hits per month. That seems too less.

**Comment by PatelTilak** [comment]
Is #425 still in the list ?

Only downside that I see is that It does not have Jazzy Landing Page & provides only the bare minimum functionality of storing & retrieving Key Value Pair 😄

**Comment by shailesh** [comment]
> @shailesh I liked keyvalue.xyz but the system does not seem to be up. Can you try its API and let me know?

Yup this is not up and unable to test it out.

**Comment by optimusprimenumber** [comment]
i've had dedicated hosting for years which i don't really use. I've made an api which basically posts and gets from a redis instance. 

Examples are below

GET : http://ashwini.best/{keyname} to get the value in plain text (this works with the existing python code since it expects plain text)

PUT : http://ashwini.best/{keyname} with body containing the value in plain text (again, this is how the docs want the user to submit the otp text to the key value db)

------------------------------------------

Pros
------------

- You get a dedicated developer keeping this service up  as well as using my own money for hosting costs (to a reasonable degree - i'm estimating i'll cover up to to 60-70 dollars per month for a year)

- Excellent support (i'm on sabbatical for a year and basically have a lot of time to kill) so you will get new enhancements (like TTL) really fast


Cons
------------------

- Existing cloud services which are designed for this might be more reliable to unexpected things like load blowing up unexpected
- I will only keep this service online for a year from my own pocket (and if monthly hosting costs exceed 70 dollars, we will either need to find some way to keep costs down or raise some money)
- I'm a random guy (can i be trusted to keep my word? a valid concern)


Some info about me, i'm taking a year off from my programming job due to some personal problems and since i will have a lot of time, i wanted to contribute to this project (since i used it successfully to get a vaccination booking, thanks for that!). I also wanted to study performance aspects of nginx and redis so i thought this is a great way for me to learn by doing as well as contribute back.

**Comment by pradiptabasu** [comment]
Can KvDB Pro be bought with Credit cards issued in India ?

**Comment by bombardier-gif** [comment]
yes. I did that

**Comment by bombardier-gif** [comment]
> i've had dedicated hosting for years which i don't really use. I've made an api which basically posts and gets from a redis instance.
> 
> Examples are below
> 
> GET : [http://ashwini.best/{keyname}](http://ashwini.best/%7Bkeyname%7D) to get the value in plain text (this works with the existing python code since it expects plain text)
> 
> PUT : [http://ashwini.best/{keyname}](http://ashwini.best/%7Bkeyname%7D) with body containing the value in plain text (again, this is how the docs want the user to submit the otp text to the key value db)
> 
> ## Pros
> * You get a dedicated developer keeping this service up  as well as using my own money for hosting costs (to a reasonable degree - i'm estimating i'll cover up to to 60-70 dollars per month for a year)
> * Excellent support (i'm on sabbatical for a year and basically have a lot of time to kill) so you will get new enhancements (like TTL) really fast
> * Can support a couple billion requests (i use an estimation on request/response sizes) before i have to start paying more than my fixed cost hosting
> 
> ## Cons
> * Existing cloud services which are designed for this might be more reliable to unexpected things like load blowing up unexpected
> * I will only keep this service online for a year from my own pocket (and if monthly hosting costs exceed 70 dollars, we will either need to find some way to keep costs down or raise some money)
> * average response latency for 500-600 qps is around 1.x second (trying to get this down, and trying to increase throughput as well)
> * I'm a random guy (can i be trusted to keep my word? a valid concern). I'm willing to give the maintainer of this repo, my personal details if that will help.
> 
> Some info about me, i'm taking a year off from my programming job due to some personal problems and since i will have a lot of time, i wanted to contribute to this project (since i used it successfully to get a vaccination booking, thanks for that!). I also wanted to study performance aspects of nginx and redis so i thought this is a great way for me to learn by doing as well as contribute back.

Thanks. At this moment I dont want to add moving components to the system, as we dont have anyone oncall to check the systems. This is largely community driven. We can think of this once we run out of options.
