### ISSUE TITLE
Helping users faster

### ISSUE THREAD

**Issue by 6mxo89sqh** [bombardier-gif/covid-vaccine-booking#445]
Hi @shailesh @bombardier-gif @BumpyKnuckls,

We have lot of issues reported but if you see most of them are help related. Can try creating a community on gitter.im or discord.com server and resolve queries/help instantly? 

This will also help reduce down the issues as **users can resolve amongst them**. 
Users will be happy as they can run their script faster instead of waiting on issue replies on github.

Thoughts?

**Comment by BumpyKnuckls** [comment]
While this is a great suggestion, I am not sure any of us would have the bandwidth to manage the rooms on discord or gitter. I'll also let others chime in their thoughts.

**Comment by shailesh** [comment]
Yes Sure, But for now I'm okay with Git issues, as far we go we can open up one sometime soon if required.

**Comment by bombardier-gif** [comment]
+1 to @BumpyKnuckls Right now we can balance updating our documentation and issues.
