### ISSUE TITLE
&vaccine={vaccine_type} doesn't work anymore. Can someone please confirm?

### ISSUE THREAD

**Issue by warlock2k** [bombardier-gif/covid-vaccine-booking#451]
We will need to filter after making the initial api call.

In the viable_options method, need to add following

```
 if(center["vaccine"] == vaccine_type)
  out = {
    "name": center["name"],
    "district": center["district_name"],
    "pincode": center["pincode"],
    "center_id": center["center_id"],
    "vaccine": session["vaccine"],
    "fee_type": center["fee_type"],
    "available": available_capacity,
    "date": session["date"],
    "slots": session["slots"],
    "session_id": session["session_id"],
  }
  options.append(out)
```

I will work on adding this after someone confirms.

**Comment by nolimits0007** [comment]
> We will need to filter after making the initial api call.
> 
> In the viable_options method, need to add following
> 
> ```
>  if(center["vaccine"] == vaccine_type)
>   out = {
>     "name": center["name"],
>     "district": center["district_name"],
>     "pincode": center["pincode"],
>     "center_id": center["center_id"],
>     "vaccine": session["vaccine"],
>     "fee_type": center["fee_type"],
>     "available": available_capacity,
>     "date": session["date"],
>     "slots": session["slots"],
>     "session_id": session["session_id"],
>   }
>   options.append(out)
> ```
> 
> I will work on adding this after someone confirms.

@warlock2k r u talking about this.  I selected Covaxin but it booked Covishield.

<img width="828" alt="Screenshot 2021-06-03 at 21 51 51" src="https://user-images.githubusercontent.com/84738436/120698998-6febdb80-c4cd-11eb-91bd-28a85054a3e8.png">

**Comment by warlock2k** [comment]
@nolimits0007 Yes.

**Comment by nolimits0007** [comment]
> @nolimits0007 Yes.

Till when this will be resolved. Tomorrow early morning i have to make booking.

**Comment by warlock2k** [comment]
@nolimits0007 You pick this change (#453 ) into your local if it is urgent.

**Comment by nolimits0007** [comment]
> @nolimits0007 You pick this change (#453 ) into your local if it is urgent.

Really i don't know this. Can u hlp

**Comment by 6mxo89sqh** [comment]
@nolimits0007 , When does `vaccine` query param not work?

**Comment by warlock2k** [comment]
![image](https://user-images.githubusercontent.com/45149593/120753792-4eb8d880-c529-11eb-9a4b-61c1763c9f81.png)

**Comment by 6mxo89sqh** [comment]
@warlock2k You are using public API. Can you check in other?

**Comment by Nakul93** [comment]
I think @nolimits0007 pulled your PR @6mxo89sqh where initially you were using Public API. Maybe that was causing this issue. I don't think this is an issue when protected APIs are used.

**Comment by 6mxo89sqh** [comment]
> I think @nolimits0007 pulled your PR @6mxo89sqh where initially you were using Public API. Maybe that was causing this issue. I don't think this is an issue when protected APIs are used.

Yup indeed.

**Comment by warlock2k** [comment]
Yeah my bad, just checked it works fine with protected APIs

**Comment by 6mxo89sqh** [comment]
Thanks @warlock2k !
