### ISSUE TITLE
Resurrect autobook input, to make this an all comprehensive repo

### ISSUE THREAD

**Issue by mrms123** [bombardier-gif/covid-vaccine-booking#455]
In this fork, the auto-book flag has been bypassed and is in an auto-book only mode.

I think there still exists significant value for a fork, that automates OTP, but intimates user when a slot is available - to make the choice (COWIN still has a lot of data errors, and the pin code functionality is buggy).

**Comment by Nakul93** [comment]
So what are you suggesting, to bring back the option of choosing slots manually?

**Comment by mrms123** [comment]
Yeah - just for some cases where you need to select manually. I mean this repo is being more actively developed now than the other one - so probably not a bad thing to have that functionality in there just in case

I've actually made the code changes - will open a PR and tag you

**Comment by Nakul93** [comment]
Tbh the whole point of this is this script is to keep everything automated which increases the chances of a slot getting booked.
Let see what others think do we really want this feature.
I’ll put this to vote.

**Comment by bombardier-gif** [comment]
+1 to Nakul. The whole point of this repo is to automate everything e2e and increase the chance of booking.

if you wait for an input, there is a very high chance that you will miss it. 
Note: Even if you book a particular slot most vaccination centers are flexible with act
