### ISSUE TITLE
Is same due date necessary for everyone in the same booking?

### ISSUE THREAD

**Issue by mrms123** [bombardier-gif/covid-vaccine-booking#458]
`    if all([beneficiary['status'] == 'Partially Vaccinated' for beneficiary in beneficiary_dtls]):
        today=datetime.datetime.today()
        today=today.strftime("%d-%m-%Y")
        due_date = [beneficiary["dose2_due_date"] for beneficiary in beneficiary_dtls]
        dates=Counter(due_date)
        if len(dates.keys()) != 1:
            print(
                f"All beneficiaries in one attempt should have the same due date. Found {len(dates.keys())}"
            )
            os.system("pause")
            sys.exit(1)`

I see that we are enforcing everyone to have the same due date - but on the COWIN portal, I am able to book for cases where both have different due date - but both past due date.
Have we actually tried out this scenario - or just being extra cautious here?

**Comment by Nakul93** [comment]
Short ans is no, it’s not necessary but then I don’t see the point in integrating this feature. Haven’t tried out yet coz this is a rare scenario.
Plus it would add too much complexity to the code just to check if all the selected beneficiaries are past their due date
Most of the accounts have same due date for all their beneficiaries(same age group). So it’s not a urgent feature that’s required.
