### ISSUE TITLE
covid-vaccine-slot-booking.py  NOT WORKING  AFTER NEW CODE DOWNLOAD #URGENT

### ISSUE THREAD

**Issue by supriyo2222** [bombardier-gif/covid-vaccine-booking#460]
Hi , 

python covid-vaccine-slot-booking.py  NOT WORKING  AFTER NEW CODE DOWNLOAD

D:\covid-vaccine-booking-2.0.6\src>python covid-vaccine-slot-booking.py
Traceback (most recent call last):
  File "D:\covid-vaccine-booking-2.0.6\src\covid-vaccine-slot-booking.py", line 9, in <module>
    from ratelimit import disable_re_assignment_feature
  File "D:\covid-vaccine-booking-2.0.6\src\ratelimit.py", line 2, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'

D:\covid-vaccine-booking-2.0.6\src>

**Comment by rajeshmgnair** [comment]
pip install boto3

**Comment by supriyo2222** [comment]
thanks

**Comment by supriyo2222** [comment]
thanks a lot for such quick fix
