### ISSUE TITLE
Rate limited after 20 requests.

### ISSUE THREAD

**Issue by Dugdudada** [bombardier-gif/covid-vaccine-booking#461]
Rate is limited after 20 requests . Changing frequency is also not doing any good.

**Comment by 6mxo89sqh** [comment]
For 'search for seven days', you will be rate limited. try single day search

**Comment by rjrk2010** [comment]
@6mxo89sqh How to do single day search?

**Comment by 6mxo89sqh** [comment]
In the latest version, it should ask you whether you want to do seven day search or single day search.

**Comment by lohithvadde** [comment]
You mean, for single day search there is no rate limit ? Not even throwing any status codes ?? like 429, 403 , 204 etc.,

**Comment by rjrk2010** [comment]
@6mxo89sqh  Thanks, I didn't pull the latest code so didn't saw that option. 
Also, In Single day search also I am seeing the "Rate limited by Cowin"

**Comment by 6mxo89sqh** [comment]
Single day search is ratelimited at 100 request per 5 min

Seven day search is ratelimited at 20 request per session + 100 request per 5 min

**Comment by lohithvadde** [comment]
@6mxo89sqh What's the difference between CALENDAR_URL_DISTRICT and FIND_URL_DISTRICT ?
How do we do 7 day search ? and 1 day search ?
https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/src/utils.py#L13
What should we pass in the date here, for 7 day & 1 day search ?

**Comment by lohithvadde** [comment]
> Single day search is ratelimited at 100 request per 5 min
> 
> Seven day search is ratelimited at 20 request per session + 100 request per 5 min

If we do the single day search with in 100 requests per 5 min, how long can it run with out the need of otp ? 15 mins ??
What's the approximate session time out in this case ?

**Comment by yohannlouis** [comment]
With Single day search - still getting rate limited with 5sec frequency for a single location (pincode or district). Making only 60/100 requests in 5 mins.

**Comment by yohannlouis** [comment]
With Single day search - still getting rate limited with 5sec frequency for a single location (pincode or district). Making only 60/100 requests in 5 mins.

**Comment by gitmnj** [comment]
@6mxo89sqh @bombardier-gif @shailesh can you tell me the changes to make single day option as default in the code and also can you share detailed AWS and Docker using steps

**Comment by 6mxo89sqh** [comment]
> With Single day search - still getting rate limited with 5sec frequency for a single location (pincode or district). Making only 60/100 requests in 5 mins.

Please refer #467

**Comment by 6mxo89sqh** [comment]
> @6mxo89sqh @bombardier-gif @shailesh can you tell me the changes to make single day option as default in the code and also can you share detailed AWS and Docker using steps

Can you please make a create a seperate issue for making default as single day search? 
For aws and docker steps, refer [this](https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/docs/AWS.md).

**Comment by gitmnj** [comment]
@6mxo89sqh ya I'll create but atleast you share it her na

**Comment by 6mxo89sqh** [comment]
> @6mxo89sqh ya I'll create but atleast you share it her na

https://www.github.com/bombardier-gif/covid-vaccine-booking/tree/main/docs/AWS.md

**Comment by gitmnj** [comment]
@6mxo89sqh  do we have to wait 24hrs to generate key pair after successful registration

**Comment by 6mxo89sqh** [comment]
Not sure. Others who have recently tried AWS signup can answer that.

**Comment by gitmnj** [comment]
got it working thankyou @6mxo89sqh

**Comment by shailesh** [comment]
Close this as you were able to run it.
