### ISSUE TITLE
difficulty

### ISSUE THREAD

**Issue by springsmooth** [bombardier-gif/covid-vaccine-booking#465]
bro can u please upload the steps to run your script. I m from a non-technical background. So it is very difficult to follow

**Comment by Nakul93** [comment]
Are you using Windows?

**Comment by bombardier-gif** [comment]
@springsmooth Can you please let us know the things you want clarity on? It could be a nice opportunity to update the readme to make it more readable.
Also if you want something more easy you can try this repo: https://github.com/pallupz/covid-vaccine-booking
It has limited features though

**Comment by springsmooth** [comment]
Yes..I am using windows 10...and I have installed python 3.7 too.As per
readme I run the windows.bat.But after that I don't what to do.
It will be helpful if you write all the steps after downloading the
zip file.
Regards

**Comment by salian** [comment]
https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/README.md are you getting stuck on any step?

**Comment by springsmooth** [comment]
Yes after installing windows.bat what to do?

**Comment by salian** [comment]
Once you run windows.bat it will take some time to set up, after which you should see a prompt asking you to enter the mobile number. Enter the mobile number and continue with the instructions.

If instead you are seeing some error message, then please share the error message here. 
If you can't find any error message, please describe what happens when you run windows.bat

**Comment by shailesh** [comment]
For Windows: https://github.com/bombardier-gif/covid-vaccine-booking/releases/download/v2.0.6/covid-vaccine-slot-booking.exe

For Android: https://github.com/bombardier-gif/covid-vaccine-booking/releases/download/v2.0.6/CoWinOtpRetreiver.apk

If you are asked for a bucket key in any steps then create one from kvdb.io and use it for OTP sync

**Comment by Nakul93** [comment]
> Once you run windows.bat it will take some time to set up, after which you should see a prompt asking you to enter the mobile number. Enter the mobile number and continue with the instructions.
> 
> If instead you are seeing some error message, then please share the error message here.
> If you can't find any error message, please describe what happens when you run windows.bat

Ok so I've tested this but after extracting the python runtime and installing the dependencies it just quits. Its not really able to run the script
