### ISSUE TITLE
Add rate limiting info

### ISSUE THREAD

**Issue by 6mxo89sqh** [bombardier-gif/covid-vaccine-booking#467]
There are too many questions regarding ratelimiting. 

Show ratelimiting related info before selecting districting/pincode.

Update the readme stating what are the ratelimits applicable in what scenario 

Single day: 100 per 5 mins

Seven days: 100 per 5 mins + 20 per session

Also explain how to calculate 100 per 5 min.

**Comment by rjrk2010** [comment]
@6mxo89sqh  Even for a single day I am getting this rate-limited warning after 15 requests. Can anyone else facing this issue.

**Comment by 6mxo89sqh** [comment]
> @6mxo89sqh Even for a single day I am getting this rate-limited warning after 15 requests. Can anyone else facing this issue.

just tried, its working fine. Please take the latest code.

**Comment by 6mxo89sqh** [comment]
@bombardier-gif Idea is to let users know about the rate limit in the script itself so that we don't get less issues on GitHub.
