### ISSUE TITLE
Remove references to IFTTT

### ISSUE THREAD

**Issue by 6mxo89sqh** [bombardier-gif/covid-vaccine-booking#468]
The apk built and being used is super strong. readme has got a lot cluttered. Let's remove IFTTT and all related references from readme and code

If people don't trust this app, they shouldn't trust this code either.

**Comment by 6mxo89sqh** [comment]
@shailesh @Nakul93 @BumpyKnuckls @bombardier-gif thoughts?

**Comment by swaroopbekal** [comment]
I would like to have IFTTT. Free version works fine if you allow it to show pesistant notification.

**Comment by 6mxo89sqh** [comment]
FYI, IFTTT is slow sometimes.

**Comment by bombardier-gif** [comment]
Interesting debate: here are my thoughts:

keeping just APK:
1.  stable for a while
2.  easy to setup 

Other methods:
1. IFTTT: works end to end but needs premium account. Lot of people dont know how to debug the setup. Lot of issues
2. iOS Shortcuts:  Only alternative for iOS people

One way could be
1. remove IFTTT and iOS in the main readme
2. Add them in a wiki page instead, as they are tried and tested and give an option
3. We will treat it as End of life and will not provide fixes at high priority

Thoughts @BumpyKnuckls ?

**Comment by BumpyKnuckls** [comment]
Yeah. I think moving IFTTT and iOS shortcuts to another page in a wiki gets us the best of the both worlds:

- Giving alternate options to those who want it
- Also keeping the README lean.

Nuking them entirely from the codebase and README imo might not be a good idea. Lets keep them, but instead move to another page.

**Comment by nolimits0007** [comment]
@bombardier-gif @BumpyKnuckls @6mxo89sqh @Nakul93  every coder here is great don't remove anything everything is working great don't nuke anybody because of some few people making mistakes.

**Comment by bunduuk** [comment]
For people who cannot book a vaccine slot and there 2nd dose is nearing, and also for people who are not too great in using their device its easier for someone else to book for them, just by asking them to download the ifttt app and sharing the login details, while configuring everything from the ifttt app or website itself. So I believe the ifttt method should not be removed from the readme file.
