### ISSUE TITLE
Unable to book 2nd Dose vaccine

### ISSUE THREAD

**Issue by anupam07ii** [bombardier-gif/covid-vaccine-booking#469]
It asks to delete the first dose administered in order to continue booking. How to rectify that?

**Comment by anupam07ii** [comment]
also unable to reschedule the appointment

**Comment by 6mxo89sqh** [comment]
Did you get first dose certification ?

**Comment by anupam07ii** [comment]
problem sorted for rescheduling, cancel the previous appointment and program works well, how can I get it to re-check for OTP when CoWin retry attempts has reached to its limit?

**Comment by 6mxo89sqh** [comment]
u need to wait.

**Comment by anupam07ii** [comment]
if I interrupt and re-execute the program it starts with a new OTP, I want to keep this running in the loop so that I'm able to book the slot. Currently it checks for 20 times then Cowin retry attempt reached limit message is shown.

**Comment by 6mxo89sqh** [comment]
you are trying seven day search. try fixed date search and see if it helps.

**Comment by salian** [comment]
If you want to minimize number of OTPs, use the option to specify one fixed date like dd-mm-yy, search by district (or district + pin code, but not multiple pin codes), and don't go lower than 5 seconds. This is the simplest way and will trigger an OTP every 15 minutes.

Else if you really want to search weekly, and are comfortable with editing code, you can change the formula for remaining_seconds in covid-vaccine-slot-booking.py line 13 to `190`, and go for an 8 second interval. Avoid multiple pin code search.

`remaining_seconds = payload['iat'] + 190 - int(time.time())`

The second way will trigger an OTP every 3 minutes; be reasonable if you're doing this, and don't leave it on all night.

**Comment by anupam07ii** [comment]
After some initial setup and generating the Json file once, I have automated the code request OTP, Fetch the OTP, and search for slots for a particular Pincode.

@salian will try to use your advice and try to trigger OTP every 15 minutes but the issue being once the limit is reached the program doesn't go back to request for OTP, need to work on that part.

**Comment by shailesh** [comment]
> problem sorted for rescheduling, cancel the previous appointment and program works well, how can I get it to re-check for OTP when CoWin retry attempts has reached to its limit?

I hope this resolves the issue. we do not have any rescheduling or cancellation API in place. One will have to do that manually but yes you might have got the instructions or table shown for already booked.
