### ISSUE TITLE
why random

### ISSUE THREAD

**Issue by uvmittal** [bombardier-gif/covid-vaccine-booking#47]
when booking why does it choose randomly is there a way to choose any

**Comment by BumpyKnuckls** [comment]
It improves the chances of getting a slot.

**Comment by bombardier-gif** [comment]
+1 to @BumpyKnuckls 
_When no of slots are less, it will be avaliable only in particular slots._ : we attempt only the available slots. There are a lot of scripts which automatically attempt the first slot. We have an edge over those scripts. 

_Better to go through all slots and try to book it._: There is no way we can go through those slots. We need to chose one slot and attempt. By the time we book another slot, it would be over. so we need to query again.
