### ISSUE TITLE
Access rules regarding Protected APIs

### ISSUE THREAD

**Issue by Nakul93** [bombardier-gif/covid-vaccine-booking#475]
Guys check this out: https://sandbox.ndhm.gov.in/cowin/

CC: @bombardier-gif @shailesh @6mxo89sqh @BumpyKnuckls

**Comment by 6mxo89sqh** [comment]
Planning to apply?

**Comment by gitmnj** [comment]
litt

**Comment by Nakul93** [comment]
> Planning to apply?

Nah, its for organisations and not individuals. As per this doc it says an individual can only access Public API(rate limited) for using the non rate limited public API and protected API we need to register with them. Thats a bit confusing since we are already using protected APIs.

**Comment by salian** [comment]
It might be useful to have one single server sending out slot availability notifications which everyone can then subscribe to.

**Comment by evioxtech** [comment]
Well we tried to apply but it is not taking any PAN,GST or CIN number and saying invalid.Strange.If somebody can help us there so at least we can go through the application

**Comment by bombardier-gif** [comment]
> It might be useful to have one single server sending out slot availability notifications which everyone can then subscribe to.

This is an interesting design. We would need to rearchitect a new solution for it. We could have a reservation queue where people can get a token and it will be attempted accordingly. This is how cowin should have been in the first place. 

But also it would expose us to serious trouble for implementing a centralised system

**Comment by evioxtech** [comment]
Ok great we were able to apply for the Protected apis lets see what they have to say now.Will keep posted
Thanks

**Comment by nolimits0007** [comment]
> > Planning to apply?
> 
> Nah, its for organisations and not individuals. As per this doc it says an individual can only access Public API(rate limited) for using the non rate limited public API and protected API we need to register with them. Thats a bit confusing since we are already using protected APIs.

@Nakul93 they will only whitelist ur public ip when u give them ur details . No privacy left . My Gosh PAN CARD ,GST we r here for helping people who r not getting vaccine.

**Comment by mrms123** [comment]
>Thats a bit confusing since we are already using protected APIs.

Okay - so this is a quirk from how pallupz went about building the codebase. He didn't use the API docs - instead he reverse engineered CoWIN portal by looking at what requests it was making.
https://github.com/pallupz/covid-vaccine-booking/issues/130

So essentially, the whole code is using the protected key that was allocated to the CoWIN web app. Technically, you are not supposed to be using the protected APIs, because you haven't registered on API Setu, and the code is piggybacking on CoWIN's authorization. Which is also why this whole thing is a bit in the grey area.

**Comment by Nakul93** [comment]
Interesting

**Comment by shailesh** [comment]
> > Thats a bit confusing since we are already using protected APIs.
> 
> Okay - so this is a quirk from how pallupz went about building the codebase. He didn't use the API docs - instead he reverse engineered CoWIN portal by looking at what requests it was making.
> [pallupz#75](https://github.com/pallupz/covid-vaccine-booking/issues/75)
> [pallupz#130](https://github.com/pallupz/covid-vaccine-booking/issues/130)
> 
> So essentially, the whole code is using the protected key that was allocated to the CoWIN web app. Technically, you are not supposed to be using the protected APIs, because you haven't registered on API Setu, and the code is piggybacking on CoWIN's authorization. Which is also why this whole thing is a bit in the grey area.

Right, this is the right way. even we are unable to call beneficiaries API from Postman, it returns unauthorized. We are using Protected ones no doubt. The Cowin is a bit buggy code written.

**Comment by shailesh** [comment]
> Guys check this out: https://sandbox.ndhm.gov.in/cowin/
> 
> CC: @bombardier-gif @shailesh @6mxo89sqh @BumpyKnuckls

The company that I work for has applied for the same, waiting to see how would that make a difference.

**Comment by shailesh** [comment]
> > > Planning to apply?
> > 
> > 
> > Nah, its for organisations and not individuals. As per this doc it says an individual can only access Public API(rate limited) for using the non rate limited public API and protected API we need to register with them. Thats a bit confusing since we are already using protected APIs.
> 
> @Nakul93 they will only whitelist ur public ip when u give them ur details . No privacy left . My Gosh PAN CARD ,GST we r here for helping people who r not getting vaccine.


Agree on IP Whitelisting. And maybe a static token consisting of a secret keys

**Comment by evioxtech** [comment]
Hello Team,
Our request for protected api is approved and details regarding accessing the apis is provided to us with the keys

**Comment by mrms123** [comment]
Can you share the T&C that have been instructed to you for the use of the
protected API?
