### ISSUE TITLE
Many Times ending with this error and slot is not booked 

### ISSUE THREAD

**Issue by jishnu-gv** [bombardier-gif/covid-vaccine-booking#48]
Captcha Response Code: 200
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!

Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}

**Comment by srmk1** [comment]
@jishnu-gv This is not a bug, may be your frequency of polling is very high OR too many people are polling at very short frequency.

**Comment by bombardier-gif** [comment]
Yes the error clearly says that the slot is completely booked. Many slots vanish in a second :(
