### ISSUE TITLE
Use proxies to fix the Rate Limit Error

### ISSUE THREAD

**Issue by dhhruv** [bombardier-gif/covid-vaccine-booking#480]
How about we use proxies (Authentic and Reliable) to send requests where every request uses a random proxy to send?
If you've have any proxy-list (Free) or website which is authentic and reliable then let me know.

Just a suggestion. Please let me know what everybody thinks on the same.

**Comment by nandnitw** [comment]
cowin api binded with IP and session id both. so just changing IP by proxy may not work.

**Comment by dhhruv** [comment]
> cowin api binded with IP and session id both. so just changing IP by proxy may not work.

Then how is #452 working ?

**Comment by shailesh** [comment]
Using AWS instances
