### ISSUE TITLE
Captcha Removed on CoWin

### ISSUE THREAD

**Issue by siddharthgoyal90** [bombardier-gif/covid-vaccine-booking#481]
Captcha has been removed and is no longer required to enter while booking since yesterday. Does that require any changes in the existing script OR will the script just by-pass that automatically? Help needed.

**Comment by Nakul93** [comment]
@siddharthgoyal90 The changes have already been made. Please pull the latest changes.

**Comment by siddharthgoyal90** [comment]
@Nakul93 thanks for your prompt response. DO you mean its in there in the latest main branch?

**Comment by Nakul93** [comment]
Yes the script is still there but we have just commented it out. Don’t worry it won’t affect the booking process any manner

**Comment by siddharthgoyal90** [comment]
Thank you @Nakul93 once again.

On a separate note, can you suggest the latest recommended approach to work around the rate limit issue. I am running the script after a week, and it seems I just cant avoid getting this error even reducing the frequency and tried with all Option 1, 2 and 3. 

I know there are some open issues posts. However, can you please point and suggest the latest fix which works?

Thanks once again!

**Comment by Nakul93** [comment]
Rate limit issue has been fixed, if you keep the refresh rate above 5secs and choose findby date option(which searches only for a single date) rather than calendar search which searches for a week(this causes rate limiting issue).
Run the latest code, and this would be prompted

**Comment by siddharthgoyal90** [comment]
@Nakul93 Okay Nakul thats perfect and thanks again for your help! So we dont need any of the AWS Setup as mentioned if you are using main branch, correct?

**Comment by Nakul93** [comment]
Option2 and option3 should work. I would suggest not to use more than 3 pincodes for option3. 
And no ,AWS setup is not mandatory it is used when user wants to have a refresh frequency less than 5secs and need to run it for a longer time.

**Comment by siddharthgoyal90** [comment]
@Nakul93 thanks for your response. In that case can I go with Option 2, and select multiple districts within a state? Does that works successfully? Thanks once again for your response!

**Comment by Nakul93** [comment]
Yeah you could try that. Let me know if that works for you
