### ISSUE TITLE
Booking failed due to cowin api returning cache data #Error 409

### ISSUE THREAD

**Issue by nandnitw** [bombardier-gif/covid-vaccine-booking#482]
![9C395591-9109-4B55-8C47-F2214F8D37FA](https://user-images.githubusercontent.com/50792667/120917370-8ca23200-c6cc-11eb-8288-c4c8f1c85c5b.jpeg)

protected Cowin api these days returning cache data. so booking failed with error 409. Same problem i observed on cowin official site. telegram notification come early, but centre not available on cowin site, and suddenly it shows all slot booked. Anyone having solution for this?

**Comment by Nakul93** [comment]
Are you using the single date search option?

**Comment by nandnitw** [comment]
no. district wise for a week. there is no cache issue with date wise?

**Comment by nandnitw** [comment]
but i can see issue on cowin site too. telegram notification come, but centre not visible for 2-3 min, then suddenly it appear and shows all booked.

**Comment by Nakul93** [comment]
Yeah this is a known issue, if you the search for a week option you get rate limited plus there is a chance of delayed data as well due to caching.
Suggest you to switch to date wise option.

**Comment by nandnitw** [comment]
it worked. thanks for help
