### ISSUE TITLE
Unable to run the script in docker locally

### ISSUE THREAD

**Issue by Nakul93** [bombardier-gif/covid-vaccine-booking#483]
Followed the instructions on Readme but got the following error,
```
Unable to find image 'docker.pkg.github.com/bombardier-gif/covid-vaccine-booking/cowin:latest' locally
docker: Error response from daemon: Head https://docker.pkg.github.com/v2/bombardier-gif/covid-vaccine-booking/cowin/manifests/latest: no basic auth credentials.
See 'docker run --help'.
```

**Comment by 6mxo89sqh** [comment]
@Nakul93 u need to login to docker

Create your personal access token from [here](https://github.com/settings/tokens/new?scopes=read:packages)
Run following:

```bash
export PAT=<YOUR_TOKEN>
echo $PAT | docker login docker.pkg.github.com -u <GITHUB_USERNAME> --password-stdin
```

**Comment by Nakul93** [comment]
> @Nakul93 u need to login to docker
> 
> Create your personal access token from [here](https://github.com/settings/tokens/new?scopes=read:packages)
> Run following:
> 
> ```shell
> export PAT=<YOUR_TOKEN>
> echo $PAT | docker login docker.pkg.github.com -u <GITHUB_USERNAME> --password-stdin
> ```

Ok done. Now how to actually run it. I've tried running it and it prints some kind of a token and then exits

**Comment by Saurabh-meshram** [comment]
Getting same error in AWS 

Unable to find image 'docker.pkg.github.com/bombardier-gif/covid-vaccine-booking/cowin:latest' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/bombardier-gif/covid-vaccine-booking/cowin/manifests/latest: no basic auth credentials.
See 'docker run --help'.

**Comment by 6mxo89sqh** [comment]
> > @Nakul93 u need to login to docker
> > Create your personal access token from [here](https://github.com/settings/tokens/new?scopes=read:packages)
> > Run following:
> > ```shell
> > export PAT=<YOUR_TOKEN>
> > echo $PAT | docker login docker.pkg.github.com -u <GITHUB_USERNAME> --password-stdin
> > ```
> 
> Ok done. Now how to actually run it. I've tried running it and it prints some kind of a token and then exits
```bash
export PAT=<YOUR_TOKEN_FROM_STEP_3>
echo $PAT | docker login docker.pkg.github.com -u <GITHUB_USERNAME> --password-stdin
docker run --rm \
  -v $(pwd)/configs:/configs \
  -e "TZ=Asia/Kolkata" \
  --network="host" \
  -it \
  docker.pkg.github.com/bombardier-gif/covid-vaccine-booking/cowin:latest
```

**Comment by Saurabh-meshram** [comment]
> > > @Nakul93 u need to login to docker
> > > Create your personal access token from [here](https://github.com/settings/tokens/new?scopes=read:packages)
> > > Run following:
> > > ```shell
> > > export PAT=<YOUR_TOKEN>
> > > echo $PAT | docker login docker.pkg.github.com -u <GITHUB_USERNAME> --password-stdin
> > > ```
> > 
> > 
> > Ok done. Now how to actually run it. I've tried running it and it prints some kind of a token and then exits
> 
> ```shell
> export PAT=<YOUR_TOKEN_FROM_STEP_3>
> echo $PAT | docker login docker.pkg.github.com -u <GITHUB_USERNAME> --password-stdin
> docker run --rm \
>   -v $(pwd)/configs:/configs \
>   -e "TZ=Asia/Kolkata" \
>   --network="host" \
>   -it \
>   docker.pkg.github.com/bombardier-gif/covid-vaccine-booking/cowin:latest
> ```

I am getting error after running above command in AWS EC2 (Ubuntu) instance.

Unable to find image 'docker.pkg.github.com/bombardier-gif/covid-vaccine-booking/cowin:latest' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/bombardier-gif/covid-vaccine-booking/cowin/manifests/latest: no basic auth credentials.

**Comment by 6mxo89sqh** [comment]
https://github.com/bombardier-gif/covid-vaccine-booking/wiki/Running-on-Docker

@Saurabh-meshram You need to login first. Use docker login command to login.

**Comment by Nakul93** [comment]
> ```shell
> export PAT=<YOUR_TOKEN_FROM_STEP_3>
> echo $PAT | docker login docker.pkg.github.com -u <GITHUB_USERNAME> --password-stdin
> docker run --rm \
>   -v $(pwd)/configs:/configs \
>   -e "TZ=Asia/Kolkata" \
>   --network="host" \
>   -it \
>   docker.pkg.github.com/bombardier-gif/covid-vaccine-booking/cowin:latest
> ```

But the network="host" parameter is for running on AWS right. I want to run it locally

**Comment by nolimits0007** [comment]
@Nakul93 i have tried mine, it is working k .

<img width="670" alt="Screenshot 2021-06-06 at 22 05 07" src="https://user-images.githubusercontent.com/84738436/120932526-d6623b00-c713-11eb-98c7-dce5c55f84f0.png">

**Comment by Nakul93** [comment]
That's because you are using AWS ec2 instance. The same cmd surprisingly works for local as well. 
@6mxo89sqh please update the documentation, its kind of confusing. Also I saw that json file is not getting stored anywhere. And it doesn't take KVDB bucket key even after I set it up as env variable.

**Comment by nolimits0007** [comment]
> That's because you are using AWS ec2 instance. The same cmd surprisingly works for local as well.
> @6mxo89sqh please update the documentation, its kind of confusing. Also I saw that json file is not getting stored anywhere. And it doesn't take KVDB bucket key even after I set it up as env variable.

@Nakul93 about json file u r correct every time i have give input .

**Comment by 6mxo89sqh** [comment]
> That's because you are using AWS ec2 instance. The same cmd surprisingly works for local as well.
> @6mxo89sqh please update the documentation, its kind of confusing. Also I saw that json file is not getting stored anywhere. And it doesn't take KVDB bucket key even after I set it up as env variable.

I ended up restructuring the entire readme 🤦 

@Nakul93 in docker env variable are passed using `-e` flag. e.g. `-e "KVDB_BUCKET=sdfdsfsdf"`
--host=network joins docker to local network. using that on local also should be fine.

**Comment by Nakul93** [comment]
I guess you need to update the docker package as well. It doesn't seem to be latest

**Comment by 6mxo89sqh** [comment]
That automatically gets updated when there is a release :) I ll raise a release.

**Comment by Nakul93** [comment]
Closing this issue as this has been resolved
