### ISSUE TITLE
Unable to create OTP

### ISSUE THREAD

**Issue by Jotsnam** [bombardier-gif/covid-vaccine-booking#489]
Getting this error code
{"errorCode":"USRAUT0018", "error":"Generate OTP failed"}. 
What could be the possible reasons for this & any solutions  please?

**Comment by HarshGupta011** [comment]
+1

**Comment by ithihasmadala** [comment]
Same error, looks like a cooling period for your phone number. FFFFFFF

**Comment by dreamhatx** [comment]
Same error.

- Is there any specific limit on how many OTP an account can request in a time interval? 
- How much is the cooldown time?
- Is it just temporary or permenant?

Couldn't find it anywhere related to OTP limiting on the [API docs](https://apisetu.gov.in/public/api/cowin/cowin-protected-v2). Does anyone know any of these?

**Comment by 6mxo89sqh** [comment]
+1 on this. my number also got impacted today. not able to find the pattern yet. i tried changing ips n all but nothing worked.

**Comment by ggoel1998** [comment]
Same thing happened with my  number although no api calls/OTP calls were made on it in 24hours , so I guess there is a different reason.

**Comment by nandnitw** [comment]
same error. is it because of using bot?

**Comment by darthfishious** [comment]
https://www.dqindia.com/cowin-otp-issues-arise-citizens-platform-displays-generate-otp-failed-message/

**Comment by ithihasmadala** [comment]
> Same error.
> 
> - Is there any specific limit on how many OTP an account can request in a time interval? 
> - How much is the cooldown time?
> - Is it just temporary or permenant?
> 
> Couldn't find it anywhere related to OTP limiting on the [API docs](https://apisetu.gov.in/public/api/cowin/cowin-protected-v2). Does anyone know any of these?

The only thing we know is we can do 100 API calls every 5 minutes. And personally, I amy have requested for at least a 1000 OTPs till now, and the problem happened for the first time today...

**Comment by adizz** [comment]
This must be due to multiple OTP requests, I'm able to get OTPs on my other number.

**Comment by nolimits0007** [comment]
I don't think there is an issue receiving messages . Just checked it.

**Comment by nmanjuonline** [comment]
Anybody else facing this issue.?

**Comment by kunalmoharir** [comment]
I am facing the same since this morning.

**Comment by nijeesh4all** [comment]
```
{"errorCode":"USRAUT0018", "error":"Generate OTP failed"}
```

i actually got a call some someone saying they are from covin support and asked me if i am running any automated script

**Comment by nmanjuonline** [comment]
> ```
> {"errorCode":"USRAUT0018", "error":"Generate OTP failed"}
> ```
> 
> i actually got a call some someone saying they are from covin support and asked me if i am running any automated script

Ooops!

**Comment by darthfishious** [comment]
https://www.dqindia.com/cowin-generate-otp-failed-usraut0018-errors-fixed-evening-8-june/

**Comment by dreamhatx** [comment]
I had this same error (`USRAUT0018`) for more than 24 hours. But now the error has changed. It is now,

```json
{"errorCode":"USRAUT0030", "error":"Exceeded Search Limit. Please try after some time."}
```

But I havn't recieved a single OTP since yesterday and still I have to wait.

**Comment by nmanjuonline** [comment]
> ```
> {"errorCode":"USRAUT0018", "error":"Generate OTP failed"}
> ```
> 
> i actually got a call some someone saying they are from covin support and asked me if i am running any automated script.
> 
> update:
> 
> He threatened me sating that "actions" will be taken, if you continue doing it.

Are yo sure that it was genuine call and not a prank?

**Comment by kunalmoharir** [comment]
> I had this same error (`USRAUT0018`) for more than 24 hours. But now the error has changed. It is now,
> 
> ```json
> {"errorCode":"USRAUT0030", "error":"Exceeded Search Limit. Please try after some time."}
> ```
> 
> But I haven't recieved a single OTP since yesterday and still I have to wait.

Exactly the same issue

**Comment by Nakul93** [comment]
Are you all able to get OTP while using browser/app?

**Comment by nandnitw** [comment]
> Are you all able to get OTP while using browser/app?

nope. everywhere same. just error code changed now. {"errorCode":"USRAUT0030", "error":"Exceeded Search Limit. Please try after some time."}

**Comment by Nakul93** [comment]
It seems like this issue affects those users who has taken covaxin and is due for dose2.
[Read here](https://www.dqindia.com/cowin-displays-generate-otp-failed-usraut0018-errors-citizens-unable-book-slots-second-dose-covid-19-vaccine/)

**Comment by nmanjuonline** [comment]
> It seems like this issue affects those users who has taken covaxin and is due for dose2.
> [Read here](https://www.dqindia.com/cowin-displays-generate-otp-failed-usraut0018-errors-citizens-unable-book-slots-second-dose-covid-19-vaccine/)

I was trying to book my first dose when it failed generating OTPs

**Comment by Nakul93** [comment]
> > It seems like this issue affects those users who has taken covaxin and is due for dose2.
> > [Read here](https://www.dqindia.com/cowin-displays-generate-otp-failed-usraut0018-errors-citizens-unable-book-slots-second-dose-covid-19-vaccine/)
> 
> I was trying to book my first dose when it failed generating OTPs

Have you tried [this](https://github.com/cowinapi/developer.cowin/issues/409#issuecomment-856580076)

**Comment by sudo-u** [comment]
hmm for now...has anyone tried observing slot opening time pattern from previous days  & running the script 10mins before the slot opens ? (that if you are getting OTP's in the first place) .....instead of running it continuously....being cautious

**Comment by nmanjuonline** [comment]
It's working now!

**Comment by ithihasmadala** [comment]
> > > It seems like this issue affects those users who has taken covaxin and is due for dose2.
> > > [Read here](https://www.dqindia.com/cowin-displays-generate-otp-failed-usraut0018-errors-citizens-unable-book-slots-second-dose-covid-19-vaccine/)
> > 
> > 
> > I was trying to book my first dose when it failed generating OTPs
> 
> Have you tried [this](https://github.com/cowinapi/developer.cowin/issues/409#issuecomment-856580076)

This worked!!!! Just changed 1 line in the code. ```txnId = requests.post(url=OTP_PRO_URL, json=data, headers=request_header)``` Change it to ```txnId = requests.post(url=OTP_PUBLIC_URL, json=data, headers=request_header)```. I just got my second dose of Covaxin for tomorrow. GGGGG

**Comment by nandnitw** [comment]
now otp getting generated from cowin site as well.

**Comment by mrms123** [comment]
`hmm for now...has anyone tried observing slot opening time pattern from previous days & running the script 10mins before the slot opens ? `

I think this is the way to go - generally, slots are released by the DMO office in every district. And they manually update every center one by one. Hence it is roughly the same time every day, but not exactly the same time every day.
What might work is - keep a watchout for your districts on telegram. When the first update kicks in in the group - start the code. 

The last thing you want - is to have taken the first dose from somewhere, and then have that [phone number perma banned from CoWIN

**Comment by agarwalshashwat** [comment]
> ```
> {"errorCode":"USRAUT0018", "error":"Generate OTP failed"}
> ```
> 
> i actually got a call some someone saying they are from covin support and asked me if i am running any automated script.
> 
> update:
> 
> He threatened me sating that "actions" will be taken, if you continue doing it.

Yes, I received same call just now and the person asked me if I am using the automated script, if so then please stop it else an enquiry against you will be done.

**Comment by agarwalshashwat** [comment]
> > ```
> > {"errorCode":"USRAUT0018", "error":"Generate OTP failed"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i actually got a call some someone saying they are from covin support and asked me if i am running any automated script.
> > update:
> > He threatened me sating that "actions" will be taken, if you continue doing it.
> 
> Are yo sure that it was genuine call and not a prank?

Yes he is right, the same call happened to me and the caller started with taking the name of the beneficiary I was trying to book for.

**Comment by 6mxo89sqh** [comment]
@nijeesh4all @agarwalshashwat 

What was your frequency of requesting OTP? How long did it work without any issues? When did it stop working?

**Comment by ithihasmadala** [comment]
I think it is better if each of us use a different secret key and set refresh to 15 seconds or more. You can get new secret keys easily from cowin by inspecting the network.

**Comment by 6mxo89sqh** [comment]
@nijeesh4all & @agarwalshashwat, please connect with me on [this link](https://discord.gg/UDzShm7X).

**Comment by nijeesh4all** [comment]
> @nijeesh4all @agarwalshashwat
> 
> What was your frequency of requesting OTP? How long did it work without any issues? When did it stop working?

150s

I was running it for the past 5 days, it stopped around noon yesterday

**Comment by sudo-u** [comment]
> `hmm for now...has anyone tried observing slot opening time pattern from previous days & running the script 10mins before the slot opens ? `
> 
> I think this is the way to go - generally, slots are released by the DMO office in every district. And they manually update every center one by one. Hence it is roughly the same time every day, but not exactly the same time every day.
> What might work is - keep a watchout for your districts on telegram. When the first update kicks in in the group - start the code. 
> 
> The last thing you want - is to have taken the first dose from somewhere, and then have that [phone number perma banned from CoWIN

Yeah..Agree With that

**Comment by sudo-u** [comment]
https://www.dqindia.com/cowin-users-get-account-blocked-exceeding-search-limit-message-heres/

**Comment by sudo-u** [comment]
If Telegram Bots are allowed & have no problem...then how about 

- step1: enter mobile number, KVDB key, beneficiary name, vaccine type etc (save info )

- step2:  monitor for slot availability for particular district/pincodes... like how telegram bot does 

- step3: if slots become available ,only then initiate login process ( OTP ) & book slots

**Comment by agarwalshashwat** [comment]
> @nijeesh4all @agarwalshashwat
> 
> What was your frequency of requesting OTP? How long did it work without any issues? When did it stop working?



> @nijeesh4all & @agarwalshashwat, please connect with me on [this link](https://discord.gg/UDzShm7X).


> @nijeesh4all @agarwalshashwat
> 
> What was your frequency of requesting OTP? How long did it work without any issues? When did it stop working?

Sorry for replying late, I was at work. So I started with 10s on 1st June and was able to book one slot too, but when max search in 10 mins was made to 20, I switched to 30s refresh rate. Also, I was running the script from 12 pm to 10 pm as the Pincode I was searching for did not have any particular time frame to release the slots.

**Comment by Nakul93** [comment]
@agarwalshashwat the fix has been released for the 20searches per session thing. Now you can do a single day search with low refresh rate to avoid getting rate limited. 
Today I ran the script for almost 5hrs without any issues and was able to book a slot
