### ISSUE TITLE
error fetching OTP API:Not Found, works when otp is entered manually

### ISSUE THREAD

**Issue by aakashs11** [bombardier-gif/covid-vaccine-booking#493]

**Comment by Nakul93** [comment]
Please pull the latest changes and check if it works.
Also have you set your own KVDB bucket?

**Comment by aakashs11** [comment]
Same error even with the latest changes.
yes, I'm using the CoWIN OTP retriever

**Comment by Nakul93** [comment]
Have you done this,
https://github.com/bombardier-gif/covid-vaccine-booking#kvdb-setup
After setting it up pass the KVDB key as a argument.

**Comment by aakashs11** [comment]
Setting up a new key helped, thanks!
