### ISSUE TITLE
Not working src

### ISSUE THREAD

**Issue by devakar80** [bombardier-gif/covid-vaccine-booking#498]
➜  covid-vaccine-booking git:(heads/main) python3 src/covid-vaccine-slot-booking.py
Traceback (most recent call last):
  File "src/covid-vaccine-slot-booking.py", line 8, in <module>
    from utils import generate_token_OTP, generate_token_OTP_manual, check_and_book, beep, BENEFICIARIES_URL, WARNING_BEEP_DURATION, \
  File "/Users/venkateshsheshgiri/Cowin/covid-vaccine-booking/src/utils.py", line 4, in <module>
    from inputimeout import inputimeout, TimeoutOccurred
ModuleNotFoundError: No module named 'inputimeout' #

**Comment by anandmr1** [comment]
You need to install the dependencies, see Readme 

Third-Party Package Dependency:

    tabulate : For displaying data in tabular format.
    requests : For making GET and POST requests to the API.
    inputimeout : For creating an input with timeout.

Install all dependencies by running: pip install -r requirements.txt

**Comment by devakar80** [comment]
Working..


Thanks
