### ISSUE TITLE
OTP=Manual, Script=Automatic

### ISSUE THREAD

**Issue by sid8840** [bombardier-gif/covid-vaccine-booking#50]
kudos to your idea
I was able to run your project on windows. successfully get the captcha window.

can you put an option between Manual or Automatic OTP capture??
it would be grateful as IFTT setup on android would be cumbersome for nonsavvy users. a simple OTP forward would be too simple.
the Autobook with random slots is a great idea. Hats Off!!\
less user input...more chances to get a slot.

**Comment by bombardier-gif** [comment]
If you want manual OTP you can use the original repo: github.com/pallupz/covid-vaccine-booking
