### ISSUE TITLE
cowin guys removed State&District option in UI !!!!!

### ISSUE THREAD

**Issue by shivaslifzz** [bombardier-gif/covid-vaccine-booking#501]
![image](https://user-images.githubusercontent.com/61616987/121233223-0cd4bd00-c8b0-11eb-868d-3afb5cd9d7dd.png)

**Comment by shivaslifzz** [comment]
it won't impact our code bcz it's only removed UI but background still API's present for state and district option

**Comment by mrms123** [comment]
Just click randomly in that region - it goes to state and district selector. Looks more like a botched update than anything else.

**Comment by shivaslifzz** [comment]
yaaa this worst enhancement done by cowing guys :) :) not even visible 

![image](https://user-images.githubusercontent.com/61616987/121234852-cc763e80-c8b1-11eb-93ff-08b6bc3c48d8.png)
