### ISSUE TITLE
Error jwt function

### ISSUE THREAD

**Issue by suumiit** [bombardier-gif/covid-vaccine-booking#503]
module 'jwt' has no attribute 'decode'

**Comment by aman-3003** [comment]
> module 'jwt' has no attribute 'decode'

Install the dependencies using : 
- pip install -r requirements.txt (Windows)
- pip3 install -r requirements.txt (Mac)

Then run the file it should work.

**Comment by suumiit** [comment]
already did...

**Comment by Nakul93** [comment]
The problem occurs if you have both JWT and PyJWT installed on your system. Uninstall jwt, by `pip uninstall jwt`

**Comment by suumiit** [comment]
thank you so much, reinstalled it and its working... @Nakul93 @aman-3003.... 💗💗💗
