### ISSUE TITLE
Add entropy to refresh_freq & 🤫

### ISSUE THREAD

**Issue by 40ZqTYY4ag3tAO4hdlxR1** [bombardier-gif/covid-vaccine-booking#507]
In light of the new T&C https://github.com/bombardier-gif/covid-vaccine-booking/issues/505 and the phone calls noted in this thread https://github.com/bombardier-gif/covid-vaccine-booking/issues/489 maybe its time for users to review their OPSEC & the devs too.

Stop posting screenshots with a phone number, beneficiary ID, PIN code, the scripts success notification which shows a timestamp. 

Cowin will always have Personally Identifiable Information nothing can be done about that. They will always have your IP even if you are using AWS, Jeff will happily give them the account associated with the instances IP when he receives a subpoena. 

The best that can be done is an attempt to blend in to the crowd

- **The current Useragent  is too unique** 0.03% source https://www.amiunique.org/fp This has been kinda brought up earlier https://github.com/bombardier-gif/covid-vaccine-booking/pull/394 https://github.com/bombardier-gif/covid-vaccine-booking/issues/185 https://github.com/bombardier-gif/covid-vaccine-booking/issues/331

> https://github.com/bombardier-gif/covid-vaccine-booking/blob/4931d999029bfa676a30cf790b0828672f2d454e/src/covid-vaccine-slot-booking.py#L76

- **~~Add entropy~~ Add some entropy to refresh_freq** . The user defined refresh_freq is easy to identify as automation ... its easy for Cowin to identify a pattern and gather evidence. If you hit the endpoint every 30 seconds on the dot for an hour, they know its not a human

- Once you have helped yourself and your friends/family... give it a rest

@6mxo89sqh https://github.com/bombardier-gif/covid-vaccine-booking/issues/489#issuecomment-857401183_ After your pow wow on discord , are there other patterns/behaviors users should think about modifying?

The only solution is not to blend in and use common sense strategies like https://github.com/bombardier-gif/covid-vaccine-booking/issues/489#issuecomment-857032762_ https://github.com/bombardier-gif/covid-vaccine-booking/issues/489#issuecomment-857780973_

The nail that sticks out gets hammered down

**Comment by nibir08in** [comment]
Guys, how to tackle this now - http://timesofindia.indiatimes.com/articleshow/83387752.cms?utm_source=contentofinterest&utm_medium=text&utm_campaign=cppst

**Comment by anandmr1** [comment]
+1, someone please add this feature.
