### ISSUE TITLE
Error for different due dates

### ISSUE THREAD

**Issue by Aryamn** [bombardier-gif/covid-vaccine-booking#508]
Why the program is throwing errors for different due dates?
        
 ```
 today = datetime.datetime.today()
  today = today.strftime("%d-%m-%Y")
  due_date = [beneficiary["dose2_due_date"] for beneficiary in beneficiary_dtls]
  dates = Counter(due_date)
  if len(dates.keys()) != 1:
      print(
          f"All beneficiaries in one attempt should have the same due date. Found {len(dates.keys())}"
      )
      os.system("pause")
      sys.exit(1)
```

**Comment by Nakul93** [comment]
Yeah so currently it doesn’t support multiple beneficiaries with different due dates. You can try them one at a time.

**Comment by Aryamn** [comment]
If I remove the if condition then what will happen?
Also since the maximum due date has already been passed so what is the problem?

**Comment by Nakul93** [comment]
> If I remove the if condition then what will happen?
> Also since the maximum due date has already been passed so what is the problem?

It will work for your case. But consider a scenario where multiple beneficiaries are selected and not all have past their due date. Then this will be a problem

**Comment by Aryamn** [comment]
Thanks for clearing the doubts.
