### ISSUE TITLE
Not an issue : Android support here

### ISSUE THREAD

**Issue by Vishvajeet590** [bombardier-gif/covid-vaccine-booking#513]
Hi, guys I created the app to run these scripts on android. It can save time and energy. It aims to reduce dependency on the only PC to run scripts.  Also, I have added a feature to send OTP to PC version script without any hassle of setting up IFTTT or buckets.
It also has a feature to store multiple JSON profiles which can be used to run to script quickly.

Repository link ---> [Here you go](https://github.com/Vishvajeet590/CowinPy-Andy).

**Comment by bombardier-gif** [comment]
This is cool. Could you ask the main developer (pallupz) to mention your repository in his readme? That would enable more discovery of your repo.

**Comment by Vishvajeet590** [comment]
I don't know how to contact him about this. But I shared the repository in his discord group, but no reply yet.

**Comment by sudo-u** [comment]
> I don't know how to contact him about this. But I shared the repository in his discord group, but no reply yet.

Hey do we have a Dicord group ?, can I get an Invite please

**Comment by Vishvajeet590** [comment]
> > I don't know how to contact him about this. But I shared the repository in his discord group, but no reply yet.
> 
> Hey do we have a Dicord group ?, can I get an Invite please

[Look here.](https://github.com/pallupz/covid-vaccine-booking/issues/254#issuecomment-854475924)

**Comment by sudo-u** [comment]
> > > I don't know how to contact him about this. But I shared the repository in his discord group, but no reply yet.
> > 
> > 
> > Hey do we have a Dicord group ?, can I get an Invite please
> 
> [Look here.](https://github.com/pallupz/covid-vaccine-booking/issues/254#issuecomment-854475924)

Thanks ...but getting Invalid invite

**Comment by Vishvajeet590** [comment]
Discord ---> [HERE](https://discord.gg/rYWVxsmV)

**Comment by sudo-u** [comment]
> Discord ---> [HERE](https://discord.gg/rYWVxsmV)

Thank you...got it

**Comment by shivaslifzz** [comment]
@Vishvajeet590 can you share the android app link here or in discord

**Comment by RonakTotla** [comment]
@Vishvajeet590 repo not found! What's up?

**Comment by Vishvajeet590** [comment]
Made it private 😐

**Comment by RonakTotla** [comment]
May I ask why so?
Anyways, your repo your wish

**Comment by Vishvajeet590** [comment]
> May I ask why so?

I think we are violating the TOS of Cowin and they can take action against us. It was also on my main account so don't want any trouble.

**Comment by RonakTotla** [comment]
Oh okay
All the best for your work ahead!

**Comment by Vishvajeet590** [comment]
> Oh okay
> All the best for your work ahead!

Thanks..... had fun creating that and fixing bugs. ✌
