### ISSUE TITLE
What settings to use after the new cowin T&C?

### ISSUE THREAD

**Issue by aadishj19** [bombardier-gif/covid-vaccine-booking#522]
which setting, time interval etc to use so cowin doesn't block account after the new terms and conditions?

**Comment by PATTOOo** [comment]
use most of default settings
1. search by district/state for pincode
2. refresh rate 15+ seconds
3. single date search
4. do not run bot more than 4-6 hours

**Comment by Nakul93** [comment]
I would suggest to look for trends from telegram alerts and accordingly start the script. If you know particular time of center opening slots then you can run the script even at lower refresh rate like 5secs

**Comment by Nakul93** [comment]
You could try out this [repo](https://github.com/Nakul93/BooKie). It allows searching for slots without logging in so it won't block your account if you want to search for hrs. The search results are uncached and are sometimes faster than telegram alerts.

**Comment by aadishj19** [comment]
> You could try out this [repo](https://github.com/Nakul93/BooKie). It allows searching for slots without logging in so it won't block your account if you want to search for hrs. The search results are uncached and are sometimes faster than telegram alerts.

Thanks!
