### ISSUE TITLE
suggesion about more automation

### ISSUE THREAD

**Issue by PATTOOo** [bombardier-gif/covid-vaccine-booking#523]
can i post some other git page here ?
i am not able to contact owners account. so i created issue here. sorry in advance

**Comment by Nakul93** [comment]
Yeah sure do share it.

**Comment by PATTOOo** [comment]
https://github.com/shashankbafna/cowin-vaccination-book-slot
here it is getting operated through telegram(it works for single user). if we can this script like this.  it will become very easy for others.

**Comment by Nakul93** [comment]
> https://github.com/shashankbafna/cowin-vaccination-book-slot
> here it is getting operated through telegram(it works for single user). if we can this script like this. it will become very easy for others.

So if I understand this correctly then the only difference is we give input via Telegram bot right?It still needs to run the script on computer

**Comment by PATTOOo** [comment]
yes it need to run script on computer. telegram is just for inputs.
i was thinking can i run scripts on raspberry pi and tell others to use from telegram inputs

**Comment by Nakul93** [comment]
But as you mentioned it works for just single user right plus if you are using pro URL for a long time then your no might get blocked

**Comment by PATTOOo** [comment]
hmm yeah. cant run multiple scripts on single ip also right? leave it then.
thanks man

**Comment by Nakul93** [comment]
> hmm yeah. cant run multiple scripts on single ip also right? leave it then.
> thanks man

Yeah exactly.
