### ISSUE TITLE
Feature: add filter for Sputnik vaccine

### ISSUE THREAD

**Issue by saint7007** [bombardier-gif/covid-vaccine-booking#524]
In Delhi, Sputnik has been started. Can you add input for sputnik, for now I see, covaxin and covishield?

**Comment by Nakul93** [comment]
Sputnik option is already present in the script. Please update your code and check.

**Comment by Nakul93** [comment]
As per the news SputnikV has made a soft launch.
It’s still open for registration on cowin.
Closing this
