### ISSUE TITLE
Checking without login

### ISSUE THREAD

**Issue by 520rahul** [bombardier-gif/covid-vaccine-booking#525]
@bombardier-gif ur repo is working great. I just want to add a suggestion in repo. There r many districts where online slots timing is not fixed and slots r uploaded on random basis and sometimes telegram channels also dont notify the same and v miss the slot, therefore it is not possible for keep login in 15 minutes for slots checking. I was thinking can u make a optional feature of checking slots without login and when the repo find out a desired slot it automatically sends otp to the mobile no. By this our login attempts can be saved and and v can run the repo for longer time without any problem.  But plz keep this feature as optional and not mandatory for everone, as inserting otp takes time so for the districts where slot uploading time is fixed and v know the exact timing in that case we can use current version of repo.  @Nakul93 @6mxo89sqh

**Comment by bombardier-gif** [comment]
Hi Rahul, if you setup the Android App or the IFTTT it automatically logsin after 15 mins, and also autoreads the OTP sms. Thats the main point of this repo. Please open an issue if you are not able to set it.
