### ISSUE TITLE
"Start Listening CoWIN OTP" automatically turns off when minimizing CoWIN OTP Retriever

### ISSUE THREAD

**Issue by malayilneil** [bombardier-gif/covid-vaccine-booking#527]
I used to use IFTTT and very recently made the change to CoWIN OTP Retriever. I had turned off all battery savers and optimizations for the app. However, when I turn on the "start listening" feature and minimize the app, it turns off again.

Any suggestions?

**Comment by Nakul93** [comment]
Have you turned on run app in background?

**Comment by malayilneil** [comment]
Yup I have

**Comment by Nakul93** [comment]
Are you sure you are not closing the app instead of minimising?

**Comment by malayilneil** [comment]
Pretty sure that's the case @Nakul93

**Comment by Nakul93** [comment]
So your saying as soon as the app is minimised the start listening to OTP switch gets turned off, but the app remains open in background?

**Comment by malayilneil** [comment]
Exactly @Nakul93

**Comment by Nakul93** [comment]
Are you using the latest version of the app?

**Comment by PATTOOo** [comment]
1. Instead of using back key. Use home key to minimise app.
2. Confirm that you are not in power savings mode.
3. Make sure Battery saving for app is not optimised.

**Comment by malayilneil** [comment]
@PATTOOo I think using the home key worked!
