### ISSUE TITLE
New Age Category added to Cowin 30+. Will it require any code changes..?

### ISSUE THREAD

**Issue by saurabh1069** [bombardier-gif/covid-vaccine-booking#528]
Today i have seen new age category in cowin. since it's 30+ will it require any changes to script.?

![image](https://user-images.githubusercontent.com/26090183/122726726-e6415980-d293-11eb-863d-dd7f28cd91e4.png)

**Comment by salian** [comment]
See #494

**Comment by saurabh1069** [comment]
Thanks
