### ISSUE TITLE
Not Working For Above 45+ 2nd Dose

### ISSUE THREAD

**Issue by Jishnu441** [bombardier-gif/covid-vaccine-booking#538]
I was looking for a slot for my mom's 2nd dose when i search it shows 0 center available in the script but when i checked it in the cowin site there was a many centre's available idk why the script shows like this and site shows another. so to check if the script was broken i tried to book a 18+ 1st dose and the script worked fine so i figured that the issue was only for 45+ idk about 1st dose 45+ but there is an issue for 45+ 2nd dose.

I think the issue started in 6th july 2021, it was working fine untill then because i booked a slot for my dad last week and it worked then, i think this started after the cowin site updated its format and made all the centers 18+ instead of 18-44 , 45+ format. I am from kerala, india if region has something to do with this.

any help is appreciated 

thanks for the script btw! 

![Screenshot 2021-07-09 205417](https://user-images.githubusercontent.com/83004520/125101523-ed6fc080-e0f7-11eb-8e4d-f0c4b8075ac9.jpg)

**Comment by mash40** [comment]
Even I was trying for the same, were you able to book successfully?

**Comment by jishnu-001** [comment]
nope, i tried again for my mom but i wasn't able to get it , even when the cowin site showed slots available the script showed 0 centers available just like in the screenshot from my first post. 
it used to work for 45+ 2nd dose but now it doesn't idk why. i think it got to do something with the change in format to 18+ only from 18-44 and 45+, i hope someone finds a way to fix it.

**Comment by mash40** [comment]
> > Even I was trying for the same, were you able to book successfully?
> 
> i found a fix try, it worked for me
> 
> @mash40

Thanks for your effort, will try and let you know the result.

**Comment by 520rahul** [comment]
@bombardier-gif plz update the repo for solution of this bug

**Comment by bombardier-gif** [comment]
sure! thanks
