### ISSUE TITLE
How to book for 18+ age group center which allow everyone above 18?

### ISSUE THREAD

**Issue by samypy** [bombardier-gif/covid-vaccine-booking#541]
How to book for 18 & Above age group center which allow everyone above 18?

![image](https://user-images.githubusercontent.com/59316197/128537740-8d207434-6316-47ad-88a6-bc75d3688c03.png)

**Comment by mjishnu** [comment]
use the new version v2.0.14 i too faced this issue #538 and it has been fixed now
