### ISSUE TITLE
Need to handle SSLError 

### ISSUE THREAD

**Issue by mayur-who** [bombardier-gif/covid-vaccine-booking#56]
HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/appointment/beneficiaries (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
Exiting Script
sh: 1: pause: not found

**Comment by bombardier-gif** [comment]
It looks like you are being ratelimited :)
Please wait for a while and try again. I hope cowin did not implement rate-limiting.

**Comment by mayur-who** [comment]
one way to get around with this error is make sure you sleep enough time so that there are less than 100 requests in 5 minutes.
I had 4 pin codes and I was sleeping for 1 second only. I modified it by adding more sleep (2 second sleep and only 1 pincode) and I haven't seen SSLError
