### ISSUE TITLE
Feature Request - Ability to Enter OTP Manually.

### ISSUE THREAD

**Issue by monish-1234** [bombardier-gif/covid-vaccine-booking#57]
Automating the entire process is good. But sometime IFTTT doesn't send the webhook. So giving an option to manually enter the OTP if they wanted in between automatically check the DB,  will be a really good move.

**Comment by bombardier-gif** [comment]
You can use the original repo to manually enter the OTP https://github.com/pallupz/covid-vaccine-booking
The core logic is same (I forked from his repo)
