### ISSUE TITLE
Automatic booking now needs us to enter captcha

### ISSUE THREAD

**Issue by renjithsasidharan** [bombardier-gif/covid-vaccine-booking#6]

**Comment by renjithsasidharan** [comment]
============> Got Choice: Center #1, Slot #3
Booking with info: {'beneficiaries': ['xxxxxxxxxxx'], 'dose': 1, 'center_id': 421758, 'session_id': 'xxx, 'slot': '01:00PM-03:00PM'}
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}
Response: 400 : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}

**Comment by bombardier-gif** [comment]
Yup. The party is officially over my friend.

**Comment by renjithsasidharan** [comment]
Can we have a popup for the user to see and enter captcha?

**Comment by salian** [comment]
It would be more useful to create a training data set of 10k solved captchas.

**Comment by renjithsasidharan** [comment]
That would be borderline illegal to so that.

**Comment by bombardier-gif** [comment]
Now the code supports captcha popup,  implemented in the main repo. I booked it for a bunch of people. Please try and let me know
