### ISSUE TITLE
Slot not booking due to security code error

### ISSUE THREAD

**Issue by panchaljay997** [bombardier-gif/covid-vaccine-booking#61]
![IMG-20210510-WA0011](https://user-images.githubusercontent.com/84022078/117816679-68496600-b284-11eb-8920-8917251028e6.jpeg)

Please solve the issue and update the application, if possible send it to this mail.

Thank you👍🏻

**Comment by bombardier-gif** [comment]
It means the captcha did not go through. Its a problem we are facing that the captcha isnt very reliable. Try couple of times and it usually succeeds.

**Comment by sid8840** [comment]
> ![IMG-20210510-WA0011](https://user-images.githubusercontent.com/84022078/117816679-68496600-b284-11eb-8920-8917251028e6.jpeg)
> 
> Please solve the issue and update the application, if possible send it to this mail.
> 
> Thank you👍🏻

captcha test passed??
