### ISSUE TITLE
Help needed: Clean the readme

### ISSUE THREAD

**Issue by bombardier-gif** [bombardier-gif/covid-vaccine-booking#63]
Right now the readme has super huge screenshots and badly formatted steps. Could someone please volunteer to clean it up?

**Comment by bombardier-gif** [comment]
Absolutely @dhavalsavalia !

**Comment by dhavalsavalia** [comment]
![Screenshot 2021-05-11 at 9 22 07 PM](https://user-images.githubusercontent.com/27001046/117846308-f29ec380-b29e-11eb-9bbf-345c9ef58bec.png)

What do you think about this size? It's 30% of the original.

**Comment by bombardier-gif** [comment]
Looks neat! The resolution can be tweaked to make it more readable though "Android SMS"

**Comment by vasugamdha** [comment]
Yeah! came here with this same suggestion.

> Dedicated wiki is a neat Idea. To break the readme into multiple pages.

I suggest this directory structure

covid-vaccine-booking
├─ guide
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├─ IFTTT.md (For Android and Web)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├─ Android.md (CoWinOTPRetriever Android App)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├─ iOS.md (Shorcuts App)
├─ src
├─ tests

And link all those .md in the main README.md
I could have added myself but I am a bit busy, recently. Contact me if need any help.

**Comment by bombardier-gif** [comment]
@BumpyKnuckls Thank you so much for cleaning this up. So many people would benefit out of this work
🥇
