### ISSUE TITLE
Input is not working when i'm trying to enter the OTP

### ISSUE THREAD

**Issue by agnibha123** [bombardier-gif/covid-vaccine-booking#64]
**After entering the Mobile number.......When I'm getting the Otp.........Input is not working when I am trying to give the OTP** 
Running Script
Enter the registered mobile number: 8697xxxxxx
clearing OTP bucket: https://kvdb.io/3YgXf9PHYHbX6NsF7zP6Us/8697xxxxxx
Requesting OTP with mobile number 8697xxxxxx..
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:

**Comment by BumpyKnuckls** [comment]
Is it not working inspite of restarting the script?

**Comment by agnibha123** [comment]
I am trying to put OTP manually.....not using IFTTT.......is that okay?

**Comment by bombardier-gif** [comment]
No this is fully automated script. It reads the OTP using IFTTT/ or iOS shortcuts. You need to set that up.

You cannot enter otp manually.
