### ISSUE TITLE
OTP recived but not allowing to enter

### ISSUE THREAD

**Issue by madhu2504** [bombardier-gif/covid-vaccine-booking#65]
I am running on MacOs, and getting following error. Please help how to resolve this. 

Requesting OTP with mobile number..XXXXXX..
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:
OTP SMS len is:0
OTP SMS is:

**Comment by BumpyKnuckls** [comment]
Also is it not working inspite of restarting the script?

**Comment by bombardier-gif** [comment]
This is a fully automated script. It reads the OTP by itself using IFTT or Shortcuts. 
You cannot enter OTP.
