### ISSUE TITLE
anticaptcha issue after selecting no

### ISSUE THREAD

**Issue by elv10** [bombardier-gif/covid-vaccine-booking#66]
![issue 600](https://user-images.githubusercontent.com/83970080/117841418-acdffc00-b29a-11eb-960c-f83f3068c141.png)

**Comment by BumpyKnuckls** [comment]
@dhavalsavalia would you know why this may be the case?

**Comment by dhavalsavalia** [comment]
Oh, my bad. Pushing patch

**Comment by BumpyKnuckls** [comment]
@elv10 can you pull the latest main and try again. @dhavalsavalia has pushed the fix.

**Comment by elv10** [comment]
thanks @BumpyKnuckls - it is working now
