### ISSUE TITLE
Help needed: Allow manual OTP inputs

### ISSUE THREAD

**Issue by bombardier-gif** [bombardier-gif/covid-vaccine-booking#68]
A bunch of people have been asking to  let users input the OTP manually. Initially i pointed them to the original repo https://github.com/pallupz/covid-vaccine-booking

But now this repo also has captcha auto-read support. So it might make sense for giving an option to bypassing auto read.

It will also help users who find it tough to install IFTTT and iOS Shortcuts.

Ideally it can be another option asked before running the script, whether to autoread OTP or manually enter it.

**Comment by dhavalsavalia** [comment]
I thought of it this way. If a user wants to do a manual verification then they will append a dot `.` after their phone number so that they don't have to have another prompt.

So, if they want to do manual verification they will enter ```9999999999.```. What do you say?

**Comment by bombardier-gif** [comment]
And also default should be auto-read (n in this case)
