### ISSUE TITLE
Is it possible to get notifications for slot availability? I think you can implement that.

### ISSUE THREAD

**Issue by callmetushar123** [bombardier-gif/covid-vaccine-booking#7]

**Comment by bombardier-gif** [comment]
Yes I updated the code.. I was not able to see the OTP sms in a timely manner so not able to test it. Shall do it tomorrow.

**Comment by bombardier-gif** [comment]
Also what kind of notifications are you asking?

**Comment by callmetushar123** [comment]
> Also what kind of notifications are you asking? 

I have not used the script yet. I was talking whether it has a vaccine slot notifier feature or not, similar to Paytm vaccine notifier?

**Comment by bombardier-gif** [comment]
This beeps when a slot is available. And also says "Slot Spotted."
