### ISSUE TITLE
Latest code has below issue after OTP verification

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#71]
'types.SimpleNamespace' object has no attribute 'captcha_automation'

**Comment by xxxAng** [comment]
@bombardier-gif  @dhavalsavalia .. alternatively you can the steps for 
anti-captcha.com private key configuration in read me section .

**Comment by bombardier-gif** [comment]
Also is there any reference to line number @xxxAng ? I will try to fix it before dhaval gets to see this

**Comment by dhavalsavalia** [comment]
@xxxAng @bombardier-gif I am redoing readme but it might take a little time as I will be working today.

**Comment by bombardier-gif** [comment]
Good inputs. PR is welcome :)

**Comment by bombardier-gif** [comment]
@dhavalsavalia what is the rootcause for "'types.SimpleNamespace' object has no attribute 'captcha_automation'"

**Comment by xxxAng** [comment]
Not his fault, I tried to run the program using old saved jason settings,
where as he added once more setting for captcha.
I regenerated the setting it worked for me.

**Comment by bombardier-gif** [comment]
Can you please update the readme at the bottom troubleshooting section? so that others can benefit out of your investigation?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
