### ISSUE TITLE
is it possible to add otp manually while script is trying to read the response from ifttt?

### ISSUE THREAD

**Issue by root-ansh** [bombardier-gif/covid-vaccine-booking#72]
i can see an otp generated in my device, but the script is unable to detect it. if a popup is open where i can manually enter the otp, it will be faster

**Comment by root-ansh** [comment]
yes ifttt was working before, but now its taking time. i pulled the latest code and can use the manual otp functionality, many thanks

**Comment by bombardier-gif** [comment]
I agree automation preference can be stored. But phone number would make it difficult for other people to use for multiple people easily.
