### ISSUE TITLE
otp in exe file

### ISSUE THREAD

**Issue by springsmooth** [bombardier-gif/covid-vaccine-booking#75]
i am not able to enter the otp.
![Screenshot (13)](https://user-images.githubusercontent.com/83895439/117873253-343e6700-b2bd-11eb-9014-90b93232abe0.png)
here is the ss of the error I m getting

**Comment by bombardier-gif** [comment]
You have chosen autoread of otp. Please pull the latest code and chose manual entry

**Comment by bombardier-gif** [comment]
@dhavalsvalia the exe creation is broken

**Comment by springsmooth** [comment]
> You have chosen autoread of otp. Please pull the latest code and chose manual entry

The code is latest.There is no option of choosing manual  entry.Can u share the steps?

**Comment by bombardier-gif** [comment]
The exe is broken. 
As a workaround, you can run the script with the steps given in the readme.

**Comment by dhavalsavalia** [comment]
@bombardier-gif I am sorry. I don't have Windows so I can't compile the executable for it. Can someone volunteer?

**Comment by bombardier-gif** [comment]
Meanwhile I will remove the EXE as lot of people are using the old version till we fix the exe.
