### ISSUE TITLE
Added CoWin OTP retriever android app as an alternate to IFTTT

### ISSUE THREAD

**Issue by ujaiswal** [bombardier-gif/covid-vaccine-booking#78]
I felt that the IFTTT android app setup part could be more simplified by creating a simple android app.
This way people do not have to worry about whether they should get a pro or continue using a free account.

Check this PR:
https://github.com/bombardier-gif/covid-vaccine-booking/pull/77

**Comment by sumit2k21** [comment]
Can someone build an iOS app for this ? which can automatically read the messages and send them to kv db without manual taps on Phone ? Currently while using shortcuts we have to tap on phone to allow it every time otp authentication happens.

**Comment by bombardier-gif** [comment]
iOS does not give access to your messages so the only option is the Shortcuts.
