### ISSUE TITLE
Error fetching the API bucket

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#79]
API bucket to fetch OTP not working suddenly,

![image](https://user-images.githubusercontent.com/25231713/117936808-4925f500-b2d3-11eb-8316-4a2cdb40daeb.png)

**Comment by VirajBagal** [comment]
Same for me!

**Comment by xxxAng** [comment]
@bombardier-gif   :( the script broke due to this

**Comment by VirajBagal** [comment]
Your mobile number is visible. Please hide it

**Comment by xxxAng** [comment]
@VirajBagal  my bad .. thanks

**Comment by sumit2k21** [comment]
same issue for me

**Comment by sbhardwa123** [comment]
Same issue

**Comment by Aryamn** [comment]
Same issue for me. I think there is a problem with the kvdb link mentioned in the applet. Applet itself is failing.

**Comment by sumit2k21** [comment]
yeah, we need the script that he was using on the original bucket, we can configure individual buckets but need to working script.

**Comment by rakole** [comment]
@bombardier-gif yes please, share script to setup our individual bucket for those who want to.

**Comment by bombardier-gif** [comment]
I am also facing the same issue. The root cause is that someone deleted the bucket. It is guarded by a secret key but i dont know how this happened. 

1. ASAP I am creating a new bucket and updating the code
2. I will updated the steps to create your own bucket

**Comment by BumpyKnuckls** [comment]
In the meantime if you wanna use your own bucket, please change the following line in utils.py file's function `book_appointment` to use your own bucket instead:

 ```
requests.put("https://kvdb.io/2EKK2edg4qNknwfP1PsKqV/" + mobile, data={})
```

**Comment by bombardier-gif** [comment]
Updated the code with a new bucket. 
**Steps to create a new bucket:** go to kvdb.io and register
in the Get Started section, you can create a bucket.
Then an id is generated which can be pasted in your code.

**Comment by devansh7777** [comment]
> Updated the code with a new bucket.
> **Steps to create a new bucket:** go to kvdb.io and register
> in the Get Started section, you can create a bucket.
> Then an id is generated which can be pasted in your code.

it costs 19 dollars man! extendclass gig was quite decent too. if you could guide me how to use that in this script.
