### ISSUE TITLE
Solved the captcha problem

### ISSUE THREAD

**Issue by kokroo** [bombardier-gif/covid-vaccine-booking#8]
DM me for details. All processing happens on device, captcha is successfully solved every time.

**Comment by axd123** [comment]
if you could share the code, maybe someone can bake it into one of the implementations 🤷‍♂️

**Comment by kokroo** [comment]
> if you could share the code, maybe someone can bake it into one of the implementations 🤷‍♂️

The problem is, it's not easy to use for everyone since it's not an easy implementation. That's why I wanted to discuss it first with the repo owner.

**Comment by kokroo** [comment]
@bombardier-gif Can you delete this issue please? it didn't work out.
