### ISSUE TITLE
Multiple instances of the script simultaneously for different locations

### ISSUE THREAD

**Issue by sreevathsa** [bombardier-gif/covid-vaccine-booking#81]
I need to book slots in 2 cities where family members are spread out. Can I run multiple instances of the script from the same directory? In such a setup, despite keying in the captcha, I get the unauthenticated access/token invalid error as below. Is it related to running two instances of the script? 

======================= ATTEMPTING BOOKING ==========================
Booking Response Code: 401
Booking Response : Unauthenticated access!
TOKEN INVALID
Token is INVALID.

Also, a related question for the instance of the script that doesn't throw the error above - for 1 open slot why does it ask for captcha verification 5-6 times? After every input of the captcha code the server response is: "This vaccination center is completely booked for the selected date." Is this expected?

**Comment by sreevathsa** [comment]
Note that the unauthenticated access/invalid token error is in one of the two instances and not both. And also it doesn't show up consistently.

**Comment by sreevathsa** [comment]
Also, I am using the same phone number in both the instances.

**Comment by bombardier-gif** [comment]
You can link different numbers for different locations and run them.

Also for the "This vaccination center is completely booked for the selected date." it just means that someone else is faster in booking :|
