### ISSUE TITLE
Bucket not found issue

### ISSUE THREAD

**Issue by ayushanshul07** [bombardier-gif/covid-vaccine-booking#82]
error fetching OTP API:bucket not found
error fetching OTP API:bucket not found

**Comment by jatinguta** [comment]
clearing OTP bucket: https://kvdb.io/3YgXf9PHYHbX6NsF7zP6Us/983******
Requesting OTP with mobile number 983*****..
error fetching OTP API:bucket not found
error fetching OTP API:bucket not found

**Comment by ayushanshul07** [comment]
I saw that in latest commit he has changed bucket. Closing issue. Please update readme.
