### ISSUE TITLE
Need automatic pincodes list fetching based on current location & distances

### ISSUE THREAD

**Issue by sumit2k21** [bombardier-gif/covid-vaccine-booking#84]
Would be really helpful, if we can have an option where I enter one pincode or lets say my current location, and distance 20 KM and based on this it automatically inputs pincodes for search.
Also it would be good if I can see centers on a map web based / streamlit is an option. so that I can see available centers in the map and can comprehend distance of those centers also.

**Comment by bombardier-gif** [comment]
Nice ideas. You are welcome to contribute.
