### ISSUE TITLE
What happens if you say no to recapta autofill option ?

### ISSUE THREAD

**Issue by avadhut007** [bombardier-gif/covid-vaccine-booking#89]
Please add free resources. What happens if you say no during captcha autofill does it send any notification for booking ?

**Comment by xxxAng** [comment]
@avadhut007 whats happening if you save that option 'yes' ? does it book and fill captcha automatically ? or its asking for secret key ?

If you say 'no' it will ask you to enter captcha before booking.

**Comment by bombardier-gif** [comment]
It opens a window with a captcha and a text box where you can enter ir
