### ISSUE TITLE
Removing dependency on Android

### ISSUE THREAD

**Issue by krishnanvivek** [bombardier-gif/covid-vaccine-booking#9]
Your script is good, however there is a small workaround for people with phones other than Android. 
You can use the send trigger as "Send IFTTT any email" and link your email to it. You can then configure the web request to contain the "body" of the mail, to forward it to the same link that you provided.
The only caveat here is you need to forward the SMS to the mail id "trigger@applet.ifttt.com" as soon as you receive the SMS. The mail body should not contain any other info like signature etc.
This works, so as soon as you get the SMS OTP alert you can forward the contents to the mail id and the script does rest of the job.
I haven't been able to book any slots yet, but this workaround is useful since I don't need to be around the script to get it working.
You can probably update you README with this info.

**Comment by salian** [comment]
This is a bit silly. Slots are getting over in single-digit seconds. Forwarding an SMS manually that too via e-mail brings in so much latency, it would be better to just use a notifier script and book manually.

**Comment by krishnanvivek** [comment]
> This is a bit silly. Slots are getting over in single-digit seconds. Forwarding an SMS manually that too via e-mail brings in so much latency, it would be better to just use a notifier script and book manually.

I'd rather sit and forward the SMS to a mail id via my phone(takes 10-15 seconds) and hope for the booking to go ahead, than get notified and then wait for the OTP, enter it and then book which is far more latent. BTW the OTP obtained during scheduling also gets delayed sometimes .. So we're all trying the best approach ...whatever works for anyone ..

**Comment by callmetushar123** [comment]
> > This is a bit silly. Slots are getting over in single-digit seconds. Forwarding an SMS manually that too via e-mail brings in so much latency, it would be better to just use a notifier script and book manually.
> 
> I'd rather sit and forward the SMS to a mail id via my phone(takes 10-15 seconds) and hope for the booking to go ahead, than get notified and then wait for the OTP, enter it and then book which is far more latent. BTW the OTP obtained during scheduling also gets delayed sometimes .. So we're all trying the best approach ...whatever works for anyone ..

But according to him the script will not work because of the implementation of CAPTCHA. So I think it'll end up being notifier.

**Comment by krishnanvivek** [comment]
> > > This is a bit silly. Slots are getting over in single-digit seconds. Forwarding an SMS manually that too via e-mail brings in so much latency, it would be better to just use a notifier script and book manually.
> > 
> > 
> > I'd rather sit and forward the SMS to a mail id via my phone(takes 10-15 seconds) and hope for the booking to go ahead, than get notified and then wait for the OTP, enter it and then book which is far more latent. BTW the OTP obtained during scheduling also gets delayed sometimes .. So we're all trying the best approach ...whatever works for anyone ..
> 
> But according to him the script will not work because of the implementation of CAPTCHA. So I think it'll end up being notifier.

Agreed. The strangest part is the bookings get over in seconds even if there are slots and I'm still trying to find out if there are scripts that take this the whole way through scheduling. It'll take some robust image processing libraries to get it done, but the search is on.

**Comment by callmetushar123** [comment]
> > > > This is a bit silly. Slots are getting over in single-digit seconds. Forwarding an SMS manually that too via e-mail brings in so much latency, it would be better to just use a notifier script and book manually.
> > > 
> > > 
> > > I'd rather sit and forward the SMS to a mail id via my phone(takes 10-15 seconds) and hope for the booking to go ahead, than get notified and then wait for the OTP, enter it and then book which is far more latent. BTW the OTP obtained during scheduling also gets delayed sometimes .. So we're all trying the best approach ...whatever works for anyone ..
> > 
> > But according to him the script will not work because of the implementation of CAPTCHA. So I think it'll end up being notifier.
> 
> Agreed. The strangest part is the bookings get over in seconds even if there are slots and I'm still trying to find out if there are scripts that take this the whole way through scheduling. It'll take some robust image processing libraries to get it done, but the search is on.

Well it's happening in my state too. Just like railway bookings. I too believe, people have found a workaround.

**Comment by bombardier-gif** [comment]
I updated the code. Please try again. This has captcha support from the main repo by pallupz.
