### ISSUE TITLE
error fetching OTP API:bucket not found

### ISSUE THREAD

**Issue by vesan83** [bombardier-gif/covid-vaccine-booking#90]
error fetching OTP API:bucket not found

and in ifttt error is 
Your server returned a 404. Unable to make web request to https://kvdb.io/3YgXf9PHYHbX6NsF7zP6Us/9xxxxxxxxx

**Comment by xxxAng** [comment]
#79 
its fixed .. re download the code and run again ...

**Comment by vesan83** [comment]
tried again after new fresh download, no luck still

**Comment by bombardier-gif** [comment]
Did you make sure that the IFTTT works properly?
is the url set correctly?

**Comment by vesan83** [comment]
Yes ifttt is working properly 
everything was working fine till today morning


i am using the exe file since i dont know prog language

**Comment by govindasomani** [comment]
> Yes ifttt is working properly
> everything was working fine till today morning
> 
> i am using the exe file since i dont know prog language

You can refer to this doc for running the python script directly. 
[Steps.docx](https://github.com/bombardier-gif/covid-vaccine-booking/files/6465967/Steps.docx)

**Comment by pratulk09** [comment]
not fixed same error
says Your server returned a 404. Unable to make web request https://kvdb.io/3YgXf9PHYHbX6NsF7zP6Us/9xxxxxxxxx

**Comment by vesan83** [comment]
> > Yes ifttt is working properly
> > everything was working fine till today morning
> > i am using the exe file since i dont know prog language
> 
> You can refer to this doc for running the python script directly.
> [Steps.docx](https://github.com/bombardier-gif/covid-vaccine-booking/files/6465967/Steps.docx)

any idea of the following error
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ikornu1** [comment]
@vesan83 reinstall python using custom mode and check all the boxes. I am not a techie but I had a similar issue. I did this and it worked.

**Comment by xxxAng** [comment]
@vesan83, you will have to add python environment variable.

**Comment by vesan83** [comment]
solved it with this video
https://www.youtube.com/watch?v=dj5oOPaeIqI

**Comment by yashk2103** [comment]
@vesan83 Install latest python. Then open cmd and run the pip command mentioned in Readme.md. Then after everything is succesfully installed, go and run the script directly from the src folder.

Check this article to install Python: https://phoenixnap.com/kb/how-to-install-python-3-windows

Hope this helps

**Comment by bombardier-gif** [comment]
@vesan83 you need to pull the latest code. the exe no longer works. I will delete it from the repo
