### ISSUE TITLE
Minimum polling interval - anyone tried successfully ?

### ISSUE THREAD

**Issue by xxxAng** [bombardier-gif/covid-vaccine-booking#91]
What is the minimum polling interval you guys and tried successfully ?
Without getting IP blocked or account blocked.
@bombardier-gif

**Comment by RonakTotla** [comment]
I tried successfully with 1 sec polling interval. But that was yesterday.

**Comment by xxxAng** [comment]
@RonakTotla  what about today ? is there a chance of getting blocked IP ?

**Comment by RonakTotla** [comment]
@xxxAng ok let me run it and check. will update in a while

**Comment by xxxAng** [comment]
Thanks @RonakTotla  appreciated!!!

**Comment by bombardier-gif** [comment]
1 is what we allow at the minimum.

**Comment by RonakTotla** [comment]
> Thanks @RonakTotla appreciated!!!

it is running fine...what sample size of time are you looking at @xxxAng

**Comment by xxxAng** [comment]
Nice to get confirmation
