### ISSUE TITLE
Cannot book slots. OTP Error with manual filling

### ISSUE THREAD

**Issue by monish-1234** [bombardier-gif/covid-vaccine-booking#92]
`================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}
Response: 400 : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}
Response: 400 : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}
================================= GETTING CAPTCHA ==================================================`

Ended with Cloudflare blocking the requests

**Comment by monish-1234** [comment]
'''json
{"beneficiary_dtls": [{"bref_id": "xxxxx", "name": "xxxxx", "vaccine": "", "age": 26, "status": "Not Vaccinated"}, {"bref_id": "xxxxxxxx", "name": "xxxxxxx", "vaccine": "", "age": 27, "status": "Not Vaccinated"}], "location_dtls": [{"district_id": 571, "district_name": "Chennai", "alert_freq": 1320}], "search_option": 2, "minimum_slots": 2, "refresh_freq": 5, "auto_book": "yes-please", "start_date": 2, "vaccine_type": "COVISHIELD", "fee_type": ["Free", "Paid"], "captcha_automation": "n", "captcha_automation_api_key": null}

**Comment by monish-1234** [comment]
I entered captcha_automation as `n` instead of `no` . That was the issue. Closing

**Comment by Huzaifg** [comment]
I have the same issue and I also entered captcha_automation as `n` instead of `no`. Have not tested if thats the issue though

**Comment by monish-1234** [comment]
Yes that was the issue for me. Editing the JSON with `no` solved it.
