### ISSUE TITLE
Cannot parse response Ios automation shortcut

### ISSUE THREAD

**Issue by sumit2k21** [bombardier-gif/covid-vaccine-booking#93]
![image](https://user-images.githubusercontent.com/81756345/117960667-d8b2be80-b33a-11eb-8a3f-2c839bc341fb.png)

Hi while creating the automation following the README.md instruction, it gives this issue on running.
Also notification comes on my locked screen of shortcut, while I click on it an option comes to run it & I am not sure without clicking the option will it run automatically or not.
![image](https://user-images.githubusercontent.com/81756345/117961047-4828ae00-b33b-11eb-9557-fe150a01da08.png)

**Comment by sumit2k21** [comment]
Seems like automation using message can't not run without asking. 
**NOTE** This thing is less useful on iOS phones, iphones. Its better to have it setup on android phones for receiving messages.
https://support.apple.com/en-in/guide/shortcuts/apd602971e63/ios

**Comment by sumit2k21** [comment]
**NOTE** Its better to keep refresh interval as atleast 5 seconds, if we keep 1 seconds then the it will start giving issues.

**Comment by bombardier-gif** [comment]
iOS Shortcuts is a viable alternative for those who dont have access to android phones
