### ISSUE TITLE
Getting setFont(Times-Roman) missing

### ISSUE THREAD

**Issue by VirajBagal** [bombardier-gif/covid-vaccine-booking#94]
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None

**Comment by RonakTotla** [comment]
solutions mentioned in closed threads

**Comment by xxxAng** [comment]
Go to the read me section trouble shooting ...
Duplicate issue @VirajBagal

**Comment by VirajBagal** [comment]
Solved using the troubleshooting section. Thanks!
