### ISSUE TITLE
error fetching OTP API:bucket not found      downloaded latest code and ran EXE

### ISSUE THREAD

**Issue by agnibha123** [bombardier-gif/covid-vaccine-booking#95]
https://kvdb.io/3YgXf9PHYHbX6NsF7zP6Us/8697xxxxxx

downloaded latest code and ran but applet is failing

**Comment by mustafabhanpura** [comment]
Facing the same issue. @bombardier-gif

**Comment by RonakTotla** [comment]
not possible. i'm running the script as i type this

**Comment by vesan83** [comment]
even i am facing the same issue still

**Comment by bombardier-gif** [comment]
exe is not updated. Pleaase use the script directly

**Comment by vesan83** [comment]
can you please update the exe
it will help people like us who dont know script language

**Comment by agnibha123** [comment]
script is working fine
