### ISSUE TITLE
Better Handling of Slots Booked before Captcha Verification

### ISSUE THREAD

**Issue by monish-1234** [bombardier-gif/covid-vaccine-booking#96]
Run the Captcha again and again even if the center is completely booked. Captcha function shouldn't be called If the Center is full. It should return to searching

`enters available in Chennai from 13-05-2021 as of 2021-05-12 17:11:22: 35
+-------+-----------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                        | district   |   pincode |   available | date       | slots                                                                        |
+=======+=============================+============+===========+=============+============+==============================================================================+
|     1 | Apollo Speciality Hospitals | Chennai    |    600035 |           3 | 13-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-06:00PM'] |
+-------+-----------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
Random Rows.Column:1.2
============> Got Choice: Center #1, Slot #2
Booking with info: {'beneficiaries': ['xxxxx', 'xxxxx'], 'dose': 1, 'center_id': 603579, 'session_id': '915exxxx1-d6fe-4014-b2a4-e945xxxxx93ac', 'slot': '11:00AM-01:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
===================================================================================
Centers available in Chennai from 13-05-2021 as of 2021-05-12 17:11:32: 35
+-------+-----------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                        | district   |   pincode |   available | date       | slots                                                                        |
+=======+=============================+============+===========+=============+============+==============================================================================+
|     1 | Apollo Speciality Hospitals | Chennai    |    600035 |           3 | 13-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-06:00PM'] |
+-------+-----------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
Random Rows.Column:1.2
============> Got Choice: Center #1, Slot #2
Booking with info: {'beneficiaries': ['xxxxx', 'xxxxxx'], 'dose': 1, 'center_id': 603579, 'session_id': 'xxxxxxx-d6fe-4014-b2a4-e9xxxxx8093ac', 'slot': '11:00AM-01:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200`

**Comment by bombardier-gif** [comment]
This happens when someone books it before you enter the captcha. There isnt much we can do here than be quick at it. The captcha is a bit buggy and it might need multiple tries.
