### ISSUE TITLE
"Please enter valid security code" error in captcha without window with option to enter captcha

### ISSUE THREAD

**Issue by Huzaifg** [bombardier-gif/covid-vaccine-booking#98]
Without a window opening to enter the captcha manually, "Please enter valid security code"  kept getting returned when booking was attempted. 

![Screenshot 2021-05-12 at 5 39 40 PM](https://user-images.githubusercontent.com/64803446/117973109-98a70800-b349-11eb-9d95-e982bac8bd56.png)

**Comment by monish-1234** [comment]
@Huzaifg Did you install all the packages in requirement.txt ?

If so, then I had the same issue. Check this . #92

**Comment by bombardier-gif** [comment]
interesting, can you provide more information such as:
1. were you running the script on a laptop or on a server?
2. Did you use the autocaptcha or manual captcha?

**Comment by cryptoe** [comment]
Confirmed: 
Same issue:
```
On laptop (should not matter rite)
OS : DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

**Comment by Huzaifg** [comment]
1. Laptop 
   ` macOS Big Sur Version 11.2 `
2. Manual Captcha. However I entered captcha_automation as `n `instead of `no`. Might be the problem. Have not tested. #92

**Comment by bombardier-gif** [comment]
the captcha pops up as another window. Please check for newly created windows

**Comment by karthik-bharadwaj-h** [comment]
I had a ssh session to one of the text based server machines where the script was run. Didn't have any GUI support. So used timg instead.

<img width="711" alt="screenshot" src="https://user-images.githubusercontent.com/20438441/118003591-57712100-b366-11eb-87de-30cb7bc38342.png">

```diff
diff --git a/src/captcha.py b/src/captcha.py
index 4594db3..3301c39 100644
--- a/src/captcha.py
+++ b/src/captcha.py
@@ -1,6 +1,7 @@
 from svglib.svglib import svg2rlg
 from reportlab.graphics import renderPM
-import PySimpleGUI as sg
+import numpy as np
+import timg
 import re
 from PIL import Image
 from anticaptchaofficial.imagecaptcha import imagecaptcha
@@ -16,15 +17,14 @@ def captcha_builder(resp):
     im = im.convert('RGB').convert('P', palette=Image.ADAPTIVE)
     im.save('captcha.gif')

-    layout = [[sg.Image('captcha.gif')],
-          [sg.Text("Enter Captcha Below")],
-          [sg.Input()],
-          [sg.Button('Submit', bind_return_key=True)]]
-
-    window = sg.Window('Enter Captcha', layout)
-    event, values = window.read()
-    window.close()
-    return values[1]
+    obj = timg.Renderer()
+    obj.load_image_from_file("captcha.gif")
+    obj.resize(100,50)
+    obj.render(timg.ASCIIMethod)
+    for x in range(10):
+        print('\a')
+    text = input("Enter the captcha text here : ")
+    return text;
```

**Comment by karthik-bharadwaj-h** [comment]
@Huzaifg
Please mask your beneficiary info details (in your screenshot above) as it also contains Aadhar number which could be misused in a public forum

**Comment by bombardier-gif** [comment]
> I had a ssh session to one of the text based server machines where the script was run. Didn't have any GUI support. So used timg instead.
> 
> <img alt="screenshot" width="711" src="https://user-images.githubusercontent.com/20438441/118003591-57712100-b366-11eb-87de-30cb7bc38342.png">
> 
> ```diff
> diff --git a/src/captcha.py b/src/captcha.py
> index 4594db3..3301c39 100644
> --- a/src/captcha.py
> +++ b/src/captcha.py
> @@ -1,6 +1,7 @@
>  from svglib.svglib import svg2rlg
>  from reportlab.graphics import renderPM
> -import PySimpleGUI as sg
> +import numpy as np
> +import timg
>  import re
>  from PIL import Image
>  from anticaptchaofficial.imagecaptcha import imagecaptcha
> @@ -16,15 +17,14 @@ def captcha_builder(resp):
>      im = im.convert('RGB').convert('P', palette=Image.ADAPTIVE)
>      im.save('captcha.gif')
> 
> -    layout = [[sg.Image('captcha.gif')],
> -          [sg.Text("Enter Captcha Below")],
> -          [sg.Input()],
> -          [sg.Button('Submit', bind_return_key=True)]]
> -
> -    window = sg.Window('Enter Captcha', layout)
> -    event, values = window.read()
> -    window.close()
> -    return values[1]
> +    obj = timg.Renderer()
> +    obj.load_image_from_file("captcha.gif")
> +    obj.resize(100,50)
> +    obj.render(timg.ASCIIMethod)
> +    for x in range(10):
> +        print('\a')
> +    text = input("Enter the captcha text here : ")
> +    return text;
> ```

This is a cool thing to do @karthik-bharadwaj-h Could you add this in our wiki?
