### ISSUE TITLE
Help Needed: Captcha Test 

### ISSUE THREAD

**Issue by GOODBOIXD** [bombardier-gif/covid-vaccine-booking#99]
```
Installed tkinter_version: 8.6.9
 ----------------------------------------------------------------------------------------------------
Opening test window. Click on "Quit" to run further tests
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
window opening ...
Yeah !!! you have entered captcha. This means you are all set to render required captcha at the time of booking ...

x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
Started solving captcha...
making request to createTask
could not create task
API error ERROR_KEY_DOES_NOT_EXIST: Account authorization key not found in the system
Task finished with error: ERROR_KEY_DOES_NOT_EXIST - 0
```
I get the following after I enter the captcha. I got the output I am supposed to get - "Yeah !!! you have entered captcha. This means you are all set to render required captcha at the time of booking ..." but what is this error in the last line? Is this supposed to be this way? 

Also, @bombardier-gif  epic work done! Thank you for this!

**Comment by bombardier-gif** [comment]
Did you provide the captcha registration key?

**Comment by GOODBOIXD** [comment]
Registration key? I am sorry but where is that? I don't see any instructions about the key?

**Comment by bombardier-gif** [comment]
you can do manually, but you need to chose that option while starting the script

**Comment by GOODBOIXD** [comment]
While starting the script? I didn't see any option of selecting or not selecting anti captcha while starting the script. Does this option come while I am booking? Also, where do I provide the registration key? Which file and line?

**Comment by vesan83** [comment]
any idea of how to buy https://anti-captcha.com/ codes in india.

**Comment by GOODBOIXD** [comment]
> any idea of how to buy https://anti-captcha.com/ codes in india.

Go to anti-captcha.com and use their paypal service, you will get a coupon, use that coupon code to redeem!

**Comment by GOODBOIXD** [comment]
Also, do I need to provide the key in captcha_tests last line only? or somewhere else too?  maybe @dhavalsavalia can help

**Comment by GOODBOIXD** [comment]
Nevermind, read the utils.py, the option to select comes while booking. As well as the option to enter key! Lmk if this is correct and then we can close this. Thanks again! :)

**Comment by ishallwin20** [comment]
you can close it.

**Comment by AanchalV** [comment]
Hi. I am getting the same error. Though i am opting to choose manual input of captcha. Missed 4-5 slots yesterday because i was not able to get through captcha. 
Please help!

**Comment by GOODBOIXD** [comment]
> Hi. I am getting the same error. Though i am opting to choose manual input of captcha. Missed 4-5 slots yesterday because i was not able to get through captcha.
> Please help!

Do you get the captcha screen where you are supposed to enter the captcha? And if so, what's the error that it shows? Does it show "can't be booked because slots filled" or "invalid response? "
